### ISSUE TITLE
throw error when link doesn't have parentNode

### ISSUE THREAD

**Issue by VieZhong** [webpack-contrib/mini-css-extract-plugin#1017]
### Bug report

Throw error when link doesn't have parentNode.

![image](https://user-images.githubusercontent.com/16253049/218722194-b65ba044-1770-43a7-8692-e8e80fc7de08.png)

see this pr to fix it: https://github.com/webpack-contrib/mini-css-extract-plugin/pull/1016

**Comment by alexander-akait** [comment]
Fixed

**Comment by VieZhong** [comment]
您好，您的邮件我已经收到。      By 钟远维   联系方式：13098843729    QQ：995825700   新浪微博： 百年佛一__屎维保持谦虚
