### ISSUE TITLE
How to use MiniCssExtractPlugin with Vue3 with defineAsyncComponent

### ISSUE THREAD

**Issue by rendomnet** [webpack-contrib/mini-css-extract-plugin#1027]
When I use this code `return defineAsyncComponent(() => import(`screens/${screenName}.vue`))` in my Vue app, where `screenName` can be any string.

I get the `WARNING in chunk Conflicting order error` in my Webpack 5.
Is it possible to resolve this error?

**Comment by alexander-akait** [comment]
Set this https://github.com/webpack-contrib/mini-css-extract-plugin#ignoreOrder, anyway I recommend to fix order
