### ISSUE TITLE
生产环境没有抽离出css

### ISSUE THREAD

**Issue by denglai** [webpack-contrib/mini-css-extract-plugin#106]
![1524452064 1](https://user-images.githubusercontent.com/20442608/39104884-0c6303d6-46e5-11e8-8b72-92597356bd02.jpg)
![1524452094 1](https://user-images.githubusercontent.com/20442608/39104885-0cbb426c-46e5-11e8-89db-6f2aa0fc8203.jpg)
![1524452110 1](https://user-images.githubusercontent.com/20442608/39104886-0d019bcc-46e5-11e8-9d71-091b090ee26d.jpg)
![1524452165 1](https://user-images.githubusercontent.com/20442608/39104887-0d48fbfc-46e5-11e8-967f-dc8ea23070ef.jpg)
![1524452178 1](https://user-images.githubusercontent.com/20442608/39104888-0d9756b2-46e5-11e8-9af9-3be2fbafc2a1.jpg)
![1524452195 1](https://user-images.githubusercontent.com/20442608/39104889-0e080e98-46e5-11e8-865a-a1942dd68e04.jpg)

**Comment by Onelin** [comment]
小伙儿你起码google翻译一下吧...
把style-loader注释打开,把MiniCss放到style-loader的后面试一下

**Comment by denglai** [comment]
试了一下，还是不可以啊，尴尬了……………………

**Comment by denglai** [comment]
![1524453911 1](https://user-images.githubusercontent.com/20442608/39105533-0d27fb06-46e9-11e8-927d-7f905884b09d.jpg)

**Comment by Onelin** [comment]
那从你的代码里我看不出什么来了,我在我的项目里是可以提取到的~~~

**Comment by Onelin** [comment]
对了,你在哪个环境下用的这个插件,开发还是生产 是不是环境问题.这个插件只需要在生产中用到

**Comment by evilebottnawi** [comment]
Please use English. Thanks!
