### ISSUE TITLE
when use splitChunk the css order is not correct，but style-loader works fine

### ISSUE THREAD

**Issue by hangaoke1** [webpack-contrib/mini-css-extract-plugin#1061]
### Bug report

use style-loader，the text is blue，it is correct
```
npm run dev
```
![image](https://github.com/webpack-contrib/mini-css-extract-plugin/assets/19623160/f5b49192-f326-4528-90f1-d69dfdc715f9)

use mini-css-extrat-plugin，the text is red，it is wrong
```
npm run build
cd dist
serve
```
![image](https://github.com/webpack-contrib/mini-css-extract-plugin/assets/19623160/28a2b4b4-56a8-4e8b-b7a0-a083c9f42bd1)

### Actual Behavior
text is red

### Expected Behavior
text is blue

### How Do We Reproduce?
https://github.com/hangaoke1/css-order

**Comment by alexander-akait** [comment]
This is a known problem, you have `A -> B` and `B -> A`, avoid override global classes, please consider to use CSS modules or move global classes to the one file, feel free to ask any questions, you can use the search to fine more infrmation why it happens
