### ISSUE TITLE
Production environment css style repeated packaging

### ISSUE THREAD

**Issue by shwehb** [webpack-contrib/mini-css-extract-plugin#1068]
### Bug report

The same css exists in the entry file and the asynchronous import file, causing the entry file css style to be overwritten when the asynchronous chunk is loaded.
Is it the expected result?

mini-css-extract-plugin@2.7.6

**Comment by alexander-akait** [comment]
Hello, yes, it is expected, because you have global styles and when override them in async CSS chunk, this is how it works

Please fill out all fields in future if you want more infromation and examples how it can be fixed, feel free to feedback
