### ISSUE TITLE
Extract css aot build failed when @import from a external url

### ISSUE THREAD

**Issue by vincent-cm** [webpack-contrib/mini-css-extract-plugin#107]
ERROR in ./src/styles/styles.scss (./node_modules/css-loader??ref--12-1!./node_modules/postcss-loader/lib??ref--12-2!./node_modules/less-loader/dist/cjs.js??ref--12-3!./node_modules/sass-loader/lib/loader.js??ref--12-4!./src/styles/styles.scss)
    Module build failed:

    @import url("https://fonts.googleapis.com/css?family=Montserrat:400,700");
    @import url("https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700");
    ^
    Can't resolve './https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' in '/..../src/styles'
          in /..../src/styles/styles.scss (line 6, column 0)

The webpack.prod.js is configured like:

    rules: [
        /**
         * Extract CSS files from .src/styles directory to external CSS file
         */
        {
          test: /\.(css|scss|less)$/,
          use: [
            MiniCssExtractPlugin.loader,
            {
              loader: 'css-loader',
              options: {
                minimize: {
                  safe: true
                },
                importLoaders: 2,
                sourceMap: true
              }
            },
            {
              loader: 'postcss-loader',
              options: {
                plugins: () => [require('autoprefixer')],
                sourceMap: true
              }
            },
            {
              loader: 'less-loader',
              options: {}
            },
            {
              loader: 'sass-loader',
              options: {
                sourceMap: true
              }
            }
          ],
          include: [helpers.root('src', 'styles')]
        }
      ]

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by evilebottnawi** [comment]
@vincent-cm you have invalid configuration for loaders, after `sass-loader` you run `less-loader`. Why?

**Comment by evilebottnawi** [comment]
@vincent-cm If you create boilerplate better use same way https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js#L126

**Comment by vincent-cm** [comment]
Thanks @evilebottnawi That is my mistake
