### ISSUE TITLE
In production environment, CSS failed to extract

### ISSUE THREAD

**Issue by denglai** [webpack-contrib/mini-css-extract-plugin#108]
![image](https://user-images.githubusercontent.com/20442608/39174492-80a956b4-47da-11e8-8b20-4039fdb99890.png)
index.js
![image](https://user-images.githubusercontent.com/20442608/39174534-9395b2c2-47da-11e8-86f7-e39517ded444.png)
webpack.common.js
![image](https://user-images.githubusercontent.com/20442608/39174587-bee9ecea-47da-11e8-902f-620d7064b04e.png)
webpack.prod.js
![image](https://user-images.githubusercontent.com/20442608/39174615-cff2db14-47da-11e8-982e-deed7c416269.png)
![image](https://user-images.githubusercontent.com/20442608/39174678-f5fb8496-47da-11e8-8277-ddb9d1fb828f.png)

![image](https://user-images.githubusercontent.com/20442608/39174701-004eae28-47db-11e8-841c-da20a783cfec.png)

If you change the --mode production configured by build to --mode development, you can get out of CSS，surprise;
![image](https://user-images.githubusercontent.com/20442608/39174940-99a2d73e-47db-11e8-9ec5-19a90769d424.png)
![image](https://user-images.githubusercontent.com/20442608/39174962-aaf5eb20-47db-11e8-9628-d613d67fe705.png)

why????

**Comment by evilebottnawi** [comment]
I can understand you, please provide more information what you have and what you expected and then reopen/recreate issue. Thanks!
