### ISSUE TITLE
Can we ignore some code while minify css file?

### ISSUE THREAD

**Issue by shamim-apex** [webpack-contrib/mini-css-extract-plugin#1087]
For example i wan't to put some logic in my css class like

.background {
    <# if(variable == true) {>
       background: transparent;
    <# }
 }

and the plug in let me ignore these <#  #> syntax and build it successfully.
Documentation Is:

- [x ] Missing
- [x ] Needed
- [ x] Confusing
- [ x] Not Sure?

**Comment by alexander-akait** [comment]
Answered. No. Please don't duplicate issues, thank you
