### ISSUE TITLE
Cannot generate CSS file from SCSS

### ISSUE THREAD

**Issue by cyiannatsos** [webpack-contrib/mini-css-extract-plugin#109]
Hello I have managed to setup a boilerplate project for react development. At this point I followed the documentation of the plugin and it is working as expected. The only thing I haven't managed to do it to extract any scss or css files to a style.css file in dist repository.

My Scripts:

`"start": "webpack-dev-server --config ./webpack.config.js --mode development",
"prod": "webpack --config ./webpack.config.js --mode production"`

My webpack.config.js file:

`
const webpack = require('webpack');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const devMode = process.env.NODE_ENV !== 'production';

module.exports = {
    entry: [
      './src/index.js',
      'react-hot-loader/patch'
    ],
    output: {
      path: __dirname + '/dist',
      publicPath: '/',
      filename: 'bundle.js'
    },
    module: {
        rules: [
          {
            test: /\.(js|jsx)$/,
            exclude: /node_modules/,
            use: ['babel-loader']
          },
          {
            test: /\.s?[ac]ss$/,
            use: [
              devMode ? 'style-loader' : MiniCssExtractPlugin.loader,
              'css-loader',
              'postcss-loader',
              'sass-loader',
            ],
          }
        ]
      },
      resolve: {
        extensions: ['*', '.js', '.jsx']
      },
      plugins: [
        new MiniCssExtractPlugin({
          // Options similar to the same options in webpackOptions.output
          // both options are optional
          filename: devMode ? '[name].css' : '[name].[hash].css',
          chunkFilename: devMode ? '[id].css' : '[id].[hash].css',
        })
      ],
    devServer: {
      contentBase: './dist',
      hot: true
    },
    // optimization: {
    //     splitChunks: {
    //       cacheGroups: {
    //         styles: {
    //           name: 'styles',
    //           test: /\.s?[ac]ss$/,
    //           chunks: 'all',
    //           enforce: true
    //         }
    //       }
    //     }
    //   }
  };
`
If I include the optimization then a second file 0.bundle.js is generated in the dist folder. If I don't the css is included in the bundle.js as below.

![project](https://user-images.githubusercontent.com/17806034/39180736-570f0976-47c0-11e8-8107-69b3019382b7.JPG)

What am I missing?

**Comment by evilebottnawi** [comment]
@cyiannatsos please use `gitter` or `stackoverflow` for question. Also without minimum reproducible test repo hard to say what wrong, maybe you just forget `@import` scss file

**Comment by cyiannatsos** [comment]
Will do that apologies for asking in the repo issues. In case you want to test for verification in the documentation here's the files. npm install and you're good to go.

[react-setup.zip](https://github.com/webpack-contrib/mini-css-extract-plugin/files/1942348/react-setup.zip)
