### ISSUE TITLE
Generated hash on root file

### ISSUE THREAD

**Issue by tomxhu** [webpack-contrib/mini-css-extract-plugin#111]
Is there a way to generate a hash for the root css even if there aren't any chunks for it?
![untitled](https://user-images.githubusercontent.com/3477616/39213856-a67a2c78-47e0-11e8-9224-0ba5e957843c.png)

Is this coming from the default output location?

**Comment by evilebottnawi** [comment]
No, if you don't do import css files it is impossible to generate hash, you can use `CopyWebpackPlugin` for this - just copy source from src location and add hash. Thanks!

**Comment by tomxhu** [comment]
widget.css is generated from mini-css-extract plugin, not a static file

**Comment by evilebottnawi** [comment]
@tomxhu use options for plugin
```
      filename: "[name]-[contenthash].css",
      chunkFilename: "[name]-[contenthash].css"
```

**Comment by tomxhu** [comment]
I have ```const extractCssPlugin = new MiniCssExtractPlugin({
    name: `assets/[name]-[contenthash]${getFilenameSuffix(ENV)}.css`,
    chunkFilename: 'assets/[name]-[contenthash].css',
  })``` for my plugins, do I need to use that for my loader as well?
