### ISSUE TITLE
"installedCssChunks is not defined" after 2.9.0 update

### ISSUE THREAD

**Issue by michaelfaith** [webpack-contrib/mini-css-extract-plugin#1110]
After upgrading from 2.8.1 to 2.9.0 (and then 2.9.1), we're seeing this error repeatedly in the Chrome dev console.  We didn't change any aspect of our config or css loading set-up.

![image](https://github.com/user-attachments/assets/55c85e4e-0cc6-4091-bc4e-04be1b779e6e)

I believe this is related to this change: https://github.com/webpack-contrib/mini-css-extract-plugin/pull/1043

Plugin config
```js
...
  {
        test: /\.less$/,
        include: [path.join(appDirectory, 'stylesheets')],
        exclude: [],
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {
              sourceMap: DEV,
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                plugins: [require('autoprefixer')],
              },
              sourceMap: DEV,
            },
          },

          {
            loader: 'less-loader',
            options: {
              lessOptions: {
                math: 'always',
              },
              sourceMap: DEV,
            },
          },
        ],
      },
...
plugins: [
   ...
  new MiniCssExtractPlugin({
      experimentalUseImportModule: true,
      filename: '[name].[contenthash:20].css',
    }),
  ...
]

```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 1.10 GB / 36.00 GB
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.12.2/bin/npm
  Browsers:
    Chrome: 127.0.6533.120
    Safari: 17.6
  Packages:
    babel-loader: ^9.1.3 => 9.1.3 
    css-loader: ^6.11.0 => 6.11.0 
    expose-loader: ^5.0.0 => 5.0.0 
    json-loader: ~0.5.7 => 0.5.7 
    less-loader: ^12.2.0 => 12.2.0 
    postcss-loader: ^8.1.1 => 8.1.1 
    source-map-loader: ^5.0.0 => 5.0.0 
    style-loader: ^4.0.0 => 4.0.0 
    webpack: ^5.93.0 => 5.93.0 
    webpack-cli: ^5.1.4 => 5.1.4 
```

**Comment by alexander-akait** [comment]
Please create reproducible test repo, otherwise I can't help, thank you

**Comment by lukpsaxo** [comment]
We are also seeing the issue, in watch mode only and only on certain usage patterns of split bundles. We will try and help with more info by debugging within a few weeks unless someone beats us to it.

**Comment by michaelfaith** [comment]
> We will try and help with more info by debugging within a few weeks unless someone beats us to it.

Thanks, that would be super helpful.  We're in a large private monorepo, and it'll be a bit before I can try and create a public repro to share.

**Comment by alexander-akait** [comment]
Yeah, I am glad to help with it, but wihtour more information, it is hard, it happends only in 2.9.0?

**Comment by michaelfaith** [comment]
> Yeah, I am glad to help with it, but wihtour more information, it is hard, it happends only in 2.9.0?

I appreciate it.  Yes, we were on 2.8.1 for a while without issue.  This only started happening after updating to 2.9, and I believe it's related to that change I linked specifically.

**Comment by alexander-akait** [comment]
I think it can be due it - https://github.com/webpack-contrib/mini-css-extract-plugin/commit/ee25e51a8d06292dd8643f5bf1d6c4faa51c4f4c, do you have `Preload` or `Prefetch` for you dynamic chunks?

**Comment by alexander-akait** [comment]
Looks like `withPrefetch && hasCssMatcher` is `true`, but it should happens, can you try to debug it locally?

**Comment by michaelfaith** [comment]
For sure, I can debug it locally.  I'll have to set that branch back up, but that won't take a long.

**Comment by michaelfaith** [comment]
We aren't doing any prefetching ourselves, but from what I can tell, this seems to always be breaking on a chunk that's coming from a library we're using that's calling `import` with `webpackPrefetch: true`.  That chunkId seems to always be the one that's going through this mini-css code where `installedCssChunks` is undefined:

![image](https://github.com/user-attachments/assets/c52ac4fd-eb95-4846-9dd3-5c03677e2296)

The library in question is just passing the import function until `React.lazy`.

**Comment by alexander-akait** [comment]
@michaelfaith Maybe you can try to create reproducible test repo with this library, look like you have CSS chunks before, but then it was removed for bundle, but runtime code already was created

**Comment by Plonq** [comment]
I am running into this issue as well, in an Angular app. mini-css version is 2.9.0. If I change all three instances of the `/* webpackPrefetch: true */` magic comment to `/* webpackPrefetch: false */` then the error goes away.

I'll try to provide a minimal repro if I can.

**Comment by alexander-akait** [comment]
@Plonq Where do you change `/* webpackPrefetch: false */`? Can you show me a code?

**Comment by alexander-akait** [comment]
If someone gives me the code that causes this problem, then I will be able to fix it, logically this cannot happen at all

**Comment by Plonq** [comment]
> @Plonq Where do you change `/* webpackPrefetch: false */`? Can you show me a code?

If you have no instances of `/* webpackPrefetch: true */` then you must not have the same issue as me. But, as per [the docs](https://webpack.js.org/api/module-methods/), it's a magic method used in a dynamic import, like so:

```javascript
import(
  /* webpackPrefetch: true */
  "some-file.js"
);
```

**Comment by alexander-akait** [comment]
@Plonq Can you run `npm ls webpack` and `npm ls mini-css-extract-plugin`?

Also can you put here - https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L904
```
console.log(chunkMap);
console.log(runtimeRequirements.has(RuntimeGlobals.ensureChunkHandlers));
console.log(withLoading);
console.log(withPrefetch);
console.log(hasCssMatcher); 
console.log(conditionMap);
```

It is necessary to understand why the prefetch generated, but the generation of runtime for chunks does not occur, very weird.

and show me values?

**Comment by alexander-akait** [comment]
I was able to reproduce

**Comment by alexander-akait** [comment]
Please try - https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v2.9.2

**Comment by Plonq** [comment]
v2.9.2 seems to fix it. The prefetch is still not working, however I've confirmed that is actually an unrelated, pre-existing issue (likely with webpack).

FWIW, I had to override the version like so:

```json
  "overrides": {
    "@angular-devkit/build-angular": {
      "mini-css-extract-plugin": "2.9.2"
    }
  }
```

NPM LS:

```
❯ npm ls mini-css-extract-plugin
REDACTED@0.0.0 /Users/REDACTED
└─┬ @angular-devkit/build-angular@18.2.10 overridden
  └── mini-css-extract-plugin@2.9.2 overridden
```

```
❯ npm ls webpack
REDACTED@0.0.0 /Users/REDACTED
├─┬ @angular-devkit/build-angular@18.2.10
│ ├─┬ @angular-devkit/build-webpack@0.1802.10
│ │ └── webpack@5.95.0 deduped
│ ├─┬ @ngtools/webpack@18.2.10
│ │ └── webpack@5.95.0 deduped
│ ├─┬ babel-loader@9.1.3
│ │ └── webpack@5.95.0 deduped
│ ├─┬ copy-webpack-plugin@12.0.2
│ │ └── webpack@5.94.0 deduped
│ ├─┬ css-loader@7.1.2
│ │ └── webpack@5.95.0 deduped
│ ├─┬ less-loader@12.2.0
│ │ └── webpack@5.95.0 deduped
│ ├─┬ mini-css-extract-plugin@2.9.0
│ │ └── webpack@5.94.0 deduped
│ ├─┬ postcss-loader@8.1.1
│ │ └── webpack@5.95.0 deduped
│ ├─┬ sass-loader@16.0.0
│ │ └── webpack@5.95.0 deduped
│ ├─┬ source-map-loader@5.0.0
│ │ └── webpack@5.95.0 deduped
│ ├─┬ webpack-dev-middleware@7.4.2
│ │ └── webpack@5.95.0 deduped
│ ├─┬ webpack-dev-server@5.0.4
│ │ └── webpack@5.95.0 deduped
│ ├─┬ webpack-subresource-integrity@5.1.0
│ │ └── webpack@5.95.0 deduped
│ └─┬ webpack@5.94.0
│   └─┬ terser-webpack-plugin@5.3.10
│     └── webpack@5.95.0 deduped
├─┬ @types/webpack@5.28.5
│ └── webpack@5.95.0
├─┬ copy-webpack-plugin@11.0.0
│ └── webpack@5.95.0 deduped
├─┬ html-webpack-plugin@5.6.0
│ └── webpack@5.95.0 deduped
├─┬ moment-locales-webpack-plugin@1.2.0
│ └── webpack@5.95.0 deduped
└─┬ webpack-shell-plugin-next@2.3.2
  └── webpack@5.95.0 deduped
```

**Comment by alexander-akait** [comment]
> The prefetch is still not working

That's weird, has this ever worked before? Maybe you can recreate the structure?

**Comment by michaelfaith** [comment]
Thanks so much for sticking with this issue, even though I wasn't able to put together a repo.  Really appreciate it.

**Comment by Plonq** [comment]
> > The prefetch is still not working
> 
> That's weird, has this ever worked before? Maybe you can recreate the structure?

I'm sure it worked at some point when I first added the magic comment, but it was a while ago so who knows when it stopped working.

Echoing michael, appreciate the responsiveness!
