### ISSUE TITLE
Multiple entrypoints with one output file per entrypoint

### ISSUE THREAD

**Issue by ezzatron** [webpack-contrib/mini-css-extract-plugin#116]
Is this supported by MCEP? It was possible in ETP, because each loader was tied to an instance of the plugin:

```js
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const path = require('path')

const themeA = path.resolve(__dirname, 'src/theme-a.scss')
const themeB = path.resolve(__dirname, 'src/theme-b.scss')

const extractA = new ExtractTextPlugin({filename: 'theme-a.css'})
const extractB = new ExtractTextPlugin({filename: 'theme-b.css'})

module.exports = {
  entry: [themeA, themeB],
  module: {
    rules: [
      {
        test: themeA, 
        loader: extractA.extract({use: ['css-loader', 'sass-loader']}),
      },
      {
        test: themeB, 
        loader: extractB.extract({use: ['css-loader', 'sass-loader']}),
      },
    ],
  },
  plugins: [extractA, extractB]
}
```

But MCEP I'm not sure if it's possible to achieve the same thing, because there is only one loader (`MiniCssExtractPlugin.loader`), and so it cannot distinguish which inputs belong to which instance of MiniCssExtractPlugin.

**Comment by evilebottnawi** [comment]
You don't need multiple instances, please read https://github.com/webpack-contrib/mini-css-extract-plugin/issues/115

**Comment by ezzatron** [comment]
Thanks for pointing me at that issue. I managed to get multiple themes extracted, but unfortunately it completely stops ALL the JavaScript in my main bundle from running. My React app basically becomes a blank page.

I also think I hit #85, because each theme is also outputting a useless `.js` file. I'm not sure if that's related to the whole app breaking, but I noticed [this comment](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/85#issuecomment-379472847) which sounds similar:

> but then the SPA doesn't load and fails silently

I put together a GitHub repo to reproduce the problem over at [ezzatron/webpack-4-test-sass-themes](https://github.com/ezzatron/webpack-4-test-sass-themes). If you run it as-is, you get the themes working, but no JavaScript runs. If you remove the `cacheGroups` configuration, you get JavaScript running, but the themes no longer work.

I have no idea what to try next. It would help if I knew where to look for the API docs for the `module` argument you get when providing a cache group `test` as a function, or the docs for what `enforce` is supposed to do.

**Comment by evilebottnawi** [comment]
@ezzatron `test: function (...argf) => { console.log(args); }` and you can see all modules

**Comment by lukepolo** [comment]
@ezzatron Yah #85 is why your js broke, if you include the extra emitted JS file it should work fine.

**Comment by evilebottnawi** [comment]
@ezzatron extract `theme/blue/main` and `theme/green/main` css to own bundle

**Comment by ezzatron** [comment]
@evilebottnawi Thank you, I managed to get it working using multiple bundles! 

The only (minor) issue I have now is the useless JS file that is produced by each of the CSS-only bundles, but I assume that's more of a general problem with Webpack bundles, rather than something caused by MCEP specifically.

For anyone in a similar situation, this is the magic sauce I needed:

```js
const HtmlWebPackPlugin = require("html-webpack-plugin")
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const path = require('path')

const main = path.resolve(__dirname, 'src')
const themeBlue = path.resolve(__dirname, 'src/theme-blue.scss')
const themeGreen = path.resolve(__dirname, 'src/theme-green.scss')

module.exports = {
  mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
  plugins: [
    new HtmlWebPackPlugin({
      filename: 'theme/blue/index.html',
      chunks: ['main', 'theme/blue/main'],
    }),
    new HtmlWebPackPlugin({
      filename: 'theme/green/index.html',
      chunks: ['main', 'theme/green/main'],
    }),
    new MiniCssExtractPlugin(),
  ],
  entry: {
    main: main,
    'theme/blue/main': themeBlue,
    'theme/green/main': themeGreen,
  },
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
      },
    ]
  },
  optimization: {
    splitChunks: {
      cacheGroups: {
        themeBlue: {
          test: themeBlue,
          name: 'theme/blue/main',
          chunks: 'all',
        },
        themeGreen: {
          test: themeGreen,
          name: 'theme/green/main',
          chunks: 'all',
        },
      },
    },
  },
}
```

Which produces this directory structure when built:

```
dist/
  theme/
    blue/
      index.html
      main.css
      main.js (useless)
    green/
      index.html
      main.css
      main.js (useless)
  main.js
```

**Comment by ezzatron** [comment]
I also updated [ezzatron/webpack-4-test-sass-themes](https://github.com/ezzatron/webpack-4-test-sass-themes) with the working config.
