### ISSUE TITLE
Hashing Issue. Changing styles cause invalidate script hash

### ISSUE THREAD

**Issue by mishelen** [webpack-contrib/mini-css-extract-plugin#117]
maybe I'm not in the right place writing. But the situation is that after migration to Webpack 4 I had to change the style extractor to `mini-css-extract-plugin` from `extract-text-webpack-plugin`. From now on hashing began not to work properly: if I change styles, the hash of entry scripts changes, but if I change scripts, the hash of styles does not change.

I use the same settings as I did with webpack 3. Then I studied the problem length and breadth. Solving is simple: 
```js
output: {
        filename: '[name].[chunkhash].js'
},
plugins: [
        new webpack.HashedModuleIdsPlugin(),
        new ExtractCSS({
            filename: '[name].[contenthash].css'
        })
]
```
\+ extract runtime chunk aka manifest

But now I dont have any glue.
I'm just created repo with this issue: https://github.com/mishelen/reproduce_hash_invalidation  webpack settings are in `config` folder

ubuntu 16.04.04
node v8.11.1
[used packages version](https://github.com/mishelen/reproduce_hash_invalidation/blob/master/package.json#L17)

**Comment by evilebottnawi** [comment]
@mishelen yes, it is bug, not in plugin, inside webpack. Ref https://github.com/webpack/webpack/issues/7138. Thanks for issue

**Comment by mishelen** [comment]
@evilebottnawi Thank you. It remains only to add +1 to the specified issue and add a reference to my repo
