### ISSUE TITLE
can't get my css served in a react universal app!

### ISSUE THREAD

**Issue by elhariri** [webpack-contrib/mini-css-extract-plugin#120]
Hi, i'm trying to build an isomorphic react application, i've added mini-css-extract-plugin in my client webpack config. in my server i'm using renderToString and pushing the string in my html like this : 

```
<!DOCTYPE html>
  <html>
    <head>
    // usual stuff
    </head>
    <body>
      <div id="app">
        ${html}   // here goes the rendered html
      </div>
      <script type="text/javascript"  src=".dist/public/bundle.js"></script>
    </body>
  </html>
```

the build is compiled perfectly but i can't get css on my page (the css file is imported in my root component app)

**Comment by evilebottnawi** [comment]
@elhariri can you create minimum reproducible test repo?

**Comment by elhariri** [comment]
@evilebottnawi i'm new to development in general and i'm afraid that it would take me a lot of time to create it (i'm creating for free a free educational wwebsite for a non lucratif association and it's really taking me a lot of time) so is it ok if i just copied my server, my client and server webpack config and my main react component files if it's ok i'll post them as soon as possible i don't have my laptop with me.

**Comment by evilebottnawi** [comment]
@elhariri feel free to ping me when you done this. Thanks minimum reproducible test repo it is hard to detect where problem happens

**Comment by elhariri** [comment]
i servit directly from the server with the renderFullPage function, if it's not a good practice please guide me

**Comment by evilebottnawi** [comment]
@elhariri i can't know it is good solution for your use case or not, please use for this `stackoverflow`, `gitter` or `slack`

**Comment by elhariri** [comment]
Oooh sorry, and thank you for your reply :).

**Comment by evilebottnawi** [comment]
@elhariri feel free to feedback if you some questions
