### ISSUE TITLE
when  the env is production,it generated css file is empty,but in development is right

### ISSUE THREAD

**Issue by dongqizhen** [webpack-contrib/mini-css-extract-plugin#122]
this is my config in config.js

const devMode = process.env.NODE_ENV !== 'production'

in optimization:

splitChunks: {
           
            cacheGroups: {
                styles: {
                  name: 'styles',
                  test: /\.scss|css|sass$/,
                  chunks: 'all',
                  enforce: true
                }
            }
        },

in rules:
            {
                test: /\.(sass|scss)$/,
                use:
                [
                    devMode ? 'style-loader' : MiniCssExtractPlugin.loader,
                    'css-loader',
                    'postcss-loader',
                    'sass-loader',
                ],
            }

in plugin:
new MiniCssExtractPlugin({
            filename: devMode ? 'css/[name].css' : 'css/[name].[hash].css',
            chunkFilename: devMode ? 'css/[id].css' : 'css/[id].[hash].css',
        })

the env is production that view  :
![7twx5zuw99 ibeo7tod79w](https://user-images.githubusercontent.com/23066771/39569726-a42988f0-4ef8-11e8-8df0-edab222cd906.png)

but in development :
![c4vky vqejzuc3 5 2 _pe](https://user-images.githubusercontent.com/23066771/39569753-b821f8ce-4ef8-11e8-8c29-5f8af2e3a298.png)

**Comment by evilebottnawi** [comment]
@dongqizhen please use for this `stackoverflow`, `gitter` or `slack`, it is bug tracker, not QA service. Thanks!

**Comment by weizheng1992** [comment]
Have you solved this problem, please? I've also met this problem.
