### ISSUE TITLE
Error: Didn't get a result from child compiler

### ISSUE THREAD

**Issue by michaelize** [webpack-contrib/mini-css-extract-plugin#126]
```
node: 8.9.4
OS: OSX
mini-css-extract-plugin: 0.4.0
```
I'm having the following error. I'm using vue-loader and @rails/webpacker

ERROR in ./node_modules/quill/dist/quill.snow.css (./node_modules/css-loader??ref--6-1!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader!./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader??ref--13-1!./node_modules/postcss-loader/lib??ref--13-2!./node_modules/quill/dist/quill.snow.css)
    Module build failed: Error: Didn't get a result from child compiler

css-loader config:
```
module.exports = {
  test: /\.css$/,
  use: [
    // 'vue-style-loader',
    MiniCssExtractPlugin.loader,
    {
      loader: 'css-loader',
      options: {
        minimize: !devMode,
        includePaths: [
          join(baseDir, 'node_modules')
        ],
        importLoaders: 1,
        modules: true,
        sourceMap: true
      }
    },
    {
      loader: 'postcss-loader',
      options: {
        ident: 'postcss',
        plugins: () => [
          require('postcss-import'),
          require('postcss-cssnext')({
            features: {
              customProperties: {
                warnings: false
              }
            }
          }),
          require('autoprefixer')(),
          require('cssnano')()
        ],
        sourceMap: true
      }
    },
    'resolve-url-loader'
  ]
}
```
optimization config:
```
{
    minimizer: [
      // new UglifyJsPlugin({
      //   cache: true,
      //   parallel: true,
      //   sourceMap: false,
      //   uglifyOptions: {
      //     mangle: false,
      //     compress: false // { unused: false, drop_console: env.NODE_ENV === 'production' }
      //   }
      // }),
      new OptimizeCSSAssetsPlugin({})
    ],
    splitChunks: {
      chunks: 'async',
      minSize: 30000,
      minChunks: 1,
      maxAsyncRequests: 5,
      maxInitialRequests: 3,
      automaticNameDelimiter: '~',
      name: true,
      cacheGroups: {
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          priority: -10
        },
        default: {
          minChunks: 2,
          priority: -20,
          reuseExistingChunk: true
        },
        styles: {
          name: 'styles',
          test: /\.css$/,
          chunks: 'all',
          enforce: true
        }
      }
    }
  }
```

I am importing css files inside vue component:
```
import 'quill/dist/quill.core.css'
import 'quill/dist/quill.snow.css'
import 'quill/dist/quill.bubble.css'
```

vue-loader config:
```
module.exports = {
  test: /\.vue(\.erb)?$/,
  loader: 'vue-loader',
  options: {
    loaders: {
      js: 'babel-loader',
      file: 'file-loader',
      css: 'vue-style-loader!css-loader!sass-loader',
      scss: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=false',
      sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=true'
    }
  }
}
```

Appreciate if someone can show me any hints where I did wrong.

Thanks!

**Comment by evilebottnawi** [comment]
@michaelize Can you create minimum reproducible test repo?

**Comment by vasivas** [comment]
@evilebottnawi https://github.com/vasivas/mini-css-extract-plugin-bug-demo

**Comment by evilebottnawi** [comment]
@vasivas I clone your repo and run `npm run start` all works fine. Please provide reproducible test repo and describe steps how reproduce

**Comment by evilebottnawi** [comment]
@vasivas also please provide **minimum** reproducible test repo, because i don't have many time looks on you configuration and other unnecessary stuff

**Comment by vasivas** [comment]
@evilebottnawi  minimum? it is minimum.. if you get rid of webpack-hot-middleware webpack-hot-server-middleware and ssr, the mini-css-extract-plugin is likely to work.

**Comment by evilebottnawi** [comment]
Diplicate https://github.com/webpack-contrib/mini-css-extract-plugin/issues/34. `mini-css-extract-plugin` doesn't support hrm right now, feel free to send PR to fix it

**Comment by vasivas** [comment]
@evilebottnawi then open my issues in extract-text-webpack-plugin. It supports hmr!

**Comment by evilebottnawi** [comment]
@vasivas webpack@4 doesn't support `ETWP` you should send PR with support hmr to this plugin

**Comment by glook** [comment]
retuned back to ```extract-text-webpack-plugin@next```. Now it works fine!

**Comment by StefanoSega** [comment]
I'm using v.0.5.0 and I get the same error, but doesn't seem related to HMR, since I'm not using it:

```
const webpack = require('webpack');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = [{
  name: 'react-app',
  mode: 'production',
  devtool: 'eval',
  cache: true,
  entry: {
    main: [
      'babel-polyfill',
      './react/index.tsx',
    ],
    vendor: [
      'react',
      'react-dom',
    ],
  },
  output: {
    path: `${__dirname}/dist/__build__`,
    filename: '[name].js',
    chunkFilename: '[name].js',
    publicPath: '/__build__/',
  },
  module: {
    rules: [{
      test: /\.(ts|js)x?$/,
      loader: 'babel-loader',
      exclude: [/node_modules/],
    }, {
      test: /\.(ts|tsx)?$/,
      enforce: 'pre',
      loader: 'tslint-loader',
      exclude: [/node_modules/],
      options: {
        emitErrors: true,
      },
    }, {
      test: /\.scss$/,
      resourceQuery: /^\?raw$/,
      use: [MiniCssExtractPlugin.loader, {
        loader: 'css-loader',
        options: {
          modules: true,
          sourceMap: true,
          camelCase: false,
          localIdentName: '[local]',
        },
      }, 'sass-loader', 'postcss-loader'],
    }, {
      test: /\.scss$/,
      use: [MiniCssExtractPlugin.loader, {
        loader: 'css-loader',
        options: {
          modules: true,
          sourceMap: true,
          camelCase: true,
          localIdentName: '[path]___[name]__[local]___[hash:base64:5]',
        },
      }, 'sass-loader', 'postcss-loader'],
    }],
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js'],
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        CLIENT: JSON.stringify(true),
      },
    }),
    new webpack.IgnorePlugin(/^vertx$/),
    new MiniCssExtractPlugin({
      filename: "style.css",
      chunkFilename: "[id].css"
    }),
  ],
  optimization: {
    splitChunks: {
      cacheGroups: {
        vendor: {
          test: /node_modules/,
          name: 'vendor',
          enforce: true
        },
      },
    },
  },
}];
```

If I don't include .scss files with the `?raw` querystring everything works fine, the error comes when I try something like `import './index.scss?raw';` because I want to include a certain .scss file without changing the classnames since they're 3rd party libraries.

**Comment by davidfurlong** [comment]
Im getting this on production builds which dont use HMR

**Comment by mercuriete** [comment]
@davidfurlong thanks, you saved me lot of time.

**Comment by fancyboynet** [comment]
@davidfurlong can you paste the config please?I am still a little confused, thanks.

**Comment by dtothefp** [comment]
If HotModuleReplacementPlugin as option multiStep: true this happens

**Comment by rodrigoriome** [comment]
@davidfurlong is right, this error happens when webpack has 2 `module.rules` for same file type. The simplest way I've found to stop the error is to adding another rule with a prefix on it. In my case I am using React from Create-React-App and I don't pretend to eject config so soon.

This is what you need to insert in your configuration override file (i.e. config-overrides.js):

```javascript
{
    test: /\custom\.s[ac]ss$/,
    // any loader or other configurations you like
    // use: [ ... ]
}
```

**Comment by ejoo** [comment]
> Im getting this on production builds which dont use HMR. Turned out to be a result of having two loaders which matched the file

I didn't what he meant.

**Comment by mercuriete** [comment]
> > Im getting this on production builds which dont use HMR. Turned out to be a result of having two loaders which matched the file
> 
> I didn't get what he meant.

@ejoo 
If you have two loaders that match the same regular expresion, this fail happen.

for example:

```

  rules: [
    {
      test: /badregularexpresion$/,
      use: {
        loader: 'first-loader',
      }
    },
      test: /badregularexpresion$/,
      use: {
        loader: 'second-loader',
      }
    },
  ]
```

**Comment by ejoo** [comment]
```
{
        test: /\.s(a|c)ss$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              // you can specify a publicPath here
              // by default it uses publicPath in webpackOptions.output
              // publicPath: "../",
              hmr: false
            }
          },
          {
            loader: "vue-style-loader"
          },
          {
            loader: "css-loader"
          },

          { loader: "postcss-loader" }, // "sass-loader"
          {
            loader: "sass-loader",
            options: {
              implementation: require("node-sass"),
              sassOptions: {
                importer: magicImporter()
              }
            }
          }
        ]
      },
```

@mercuriete I'm getting the same error from the above rule. Do you think what might be causing this issue?

**Comment by xuesongde** [comment]
I @import a .scss file in a .less file also got the same error.  Keep in mind use the same file type.

**Comment by mercuriete** [comment]
@ejoo im sorry.
I dont know exactly what your problem os but...
Ussually you have to create 2 diferentes rules.
One for including node_modules and another excluding node_modules.
And i preffer to do one rule per extensión.
I dont like s(a|s)es regular expression if you are not knowing what is going on.

I would start doing lot of simple rules and then merge toghether once I understand what is going on.

Sorry for not being helpful for you. :(
