### ISSUE TITLE
hanging / not starting CircleCI tests

### ISSUE THREAD

**Issue by DanielRuf** [webpack-contrib/mini-css-extract-plugin#129]
All current tests are pending and there is no CircleCI config file in the repository.

https://github.com/webpack-contrib/mini-css-extract-plugin/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by d3viant0ne** [comment]
@DanielRuf rebase and it will pickup the new config. Sorry, looks like a PR that wasn't merged

**Comment by DanielRuf** [comment]
Thanks for taking care of it 👍 =)
