### ISSUE TITLE
Module build failed: Error: Didn't get a result from child compiler

### ISSUE THREAD

**Issue by vasivas** [webpack-contrib/mini-css-extract-plugin#131]
> ERROR in ./app/routes/hello-route/hello.style.css
> Module build failed: Error: Didn't get a result from child compiler
>     at childCompiler.runAsChild (/home/ivan/projects/react-ssr-template/node_modules/mini-css-extract-plugin/dist/loader.js:127:23)
>     at compile (/home/ivan/projects/react-ssr-template/node_modules/webpack/lib/Compiler.js:242:11)
>     at hooks.afterCompile.callAsync.err (/home/ivan/projects/react-ssr-template/node_modules/webpack/lib/Compiler.js:487:14)
>     at _err1 (eval at create (/home/ivan/projects/react-ssr-template/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:29:1)
>     at /home/ivan/projects/react-ssr-template/node_modules/awesome-typescript-loader/src/instance.ts:448:4
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ivan/projects/react-ssr-template/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:16:1)
>     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/ivan/projects/react-ssr-template/node_modules/tapable/lib/Hook.js:35:21)
>     at compilation.seal.err (/home/ivan/projects/react-ssr-template/node_modules/webpack/lib/Compiler.js:484:30)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ivan/projects/react-ssr-template/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
>     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/ivan/projects/react-ssr-template/node_modules/tapable/lib/Hook.js:35:21)
>  @ ./app/routes/hello-route/hello-route.ts 1:0-34 1:0-34
>  @ ./app/routes/hello-route/HelloRouteLoadable.tsx
>  @ ./app/App.tsx
>  @ ./client/client.tsx
>  @ multi webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000&reload=false&quiet=false&noInfo=false react-hot-loader/patch ./client/client.tsx

```
const path = require('path');

const webpack = require('webpack');

const {
    HotModuleReplacementPlugin,
    NoEmitOnErrorsPlugin,

    DefinePlugin,
    DllReferencePlugin
} = webpack;

const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const ReactLoadablePlugin = require('@7rulnik/react-loadable/webpack').ReactLoadablePlugin;



module.exports = {
    name: 'client',
    mode: 'development',
    target: 'web',
    context: path.resolve(__dirname,'src'),
    entry: [
            'webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000&reload=false&quiet=false&noInfo=false',
            'react-hot-loader/patch',
            path.join(__dirname, 'src','client','client.tsx')
        ],
    output: {
        publicPath: "/static/",
        path: path.join(__dirname,'dest'),
        filename: 'client.js',
        chunkFilename:"[name].js",
        libraryTarget: "umd2",
        globalObject: "this"
    },
    resolve: {
        extensions: [".ts", ".tsx", ".js", ".css", ".json"],
        modules: ["node_modules"],
        alias: {
            'react-loadable':'@7rulnik/react-loadable',
            '@7rulnik/react-loadable':'@7rulnik/react-loadable',

            /** routes */

            'hello-route':path.join(__dirname,'src','app','routes','hello-route','hello-route.ts'),
            'world-route':path.join(__dirname,'src','app','routes','world-route','world-route.ts'),

            /** ------ */

        }
    },
    externals: {
    },
    devtool: 'cheap-inline-module-source-map',
    node:{
        fs:'empty'
    },
    module:{
        noParse:/\.json$/,
        rules:[
            {
                test: /(\.ts|\.tsx)$/,
                use: [
                    {
                        loader:'awesome-typescript-loader',
                        options: {
                            configFileName:path.join(__dirname,'tsconfig.dev.ssr.client.json')
                        }
                    }
                ],
                include: [path.join(__dirname,'src')],
                exclude: [/node_modules/, /\*\.spec.(ts|tsx)$/]
            },
            {
                test: /\.css$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    // {loader: 'style-loader', options: {sourceMap: true}},
                    {loader: 'css-loader', options: {sourceMap: true}},
                ]
            },
            {
                test: /\.json$/,
                use: 'json-loader',
                exclude:[/node_modules/]
            },
        ]
    },
    plugins: [
        new HotModuleReplacementPlugin({
            multiStep:true
        }),
        new NoEmitOnErrorsPlugin(),

        new DllReferencePlugin({
            context: path.join(__dirname, 'dest'),
            manifest: require('./dest/root.dll.manifest.json'),
            sourceType: 'umd2',
        }),
        new DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify('development')
            }
        }),

        new MiniCssExtractPlugin({
            filename: "[name].css",
            chunkFilename: "[id].css"
        }),
        new ReactLoadablePlugin({
            filename:path.join(__dirname,'dest','loadable.manifest.json')
        }),
    ]
};

```

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/mini-css-extract-plugin/issues/126, please provide minimum reproducible test repo

**Comment by vasivas** [comment]
@evilebottnawi https://github.com/vasivas/mini-css-extract-plugin-bug-demo

**Comment by dtothefp** [comment]
If HotModuleReplacementPlugin as option `multiStep: true` this happens. Even without it HMR doesn't work for me 😢

**Comment by divyam5-30** [comment]
Error: Didn't get a result from child compiler .
Im using Nextjs  version 9.0.2
webpack 4.32.1

**Comment by divyam5-30** [comment]
const withSass = require("@zeit/next-sass");
const nextConfig = require("./config");

const withCSS = require('@zeit/next-css')


module.exports = withCSS(withSass(
    {
    cssModules: true,
    cssLoaderOptions: {
      importLoaders: 1,
      localIdentName: "[local]___[hash:base64:5]",
    },
    webpack (config, options) {
      config.module.rules.push({
            test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
            use: {
                loader: 'url-loader',
                options: {
                    limit: 100000
                }
            }
        });

    return {...nextConfig(config)};
  }
}));

this is my next.config.js file

**Comment by qipoy** [comment]
yeah i have the same issue

i use next 9.5 and antd latest

**Comment by jsking216** [comment]
> yeah i have the same issue
> 
> i use next 9.5 and antd latest

Were you able to solve this?  Having the same problem with a next 9.5 app.

**Comment by qipoy** [comment]
> > yeah i have the same issue
> > i use next 9.5 and antd latest
> 
> Were you able to solve this? Having the same problem with a next 9.5 app.

i am sory for late response.
i solve this with both import withCSS and withLESS 


`module.exports = withBundleAnalyzer(
  withCSS(
    withLess({})
 )) `
