### ISSUE TITLE
mini-css-extract-plugin + write-file-webpack-plugin 

### ISSUE THREAD

**Issue by avivaWang** [webpack-contrib/mini-css-extract-plugin#139]
I'm using the two plugins(mini-css-extract-plugin + write-file-webpack-plugin ), When the css is change, I want mini-css-extract-plugin generate a css file and use write-file-webpack-plugin to write the new chunks to the disk. 
but when local css is changing, there is no new css files write to disk. how to solve this problem?
below is my webpack-config.
`/**
 * @file
 * @author by aviva on 2018/3/14.
 */
const path = require('path');
const webpack = require('webpack');
const HtmlWebPackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const HtmlInlineSourceWebpackPlugin = require('@super-fe/BdrainfnResourceInline');
const WriteFilePlugin = require('write-file-webpack-plugin');
const moduleName = 'landing-boxapp';
const {execSync, spawn} = require('child_process');
const {getExceptCss, copyFile} = require('./tools/utils');
const syncCssList = getExceptCss();
const cssReg = new RegExp(`(${syncCssList.concat(['base', 'BdrainrwUilib']).join('|')}).*\.css$`);
copyFile(syncCssList, './node_modules/@super-fe/', './output/landing-boxapp/components/');
copyFile('head.js',
    './node_modules/@super-fe/BdrainfnMonitor/src/',
    './output/landing-boxapp/static/js/BdrainfnMonitor/');
const onlineDomain = /https:\/\/gss0.bdstatic.com\/5bd1bjqh_Q23odCf\/static\/landing-boxapp/g;
module.exports = {
    entry: {
        news: './static/js/news/index'
    },
    output: {
        path: `${__dirname}/output/${moduleName}/`,
        filename: 'static/js/[name]/index.js'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                include: [
                    path.resolve(__dirname, 'static'),
                    path.resolve(__dirname, 'node_modules/@super-fe')
                ],
                use: {
                    loader: 'babel-loader'
                }
            },
            {
                test: /\.css$/,
                exclude: cssReg,
                use: ['style-loader', {
                    loader: 'css-loader',
                    options: {
                        modules: true,
                        minimize: true
                    }
                }]
            },
            {
                test: cssReg,
                use: [
                    MiniCssExtractPlugin.loader,
                    {
                        loader: 'css-loader',
                        options: {
                            minimize: true,
                            modules: true,
                            localIdentName: '[local]'
                        }
                    }
                ]
            },
            {
                test: /\.(png|jpg|gif)/,
                use: {
                    loader: 'url-loader'
                }
            }
        ]
    },
    plugins: [
        new HtmlWebPackPlugin({
            inject: false,
            cache: false,
            template: './template/news/index.tpl',
            filename: `${__dirname}/output/${moduleName}/news/index.tpl`
        }),
        new CopyWebpackPlugin([
            {
                from: './template/layout.tpl',
                to: `${__dirname}/output/${moduleName}/layout.tpl`
            }
        ]),
        new CopyWebpackPlugin([
            {
                from: './static/js/lib',
                to: `${__dirname}/output/${moduleName}/static/js/lib`
            }
        ]),
        new MiniCssExtractPlugin({
            filename: 'style_[name].css'
        }),
        new WriteFilePlugin({
            useHashIndex: false,
            log: true
        }),
        new HtmlInlineSourceWebpackPlugin({
            option: {
                rootpath: path.resolve(__dirname, './output'),
                compress: true
            }
        }),
        new webpack.NamedModulesPlugin(),
        // new HotReloadCssPlugin()
        // new webpack.HotModuleReplacementPlugin()
    ],
    devServer: {
        contentBase: __dirname + '/output',
        publicPath: __dirname + '/output',
        hot: false,
        compress: false,
        port: 9000,
        disableHostCheck: true
    }
};`

**Comment by evilebottnawi** [comment]
@avivaWang please create minimum reproducible test repo, it is hard read code from issue without normal formatting
