### ISSUE TITLE
this[NS] is not a function

### ISSUE THREAD

**Issue by grrowl** [webpack-contrib/mini-css-extract-plugin#140]
Logging at `mini-css-extract-plugin/dist/loader.js:147`, `NS` is `/Users/tom/Documents/projectName/node_modules/mini-css-extract-plugin/dist`. It then calls `this[NS](text)`, which fails as `this[NS]` is `undefined`.

Happens on `0.5.0` and `0.4.0` too. What gives?

**Comment by silaike** [comment]
did you add `new MiniCssExtractPlugin()` in the plugins array?

**Comment by marvinhagemeister** [comment]
Duplicate of #73

**Comment by evilebottnawi** [comment]
@marvinhagemeister duplicate, thanks!
