### ISSUE TITLE
link=preload support

### ISSUE THREAD

**Issue by Medsestrun** [webpack-contrib/mini-css-extract-plugin#142]
Hi.
As I notices from https://github.com/webpack-contrib/mini-css-extract-plugin#using-preloaded-or-inlined-css href on link should work for ssr to prevent css files duplications, but it doesnt work for <link rel=preload href="">. It generates another <link rel=stylesheet href="">. Custom hack with empty style tag with data-href helps to remove duplicate, but I think this is not right way to handle it.

Maybe the source of the problem is https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L329

**Comment by antonpsaputro** [comment]
I have this issue also. Latest lighthouse test recommends as such: 
`<link rel="preload" href="styles.css" as="style">`
https://developers.google.com/web/tools/lighthouse/audits/preload

Did you find a solution @Medsestrun

**Comment by occar421** [comment]
I met this and using preload-webpack-plugin resolved it in my case.
(with `include: "allAssets"` and like `fileWhitelist: [/styles(\.[0-9a-f]+)?\.css$/]`)

**Comment by dagerikhl** [comment]
Any update on this? I might be missing something and this is already possible, but if this is possible to achieve, it would be a very nice feature to have. And if it's possible without having to include other packages, that would be even better.

**Comment by samjmckenzie** [comment]
Would love support for this.

**Comment by junibrosas** [comment]
preload-webpack-plugin is nice but will only work in tandem with html-webpack-plugin. My case is server-side rendering and I have no idea how to do it yet.

**Comment by ScriptedAlchemy** [comment]
I’ll built this soon under. 

https://github.com/ScriptedAlchemy/webpack-external-import


Of course contributions are welcome

**Comment by MikelPro** [comment]
For those who are still waiting, there is workaround for mini-css-extract-plugin > 1.2.0 :

`
      new MiniCssExtractPlugin({
        ...yourConfig,
        insert: (linkTag) => {
            const preloadLinkTag = document.createElement('link')
            preloadLinkTag.rel = 'preload'
            preloadLinkTag.as = 'style'
            preloadLinkTag.href = linkTag.href

            document.head.appendChild(preloadLinkTag, reference)
            document.head.appendChild(linkTag, reference)
        }
      })
`

**Comment by SandroMiguel** [comment]
Hey @MikelPro, thank you for your solution. It works!
I just wonder why you append both `<link ...>` tags like this:
```
<link rel="preload" as="style" href="https://some-domain.local/public/css/670.css">
<link rel="stylesheet" type="text/css" href="/public/css/670.css">
```

**Comment by callmevladik** [comment]
> Hey @MikelPro, thank you for your solution. It works!
> I just wonder why you append both `<link ...>` tags like this:
> 
> ```
> <link rel="preload" as="style" href="https://some-domain.local/public/css/670.css">
> <link rel="stylesheet" type="text/css" href="/public/css/670.css">
> ```

Because rel="preload" just tells browser which resource should be available as soon as it is required for the rendering(like priority) and rel="stylesheet" actually loads this resource

**Comment by Kirsten1996** [comment]
Hi guys,

I'm using the razzle after js boilerplate and have been running into the preload key requests when trying to improve optimization, I'm using uglifyjs and mini css extract plugin and have added the above fix to my razzle.config file

new MiniCssExtractPlugin({
  filename: '[name].css',
  insert: function (linkTag) {
    const preloadLinkTag = document.createElement('link')
    preloadLinkTag.rel = 'preload'
    preloadLinkTag.as = 'style'
    preloadLinkTag.href = linkTag.href
    document.head.appendChild(preloadLinkTag)
    document.head.appendChild(linkTag)
  }
}),

However I'm not able to see where the preloaded chunks are being injected into the head, I only see the initial rel="stylesheet"

I'm using:
- "mini-css-extract-plugin": "^1.2.0",
- "uglifyjs-webpack-plugin": "^2.2.0"

![Capture](https://user-images.githubusercontent.com/36629912/128313510-ac58c18b-3924-4d52-b17e-b9671281d061.PNG)

Am I missing something in my configuration?

**Comment by grybykm** [comment]
@Kirsten1996 it doesn't work for me as well. Looks like the `insert` function is ignored or doesn't work in `mini-css-extract-plugin`
