### ISSUE TITLE
feat: allow the option filename to be a function

### ISSUE THREAD

**Issue by berthertogen** [webpack-contrib/mini-css-extract-plugin#143]
Can we allow the filename and chunkFilename passed in trought the constructor to be functions instead of string only?

In our case it would make it easy to toggle the [hashcontent] for some bundles. 
We would pass the option as followed: 
`filename: (chunk)  =>  chunk.name === "NotHashedBundle" ? '[name].css' : '[name].[contenthash].css'`

Might be worth noting that the latest version of webpack also supports something simular to this in their output.
eg: `filename: (data) => data.chunk.name === "NotHashedBundle" ? '[name].js' : '[name].[chunkhash].js'`

**Comment by evilebottnawi** [comment]
PR welcome :+1:

**Comment by berthertogen** [comment]
Ok, I'm on it

**Comment by glen-84** [comment]
Duplicate of #67?

**Comment by evilebottnawi** [comment]
@glen-84 yep, duplicate.

Close in favor https://github.com/webpack-contrib/mini-css-extract-plugin/issues/67
