### ISSUE TITLE
Duplicate file with version in src

### ISSUE THREAD

**Issue by ogarich89** [webpack-contrib/mini-css-extract-plugin#144]
When using SSR, adds the already inserted file again

![2018-05-14 13-54-11](https://user-images.githubusercontent.com/11867673/39993674-51f73516-577f-11e8-8d67-041926161489.png)

**Comment by evilebottnawi** [comment]
@ogarich89 We already have issue about SSR https://github.com/webpack-contrib/mini-css-extract-plugin/issues/90, also we can't do nothing have only screenshot
