### ISSUE TITLE
Pretty much doesn't work at all for sass

### ISSUE THREAD

**Issue by longhornleads** [webpack-contrib/mini-css-extract-plugin#148]
Basically none of the examples work with the latest Webpack.  Any chance there is an example out there that works like the old plugin that actually worked?  I am looking for an example that I can actually build that will bundle all css and scss for now one file is fine.  As far as I can tell this plugin seems to have been forced into production before it is ready.  There are so many errors and not a lot of helpful tutorials that actually use this one successfully.

**Comment by zacharynevin** [comment]
@longhornleads Can you please provide more detail so the maintainers can help you? Just saying "it doesn't work" is a good way to get ignored.

**Comment by evilebottnawi** [comment]
@longhornleads close due no additional information, feel free update you template and recreate/reopen issue
