### ISSUE TITLE
Error type not propagated

### ISSUE THREAD

**Issue by jbedard** [webpack-contrib/mini-css-extract-plugin#152]
The webpack script loading error handling propagates the `Error.type`: https://github.com/webpack/webpack/blob/v4.8.3/lib/web/JsonpMainTemplatePlugin.js#L187-L192

Would be nice if the same was done for the css `<link>` load errors: https://github.com/webpack-contrib/mini-css-extract-plugin/blob/v0.4.0/src/index.js#L303-L309

**Comment by smartthingstutor** [comment]
??????

**Comment by evilebottnawi** [comment]
PR welcome
