### ISSUE TITLE
Does this make use of CSS Modules?

### ISSUE THREAD

**Issue by ydennisy** [webpack-contrib/mini-css-extract-plugin#160]
Hello, 
It would be great if this plugin made use of CSS modules, to keep local/global scope for applications.
Is this possible?

**Comment by evilebottnawi** [comment]
@ydennisy how it is related to extracting? Do you have problem or issue with this? Please use QA or gitter for question, it is bug tracker. Feel free to feedback or create issue if something don't works with css modules. Thanks!
