### ISSUE TITLE
Option to remove newline at the EOF

### ISSUE THREAD

**Issue by TheWashiba** [webpack-contrib/mini-css-extract-plugin#165]
Is there an option to remove newline at the EOF? It seems as this plugin always add the newline to the file.

**Comment by evilebottnawi** [comment]
@TheWashiba where we add `EOF`?

**Comment by TheWashiba** [comment]
I mean the newline char at the end of extracted file, even if I minify the CSS, the extracted "file.css" has a newline character. @evilebottnawi

**Comment by evilebottnawi** [comment]
@TheWashiba i can't find where we add newline in plugin

**Comment by TheWashiba** [comment]
@evilebottnawi does your extracted *.css file have a newline at the end of file? I'm using sass-loader and css-loader with minimize: true option, can't find any other place that would be adding the newline character, have you ever minified your css and the file extracted was one liner?

**Comment by evilebottnawi** [comment]
@TheWashiba I did not pay attention to the last character (EOL), need investigate who do it, go ahead, i don't have time on this right now

**Comment by TheWashiba** [comment]
I think I found the reason, in `src/index.js`, are lines 398 and 419 the ones that append the `\n` to the extracted file? @evilebottnawi

**Comment by evilebottnawi** [comment]
@TheWashiba are you testing? It is not QA service.

**Comment by michael-ciniawsky** [comment]
@TheWashiba You need to add a sparate plugin to minify your CSS Assets e.g `csso-webpack-plugin`optimize-css-assets-plugin`, don't use the loader option to minimize the CSS when extracting it (only for the `style-loader`)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky it can be done with `optimize-css-assets-plugin` and etc, we should fix it here

**Comment by evilebottnawi** [comment]
I was wrong, you should use `optimize-css-assets-plugin` for remove unnecessary lines/whitespaces from generated file, feel free to feedback
