### ISSUE TITLE
Vue + minicss = ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Deathangel908** [webpack-contrib/mini-css-extract-plugin#173]
Can't get `MiniCssExtractPlugin` working with Vue single component files.
Archlinux  node v10.3.0 
```
module: {
    rules: [
      {
        exclude: /node_modules/,
        test: /\.vue$/,
        loader: 'vue-loader', 

      },
      {
        test: /\.sass$/,
        use: [
          MiniCssExtractPlugin.loader,
          "style-loader",
          "css-loader",
          "sass-loader?indentedSyntax"
        ]
      },
    ]
  }
```

> Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
> ReferenceError: window is not defined
>     at eval (webpack:///./node_modules/style-loader/lib/addStyles.js?:23:2)
>     at eval (webpack:///./node_modules/style-loader/lib/addStyles.js?:12:46)

steps to reproduce:
 - `git clone  https://github.com/Deathangel908/vue-webpack-minimal && cd vue-webpack-minimal `
 - `npm install`
 - `npm run build`

**Comment by Deathangel908** [comment]
Oh I shouldn't use style-loader...
 ```
  {
        test: /\.sass$/,
        use: [
          MiniCssExtractPlugin.loader,
          "css-loader",
          "sass-loader?indentedSyntax"
        ]
      },
```

**Comment by f3l1x** [comment]
@Deathangel908 Why we shouldn't use style-loader? Thanks for an explanation.

**Comment by madhavarshney** [comment]
@f3l1x - From the README of style-loader:
> Adds CSS to the DOM by injecting a <style> tag

From the README of mini-css-extract-plugin:
> This plugin extracts CSS into separate files.  It creates a CSS file per JS file which contains CSS.

MiniCSSExtractPlugin extracts CSS into separate files and adds the assets to webpack's asset map.  Style-Loader, on the other hand, embeds the CSS as a string into the JS bundle itself and then, at runtime, injects it into the DOM with a `style` tag.  These methods conflict, hence the error.

**Comment by f3l1x** [comment]
Thank you. Of course, I'm stupid.

**Comment by lior-a** [comment]
its ok to use it for dev env with HMR (but for prod it's better to use just the extract plugin)

**Comment by 244462375** [comment]
I made the same mistake. ;-( @akoidan

**Comment by LeachZhou** [comment]
I used MiniCssExtractPlugin and configured this , but it has this problem, what should I do?
```js
 {
                test: /\.css$/i,
                exclude: /node_modules/,
                use: [
                    MiniCssExtractPlugin.loader,
                    'css-loader',
                ]
            },
{
                test: /\.(htm|html)$/i,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'html-loader',
                        options: {
                            //开启link的替换
                            attrs: ['img:src', 'link:href']
                        }
                    },
                ]
            },
```

```js
/Users/xxx/project/landing2/node_modules/webpack/node_modules/neo-async/async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/Users/xxx/project/landing2/node_modules/webpack/node_modules/neo-async/async.js:16:11)
    at /Users/xxx/project/landing2/node_modules/webpack/node_modules/neo-async/async.js:2818:7
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
