### ISSUE TITLE
Allow an excludeChunks configuration ?

### ISSUE THREAD

**Issue by imwtr** [webpack-contrib/mini-css-extract-plugin#174]
Now I have a problem with `common` chunk, setting this chunk in `html-webpack-plugin` chunks options will inject `common.js` and `common.css` to the html file. Yet the page will layout wrong when `common.css`  exists, it seems unuseful. 
So it would be greate if this plugin allows this chunk-css-extract control ~ 
`html-webpack-plugin` provides an `excludeChunks` option, but it affects both.

**Comment by evilebottnawi** [comment]
@imwtr please create minimum reproducible test repo and provide more infromation what you have and what you expect

**Comment by imwtr** [comment]
oh, i have just solved it by setting `optimization.splitChunks.cacheGroups.default` to false
thx
