### ISSUE TITLE
Remove peerDependency on Webpack

### ISSUE THREAD

**Issue by mattvagni** [webpack-contrib/mini-css-extract-plugin#175]
I'm currently using `mini-css-extract-plugin` within an NPM dependency and am running into issues due to it specifying Webpack as a peerDependency. NPM unfortunately hoists it to the root where the Webpack version may be different per project.

I was wondering how come I don't have this issue with `style-loader` and other popular loaders and noticed that they don't seem to specify a peer on Webpack at all.

Could we make the same change here? I'd be happy to open a PR if you think this is ok. I realise this is not an issue per se with `mini-css-extract-plugin` so I thought I'd open an issue first.

Thanks

**Comment by evilebottnawi** [comment]
All `loader`s and `plugin`s should use `webpack` in `peerDependencies` to avoid problems with compatibility with difference version. In near future `style-loader/css-loader` will receive update with `peerDeeps`. Also `webpack` should be on top of your `mode_modules` (just add `webpack` to your `package.json`).
