### ISSUE TITLE
how can i combine all the css of all chunks into a file?

### ISSUE THREAD

**Issue by zzzgit** [webpack-contrib/mini-css-extract-plugin#176]
I'm using code splitting

After compiled by webpack, there will be a CSS file for every chunk

Is there a way to combine all of them into one file?

**Comment by JohnnyFun** [comment]
Is this what you're after?
https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file

**Comment by happylindz** [comment]
Is that a way to extract css in a single file without creating a new `styles.js` js file?

**Comment by evilebottnawi** [comment]
Documented in docs

**Comment by joshleecreates** [comment]
The solution in the documentation is not working for me.

**Comment by ovaldi** [comment]
The solution in the documentation is not working for me.

**Comment by ZiaUrR3hman** [comment]
> Documented in docs

Guys you need provide CSS entry point or import CSS in JS file that is already added to entry point...

```

const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
entry: {
    "css": "./src/assets/css/style.css", // OR import "./assets/css/style.css" in client.js file
    "client": "./src/client.js"
  },
  optimization: {
    splitChunks: {
      cacheGroups: {
        styles: {
          name: 'styles',
          test: /\.css$/,
          chunks: 'all',
          enforce: true,
        },
      },
    },
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: '[name].css',
    }),
  ],
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader'],
      },
    ],
  },
};```

**Comment by wintercounter** [comment]
Neither for me, I end having dosens of CSS files.
