### ISSUE TITLE
Some modules are not processed

### ISSUE THREAD

**Issue by hieuhlc** [webpack-contrib/mini-css-extract-plugin#178]
I'm using latest version of mini-css-extract-plugin and webpack. I did an experiment with webpack production config wrapped by [speed-measure-webpack-plugin](https://github.com/stephencookdev/speed-measure-webpack-plugin) and got result that made me curious.

![screen_shot_2018-06-13_at_16_44_13](https://user-images.githubusercontent.com/4828178/41343887-f6e55208-6f29-11e8-8937-f181d445a18f.png)

From the screenshot you can see that there were some modules untouched by mini-css. I don't understand.

**Comment by evilebottnawi** [comment]
@hieuhlc please create issue in https://github.com/stephencookdev/speed-measure-webpack-plugin, we use standard webpack api
