### ISSUE TITLE
import css file from scss file does not load the css into the bundle

### ISSUE THREAD

**Issue by Adidi** [webpack-contrib/mini-css-extract-plugin#181]
I am using main file main.scss with all sort of import styling, one import imports css file from node_modules:
`@import "~react-grid-layout/css/styles.css";`
 when i use MiniCssExtractPlugin it does not put this css file into the final bundle

**Loaders dynamic code:**
```
const styleLoaders = [prod ? MiniCssExtractPlugin.loader : 'style-loader', {
                                                                                    loader: 'css-loader',
                                                                                    options: {
                                                                                        sourceMap: !prod
                                                                                    }
                 
                                                               }];
```
**Webpack Config:**
```
...
module: {
            rules: [
                {
                    test: /\.(sa|sc|c)ss$/,
                    use: [...styleLoaders, {
                                                loader: 'sass-loader',
                                                options: {
                                                    sourceMap: !prod
                                                }
                                            }],
                    include: path.join(__dirname, '../src/scss')
                }
            ]
        },
...
```

Thank you for any help

**Comment by evilebottnawi** [comment]
@Adidi not related to `mini-css-extract-plugin`

**Comment by Adidi** [comment]
So what it is related ?
Same code works with ExtractText plugin

**Comment by Adidi** [comment]
@evilebottnawi 

> please use stackoverflow or gitter for question, we have a lot of issue every day with questions and don't have time to solve problems with configuration

It always funny the condescending attitude of some programmers in a popular open source that presumes everybody noobs but them
It might be bug in `mini-css-extract-plugin` and you just don't want to see it. 

>  (this option disable all loaders for all paths what not included in include option)

This is not true but you are obviously not a person that wants to learn anything. 
Good Luck

**Comment by evilebottnawi** [comment]
@Adidi You do not provide either full configuration or minimum reproducible repository and ask for help, i can't help you here, because i can't reproduce your problem. I help everyone as I can, and unfortunately questions more than my time. And do not be aggressive.
