### ISSUE TITLE
Is that a way to extract css in a single file without creating a new styles.js js file

### ISSUE THREAD

**Issue by happylindz** [webpack-contrib/mini-css-extract-plugin#183]
I just find the document saying extracting all css in a single file.
[https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file](https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file)

Is that a way to extract css in a single file without creating a new styles.js js file?

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/mini-css-extract-plugin/issues/85, PR welcome
