### ISSUE TITLE
Outputting result as string?

### ISSUE THREAD

**Issue by aMadReason** [webpack-contrib/mini-css-extract-plugin#192]
This is more of a query than a Issue. I'm currently working on a project where I need to be able to use css modules process it then append to the DOM. (This probably sounds crazy but makes sense in context, it's a very specific use case).

Basically, is it possible to export the result of the mini-css-extract-plugin into a string rather than a file?

I have tried doing this with the  to-string loader and the toString method on the css-loader but it doesn't correctly merge the styles from nested css modules/react components. 

Many thanks :)

**Comment by evilebottnawi** [comment]
@aMadReason out of scope current plugin, need loader for this above `mini-css-extract-plugin` loader

**Comment by aMadReason** [comment]
@evilebottnawi  Thanks for quick reply. Any suggestions? as I said prior I did try using the to-string after mini-css-extract-plugin but it kept making a file. Thanks!

**Comment by evilebottnawi** [comment]
@aMadReason Why you need extract file and when load this file as string? It is have not sense, just use `to-string` loader

**Comment by aMadReason** [comment]
because I'm working on an edge case scenario where I need to insert the bundled css into something after css module scoping had occurred as a string. It's weird and I'd not normally do it as webpack as standard handles pretty much everything for most cases. Also, you don't need to use the string loader as the mini-css-extract-plugin has a toString method (totally basass btw), though you loose it when you use css modules.  We came up with a solution in the end, so it doesn't matter now

**Comment by 132yse** [comment]
Maybe I need this very much. Now I use web component. I need to insert style strings manually. I need string results.
