### ISSUE TITLE
css storage to other locations

### ISSUE THREAD

**Issue by LiangJunrong** [webpack-contrib/mini-css-extract-plugin#193]
In configuration, the explain is

new MiniCssExtractPlugin({
  filename:'[name].css',
  chunkFilename: '[id].css'
})

But, if I want to save css to other locations like：

new MiniCssExtractPlugin({
  filename:'css/[name].css',
  chunkFilename: 'css/[id].css'
})

my css file 'background' doesn't work, how could I use it work as before.
PS : Sorry my English is so poor, expected reply.

**Comment by ev1stensberg** [comment]
Thanks! To sum up: How can you specify another destination for css to be bundled towards?

**Comment by evilebottnawi** [comment]
```
filename:'path/to/my/dir/[name].css',
chunkFilename: 'path/to/my/dir/[id].css'
```
?

**Comment by evilebottnawi** [comment]
@LiangJunrong you have invalid `publicPath` value for `url-loader/file-loader`, without configuration i can't help

**Comment by LiangJunrong** [comment]
@evilebottnawi enm... I can use other css when I set another detination without background, because of I didn't set the true value for url-loader/file-loader?

**Comment by evilebottnawi** [comment]
@LiangJunrong without minimum reproducible test repo i can't help

**Comment by LiangJunrong** [comment]
@ev1stensberg Thanks! my question project in https://github.com/LiangJunrong/webpack-question, enm... could you read the chinese?

**Comment by ev1stensberg** [comment]
I do not :( Do you mind translating the readme/ relevant code?

**Comment by LiangJunrong** [comment]
@ev1stensberg no problem, I translating it. https://github.com/LiangJunrong/webpack-question/blob/master/readme.md

**Comment by ev1stensberg** [comment]
Could you try to use webpack-manifest plugin?

**Comment by LiangJunrong** [comment]
@ev1stensberg I have a try.
