### ISSUE TITLE
Conflict with style-loader

### ISSUE THREAD

**Issue by LiangJunrong** [webpack-contrib/mini-css-extract-plugin#196]
I can't use mini-css-extract and style-loader together

```
{
 test: /\.css$/,
 use: [
  MiniCssExtractPlugin.loader,
   'css-loader',
   'style-loader'
 ]
},
```

It's going to be wrong.
So this plugin is replace the loader "style-loader"?

**Comment by gaurav5430** [comment]
Did you figure it out? Are you using it with style loader ?
