### ISSUE TITLE
Upgrading from 0.4.0 to 0.4.1 generates "broken" css resources

### ISSUE THREAD

**Issue by doberkofler** [webpack-contrib/mini-css-extract-plugin#199]
After upgrading from 0.4.0 to 0.4.1 all of my generated css resources no longer work as expected. Just reverting back to 0.4.0 solved the problem.
I would very much appreciate, if someone could elaborate in more detail on what was changed and how this "might" break existing builds before starting to investigate the details of why the generated css files no longer work as expected.

**Comment by evilebottnawi** [comment]
@doberkofler without minimum reproducible test repo we can't help, for many people all works fine

**Comment by evilebottnawi** [comment]
And what mean `broken`?

**Comment by doberkofler** [comment]
@evilebottnawi I understand that you cannot help and only opened this issue as I hoped to get some background information before starting to debug my files.
It seems as the css files would no longer work because the content of the individual resources are now sorted differently. In my special case a file that was originally imported in an entry is has now moved up to the vendors file and this causes the problem. I am trying to create a reproducible example, but this will take some time.

**Comment by doberkofler** [comment]
I was not able to identify the problem itself but by no longer extracting css resources to the vendor chunk, I was able to upgrade to version 0.4.1:
```
splitChunks: {
	cacheGroups: {
		commons: {
			test: /\.js$/i, // ONLY JS
			name: 'vendors',
			chunks: 'all',
			minChunks: 10
		}
	}
}
```

**Comment by evilebottnawi** [comment]
@doberkofler can we close issue?

**Comment by doberkofler** [comment]
@evilebottnawi If this is not supposed to work by design: yes.
