### ISSUE TITLE
publicPath doesn't seem to be honoured when loading CSS

### ISSUE THREAD

**Issue by insin** [webpack-contrib/mini-css-extract-plugin#2]
`mini-css-extract-plugin@0.1.0`

Using an app with a router, which splits code per route and has `publicPath: '/'` in its output options, I'm seeing the following inserted into `<head>` when visiting a route which imports CSS:

![firefox_2018-03-04_22-00-22](https://user-images.githubusercontent.com/226692/36945311-b843f620-1ff7-11e8-853e-0136b73fb753.png)

If I log out `outputOptions` in `loader.js` it looks ok, but don't know what's ultimately responsible for creating the full path in the `compilation.createChildCompiler` or `NodeTemplatePlugin` it gets passed to:

```js
{ outputOptions: { filename: '*', publicPath: '/' } }
```

**Comment by Kovensky** [comment]
It seems that the plugin's output doesn't take into account the `__webpack_public_path__`. 

Compare this line in the extracted CSS output:

```js
linkTag.href = "" + ({"id":"name"}[chunkId]||chunkId) + ".css";
```

with:

```js
script.src = __webpack_require__.p + "" + ({"id":"name"}[chunkId]||chunkId) + .js";
```

For `[name].js` / `[name].css` outputs.

**Comment by ganapativs** [comment]
Same issue here.
