### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by NithishReddy** [webpack-contrib/mini-css-extract-plugin#200]
Hi,
In my project am  using react-loadable plugin for lazyload js files and using mini-css-extract-plugin for lazyloading css.

am using abc.js component on both pages (i.e Apage and Bpage). on Apage, abc.js component  using on page dom and on Bpage using on layer.
 after running minicss extract plugin, the output file name coming as Apage~Bpage.css.

Apage~Bpage.css is not accessible while using react-loadable on server side rendering. on server side rendering, route base css file is coming as loading css links like on Apage => Apage.css.

**Comment by vincent-yao27** [comment]
I have the same problem with vue SSR. Is there any workaround?

**Comment by NithishReddy** [comment]
For now, we have removed "abc~def.css" while giving below options in webpack config:
optimization: {
     splitChunks: {
      cacheGroups: {
        default: false,//disable default 'commons' chunk behavior
        vendors: false, //disable vendor splitting(not sure if you want it)
      }
    }
  }

**Comment by serut** [comment]
I needed to exclude this module while testing our app using mocha-webpack (which is SSR). Otherwise the CSS was interpreted as JS.   
See https://github.com/zinserjan/mocha-webpack/issues/234

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/90#issuecomment-380796867
