### ISSUE TITLE
Minimizing for production appears to include redundant minimization

### ISSUE THREAD

**Issue by ryancastle** [webpack-contrib/mini-css-extract-plugin#201]
It seems that Webpack 4 already provides JS and CSS minimization out of the box, so the instructions to use `optimize-css-assets-webpack-plugin` in *Minimizing for Production* are redundant. I have confirmed that adding that plugin does not affect CSS file sizes in our case.

**Comment by evilebottnawi** [comment]
@ryancastle webpack@4 doesn't have css minification out of box, looks you use minimize for css-loader, which use old cssnano with a lot of bugs. Better use https://github.com/intervolga/optimize-cssnano-plugin
