### ISSUE TITLE
Why the node version that this plugin supported is ">= 6.9.0 <7.0.0 || >= 8.9.0"

### ISSUE THREAD

**Issue by ihaichao** [webpack-contrib/mini-css-extract-plugin#203]
I found that the node version that this plugin supported is ">= 6.9.0 <7.0.0 || >= 8.9.0".

It means node version ">=7.0.0 <8.9.0" is not supported.

I want to know why.

By the way, the node in our release machine is 7.8.0 and I can't update it. Is there any workaround to use this plugin in our release machine.

**Comment by evilebottnawi** [comment]
@ihaichao Because we support only lts node version, webpack can have perf regression using non lts version

**Comment by shellscape** [comment]
This post pretty much explains the differences between odd-numbered and even-numbered releases: https://nodejs.org/en/blog/community/node-v5/

> The other release line is called Current. All release lines will be odd numbers, and have a shorter lifespan and more frequent updates to the code. The Current release line will focus on active development of necessary features and refinement of existing APIs. Node.js version 5 is this type of release.

In other words, they're unstable-stable builds. They change often, and often contain nasty bugs. They're the bleeding edge. As such, it's very tough to have official support for them.

**Comment by ihaichao** [comment]
@shellscape Thanks, that's a good explanation to my question.

**Comment by evilebottnawi** [comment]
@ihaichao feel free to feedback

**Comment by angry-dan** [comment]
Sorry to drag up an old issue, but I don't feel like this is fully answered. Why 8.9.0? I'm on 8.6.0. Other than it being easy to make minor upgrades, is there anything specifically that happened between 8.0.0 and 8.9.0 that this plugin is utilising? Same at 6.9 I suppose, was there anything that happened during the 6 cycle that caused this requirement?
