### ISSUE TITLE
webpack build css module Module build failed 

### ISSUE THREAD

**Issue by YanYuanFE** [webpack-contrib/mini-css-extract-plugin#206]
version: 0.4.1
os: Ubuntu16.04,
node: v9.11.2

Module build failed (from ./node_modules/less-loader/dist/cjs.js):

// extracted by mini-css-extract-plugin
module.exports = {"mapChart":"mapChart--b9EW_","pieCard":"pieCard--Rsrqd"};
             ^
Unrecognised input

ERROR in ./node_modules/rc-drawer/assets/index.css (./node_modules/css-loader??ref--4-1!./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader??ref--13-1!./node_modules/postcss-loader/lib!./node_modules/rc-drawer/assets/index.css)
Module build failed (from ./node_modules/css-loader/index.js):
Unknown word (1:1)

> 1 | // extracted by mini-css-extract-plugin
    | ^

 @ ./node_modules/rc-drawer/assets/index.css 2:14-190

github link: https://github.com/YanYuanFE/react-start-app/tree/dev

**Comment by evilebottnawi** [comment]
@YanYuanFE looks you have invalid configuration, you forget to add `mini-css-extract-plugin` in some loaders chain

**Comment by zhaoxiaobao** [comment]
@YanYuanFE  请问下最后怎么解决的？

**Comment by YanYuanFE** [comment]
> @YanYuanFE 请问下最后怎么解决的？

see this repo：https://github.com/YanYuanFE/react-start-app
