### ISSUE TITLE
How to hidden log info while use this plugin

### ISSUE THREAD

**Issue by yuyouwen** [webpack-contrib/mini-css-extract-plugin#208]
mini-css-extract-plugin Version: 0.4.1
webpack: 4.16.0

while compile, there are a lot of log about mini-css-extract-plugin

like this:

 Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js?{"minimize":true,"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler/index.js?{"optionsId":"0","vue":true,"scoped":false,"sourceMap":true}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/sa-textline/textLine.vue] ./node_modules/css-loader?{"minimize":true,"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"0","vue":true,"scoped":false,"sourceMap":true}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/sa-textline/textLine.vue 1.02 KiB {mini-css-extract-plugin} [built]

so, is there anyway to hidden or not showing this log.

**Comment by evilebottnawi** [comment]
Use stats for enable/disable logs

**Comment by metaloha** [comment]
My stats object is:
```
{
    all: false,
    assets: true,
    cachedAssets: true,
    errors: true,
    errorDetails: true,
    hash: true,
    performance: true,
    publicPath: true,
    timings: true
  }
```

The console is still filled with lines like @yuyouwen describes. What is the correct setting to get rid of those?

**Comment by imbolc** [comment]
@evilebottnawi @sokra Even with `stats: 'none'` there's still the same output on more than 10 screens (webpack 4). It's really annoying as I'm running a number of processes in parallel during development, so output from all the processes comes to the same screen and it's really hard to debug other processes now. Please, try to fix it if you caring of your project, a lot of people asked you already, it impacts UI hugely, but you're just closing the issues

**Comment by cointilt** [comment]
@imbolc && @metaloha I got those as well until I set the stats value in the devServer key for webpack's config:

```js
config.devServer = {
  stats: {
    children: false,
    chunks: false,
    chunkModules: false,
    modules: false,
    reasons: false,
    useExports: false,
  },
}
```

**Comment by hamstu** [comment]
Ah, that did it for me @cointilt! Thanks so much.

**Comment by darrenywyu** [comment]
use` stats` resoved my problem
doc for `stats` : [webpack-stats](https://webpack.js.org/configuration/stats/#root)

```
{
    stats: 'minimal',
}
```
