### ISSUE TITLE
.css file doesn't appear

### ISSUE THREAD

**Issue by ygnoh** [webpack-contrib/mini-css-extract-plugin#214]
#### versions
- `mini-css-extract-plugin`: `0.4.1`
- `webpack`: `4.16.2`

Since a few days ago, I have been trying to set up webpack with `mini-css-extract-plugin`. I've followed the instruction of webpack and succeeded in webpack setting.

The problem came from `mini-css-extract-plugin`. I set up the `mini-css-extract-plugin` with `css-loader` and build it using webpack. The built css is created well.  **But the css does not loaded!** Any `.css` files doesn't appear in source panel and network panel.

Here is my `webpack.config.js`:
```js
const path = require('path');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
    entry: './src/index.js',
    output: {
        filename: 'main.js',
        path: path.resolve(__dirname, 'dist')
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    "css-loader"
                ]
            }
        ]
    },
    plugins: [
        new MiniCssExtractPlugin()
    ]
};
```

And my simple js file which imports the css:
```js
import "./index.css";

alert("hello world");
```

If you want to see more details, please visit [my repository](https://github.com/ygnoh/basic-setting-up-webpack-with-react).

What am I doing wrong?

Thanks

**Comment by evilebottnawi** [comment]
@ygnoh after extract you should include `link` tag in your htm/php/etc template manually.

**Comment by ygnoh** [comment]
@evilebottnawi Thank you for your reply.
So if I want to apply `mini-css-extract-plugin` to React jsx, not only importing css in `.jsx` but also `<link ...` in the root html is needed?

**Comment by evilebottnawi** [comment]
@ygnoh after extract it is doesn't have sense, because you will have FOUC before js starting work and include link in your page
