### ISSUE TITLE
Support for dynamic `publicPath`

### ISSUE THREAD

**Issue by beshanoe** [webpack-contrib/mini-css-extract-plugin#217]
Hi there!
I'm using the plugin very similar to this one https://github.com/romainberger/webpack-rtl-plugin
Basically, it just generates RTL clone for every CSS file generated by webpack. So in case of lazy CSS chunk, there's gonna be two:
```
1.chunk.css
1.chunk.rtl.css
```
But the problem is that at runtime there's no way to specify which of them to load. 
It would be extremely useful to have an ability to pass some kind of placeholder for global variable to filename template
```js
...
plugins: [
  new MiniCssExtractPlugin({
    filename: '[name].client.$GLOBAL_VAR.css'
  }),
]
```
or support for some globally defined format function which if present, accepts a filename and returns modified one.

**Comment by evilebottnawi** [comment]
Not related to `mini-css-extract-plugin`, we just extract css from bundle, please create issue in https://github.com/romainberger/webpack-rtl-plugin

**Comment by beshanoe** [comment]
But `mini-css-extract-plugin` injects the code responsible for lazy loading:
https://github.com/webpack-contrib/mini-css-extract-plugin/blob/4afcfe2a16216d4b5e693d2fc87e177f3c8af1e2/src/index.js#L324
Is it even possible to change it from the outside, using another plugin for example?

**Comment by beshanoe** [comment]
@evilebottnawi @sokra is it possible to support `__webpack__public__path__` as a function?
That would solve this problem for sure, but it will require breaking change I guess

**Comment by simison** [comment]
This one is relevant for the discussion:
https://www.npmjs.com/package/mini-css-extract-plugin-with-rtl

Specifically commit https://github.com/beshanoe/mini-css-extract-plugin-with-rtl/commit/98e88349f51062d08769bea0f8e584ef449b1640

**Comment by jsnajdr** [comment]
Hello all :wave: We're working on switching the CSS build pipeline for the [WordPress.com Calypso front-end](https://github.com/automattic/wp-calypso) to webpack with the `mini-css-extract-plugin`. We support RTL languages and generate two versions of each CSS asset, one with `.css` extension, second one with `.rtl.css`. [webpack-rtl-plugin](https://github.com/romainberger/webpack-rtl-plugin) can do that for us. So far so good.

The `mini-css-extract-plugin` doesn't just compile CSS assets though: it also adds code to dynamically load them at runtime by tapping into the `mainTemplate.requireEnsure` hook. Here we need the forked [mini-css-extract-plugin-with-rtl](https://github.com/beshanoe/mini-css-extract-plugin-with-rtl) that patches this runtime loader code to select the desired (`.css` or `.rtl.css`) version of the CSS asset.

Is there a chance that the RTL patch could be merged into this (upstream) repo? Or that the same functionality could be implemented in some other way, e.g., by `mini-css-extract-plugin` exposing a hook that plugins like `webpack-rtl-plugin` could tap into?

**Comment by henry42** [comment]
+1
it should read __webpack_public_path__ but now it only reads the options publicPath.

**Comment by evilebottnawi** [comment]
@jsnajdr sorry for big delay, we support `publicPath` as function in master, can you describe verbosely what you expected with examples, thanks

**Comment by evilebottnawi** [comment]
`publicPath` supported `Function`, if you have problems with `publicPath` please open new issue with reproducible test repo and description what is not work as expected
