### ISSUE TITLE
Only vendor.css is being generated when mode is "production".

### ISSUE THREAD

**Issue by sandrocsimas** [webpack-contrib/mini-css-extract-plugin#218]
I'm using ````webpack 4.16.1```` and ````mini-css-extract-plugin 0.4.1````.

When I run Webpack in production mode, only vendor.css bundle is generated. Development mode generates both main.css and vendor.css.
Here is my Webpack configuration:

    const webpack = require('webpack');
    const CleanPlugin = require('clean-webpack-plugin');
    const JsUglifyPlugin = require('uglifyjs-webpack-plugin');
    const CssExtractPlugin = require('mini-css-extract-plugin');
    const CssOptimizePlugin = require('optimize-css-assets-webpack-plugin');
    const CssPurgePlugin = require('purgecss-webpack-plugin');
    const HtmlPlugin = require('html-webpack-plugin');
    const rxjsPaths = require('rxjs/_esm5/path-mapping');
    const path = require('path');
    const glob = require('glob');

    module.exports = (settings) => {
      function isProduction() {
        return settings.env === 'production';
      }

      const optimization = {
        splitChunks: {
          cacheGroups: {
            vendor: {
              name: 'vendor',
              test: /\/node_modules\//,
              chunks: 'all',
              priority: 0,
              enforce: true,
            },
          },
        },
      };
      if (isProduction()) {
        optimization.minimizer = [
          new JsUglifyPlugin({cache: true, parallel: true}),
          new CssOptimizePlugin({}),
        ];
      }

      return {
        optimization,
        mode: settings.env,
        devtool: isProduction() ? false : 'source-map',
        entry: {
          vendor: path.resolve('client', 'src', 'vendor.ts'),
          main: path.resolve('client', 'src', 'main.ts'),
        },
        output: {
          path: path.resolve('dist'),
          filename: '[name].js',
        },
        resolve: {
          extensions: ['.ts', '.js'],
          modules: [
            path.resolve('client', 'src'),
            path.resolve('node_modules'),
          ],
          alias: rxjsPaths(),
        },
        module: {
          rules: [
            {
              test: /\.ts$/,
              use: ['ts-loader', 'angular2-template-loader'],
              include: path.resolve('client', 'src'),
            },
            {
              test: /\.html$/,
              use: ['html-loader'],
              include: path.resolve('client', 'src'),
            },
            {
              test: /\.css$/,
              use: [CssExtractPlugin.loader, 'css-loader'],
              include: [
                path.resolve('node_modules', 'bootstrap', 'dist', 'css', 'bootstrap.css'),
                path.resolve('node_modules', 'angular-calendar', 'css', 'angular-calendar.css'),
              ],
            },
            {
              test: /\.less$/,
              use: [CssExtractPlugin.loader, 'css-loader', 'less-loader'],
              include: path.resolve('client', 'src', 'assets', 'styles'),
            },
            {
              test: /\.(png|jpe?g|gif|svg|ico)$/,
              use: [{
                loader: 'file-loader',
                options: {
                  name: '[path][name].[ext]',
                  context: path.resolve('client', 'src'),
                },
              }],
              include: path.resolve('client', 'src', 'assets', 'img'),
            },
            {
              test: /\.(woff(2)?|ttf|otf|eot|svg)$/,
              use: [{
                loader: 'file-loader',
                options: {
                  name: '[path][name].[ext]',
                  context: path.resolve('client', 'src'),
                },
              }],
              include: path.resolve('client', 'src', 'assets', 'fonts'),
            },
          ],
        },
        plugins: [
          new CleanPlugin(['dist'], {root: path.resolve()}),
          new webpack.optimize.ModuleConcatenationPlugin(),
          new webpack.DefinePlugin({
            'process.env': {
              API_URL: JSON.stringify(settings.apiUrl),
              WEB_URL: JSON.stringify(settings.webUrl),
            },
          }),
          new CssExtractPlugin({filename: 'assets/styles/[name].css'}),
          new CssPurgePlugin({
            paths: glob.sync(`${path.resolve('client', 'src')}/**/*`, {nodir: true}),
            whitelist: ['modal', 'dropdown', 'alert', 'collapse', 'fade', 'show', 'd-block'],
            whitelistPatterns: [/^modal-/, /^dropdown-/, /^alert-/, /^bg-/, /^cal-/],
          }),
          new HtmlPlugin({template: path.resolve('client', 'src', 'index.html')}),
        ],
      };
    };

I also commented the lines below to find what plugin is causing this, but the problem persists.

    new CssOptimizePlugin({}),
    devtool: isProduction() ? false : 'source-map',

I think the problem is this line:

    mode: settings.env,

Probably the problem is in the line above, in conjunction with the mini css extract plugin.

**Comment by evilebottnawi** [comment]
Problem in you configuration, plugins just extract css and all, `mode` doesn't have sense, please create minimum reproducible test repo

**Comment by sandrocsimas** [comment]
I don't know if this is important but here is the Webpack execution log:
````
Hash: a7a7daf1fdd9b5397095
Version: webpack 4.16.2
Time: 48009ms
Built at: 2018-07-25 21:50:48
                   Asset       Size  Chunks                    Chunk Names
assets/styles/vendor.css   41.3 KiB       0  [emitted]         vendor
               vendor.js   5.45 MiB       0  [emitted]  [big]  vendor
                 main.js    385 KiB       1  [emitted]  [big]  main
              index.html  523 bytes          [emitted]         
Entrypoint main [big] = assets/styles/vendor.css vendor.js main.js
  [8] ./node_modules/@ng-bootstrap/ng-bootstrap/modal/modal.module.js + 6 modules 18.3 KiB {0} [built]
      |    7 modules
 [22] ./node_modules/@angular/router/fesm5/router.js + 11 modules 222 KiB {0} [built]
      |    12 modules
[145] ./node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module.js + 20 modules 103 KiB {0} [built]
      |    21 modules
[146] ./node_modules/angular-calendar/fesm5/angular-calendar.js + 13 modules 449 KiB {0} [built]
      |    14 modules
[215] (webpack)/buildin/global.js 489 bytes {0} [built]
[264] ./node_modules/@angular/core/fesm5 lazy namespace object 160 bytes {1} [built]
[446] ./node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module.js + 4 modules 18 KiB {0} [built]
      |    5 modules
[447] ./node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.module.js + 3 modules 13 KiB {0} [built]
      |    4 modules
[449] ./node_modules/@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module.js + 2 modules 11.4 KiB {0} [built]
      |    3 modules
[450] ./node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.module.js + 2 modules 2.93 KiB {0} [built]
      |    3 modules
[451] ./node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js + 1 modules 1.08 MiB {0} [built]
      |    2 modules
[452] ./node_modules/ngx-clipboard/fesm5/ngx-clipboard.js + 1 modules 25.7 KiB {0} [built]
      |    2 modules
[704] ./client/src/main.ts + 71 modules 202 KiB {1} [built]
      | ./client/src/app/services/task.service.ts 3.76 KiB [built]
      | ./client/src/main.ts 968 bytes [built]
      | ./client/src/app/utils/angular.utils.ts 5.28 KiB [built]
      | ./client/src/app/services/account.service.ts 4.96 KiB [built]
      | ./client/src/app/services/alert.service.ts 2.03 KiB [built]
      | ./client/src/app/app.component.ts 1.28 KiB [built]
      | ./client/src/app/app.routes.ts 2.63 KiB [built]
      | ./client/src/app/app.module.ts 11.1 KiB [built]
      | ./client/src/app/services/company.service.ts 10.8 KiB [built]
      | ./client/src/app/services/payment.service.ts 3.11 KiB [built]
      | ./client/src/app/services/event.service.ts 1.52 KiB [built]
      | ./client/src/app/services/client.service.ts 6.97 KiB [built]
      | ./client/src/app/services/plan.service.ts 3.45 KiB [built]
      | ./client/src/app/services/token.service.ts 2.51 KiB [built]
      | ./client/src/app/utils/constants.ts 1.33 KiB [built]
      |     + 57 hidden modules
[706] ./client/src/assets/styles/main.less 39 bytes [built]
[707] ./client/src/vendor.ts 95 bytes {0} [built]
    + 817 hidden modules
````
Main.less appears here:
````
[706] ./client/src/assets/styles/main.less 39 bytes [built]
````
Searching for ````706```` in the dist folder this is the result:
````
/***/ }),
/* 706 */,
/* 707 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {
````
Looking at the json generated with --stats I found this:
````
{
    "id": 706,
    "identifier": "/home/sandro/workspace/intercambio-website/node_modules/mini-css-extract-plugin/dist/loader.js!/home/sandro/workspace/intercambio-website/node_modules/css-loader/i
ndex.js!/home/sandro/workspace/intercambio-website/node_modules/less-loader/dist/cjs.js!/home/sandro/workspace/intercambio-website/client/src/assets/styles/main.less",
    "name": "./client/src/assets/styles/main.less",
    ...
    "depth": 1,
    "source": "// extracted by mini-css-extract-plugin"
 },
````
It seems the css was extracted by ````mini-css-extract-plugin````, but the bundle is not saved. =(

**Comment by sandrocsimas** [comment]
@evilebottnawi, here is the repository to reproduce the error:
https://github.com/sandrocsimas/webpack-bug

**Comment by sandrocsimas** [comment]
It only works if I add main.less to sideEffects option in package.json.

**Comment by sandrocsimas** [comment]
OK, problem solved by adding less and css to sideEffects option in package.json.
````
"sideEffects": [
  "*.less",
  "*.css"
]
````
