### ISSUE TITLE
"Extracting all CSS in a single file" does not work when using a `vendor` cache group

### ISSUE THREAD

**Issue by jeffijoe** [webpack-contrib/mini-css-extract-plugin#224]
This is my cache group config. I'm after

```js
        cacheGroups: {
          default: false,
          vendors: false,
          vendor: {
            test: /[\\/]node_modules[\\/]/,
            name: 'vendor',
            chunks: 'all',
            enforce: true
          },
          styles: {
            name: 'bundle',
            test: /\.css$/,
            chunks: 'all',
            priority: 1000,
            enforce: true
          }
        }
```

Plugin:

```js
new MiniCssExtractPlugin({ filename: 'bundle.css' }),
```

The result is 2 files, `bundle.css` and `1.bundle.css`. If I remove the `vendor` group, I only get `bundle.css` which is what I want, but in doing so I end up  with a single JS file which is not optimal.

I'd like a single `bundle.css` while keeping separate `vendor.js` and `app.js`. 😄

**Comment by evilebottnawi** [comment]
@jeffijoe PR welcome to fix docs

**Comment by xrei** [comment]
It doesn't work even without vendor for me. Still have one css file for one chunk.

**Comment by jpzwarte** [comment]
I had something similar which i solved differently:

```
            splitChunks: {
                cacheGroups: {
                    vendor: {
                        test: /(node_modules|vendors).+(?<!css)$/,
                        name: 'vendor',
                        chunks: 'all'
                    }
                }
            }
```

The vendor bundle excludes all files with `.css` explicitly.

**Comment by evilebottnawi** [comment]
Use something like this:
`
test: (m) => {
    const name = module.nameForCondition();
    return /(node_modules|vendors)/.test(m) && !(/\.css$/.test(name)),
}

For `vendor` group, because you extract to vendor all what inside `node_modules`

**Comment by wind4gis** [comment]
Is it necessary to package all the CSS files together?
I think the (cacheGroups>minSize,maxSize) should still need to be configured...

**Comment by YueminHu** [comment]
the reasons i'm doing this is because of the same-domain-concurrent-connection-limit, too many css files(which is loaded before all js files) will delay the loading of subsequent js files...

**Comment by YueminHu** [comment]
> !(/\.css$/.test(name)),

the trailing comma will cause syntax error

**Comment by natew** [comment]
We extract to atomic css, but also running into this issue. We end up with a bunch of chunks of css with many duplicate styles, which actually degrades runtime perf as well as bundle size, so a bit more than inconvenient... would take a stab at this but webpack plugins are really hard to do right.

**Comment by alexander-akait** [comment]
@natew because bundling is not easy, can you provide example, I will look at this

**Comment by alexander-akait** [comment]
For anyone who faced with this porlbem you can use `type: "css/mini-extract"` instead the `test` option, it will split chunks only for `css/mini-extract`

Simple example:
```
 default: false,
        vendors: false,
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: "vendor",
          chunks: "all",
          enforce: true,
        },
        styles: {
          name: "bundle",
          type: "css/mini-extract",
          chunks: "all",
          priority: 100,
          enforce: true,
        },
```

Docs already uses `type: "css/mini-extract"`, feel free to feedback
