### ISSUE TITLE
TypeError: filename.includes is not a function

### ISSUE THREAD

**Issue by wuliqiangqiang** [webpack-contrib/mini-css-extract-plugin#228]
### version 
"mini-css-extract-plugin": "^0.4.1",
### webpack version 
"webpack": "^4.16.1",
"webpack-cli": "^3.1.0",

it`s my code
![image](https://user-images.githubusercontent.com/16221367/43695302-7483b802-996a-11e8-95bd-e5d8dcadcd28.png)

when i use the filename to be a function , the shell console throw error `TypeError: filename.includes is not a function`

![image](https://user-images.githubusercontent.com/16221367/43695350-d1f93df4-996a-11e8-9628-2cd4c8d3cb2b.png)

Does this plugin filename support to be a function?

**Comment by wuliqiangqiang** [comment]
hello?

**Comment by evilebottnawi** [comment]
@wuliqiangqiang no, PR already exists https://github.com/webpack-contrib/mini-css-extract-plugin/pull/225
