### ISSUE TITLE
Escaped content sequences are extracted incorrectly

### ISSUE THREAD

**Issue by dmitrif** [webpack-contrib/mini-css-extract-plugin#233]
Will get a minimal project up shortly, but creating this as a tbd issue. When the styles are as follows:
```
.something:after {
    content: "\203A";
}
```

This extracts as:
```
.something:after {
    content: "A";
}
```

Instead the expected output is the same as the input. Interestingly enough:

```
.something:after {
    content: "\u203A";
}
```

will extract as:
```
.something:after {
    content: ">";
}
```

**Comment by evilebottnawi** [comment]
@dmitrif not related to plugin, looks somehow loader do this, please create minimum reproducible test repo
