### ISSUE TITLE
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.     at Object.<anonymous> (E:\workSpaceWH\ccm\src\main\webapp\node_modules\mini-css-extract-plugin\dist\index.js:26:44)

### ISSUE THREAD

**Issue by sasaluo** [webpack-contrib/mini-css-extract-plugin#238]
I am using webpack4.2.0,and mini-css-extract-plugin0.4.1,however when i run npm dev,the above error always occur. it appeared that when no including const MiniCssExtractPlugin = require("mini-css-extract-plugin"), i run npm dev,it can compiled successfuly, when i include even const MiniCssExtractPlugin = require("mini-css-extract-plugin"),TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'. at Object.<anonymous> (E:\workSpaceWH\ccm\src\main\webapp\node_modules\mini-                             css-extract-plugin\dist\index.js:26:44)
 can anybody help me fix it? thank you in advance

**Comment by evilebottnawi** [comment]
@sasaluo upgrade you webpack to latest version. Minimum required version is `4.4.0` (https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/package.json#L43)

**Comment by sasaluo** [comment]
thanks very much
