### ISSUE TITLE
Out is not run through optimization.minimizer

### ISSUE THREAD

**Issue by mike-marcacci** [webpack-contrib/mini-css-extract-plugin#24]
I'm not sure if this is a bug or omission in the docs (still wrapping my head around all the webpack 4 changes), but the output is not minimized in production mode using the webpack defaults.

**Comment by sokra** [comment]
yep, by default webpack only comes with a JS minimizer (uglifyjs).

You can add a CSS minimizer via `optimization.minimizer: [...]`

**Comment by mike-marcacci** [comment]
Thanks @sokra. I couldn't find documentation on how to properly configure `optimization.mimimizier` (It seems that quite a few of the 4.x features are still missing from the webpack site [or I'm too dumb to find them!]).

Anyway, I added `optimize-css-assets-webpack-plugin` back to my config, which works with `mini-css-extract-plugin` exactly the same as it did with `extract-text`. I might suggest that you add a note on the readme either explaining how to add minimization with `optimization.mimimizier`, or mention that a plugin is needed, since I think the new expectation with webpack 4 is that `mode=production` will fully optimize the build by default.

**Comment by sokra** [comment]
Yep, I'll do. Or you could send a PR.

webpack 5 will probably include a CSS minimizer by default, just like with uglifyjs.

**Comment by mike-marcacci** [comment]
:-) Added a note in PR #35
