### ISSUE TITLE
webpack4 and react-toolbox issue

### ISSUE THREAD

**Issue by AndreasSchouten** [webpack-contrib/mini-css-extract-plugin#240]
I'm upgrading to webpack4 (4.16.1) and newly use mini-css-extract-plugin (0.4.1).

In my code I have imports like:

`@import "react-toolbox/lib/button/theme.css";`

in css file and

`import Switch from 'react-toolbox/lib/switch';`

in js files.

In both cases I get this error:

```
ERROR in ../node_modules/react-toolbox/lib/switch/theme.css
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../node_modules/css-loader/index.js):
Error: composition is only allowed when selector is single :local class name not in ".disabled", ".disabled" is weird

```

**Comment by evilebottnawi** [comment]
Problem with css modules, please read the error `Error: composition is only allowed when selector is single :local class name not in ".disabled", ".disabled" is weird`. Not related to extract plugin.

**Comment by AndreasSchouten** [comment]
I read this. Just wonder why this worked with Webpack 2 and  extract-text-webpack-plugin 2.
Seems Your plugin is more strict as the old one. Or maybe I miss a configuration.

Thanks for Your fast answer!

**Comment by evilebottnawi** [comment]
@AndreasSchouten Maybe you have old css-loader
