### ISSUE TITLE
How to get that generated css in webpack plugin even in dev mode  where style-loader is being used?

### ISSUE THREAD

**Issue by mzohaibqc** [webpack-contrib/mini-css-extract-plugin#244]
I've a written a webpack plugin which reads less source files and then after processing genrates a short css which allows to override the color specific styles in browser using less.modifyVars(). Here is a demo https://antd-live-theme.firebaseapp.com/

But problem is that it does not work with css-modules since class names generated after comilation will be different that what are in those files. So I think it's better to process the generated css by webpack (css, less, style loaders) in my webpack plugin. so question is

How to get that generated css in webpack plugin even in dev mode  where style-loader is being used?

Here is plugin https://github.com/mzohaibqc/antd-theme-webpack-plugin/blob/master/index.js

**Comment by evilebottnawi** [comment]
@mzohaibqc you should use two webpack build, first - build css, second build app, https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations

**Comment by mzohaibqc** [comment]
@evilebottnawi seems like a solution but I've to do something to avoid `create-react-app` eject. Thanks :)

**Comment by evilebottnawi** [comment]
@mzohaibqc looks it is impossible using `create-react-app`, you can create request on this feature in their repo
