### ISSUE TITLE
New version 0.4.2 capture lot of warnings

### ISSUE THREAD

**Issue by nuintun** [webpack-contrib/mini-css-extract-plugin#250]
![_20180822095000](https://user-images.githubusercontent.com/1730277/44438489-edcaea80-a5f1-11e8-85a6-d1f1e5120ec2.png)

Lot of conflicting order warning, but this css files not care about their order!

**Comment by luqimin** [comment]
experiencing the same issue

**Comment by evilebottnawi** [comment]
Due https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L459

**Comment by jsg2021** [comment]
What's causing this? What is it checking?

**Comment by sokra** [comment]
We are trying to generate a CSS file but your codebase has multiple possible orderings for these modules.

In this case you used `table` before `button` in one location and `button` before `table` in another location. We need to generate a single CSS file for these and can't decide which one should be first. In this case we put `table` before `button`. But this is chosen without reason. In future build we may decide the other way. But since CSS cares for rule order this can lead to issue when CSS changes without reason.

So not defining a clear order can lead to fragile builds, that's why we display a warning here.

There are two things that you can do:

Sort your imports to create a consistent order. I must admit that the warning could be improved to point to the locations that need to be changed.

Ignore the warning with `stats.warningFilter` when the order of these styles doesn't matter. Maybe the eventually add an option to mark order-independent styles directly.

**Comment by evilebottnawi** [comment]
@wende60 you should solve order problem, not downgrade

**Comment by wende60** [comment]
@evilebottnawi unfortunally i do not even understand what i have to order here... the loaders? Maybe you can give me a hint...

**Comment by evilebottnawi** [comment]
@wende60 looks above and read post https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-415345126

**Comment by timothywisdom** [comment]
We used the sort-import plugin for VS Code to insure our entire team is importing modules in the same order.
https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports

Unfortunately, even after insuring the order is the same, we still see these warnings from the mini-css-extract-plugin

**Comment by michael-ciniawsky** [comment]
@timothywisdom Sorting imports/modules **per file** (within) !== Import/Module Order in the Import/Module Tree/Graph (in relation to **other files**)

**Comment by jsg2021** [comment]
This seems like an unreasonable request... we need a way to turn this off for projects that don't care. For example, in my projects each component's styles are self contained so order is only important within each component. (each component has a very unique class name root and all selectors are scoped to them)

**Comment by timothywisdom** [comment]
I'm confused - how do I sort "Import/Module Order in the Import/Module Tree/Graph"?

**Comment by michael-ciniawsky** [comment]
It's very inconvenient at best and realistically unmanagable at a certain project size. That's what CSS Module (automatically) or a CSS naming convention (e.g BEM/ITCSS(Namspace + BEM)) (manually) are for. Nevertheless if one uses CSS without particular care on the matter he/she likely runs into issue with the CSS Cascade and there should be a warning at least (optional)

@timothywisdom It's **always** hard to tell why you get these warnings and where within your project. I'm not saying sorting them for every file doesn't eventually help, but it definitely will not solve all issues. 

See https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-415345126

> We are trying to generate a CSS file but your codebase has multiple possible orderings for these modules.

> In this case you used table before button in one location and button before table in another location. We need to generate a single CSS file for these and can't decide which one should be first. In this case we put table before button. But this is chosen without reason. In future build we may decide the other way. But since CSS cares for rule order this can lead to issue when CSS changes without reason.

**Comment by ulivz** [comment]
This was truly a bug I think. I have following structure:

```
├── ActionSheetCard
│   ├── index.js
│   └── index.less
├── CardWrap
│   └── index.js
├── ImageView
│   └── index.js
├── Request
│   ├── index.js
│   └── index.less
├── ToAlipay
│   ├── index.js
│   └── index.less
├── ToNewUrl
│   ├── index.js
│   └── index.less
├── color.less
└── index.js
```

Each ` index.less` was imported by its adjacent index.js, but this warning was still here:

```
chunk vendors [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/_css-loader@1.0.0@css-loader??ref--18-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??postcss!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js??ref--18-4!./node_modules/_antd-mobile@2.2.3@antd-mobile/lib/style/index.less
 * css ./node_modules/_css-loader@1.0.0@css-loader??ref--18-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??postcss!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js??ref--18-4!./node_modules/_antd-mobile@2.2.3@antd-mobile/es/action-sheet/style/index.less
 * css ./node_modules/_css-loader@1.0.0@css-loader??ref--18-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??postcss!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js??ref--18-4!./node_modules/_antd-mobile@2.2.3@antd-mobile/es/toast/style/index.less
 * css ./node_modules/_css-loader@1.0.0@css-loader??ref--18-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??postcss!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js??ref--18-4!./node_modules/_antd-mobile@2.2.3@antd-mobile/es/button/style/index.less
 * css ./node_modules/_css-loader@1.0.0@css-loader??ref--18-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??postcss!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js??ref--18-4!./node_modules/_antd-mobile@2.2.3@antd-mobile/es/white-space/style/index.less
```

**Comment by jsg2021** [comment]
@ulivz the warning output you gave doesn't line up with your example structure.

**Comment by zsirfs** [comment]
> We are trying to generate a CSS file but your codebase has multiple possible orderings for these modules.
> 
> In this case you used `table` before `button` in one location and `button` before `table` in another location. We need to generate a single CSS file for these and can't decide which one should be first. In this case we put `table` before `button`. But this is chosen without reason. In future build we may decide the other way. But since CSS cares for rule order this can lead to issue when CSS changes without reason.
> 
> So not defining a clear order can lead to fragile builds, that's why we display a warning here.
> 
> There are two things that you can do:
> 
> Sort your imports to create a consistent order. I must admit that the warning could be improved to point to the locations that need to be changed.
> 
> Ignore the warning with `stats.warningFilter` when the order of these styles doesn't matter. Maybe the eventually add an option to mark order-independent styles directly.

`stats.warningsFilter` not `warningFilter`

**Comment by LovaszNorbertM** [comment]
Thanks for the support offered for Webpack 4 , ref [this](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-421989979) . Very good solution , hope you get the sarcasm .

**Comment by Cap32** [comment]
> In this case you used table before button in one location and button before table in another location. We need to generate a single CSS file for these and can't decide which one should be first. In this case we put table before button. But this is chosen without reason. In future build we may decide the other way. But since CSS cares for rule order this can lead to issue when CSS changes without reason.

Is there any way to locate which modules I used `table` before `button`, and which `button` before `table`?

**Comment by TheDutchCoder** [comment]
This is most definitely a bug, because the warnings do not show up when I comment out all my SCSS imports and then re-enable them one by one.

In my case the warnings also make no real sense to me, as I import everything alphabetically anyway, so the order is always the same.

**Comment by holloway** [comment]
`create-react-app@2` is nearly out and it uses this plugin, and I'm not sure sure if we can configure `stats.warningsFilter` to disable it either.

**Comment by leinelissen** [comment]
Hey guys, I've struggled with hiding this warning with Next 7, as it uses friendly-errors-webpack-plugin and I could not get it working with the warningsFilter. Thanks to [this helpful issue](https://github.com/geowarin/friendly-errors-webpack-plugin/issues/75) I've managed to completely hide them.

```javascript
// Define the class
class FilterPlugin {
  constructor(options) {
    this.options = options;
  }

  apply(compiler) {
    compiler.hooks.afterEmit.tap(
      'FilterPlugin',
      (compilation) => {
        compilation.warnings = (compilation.warnings).filter(
          warning => !this.options.filter.test(warning.message)
        );
      }
    );
  }
}

// Instantiate the plugin and add it as a Webpack plugin
new FilterPlugin({ filter: /chunk styles \[mini-css-extract-plugin]\nConflicting order between:/ }),
```

**Comment by tomlagier** [comment]
> We are trying to generate a CSS file but your codebase has multiple possible orderings for these modules.
> 
> In this case you used `table` before `button` in one location and `button` before `table` in another location. We need to generate a single CSS file for these and can't decide which one should be first. In this case we put `table` before `button`. But this is chosen without reason. In future build we may decide the other way. But since CSS cares for rule order this can lead to issue when CSS changes without reason.
> 
> So not defining a clear order can lead to fragile builds, that's why we display a warning here.
> 
> There are two things that you can do:
> 
> Sort your imports to create a consistent order. I must admit that the warning could be improved to point to the locations that need to be changed.
> 
> Ignore the warning with `stats.warningFilter` when the order of these styles doesn't matter. Maybe the eventually add an option to mark order-independent styles directly.

We just upgraded to WP4, and are getting around ~80 of these warnings, between up to 9 or 10 files at a time. How do you suggest we address this? Manually figuring out how to keep our imports consistent across a tree containing hundreds of components is a non-starter for us, we need some sort of automated solution, or at the very least, we need the ability to get some context about where the files are conflicting.

How do you keep import order straight on a project of any significant size?

**Comment by Detachment** [comment]
@leinelissen Which file should I define this class and how to use it?  thanks

**Comment by leinelissen** [comment]
@Detachment This should be a part of the plugins section of your Webpack config.

**Comment by aaronatmycujoo** [comment]
I am using css modules so surely the orderings are irrelevant. What is the proposed solution for those that compose classes from other files?

**Comment by zhang-xiao** [comment]
I tried 0.4.1 that can fix the warnings, but I still confuse why this happens...

**Comment by missalyss** [comment]
I've been trying to ages to try and ignore the warnings; I've gotten it turned off in the terminal, but I'm using Webpack-Dev-Server, and they're also logging to the browser console. Has anyone found a way to make Webpack-Dev-Server respect `stats.warningsFilter`?

**Comment by jsg2021** [comment]
@missalyss Typically, the dev-mode config uses style-loader instead which bypasses all this.

**Comment by jsg2021** [comment]
@missalyss What I mean is: You can have two webpack configs, or logic altering the loader definition based on `NODE_ENV`... In the config for dev mode, you would not have mini-css-extract-plugin’s loader ... you would sub it with `style-loader`

**Comment by cansin** [comment]
We have a very large project where we keep our imports alphabetically ordered "per file" (which understandably does not address the problem here). I agree with the above comments. I do not think it is reasonable to try to keep the imports will be kept ordered within the whole graph. But, I also understand the indeterministic nature of the problem as is.

I think the plugin should allow an option where we can define a comparison function so that the order can be deterministic between such cases, instead of spitting out a WARNING. Wdyt?

**Comment by mAiNiNfEcTiOn** [comment]
In our case, we're doing/using:

* Dynamic imports and with it, chunk splitting
* CSS Modules (SASS -> CSS, then importing the CSS on JS 😉)

With this change we're locked on using the previous version! 🙂

**Comment by stereobooster** [comment]
Do I understand it right that `ref--18-2` stands for line 18, column 2?

**Comment by ScottAgirs** [comment]
> We are trying to generate a CSS file but your codebase has multiple possible orderings for these modules.
> 
> In this case you used `table` before `button` in one location and `button` before `table` in another location. We need to generate a single CSS file for these and can't decide which one should be first. In this case we put `table` before `button`. But this is chosen without reason. In future build we may decide the other way. But since CSS cares for rule order this can lead to issue when CSS changes without reason.
> 
> So not defining a clear order can lead to fragile builds, that's why we display a warning here.
> 
> There are two things that you can do:
> 
> Sort your imports to create a consistent order. I must admit that the warning could be improved to point to the locations that need to be changed.
> 
> Ignore the warning with `stats.warningFilter` when the order of these styles doesn't matter. Maybe the eventually add an option to mark order-independent styles directly.

Hey Tobias, is there a link to a tutorial that explains in more detail how could I go about sorting out imports to create a consistent order?

**Comment by evilebottnawi** [comment]
@Pczek https://webpack.js.org/configuration/stats/#stats

**Comment by valscion** [comment]
It felt easier to us to use a plugin called [webpack-filter-warnings-plugin](https://github.com/mattlewis92/webpack-filter-warnings-plugin) for this, so if anyone's curios, this is how this warning can be ignored:

```js
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin'); 

const config = {
  plugins: [
    // Silence mini-css-extract-plugin generating lots of warnings for CSS ordering.
    // We use CSS modules that should not care for the order of CSS imports, so we
    // should be safe to ignore these.
    //
    // See: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250
    new FilterWarningsPlugin({
      exclude: /mini-css-extract-plugin[^]*Conflicting order between:/
    })
  ]
}
```

As you can see from our comment, we're not 100% sure we're safe but at least we try to document why this warning can be ignored. I suggest others filtering these warnings do something similar ☺️

**Comment by TheDutchCoder** [comment]
I have to backtrack on my previous comment: after more testing it turns out this plugin will actually simply ignore certain requires because if has issues with the import order.

An example is one of my entry files that requires `_hero.scss`, none of my other entry files use that component.

This plugin ends up simply ignoring the file, probably because it tries to extract all CSS into a common CSS file (through splitChunks), but struggling with how to deal with import order from different entries.

What I want is the plugin to detect that `_hero.scss` is *not* shared between entries and should end up in its normal place (`products.css` in this case), instead of throwing it out.

Consider the following structure:

products.js
```
require('@sass-framework/elements/_icon.scss')
require('@sass-framework/elements/_hero.scss')
require('@sass-framework/elements/_flag.scss')
```

homepage.js
```
require('@sass-framework/elements/_icon.scss')
require('@sass-framework/elements/_flag.scss')
```

What's supposed to happen is:

common.css, containing:
```
icon.css
flag.css
```

products.css, containing:
```
hero.css
```

But what ends up happening is that products.css is *does not* contain `hero.css` because the plugin gets confused by the import order.

I'm not sure why it struggles with this (there really is no reason, as `hero.css` is referenced in only 1 entry file, so doesn't need to be split out, whereas the rest is), I just know it happens and breaks all kinds of styles because of it.

**Comment by hezhongfeng** [comment]
@events-jonas-chrisw 
me too.I use FilterWarningsPlugin,but it don't work .Use `inspect` find that the config is 
```
    /* config.plugin('copy') */
    new CopyWebpackPlugin(
      [
        {
          from: 'D:\\svn\\biz-mgmt\\branches\\v2.1.0\\public',
          to: 'D:\\svn\\biz-mgmt\\branches\\v2.1.0\\dist',
          toType: 'dir',
          ignore: [
            'index.html',
            '.DS_Store'
          ]
        }
      ]
    ),
    {
      exclude: [
        /mini-css-extract-plugin[^]*Conflicting order between:/
      ]
    }
```
have no FilterWarningsPlugin

**Comment by hezhongfeng** [comment]
@events-jonas-chrisw this is okay.
```
class CustomFilterPlugin {
  constructor({ exclude }) {
    this.exclude = exclude;
  }

  apply(compiler) {
    compiler.hooks.afterEmit.tap('CustomFilterPlugin', compilation => {
      compilation.warnings = compilation.warnings.filter(warning => !this.exclude.test(warning.message));
    });
  }
};
// ...
  configureWebpack: {
    plugins: [
      new CustomFilterPlugin({
        exclude: /Conflicting order between:/
      })
    ]
  }
```

**Comment by nuclearglow** [comment]
To alleviate the hundreds of warnings of conflicting order which we handle by CSS scoping, we use a warningsFilter:
`warningsFilter: (warning) => {
    return /Conflicting order between/gm.test(warning);
}`

**Comment by libbGit** [comment]
> We are trying to generate a CSS file but your codebase has multiple possible orderings for these modules.
> 
> In this case you used `table` before `button` in one location and `button` before `table` in another location. We need to generate a single CSS file for these and can't decide which one should be first. In this case we put `table` before `button`. But this is chosen without reason. In future build we may decide the other way. But since CSS cares for rule order this can lead to issue when CSS changes without reason.
> 
> So not defining a clear order can lead to fragile builds, that's why we display a warning here.
> 
> There are two things that you can do:
> 
> Sort your imports to create a consistent order. I must admit that the warning could be improved to point to the locations that need to be changed.
> 
> Ignore the warning with `stats.warningFilter` when the order of these styles doesn't matter. Maybe the eventually add an option to mark order-independent styles directly.

on vue-cli3，how do i use `stats.warningFilter` on vue.config.js?

**Comment by hezhongfeng** [comment]
@libbGit Look my comment.

**Comment by libbGit** [comment]
> @libbGit Look my comment.

Thank you very much, i have cleaned out the warning log

**Comment by sealzrt** [comment]
experiencing the same issue

**Comment by sealzrt** [comment]
@valscion thanks, I fixed it with webpack-filter-warnings-plugin

**Comment by patientplatypus** [comment]
Yeah this is silly - I don't want to be forced to rely on a certain order of imports in my javascript files. The component based architecture of most javascript frameworks (React et al.) is philosophically built around atomization and independence of class components and this breaks this.

**Comment by luckyyyyy** [comment]
I fixed it with webpack-filter-warnings-plugin

```javascript
    new FilterWarningsPlugin({
      exclude: /mini-css-extract-plugin[^]*Conflicting order between:/,
    }),
```

**Comment by alexdonets** [comment]
This works but only for the browser console, is there a way to filter warnings in the terminal? (I'm using Visual Code)
```
new FilterWarningsPlugin({
    exclude: /mini-css-extract-plugin[^]*Conflicting order between:/,
})
```

**Comment by GasimGasimzada** [comment]
Instead of ignoring these warnings, could someone explain to me how to debug this and try to fix the orders etc. I have a problem only between two files and in all the files where these two files are imported, the order is exactly the same. What is the reason for this?

**Comment by chickenwing** [comment]
> and in all the files where these two files are imported, the order is exactly the same

and are "all the files where these two files are imported" themselves imported to somewhere or are they "top level"? if not, then the problem mentioned in https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-416708880 might be the reason for the warnings.

I think MiniCssExtractPlugin needs to provide a compare function like mentioned here https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-438061698 so we can decide on the conflicting order ourselves.

**Comment by luckyyyyy** [comment]
> @GasimGasimzada
> 
> > and in all the files where these two files are imported, the order is exactly the same ([#250 (comment)](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-464515824))
> 
> and are "all the files where these two files are imported" themselves imported to somewhere or are they "top level"? if not, then the problem mentioned in [#250 (comment)](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-416708880) might be the reason for the warnings.
> 
> I think MiniCssExtractPlugin needs to provide a compare function like mentioned here [#250 (comment)](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-438061698) so we can decide on the conflicting order ourselves because with some imports its logicly impossible ensure correct order.

I feel the same.

**Comment by skout90** [comment]
In my case, conflict file 1 and file 2

because `same @media query`

below could confuse order

    @media only screen and (max-width: 480px) {
      .file1 {
        
      }
    }

    @media only screen and (max-width: 480px) {
      .file2 {
        
      }
    }

below couldnt confuse order

    .file1 {
       @media only screen and (max-width: 480px) {

       }
    }
    .file2 {
       @media only screen and (max-width: 480px) {

       }
    }

**Comment by psyanite** [comment]
I am also using MiniCssExtractPlugin with ts-loader and experience seeing these warnings:
```
WARNING in chunk admin-site [mini-css-extract-plugin]
Conflicting order between:
 * css ../node_modules/css-loader!../node_modules/postcss-loader/lib!../node_modules/sass-loader/lib/loader.js!./controls/card.sass
 * css ../node_modules/css-loader!../node_modules/postcss-loader/lib!../node_modules/sass-loader/lib/loader.js!./components/container.sass
 * css ../node_modules/css-loader!../node_modules/postcss-loader/lib!../node_modules/sass-loader/lib/loader.js!./controls/logo.sass
```

But am unable to figure out if these are false-warnings

**Comment by felixmosh** [comment]
Is it possible to point out the problematic imports (the file name), or something else in-order to help solve this warning?

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/mini-css-extract-plugin/issues/362

**Comment by StarpTech** [comment]
In my case the order is relevant and it produces a broken html layout. How can I avoid it? I only import a single sass file per component in next.js.

**Comment by ruijielou** [comment]
This error can be avoided by separating the style files of common components into separate files for loading.

**Comment by psyanite** [comment]
Yeah that's what I don't understand. My error is for:
card.sass
container.sass
logo.sass

but these three files do not share any css styles. 

Has anyone able to change the code so the warning doesn't show anymore?

**Comment by phattranky** [comment]
I just reorder my imports of the conflicting components. Then the issues were solved.

My **FullScreenQuizDialog** conflict with others. So I try to move it to the bottom of the imports
<img width="905" alt="Screen Shot 2019-04-30 at 6 07 40 AM" src="https://user-images.githubusercontent.com/6443154/56932549-75b4ad00-6b0e-11e9-87cb-a33ca32213d8.png">
<img width="922" alt="Screen Shot 2019-04-30 at 6 08 04 AM" src="https://user-images.githubusercontent.com/6443154/56932550-75b4ad00-6b0e-11e9-9606-96a65577bc89.png">

**Comment by tylerrrkd** [comment]
`ignoreOrder` works well.
```
plugins: [
    new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output
      // all options are optional
      filename: '[name].css',
      chunkFilename: '[id].css',
      ignoreOrder: false, // Enable to remove warnings about conflicting order
    }),
  ],
```

**Comment by fsarter** [comment]
This warning is confusing, and difficulty to address. In my case, warning:
```
Conflicting order between:
 * css ./node_modules/css-loader??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/post
css-loader/src??ref--10-oneOf-1-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-1-3!./node_modules/cache-loader/dist/cjs
.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/financial-comm/member-pricing.vue?vue&type=styl
e&index=0&id=1a72b65c&scoped=true&lang=less&
 * css ./node_modules/css-loader??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/post
css-loader/src??ref--10-oneOf-1-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-1-3!./node_modules/cache-loader/dist/cjs
.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/pricing/views/components/over-pricing-dialog.vue?vue
&type=style&index=0&id=4851d13d&scoped=true&lang=less&
```

But it's not exactly caused by `member-pricing` or `over-pricing-dialog` component, it's `index.vue` and `vip-info.vue` where i imported `member-pricing` with different orders raise the warning.

So i think the correct steps to handle this issue is:

1. search one component listed by those warnings in your codebase.
2. if the component is imported in multiple files, check their order in the import block, make sure the order is consistent.
3. if warning is not eliminated, continue checking other components listed in those warnings following step 1 and 2.

Good luck!

**Comment by Marszed** [comment]
experiencing the same issue in my Nuxt project

nuxt@2.10.1 dependences extract-css-chunks-webpack-plugin@4.6.0

but extract-css-chunks-webpack-plugin@4.6.0 has error, like this [issues-->extract-css-chunks-webpack-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250), [issues-->Nuxt](https://github.com/nuxt/nuxt.js/issues/5135)

so, you can set nuxt@2.10.1 dependences extract-css-chunks-webpack-plugin@^4.5.2

i use yarn, so i soloved it by change yarn.lock dependences extract-css-chunks-webpack-plugin@^4.5.2

**Comment by samayo** [comment]
same error today

**Comment by bitttttten** [comment]
Also started to see this issue on one of our builds today, one that we had not run for a few days.

There are no clues about which file has the issue either 😬

**Comment by samayo** [comment]
Is there an alternative to mini-css-extract? anyone?

**Comment by valscion** [comment]
This issue has been resolved by the addition of `ignoreOrder` option: https://github.com/webpack-contrib/mini-css-extract-plugin/blob/v0.8.0/README.md#remove-order-warnings

Please open an issue in the repository of the tool you're using that uses `mini-css-extract-plugin` to discuss if they should use `ignoreOrder`.

I understand the maintainers here have understood that the warnings are difficult to decipher, and they don't currently need new comments to reflect that.

Please open a new issue if `ignoreOrder` is not working as expected, with reproduction steps, if you think there is an issue with that option.

**Comment by qertis** [comment]
reopen please

**Comment by left-handed** [comment]
new MiniCssExtractPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css'),
      allChunks: true,
      ignoreOrder: true // Enable to remove warnings about conflicting order
   }),

**Comment by webylb** [comment]
并没有解决我遇到的的问题

**Comment by nicooprat** [comment]
Tried to add `ignoreOrder: true` but I'm getting some `Cannot read property 'createChildCompiler' of undefined` errors, has anyone encountered the same issue? Looks like it's coming from the `thread-loader` plugin but I couldn't find any solution there.

**Comment by Hypnosphi** [comment]
> Sort your imports to create a consistent order.

@sokra do you know any practical way to do that? As pointed out above, alphabetical order doesn't always work:

```js
// a.entry.js
import './a.css'
import './b.css'
```

```js
// b.entry.js
import './b.css'
import './c.js'
```

```js
// c.js
import './a.css'
```

Here, all the imports are sorted alphabetically, but `a.entry.js` and `b.entry.js` have different order of CSS files

**Comment by julpat** [comment]
Still waitting for this 😇 🙏 
> Sort your imports to create a consistent order. I must admit that the **warning could be improved** to point to the locations that need to be changed.

Solving this warnings by disable them globaly is wrong. **The messages are useful** when you have nested use of same components and then the order is important!

```
// Some.vue
import Decor from 'Decor.vue';
import SomethingDifferent from 'SomethingDifferent';

// SomethingDifferent.vue
import Decor from 'Decor.vue'; // completely different use of the same component
```
So the solution here is "lazy" loading (getting this from Webpack doc (?) not sure now)
```
// SomethingDifferent.vue
const Decor = () => import('Decor.vue');
```

**Comment by steveswork** [comment]
There is now an NPM package named  **[@webkrafters/ordercss](https://www.npmjs.com/package/@webkrafters/ordercss)** which tackles this issue.

Full disclosure: I initially created it to solve this very problem in one of my apps. After seeing this thread, I decided to expand it and share it with everyone. Because people should not be forced to use CSS-in-JS or any other scoped CSS paradigm if they don't want to.

If this package helps anyone, please share it with others.

Thanks and good luck!

**Comment by cdll** [comment]
same issue here💔

**Comment by Nsandomeno** [comment]
> same issue here💔

@cdll working on this too... will get back here if I find anything. Any luck for you?

**Comment by eyedean** [comment]
I wrote a detailed explanation of why this happens and what are the solutions at: https://stackoverflow.com/a/67579319

**Comment by 9mm** [comment]
So how do we fix this when everything is ordered and the error still occurs, yet we don't just want to disable the warnings?

**Comment by benomatis** [comment]
> ## NOTE FOR FUTURE READERS: See [#250 (comment)](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-544898772) for a more up-to-date comment
> It felt easier to us to use a plugin called [webpack-filter-warnings-plugin](https://github.com/mattlewis92/webpack-filter-warnings-plugin) for this, so if anyone's curios, this is how this warning can be ignored:
> 
> ```js
> const FilterWarningsPlugin = require('webpack-filter-warnings-plugin'); 
> 
> const config = {
>   plugins: [
>     // Silence mini-css-extract-plugin generating lots of warnings for CSS ordering.
>     // We use CSS modules that should not care for the order of CSS imports, so we
>     // should be safe to ignore these.
>     //
>     // See: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250
>     new FilterWarningsPlugin({
>       exclude: /mini-css-extract-plugin[^]*Conflicting order between:/
>     })
>   ]
> }
> ```
> 
> As you can see from our comment, we're not 100% sure we're safe but at least we try to document why this warning can be ignored. I suggest others filtering these warnings do something similar ☺️

This works, except the warning doesn't show `Conflicting order between:` anymore, it's just `Conflicting order`, so just remove the `between:` from the end before the last slash of the `exclude` param, and you should be good to go.
