### ISSUE TITLE
Getting error "require function is used in a way in which dependencies cannot be statically extracted"

### ISSUE THREAD

**Issue by MathRobin** [webpack-contrib/mini-css-extract-plugin#251]
Hi,

I get this message :
```shell
WARNING in ./node_modules/uglifyjs-webpack-plugin/dist/uglify/worker.js 14:130-137
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/uglifyjs-webpack-plugin/dist/uglify/Runner.js
 @ ./node_modules/uglifyjs-webpack-plugin/dist/index.js
 @ ./node_modules/uglifyjs-webpack-plugin/dist/cjs.js
 @ (webpack)/lib/WebpackOptionsDefaulter.js
 @ (webpack)/lib/webpack.js
 @ ./node_modules/mini-css-extract-plugin/dist/index.js
 @ ./node_modules/mini-css-extract-plugin/dist/cjs.js
 @ ./webpack.config.js
```
I'm using the latest versions of the tools :
- webpack @ 4.17.1
- mini-css-extract-plugin @ 0.4.2
- uglifyjs-webpack-plugin @1.3.0

It just need to have something which require "uglifyjs-webpack-plugin" to make it crash. Samples here : https://github.com/webpack/webpack/search?q=uglifyjs-webpack-plugin&unscoped_q=uglifyjs-webpack-plugin.

Config file sample :
```javascript
const
    path = require('path'),
    packageConfig = require('./package');
// Test with commenting those lines both at the same time, no error, one of them, error. The two uncommented, error too.
const    UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const     MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
    mode: 'development',
    entry: {
        app: './app/front/app.js',
        scss: './app/front/app.scss'
    },
    output: {
        path: path.resolve(__dirname, 'public'),
        filename: 'app.' + packageConfig.version + '.js'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env']
                    }
                }
            },
            {
                test: /\.((sc|c|sa)ss)$/,
                use: [
                    {
                        loader: 'style-loader'
                    },
                    {
                        loader: 'css-loader'
                    },
                    {
                        loader: 'postcss-loader',
                        options: {
                            plugins: function () {
                                return [
                                    require('autoprefixer')
                                ];
                            }
                        }
                    },
                    {
                        loader: 'sass-loader'
                    }
                ]
            }
        ]
    }
};
```
Whatever I use or not the plugin `mini-css-extract-plugin`, any project which requires `uglifyjs-webpack-plugin` crashes the same way.

Have tested with :
- node @ 10.9.0
- node @ 8.11.4
Same results, on last Ubuntu, up-to-date.

Any idea ? Thanks in advance !

**Comment by MathRobin** [comment]
Tried with or without this entry as css and with or without imported style in my js. Had the same issue.

But not now anymore. Don't understand why... So closed. Sorry for the disturb

**Comment by michael-ciniawsky** [comment]
> Tried with or without this entry as css and with or without imported style in my js. Had the same issue

The CSS entrypoint issue is unrelated to your original problem I just say it in your config. Definitely don't do that as it will create an empty JS File containing only the webpack runtime and my put your other chunk at of order etc etc :)

> But not now anymore. Don't understand why...

If it happens again please open an issue about in in `uglifjs-webpack-plugin`.  I'm not 💯  sure what we are doing there is correct, but it works that way for a while now and normally it doesn't take long until folks run into (general) issues when it comes to thinks like that, so it maybe was related to your particular setup in this case
