### ISSUE TITLE
Runtime loader code ships multiple copies of the chunkMap.hash object

### ISSUE THREAD

**Issue by jsnajdr** [webpack-contrib/mini-css-extract-plugin#253]
When using the mini-css-extract-plugin in a setup where filename templates for both JS and CSS use the `[chunkhash]` substitution:
```js
{
  output: {
    filename: '[name].[chunkhash].js'
  },
  plugins: [
    new MiniCssExtractPlugin( {
      filename: '[name].[chunkhash].css'
    } )
  ]
}
```
then the runtime code will be inflated by shipping two copies of the stringified `chunkMap.hash` object. One is in `jsonpScriptSrc` function, second one in the CSS-related code in `requireEnsure`.

Each call to `mainTemplate.getAssetPath` creates its own copy. Also, the chunk map object is instantiated (and then GCed) on every `requireEnsure` call.

Is there a way to extract the map into a local variable? This is probably a webpack core issue rather than issue with this plugin, but I'm not sure.

**Comment by evilebottnawi** [comment]
@jsnajdr sorry for delay, can you provide minimum example?

**Comment by jsnajdr** [comment]
Hi @evilebottnawi! Here is a repo with a little project that reproduces the issue: https://github.com/jsnajdr/webpack-chunkhash-duplicate

After `npm run build`, there is file `dist/main.[chunkhash].js` with two instances of the chunk map object (recreated on every call):

one for JS:
<img width="1033" alt="screenshot 2018-11-22 at 14 37 07" src="https://user-images.githubusercontent.com/664258/48906281-3ea5e580-ee64-11e8-8671-105463884ea5.png">

second one for CSS:
<img width="921" alt="screenshot 2018-11-22 at 14 39 14" src="https://user-images.githubusercontent.com/664258/48906344-6eed8400-ee64-11e8-9b4f-0b654b2655cb.png">

For large projects, the chunk map object can get quite big and becomes the largest part of the webpack runtime.

**Comment by evilebottnawi** [comment]
@jsnajdr What you expected, `css` and `js` have difference logic for loading chunks

**Comment by jsnajdr** [comment]
> What you expected, css and js have difference logic for loading chunks

I expected that there is only one instance of that object in the shipped webpack runtime.

However different the logic for CSS and JS might be, both chunk hash objects are always identical. Generated by `mainTemplate.getAssetPath`, in both cases the code to generate the object is:
```js
JSON.stringify(chunk.getChunkMaps().maps)
```

**Comment by evilebottnawi** [comment]
@jsnajdr hm, PR welcome

**Comment by alexander-akait** [comment]
It was fixed a long time ago
