### ISSUE TITLE
const { Template, util: { createHash } } = _webpack2.default;

### ISSUE THREAD

**Issue by jatinderbahl** [webpack-contrib/mini-css-extract-plugin#254]
please help I'm getting the error while using the mini-css-extract-plugin in webpack version 
webpack 4.17.1

also tried: **clear npm and deleted node modules.**

![image](https://user-images.githubusercontent.com/20404627/44654626-f49d9700-aa0f-11e8-8987-5b66be5056a0.png)

**Comment by jatinderbahl** [comment]
@evilebottnawi already tested 
![image](https://user-images.githubusercontent.com/20404627/44655196-e94b6b00-aa11-11e8-9a82-cca67a8fe3bf.png)

**Comment by evilebottnawi** [comment]
@jatinderbahl please create minimum reproducible test repo

**Comment by jatinderbahl** [comment]
@evilebottnawi  please try these steps 
1. Create a simple test app using create react app scripts.
2. Install mini-css-extract-plugin 
3. Goto react-scripts under the node_modules 
4. Find \config\webpack.config.prod.js and try to configure with mini-css-extract-plugin instead of extract-text-webpack-plugin
5. Run npm run build (I'm getting error while build the project)

[webpack.config.prod.zip](https://github.com/webpack-contrib/mini-css-extract-plugin/files/2323550/webpack.config.prod.zip)

**Comment by michael-ciniawsky** [comment]
> react app scripts

Please try to reproduce without any third-party vendor manager/wrapper tool around `webpack` first, e.g this if it 'only' happens with `react scripts` it's likely a bug there and an issue opened in react-scripts woud be better

Not meant to be mean here, but there is nothing we can do here atm, feel free to reopen if you are able to reproduce with a simple bare webpack config an/or link folks from e.g `react-scripts` to this issue, so they can eleborate why this is an issue with `mini-css-extract-plugin` in particular :)
