### ISSUE TITLE
Documentation of options

### ISSUE THREAD

**Issue by rightaway** [webpack-contrib/mini-css-extract-plugin#259]
Some better documentation of the options would be useful. Are filename and chunkFilename the only 2 options that this plugin takes or are there others? When are each of those 2 used? What tokens are available to use in both options and when should you use which?

**Comment by michael-ciniawsky** [comment]
Agreed

**Comment by rightaway** [comment]
Any progress on this? I'm just using any option that works but not sure what it's actually doing or whether there's better options I can choose.
