### ISSUE TITLE
webpack 4 production mode always generates files with numeric prefix

### ISSUE THREAD

**Issue by iongion** [webpack-contrib/mini-css-extract-plugin#26]
The following files are generated:

```
1.styles.css
1.styles.css.map
```

For this webpack config entry:

```
  new MiniCssExtractPlugin({
    filename: 'styles.css',
  }),
```

And this css loader setup:

```
{
  test: /\.css$/,
  use: [
    MiniCssExtractPlugin.loader,
    {
      loader: 'css-loader',
      options: {
        minimize: {
          discardComments: {
            removeAll: true
          },
        }
      }
    }
  ]
}
```

The same configuration using the `ExtractTextPlugin` was generating files without the `1.` prefix

**Comment by developer-lindner** [comment]
From Readme.md:

new MiniCssExtractPlugin({
    filename: "[name].css",
  })


You're doing it wrong.

**Comment by iongion** [comment]
@developer-lindner I have used a previous configuration from https://github.com/webpack-contrib/extract-text-webpack-plugin and hoped that this plugin supports similiar options, but it is not ... man this webpack world ...!

Thank you nevertheless for the help!

**Comment by developer-lindner** [comment]
@iongion You're welcome! I know... webpack (4) documentation is outdated and one have to do a lot of try and error :/

**Comment by iongion** [comment]
There are still issues that I do not understand where they come from, now the issue is `css-hot-loader`, for this config:

```
{
      test: /\.css$/,
      use: [
        MiniCssExtractPlugin.loader,
        'css-hot-loader',
        cssLoader,
        'postcss-loader',
      ],
}
```

when a file is changed, no hot swapping of css happens, although the change is detected, I attached a sample project for you to give it a look, maybe is not from your project, but from `css-hot-loader` itself
[react-demo.zip](https://github.com/webpack-contrib/mini-css-extract-plugin/files/1793818/react-demo.zip)

Do an `npm start` and then change something inside `src/pages/home/index.css` you will see that hot reloading is not working.

**Comment by workerDone** [comment]
I had the same problem with css/scss in production mode.
 Problem with default styles.
I replaced import with require in main.ts and everything fine.
`import './assets/css/styles.scss';` to => `require('./assets/css/styles.scss');`
