### ISSUE TITLE
conditional link tag in view

### ISSUE THREAD

**Issue by brewster1134** [webpack-contrib/mini-css-extract-plugin#260]
so considering the code in the readme `devMode ? 'style-loader' : MiniCssExtractPlugin.loader`, doesn't this imply you need a similar check in the view that requests the extracted css?

**Comment by michael-ciniawsky** [comment]
Please provide an example for `need a similar check in the view that requests the extracted css?`

For development and especially when using HMR one needs to use the `style-loader` to add the CSS via `<style></style>` tags and the CSS is included in the JS Chunk itself. For production it's recommended to extracted the CSS from the JS Chunk into it's own file for e.g parallel loading of CSS and JS resources

**Comment by michael-ciniawsky** [comment]
CSS included in an async chunk (`import()`)  e.g a route is loaded once the chunk is requested. The `mini-css-extract-plugin` handles does automatically
