### ISSUE TITLE
Selectively extract CSS

### ISSUE THREAD

**Issue by manniL** [webpack-contrib/mini-css-extract-plugin#262]
Hey folks!

I've asked myself if it's possible to extract CSS from my bundled files **selectively**. Think about files `a.js`, `b.js`, `c.js` and `global.js` where each has CSS included. Is there a way to extract **only the global.css**?

**Comment by corneliusio** [comment]
I've had a similar situation where I actually need to load styles into an iframe—I use the style-loader `insertInto` method to do this. But basically had to set up separate a separate rule for the file I wanted to be excluded from mini-css-extract-plugin. It's not the pretties workaround, but if you are interested in the setup you can see the two loaders involved [here](https://bitbucket.org/corneliusio/brightpack/src/master/lib/loaders/css.js) and [here](https://bitbucket.org/corneliusio/brightpack/src/master/lib/loaders/editor-css.js).

The important bits are that the main rule for css ignores the file(s) I want to (in this case) don't want to extract and then the test for the added rule is explicitly for that file(s). You can also see I'm simply importing the main rule loaders and replacing the first item so I don't have to maintain two almost identical loader setups.

All that to say, it would be really great if this could be built into the plugin in some way, but figured I'd throw it out there how it could be done currently.

**Comment by evilebottnawi** [comment]
Use `splitChunks.cacheGroups` - you can create any count of chunk. You have `test` property where should return true if you want to extract something.
