### ISSUE TITLE
ReferenceError: OptimizeCSSAssetsPlugin is not defined

### ISSUE THREAD

**Issue by tr1s** [webpack-contrib/mini-css-extract-plugin#264]
5.0.1

My webpack.config.js file works great, JS bundles on watch and minifies on build. SCSS does the same but it does NOT minify on watch nor build. The minute I add `new OptimizeCSSAssetsPlugin({ filename: "theme-webpack.scss.liquid" })` is doesn't build and the error is that OptimizeCSSAssetsPlugin is not defined.

Optimize doesn't seem to override anything.

Is this a bug ? What am I doing wrong? This has nothing to do with the .scss.liquid tags. I've tried with .scss and .css but nothing is working. I get the same undefined error. I'm working with Shopify and Shopify needs to read .scss files so I'm just trying to minify them in-case you're wondering my weird setup. 

```
const path = require('path');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');

module.exports = {
  entry: './src/theme.js',
  output: {
    path: path.resolve(__dirname, 'assets'),
    filename: 'theme-webpack.js'
  },
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        cache: true,
        parallel: true,
        sourceMap: true // set to true if you want JS source maps
      }),
      new OptimizeCSSAssetsPlugin({
        filename: "theme-webpack.scss.liquid"
      })
    ]
  },
  module: {
    rules: [{
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["env"]
          }
        }
      },
      {
        test: /\.(sa|sc|c)ss$/,
        use: [
          MiniCssExtractPlugin.loader,

          // 'style-loader', creates style nodes from JS strings //! create fallback instead, how?
          'css-loader',
          'postcss-loader',
          'sass-loader'
        ]
      }
    ]
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: "theme-webpack.scss.liquid"
    }),
    new OptimizeCssAssetsPlugin({
      assetNameRegExp: /\.optimize\.css$/g,
      cssProcessor: require('cssnano'),
      cssProcessorPluginOptions: {
        preset: ['default', { discardComments: { removeAll: true } }],
      },
      canPrint: true
    })
  ],
  resolve: {
    extensions: ['.css', '.scss', 'sass', '.js']
  }
}; 
```

Like I said even though the plugins say optimize css, I tried css, the undefined error is the problem. Also where is the documentation for doing fallbacks for `style-loader` ?

Any help would be greatly appreciated! But struggling with this for a couple days.

Thanks!

**Comment by michael-ciniawsky** [comment]
```
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
...

new OptimizeCSSAssetsPlugin({
  filename: "theme-webpack.scss.liquid"
})
```

You have a good ol' typo here (`...Css..` =>`..CSS..`) 😛

**Comment by michael-ciniawsky** [comment]
Also where is the documentation for doing fallbacks for style-loader ?

(In the README ;))

```js
const isDEV = process.env.NODE_ENV === 'development' // or anything you prefer

use: {
   isDEV ? 'style-loader' : MiniCSSPulugin.loader,
   'css-loader'
]
```

**Comment by tr1s** [comment]
@michael-ciniawsky where the hell did I copy and paste that from 😒ty!! It worked but only if I switch both to .css, turns out I can't minify .scss or .liquid files even if it's css inside the file, but it was worth a try. I'll let Shopify's system handle that then.

--

Right I did see that in the docs, but I don't fully understand what's happening and it doesn't seem to work in the first place. I think you're code example is wrong (spelling of the plugin), but if I look at the docs and switch

`MiniCssExtractPlugin.loader,`

with this.. 
      
`devMode ? 'style-loader' : MiniCssExtractPlugin.loader,`

then it works, but no matter if I run production mode or build mode the css still gets tossed in the js bundle. I thought it was only supposed to happen if I'm running dev mode?

Anyway I'm more so just curious about this, I don't think I really need this at all, I don't need or see the purpose of inline styles.

Also Is chunk files more for inlining as well? I left that out because it didn't seem necessary for me.

Thanks for the help!

**Comment by michael-ciniawsky** [comment]
> Right I did see that in the docs, but I don't fully understand what's happening and it doesn't seem to work in the first place. 

**`webpack.config.js`**
```diff
const isDEV = process.env.NODE_ENV === 'development'

const path = require('path');

const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
- const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
+ const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');

module.exports = {
  entry: './src/theme.js',
  output: {
    path: path.resolve(__dirname, 'assets'),
    filename: 'theme-webpack.js'
  },
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        cache: true,
        parallel: true,
        sourceMap: true // set to true if you want JS source maps
      }),
      new OptimizeCSSAssetsPlugin({
-       filename: "theme-webpack.scss.liquid"
+       assetNameRegExp: /\.css$/,
+       cssProcessor: require('cssnano'),
+       cssProcessorPluginOptions: {
+         preset: ['default', { discardComments: { removeAll: true } }],
+       },
+       canPrint: true
+      })
      })
    ]
  },
  module: {
    rules: [{
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["env"]
          }
        }
      },
      {
        test: /\.(sa|sc|c)ss$/,
        use: [
+         isDEV ? 'style-loader' : MiniCssExtractPlugin.loader,
          'css-loader',
          'postcss-loader',
          'sass-loader'
        ]
      }
    ]
  },
  plugins: [
    new MiniCssExtractPlugin({
-     filename: "theme-webpack.scss.liquid"
+     filename: '[name].theme.css',
+     chunkFilename: '[name].async.css'
    }),
-    new OptimizeCssAssetsPlugin({
-      assetNameRegExp: /\.optimize\.css$/g,
-      cssProcessor: require('cssnano'),
-      cssProcessorPluginOptions: {
-        preset: ['default', { discardComments: { removeAll: true } }],
-      },
-      canPrint: true
-    })
  ],
  resolve: {
    extensions: ['.css', '.scss', 'sass', '.js']
  }
}; 
```
> I think you're code example is wrong (spelling of the plugin), but if I look at the docs and switch

You know what are **variable** is and that the name can be freely choosen ? :)

> then it works, but no matter if I run production mode or build mode the css still gets tossed in the js bundle. I thought it was only supposed to happen if I'm running dev mode?

Did you set the `NODE_ENV` ? e.g via

**`package.json`**
```js
{
  "scripts": {
     "build": "NODE_ENV="production"  webpack,
     "start": "NODE_ENV="development" webpack-dev-server
   }
}
```

> Anyway I'm more so just curious about this, I don't think I really need this at all, I don't need or see the purpose of inline styles.

HMR (Hot Module Replacement) [No full page reload on CSS changes] 

If you don't need or use it 

```diff
- isDEV: 'style-loader' : MiniCSSExtractPlugin.loader
+ MiniCSSExtract.loader
```

> Also Is chunk files more for inlining as well? I left that out because it didn't seem necessary for me.

What are 'chunk files'? :) In case you mean `chunkFilename` it's equal to `filename` but for async CSS Chunks  (e.g `import('./async.css')`) which wll be loaded on-demand automatically once your application requires it (Code Splitting)

**Comment by tayler-ramsay** [comment]
Hello,

I read through the issues you were having and I am having a similar one. Was wondering if someone could see something I missing.  I am getting the same error

" OptimizeCssAssetsPlugin is not defined "


`const merge = require('webpack-merge');
const common = require('./webpack.common.js');
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");
const MediaQuerySplittingPlugin = require('media-query-splitting-plugin');


module.exports = merge(common, {
  mode: 'production',
  devtool: 'source-map',
  module: {
    rules: [{}]
  },
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        cache: true,
        parallel: true,
        sourceMap: true // set to true if you want JS source maps
      }),
      new OptimizeCSSAssetsPlugin({
        cssProcessor: require('cssnano')
      })
    ]
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: "[name].css",
      chunkFilename: "[id].css"
    }),
    new OptimizeCssAssetsPlugin({    }),
    new MiniCssExtractPlugin({
      filename: '[name]-[contenthash:8].css',
      chunkFilename: '[id].[contenthash].css'
    }),
    new MediaQuerySplittingPlugin({
      // This is default config (optional)
      media: {
        mobileEnd: 568,
        tabletPortraitEnd: 768,
        tabletLandscapeEnd: 1024,
      },
      splitTablet: true,
    })
  ],
  module: {
    rules: [{
      test: /\.(sa|sc|c)ss$/,
      use: [
        MiniCssExtractPlugin.loader,
        'css-loader',
        'postcss-loader',
        'sass-loader',
      ]
    }]
  }
});`

**Comment by tayler-ramsay** [comment]
Sorry  I had it duplicated DUMDUM
