### ISSUE TITLE
Console output is too noisy

### ISSUE THREAD

**Issue by elgs** [webpack-contrib/mini-css-extract-plugin#271]
This plugin is super useful, but it causes a lot of noise in the console. I'm wondering if there's any thing like log level options to calm it down when nothing is wrong? Thanks.

**Comment by elgs** [comment]
Sorry for bothering. This link helps: https://webpack.js.org/configuration/stats/

**Comment by duenyang** [comment]
nice!

**Comment by duenyang** [comment]
you just set it up like this:
`module.export = {
     stats = {
        children: false
    }
}`
to hide it
