### ISSUE TITLE
generated file's name error

### ISSUE THREAD

**Issue by LitileXueZha** [webpack-contrib/mini-css-extract-plugin#272]
When i using `optimization.runtimeChunk` to avoid unnecessary generated files.
The plugin options of filename is `"css/[name]-[hash].css"`. If it works well, we will get some files like below:
```
├── css    
    ├── index-dcbd465d3bca615e9fa6.css
    ├── login-dcbd465d3bca615e9fa6.css
```
But it becomes to `1-dcbd465d3bca615e9fa6.css`.  `[name]` becomes to Chunks Index
> Chunk Index seems in webpack's bundle infomation

**Comment by evilebottnawi** [comment]
@LitileXueZha same for async `js` chunks (and other type of resources), use should use `/* webpackChunkName */ ` or `NamedIdsPlugin`, look here https://github.com/webpack/webpack/issues/1949
