### ISSUE TITLE
Stats. What modules does css-chunk include?

### ISSUE THREAD

**Issue by c4off** [webpack-contrib/mini-css-extract-plugin#274]
I have a size-counting tool.  I want to know, what css-modules does a chunk include, so if one module has grown in size I can fire an alert and show, what css-file is causing troubles.

**Comment by c4off** [comment]
I have an entry-point. E.g. `category`. It imports different modules. These modules import js and css files. I want to know, what css-files are included in `category.css` chunk.

**Comment by michael-ciniawsky** [comment]
`stats.compilation.chunks`
