### ISSUE TITLE
Plugin changes behavior of splitChunks

### ISSUE THREAD

**Issue by ivensgoncalves** [webpack-contrib/mini-css-extract-plugin#277]
Hello,

I have a project with the following entries:

App1.js
It has the following scripts dependencies: "scripts/dependency1.js" and "scripts/common.js"
It has the following css dependencies: "styles/dependency1.css" and "styles/common.css"

App2.js
It has the following scripts dependencies: "scripts/dependency2.js" and "scripts/common.js"
It has the following css dependencies: "styles/dependency2.css" and "styles/common.css"

With the following "splitChunks" configuration on webpack:
```
splitChunks: {
  chunks: 'all',
  cacheGroups: {
	commons: {
	  name: 'commons',
	  chunks: 'initial',
	  minChunks: 1,
	  enforce: true
	}
  }
}
```

When I use the style-loader, I have the following output:
- App1.js
- App2.js
- Commons.js

Whatever was common to both entries, went to commons.js (including contents from style files like "common.css")
But when I switched from style-loader to MiniCssExtractPlugin, it then changed how optimization splits the code.
With MiniCssExtractPlugin I have the following output:
- App1.js
- App2.js
- Commons.js
- Commons.css

I was expecting the following output though:
- App1.js
- App2.js
- Commons.js
- App1.css
- App2.css
- Commons.css

Why everything is going to the "commons.css" chunk, even those which are exclusively used for one specific entry?

I've created a minimal project on github showing this behavior:
https://github.com/ivensgoncalves/MiniCssExtractPlugin_SplitChunks
You can run "npm run build" to build the project; the "dir" folder will have the output files.

Thanks in advance.

Best Regards,
Ivens Gonçalves.

**Comment by piecyk** [comment]
@ivensgoncalves check out the `extracting-css-based-on-entry` section in readme

https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-css-based-on-entry

basic you need something around 

```ts
const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

function recursiveIssuer(m) {
  if (m.issuer) {
    return recursiveIssuer(m.issuer);
  } else if (m.name) {
    return m.name;
  } else {
    return false;
  }
}

module.exports = {
  mode: 'development',
  entry: {
    app1: path.resolve(__dirname, 'src/app1.js'),
    app2: path.resolve(__dirname, 'src/app2.js')
  },
  plugins: [
    new CleanWebpackPlugin(['dist'], {exclude: ['.gitignore']}),
    new MiniCssExtractPlugin({
      filename: '[name].css'
    })
  ],
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader']
      }
    ]
  },
  optimization: {
    splitChunks: {
      cacheGroups: {
        app1Styles: {
          name: 'app1',
          test: (m, c, entry = 'app1') =>
            m.constructor.name === 'CssModule' && recursiveIssuer(m) === entry,
          chunks: 'all',
          enforce: true
        },
        app2Styles: {
          name: 'app2',
          test: (m, c, entry = 'app2') =>
            m.constructor.name === 'CssModule' && recursiveIssuer(m) === entry,
          chunks: 'all',
          enforce: true
        },
        commonStyles: {
          name: 'common',
          chunks: 'all',
          enforce: true,
          minChunks: 2
        }
      }
    }
  },
  resolve: {
    modules: ['src', 'node_modules']
  }
};
```

**Comment by ivensgoncalves** [comment]
Hello @piecyk 
Thanks for the quick reply.
I've just tested it, and it perfectly worked.

Thank you!


Best Regards,
Ivens Gonçalves.

**Comment by piecyk** [comment]
@ivensgoncalves great, please close the issue then! Thanks
