### ISSUE TITLE
how to use compass-mixins with mini-css-extract-plugin

### ISSUE THREAD

**Issue by heavenlian** [webpack-contrib/mini-css-extract-plugin#287]
rules: [
            {
                test:/\.(sa|sc|c)ss$/,
                use:[
                    // MiniCssExtractPlugin.loader, 
                    {
                        loader: MiniCssExtractPlugin.loader,
                        options:{
                            includePaths: [path.resolve(__dirname, 'node_modules/compass-mixins/lib')]
                        }
                    },
                    'css-loader', 
                    'sass-loader',
                ]
            }

ERROR in ./styles/app.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./styles/app.scss)
    Module build failed (from ./node_modules/sass-loader/lib/loader.js):

**Comment by micopiira** [comment]
You need to set the includePaths on the sass-loader

**Comment by evilebottnawi** [comment]
Please use `stackoverflow` or `gitter` for question. It is bug tracker. We have a lot of issue and don't have time to answer on question, sorry. You can use advise above. Thanks!
