### ISSUE TITLE
Trouble getting source map to work

### ISSUE THREAD

**Issue by lewebsimple** [webpack-contrib/mini-css-extract-plugin#29]
Maybe I'm missing something but I can't get the sourcemaps to generate either as a separate file or inline. I'm using the latest webpack (4.1.1) and mini-css-extract-plugin (0.2.0).

Relevant webpack module rules:
```
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {sourceMap: true},
          },
        ]
      },

      {
        test: /\.scss$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {sourceMap: true},
          },
          {
            loader: 'sass-loader',
            options: {sourceMap: true},
          },
        ]
      },
```

...and plugin:
```
    new MiniCssExtractPlugin({
      filename: 'css/styles.css'
    }),
```

Do I need to specify `devtool` property also ?

**Comment by lewebsimple** [comment]
Nevermind, I figured it out... turns out you actually need `devtool: 'source-map'` after all!

**Comment by yantakus** [comment]
Why doesn't it work with `devtool: 'cheap-module-eval-source-map'`? Would be very useful to have this information in the readme.

**Comment by gkatsanos** [comment]
Could the maintainer of this plugin clarify whats happening here?

**Comment by gkatsanos** [comment]
@SirKlaus 

> They say you should not do that:
> 
> Never use both the devtool option and plugin together.
> https://webpack.js.org/configuration/devtool/

Where did you see that? I don't see this in the readme.

**Comment by andrastothtw** [comment]
I have an error when both `css-loader` and `less-loader` is set to `sourceMap: true`.
```javascript
use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: { sourceMap: true },
          },
          {
            loader: 'less-loader',
            options: { sourceMap: true },
          },
        ],
```

The error message: 
> ERROR in ./src/styles/main.less
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'context' of undefined
    at Object.<anonymous> (/Users/andras.toth/IdeaProjects/contact-form-frontend/node_modules/css-loader/lib/loader.js:101:58)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/andras.toth/IdeaProjects/contact-form-frontend/node_modules/css-loader/lib/loader.js:99:31)`

And of course no css.map file is generated.

**Comment by gkatsanos** [comment]
source-map doesn't work HMR.

**Comment by heyalbert** [comment]
Some configuration as lewebsimple but newer webpack version (4.8.1). Sourcemap doesn't work at all. Bug? How does your solution looks like?

**Comment by yamass** [comment]
@lewebsimple Could you please reopen this issue? Using `devtool: 'source-map'` might be ok for production builds but not for development (much too slow). This needs to get fixed.

I personally use `devtool: 'cheap-module-source-map'` as a workaround, but it is still much slower than `cheap-module-eval-source-map`.

**Comment by Pushplaybang** [comment]
yeah seriously, this is confusing and frustrating as all hell.

**Comment by mwilkins91** [comment]
Same issue, 

```

    new webpack.SourceMapDevToolPlugin({
      filename: '[name].[chunkhash:8].js.map',
      exclude: /vendors*(.+?).js/,
      lineToLine: true,
      columns: false,
    }),

```

results in no sourcemaps being generated for extracted css

**Comment by evilebottnawi** [comment]
Please don't spam difference issue in other issue, your problem can't be solved here never, source map getting from `css-loader`, so many features can't be supports due limitation `loader` api, we need implement out of box `css` support in webpack to solve many of them, thanks

**Comment by ivan-vilches** [comment]
Any solution?

**Comment by phxism** [comment]
[Solution to no CSS source map file generated under production mode in Webpack 4](https://www.webfoobar.com/node/109) it might help

**Comment by ProTip** [comment]
@SirKlaus you saved my day by helping wrap up a final loose end!

I used `include: [/\.css$/]` to generate only CSS source map files but otherwise this solution works great so far.
