### ISSUE TITLE
Respect semver?

### ISSUE THREAD

**Issue by kud** [webpack-contrib/mini-css-extract-plugin#291]
Hello,

I'd like to know if it's possible to respect semver in your versions?

Because:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/655838/46422864-88603280-c735-11e8-8702-005bbcf9b284.png">

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/style-loader/issues/348
