### ISSUE TITLE
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by Varavarforvar** [webpack-contrib/mini-css-extract-plugin#293]
webpack -v 4.20.2

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by zilahir** [comment]
this problem still persits. does not need any step. just include 

`const MiniCssExtractPlugin = require("mini-css-extract-plugin");`

and compiling fails.
