### ISSUE TITLE
HRM working with MiniCssExtractPlugin.loader

### ISSUE THREAD

**Issue by ylacaute** [webpack-contrib/mini-css-extract-plugin#296]
Hi ! You will be happy to read me, this is not an issue !

I am able to use MiniCssExtractPlugin config with webpack-dev-server with hot reload working.

```javascript
{
        test: /\.(css|sass|scss)$/,
        use: [{
          loader: MiniCssExtractPlugin.loader
        }, {
          loader: "css-loader"
        }, {
          loader: "sass-loader"
        }]
      },
```
No need to make a special condition on the loader, no more style-loader.
As I am not sure to fully understand HRM I prefer to not create PR :)

**Comment by evilebottnawi** [comment]
@ylacaute Plugin doesn't support HMR. Look in `README`: https://github.com/webpack-contrib/mini-css-extract-plugin

> TODO:

>  HMR support

Feel free to send a PR

**Comment by ylacaute** [comment]
I read the README, that is exactly why I am posting this.

Currently I setup a fresh project with Webpack 4 and I got the hot reloading WORKING on my SCSS files without the dev condition : I always use MiniCssExtractPlugin.loader and it works like a charm.

So, maybe I don't understand but I think your feature is already done, it's already working :)

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/mini-css-extract-plugin/issues/34
