### ISSUE TITLE
Prefetch/preload referenced assets

### ISSUE THREAD

**Issue by holloway** [webpack-contrib/mini-css-extract-plugin#298]
Is there a way to indicate from CSS/Sass that certain assets should be preloaded/prefetched such as fonts?

[Webpack 4.6.0 supports prefetching/preloading](https://webpack.js.org/guides/code-splitting/#prefetching-preloading-modules) of modules, and it would be nice to be able to use this in CSS too. [Lighthouse mentions `<link rel="preload">` for fonts](https://developers.google.com/web/updates/2018/05/lighthouse#all_text_remains_visible_during_web_font_loads) as an optimisation strategy.

So I've tried adding,

    @font-face {
      font-family: 'CalibreSchoolWeb';
      font-style: 'normal';
      font-weight: 300;
      src: url(/* webpackPrefetch: true */ './fonts/CalibreSchoolWeb-Light.woff2') format('woff2');
    }

But this doesn't result in a `<link rel="preload">` added to the HTML pointing to the asset, and I can't hardcode the link tag because I don't know the resulting build filename.

It seems that `/* */`-style comments are preserved by Sass so that's not the issue ([cite](https://www.tutorialspoint.com/sass/sass_comments.htm)).

Am I just doing it wrong or is there a way of preloading these assets?

**Comment by evilebottnawi** [comment]
preload/prefetch works only for js, it will be solved in webpack 5

**Comment by holloway** [comment]
Thanks for the clarification @evilebottnawi :smile:

**Comment by dmitryuk** [comment]
Hello. Can you assist a way how it has been resolved in webpack 5?
