### ISSUE TITLE
can't use @import css file in sass/css files

### ISSUE THREAD

**Issue by joebnb** [webpack-contrib/mini-css-extract-plugin#301]
hi, there is a question about use @import  to import some .css files in css file ,webpack not bundle them all,can you help me solve this ?

js file:
```js
import './index.scss';
```

index.scss file
``` css
@import '~/node_modules/@didi/mfe-util-style/lib/index.scss';
@import '~/node_modules/bootstrap/dist/css/bootstrap.css';
```

css output file
```
/* content of  index.scss */
@import url('/node_modules/bootstrap/dist/css/bootstrap.css')
```
expect:
```
/* content of  index.scss */
/* content of  bootstrap.css */
```
did my configure wrong?

respect

**Comment by evilebottnawi** [comment]
You have invalid configuration, you don't have configuration or minimum reproducible test repo in issue so i can't help, issue not related to this plugin
