### ISSUE TITLE
Error happens when my project depends on package A, and package A depends on the css in package B

### ISSUE THREAD

**Issue by kingller** [webpack-contrib/mini-css-extract-plugin#306]
Hi,
  Error happens when my project depends on package A, and package A depends on the css in package B, when I run my project with this plugin. But when I run package A with this plugin, it's OK.

The code of import the css of B in Package A as bellow,
```
import 'B/index.css';
```
The package B is installed in A as bellow, it's OK when I run package A.
```
A
  |- node_modules
        |- B - index.css
```
But when I use package A in my project, the modules are installed like this,
```
My project
  |- node_modules 
       |- A (depends on the css in package B)
       |- B - index.css
``` 
The cause of error I think is: B is not installed under A, but the plugin still look for B under A, so error happens. Can you fix it please? Thanks.

**Comment by evilebottnawi** [comment]
@kingller it is problem in package, how we can fix it?

**Comment by kingller** [comment]
Is it possible to look for it up to node_modules under My project, not A? Since (node>=5.0, npm>=3.0),  some optimization done as the bellow example, if a and b depend on c in the same version range, then only one c will be installed, and installed to the top level as a and b
```
|--a--c
|--b--c
```
will change to
```
|--a
|--b
|--c
```

**Comment by kingller** [comment]
And now, I can only fix the error by two methods. One is copy the css of B to A, the other is use style-loader instead of mini-css-extract-plugin. But both of them are not I want.
