### ISSUE TITLE
SSR; all extracted CSS is loaded, load on demand not working

### ISSUE THREAD

**Issue by Avcajaraville** [webpack-contrib/mini-css-extract-plugin#307]
This is a follow up of issue #90.

I created a [simple repository](https://github.com/Avcajaraville/debugging-mini-css-extract-plugin) to illustrate the issue.

Please, npm install && npm start, then go to localhost:3000

If you inspect the  requested CSS, you can see all of the extracted CSS loaded, which is not the actual desired:

![captura de pantalla 2018-11-16 09 12 05](https://user-images.githubusercontent.com/2271201/48606352-badd8c00-e97f-11e8-89c3-6aac07e9da22.png)

This css contains styles for /about page, even though we are not on the about page:

![captura de pantalla 2018-11-16 09 13 02](https://user-images.githubusercontent.com/2271201/48606424-dea0d200-e97f-11e8-9cad-7753434381df.png)

CSS for /about & /test routes should be lazy loaded once we visit those routes, not before.

The desired behavior is to have this CSS loaded only when visiting the correct routes and not before.

**Comment by evilebottnawi** [comment]
@Avcajaraville can you create simple example, without `vue-loader`? Looks problem not related to plugin directly.

**Comment by Avcajaraville** [comment]
@evilebottnawi I cant remove vue-loader, if I do, none of my setup makes sense, as its a fully vue project and all the files are vue files.

**Comment by jimblue** [comment]
Hi @evilebottnawi,

Any update about this issue?

**Comment by alexander-akait** [comment]
Can't reproduce only one CSS was loaded, I think it was bug in `vue-loader` or something else
![Screenshot from 2021-02-18 18-13-15](https://user-images.githubusercontent.com/4567934/108377381-06450b80-7215-11eb-8ba3-8625e991ba69.png)

Also related https://github.com/nuxt/nuxt.js/issues/3943

**Comment by takhello** [comment]
@alexander-akait  Any clues?
------------------------------
Again, no on-demand loading, loading all the styles, resulting in program clutter

**Comment by Avcajaraville** [comment]
Thanks for your support and interest @alexander-akait
