### ISSUE TITLE
Introducing images with relative paths in scss will cause postcss to fail

### ISSUE THREAD

**Issue by pdsuwwz** [webpack-contrib/mini-css-extract-plugin#309]
question link: 

https://stackoverflow.com/questions/53313444/introducing-images-with-relative-paths-in-scss-will-cause-postcss-to-fail

repository: https://github.com/pdsuwwz/react-app

**Comment by evilebottnawi** [comment]
1. It is bug tracker, use `stackoverflow` or `gitter` for questions.
2. Please use **English** language in reproducible test repo. My native language is Russian and you will be uncomfortable reading my answers and examples on this language
3. Create **minimum** reproducible test repo, it is OSS, not all people have time to debug many code.
4. We don't touch images here, repo not related to problem.
