### ISSUE TITLE
Webpack 4 - should work with css-hot-loader

### ISSUE THREAD

**Issue by iongion** [webpack-contrib/mini-css-extract-plugin#31]
I have reported an issue on [css-hot-loader](https://github.com/shepherdwind/css-hot-loader/issues/36)
I added it here too because I cannot understand which one is creating the problem.
What is certain is that `css-hot-loader` did work with the `ExtractTextPlugin`

I saw in the *TODO* that this is planned, but there is no opened issue related to it, I wouldn't have reported it otherwise!

**Comment by shepherdwind** [comment]
Did this issue fixed now? My example code work fine now.

**Comment by evilebottnawi** [comment]
@iongion @shepherdwind Looks like bug was fixed https://github.com/webpack-contrib/mini-css-extract-plugin, feel free to feedback of problem still exists. Thanks!
