### ISSUE TITLE
Cannot generate CSS file from jsx entry

### ISSUE THREAD

**Issue by 1349279985** [webpack-contrib/mini-css-extract-plugin#311]
**Webpack Version:** 4.17.0
**React Version:** 15.1.0
**mini-css-extract-plugin Version:** 0.4.4

I have a Coupon.jsx, it import a coupon.less like this.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/15374767/48816601-c36a0400-ed7d-11e8-972e-1bafc1c9b68e.png">

webpack config like this.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/15374767/48816623-e1376900-ed7d-11e8-8b5c-dc8cc6fa391f.png">

But build result is like this.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/15374767/48816689-20fe5080-ed7e-11e8-8099-fb1ac1888eaa.png">

It doesn't generate coupon.css, I don't know why, how can it generates coupon.css

**Comment by 1349279985** [comment]
In Coupon.jsx, change 'import' to 'require', it works. mini-css-extract-plugin don't support 'import'?

**Comment by evilebottnawi** [comment]
Support, you have invalid configuration, you can't provide this, so i can't help

**Comment by evilebottnawi** [comment]
Looks you don't have loader, see README
