### ISSUE TITLE
How to enable `crossorigin` attributes for on-demand chunks?

### ISSUE THREAD

**Issue by chikara-chan** [webpack-contrib/mini-css-extract-plugin#312]
How to enable `crossorigin` attributes for on-demand chunks?

**Comment by evilebottnawi** [comment]
It is feature feel free to send a PR, looks we need option for this

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/mini-css-extract-plugin/pull/313, will be shipped in end of week, feel free to feedback

**Comment by codeocelot** [comment]
@evilebottnawi doesn't seem like this was shipped last week. Could you provide an update on when this feature will ship?

**Comment by MartinGian** [comment]
Hi, is this feature enabled in the last version of the package? Thanks
