### ISSUE TITLE
less file has not been deleted from js file after extracted

### ISSUE THREAD

**Issue by 1349279985** [webpack-contrib/mini-css-extract-plugin#317]
I have a _**index.js**_ file. It imports a _**test.less**_. 
![image](https://user-images.githubusercontent.com/15374767/48954876-3fcf3380-ef86-11e8-82ab-463378ee3344.png)
The MiniCssExtractPlugin plugins can read a css file from js and generate a **_index.css_**. But i use [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) to find that the **_index.js_** file still has **_test.less_**. I don't know why. And hope your help.This is [demo git address](https://github.com/1349279985/wepack4-demo)
![image](https://user-images.githubusercontent.com/15374767/48955089-34c8d300-ef87-11e8-90d6-04639ef4ec42.png)

**Comment by evilebottnawi** [comment]
@1349279985 better create this issue in ` webpack-bundle-analyzer`,w e use standard webpack api
