### ISSUE TITLE
Different hash ID for same output referenced by 2 different JS files

### ISSUE THREAD

**Issue by adrienharnay** [webpack-contrib/mini-css-extract-plugin#319]
Hey,

So I've implemented script type="module" support for my app, and have duplicated all my webpack config, only changing the babel options (`esmodules: true`) and the file extensions (.js => .mjs). Now when I look at the outputted files, some CSS files are duplicated with a different ID, but exactly the same content.

It happened on 4 files out of 70.

I'm aware that you would need a reproduction repo, but since it is not happening every time, I'm not sure how that could be reproduced. Would you have any idea about a possible cause?

Thanks in advance!

**Comment by evilebottnawi** [comment]
@adrienharnay please create minimum reproducible test repo

**Comment by adrienharnay** [comment]
Did you even read what I posted?

**Comment by evilebottnawi** [comment]
@adrienharnay no ideas, so i ask to try create reproducible test repo

**Comment by evilebottnawi** [comment]
We can't fix something in anything, sorry. I am closing this issue due can't reproducible, but i am open for feedback, thanks
