### ISSUE TITLE
CSS from node_modules is not include in the generated css

### ISSUE THREAD

**Issue by AvraamMavridis** [webpack-contrib/mini-css-extract-plugin#32]
I am using the module with Webpack 4.1.0
We have a ui-lib that has some components along with there `scss` files.

e.g.

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import TanForm from 'ui-lib/src/components/TanForm';

...
render() {
   return (
        <TanForm />
    )
}
```

I am using the plugin like

```
    new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output
      // both options are optional
      filename: 'obsstyles.css',
    }),

   ...

  module: {
    rules: loaders.concat([
      {
        test: [/\.scss$/, /\.css$/],
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader', 'sass-loader',
        ],
        include: [
          /src/,
          /ui-lib/,
        ],
      },
    ]),
  },
```

The generated css does not contain the classes from the `ui-lib` components
Not sure if my setup is wrong or there is a bug. I see many `undefined` classes. 

<img width="473" alt="screen shot 2018-03-09 at 14 57 32" src="https://user-images.githubusercontent.com/283690/37210792-3a92bf34-23aa-11e8-8abf-96729c923d85.png">

**Comment by sandersky** [comment]
I could be wrong but wouldn't your `include` config need to use `node_modules/ui-lib/` instead of `/ui-lib/`? Also is any of your code actually including the `ui-lib` CSS via a CSS `@import` statement or a JS `require`/`import`?

**Comment by sokra** [comment]
> Also is any of your code actually including the ui-lib CSS via a CSS @import statement or a JS require/import?

**Comment by AvraamMavridis** [comment]
The import is only through JS.

My component are importing components from a shared ui library, there, the components are importing the styles like


```
import React, { Component } from 'react'
import styles from './styles.scss
```

**Comment by michael-ciniawsky** [comment]
@AvraamMavridis Could you please post an `@import` example and the relevant part of your `webpack.config.js` ? `resolve.alias` isn't supported by `css-loader` for `@imports`'s btw :). For `node_modules/lib` => `~lib` as a shorthand is supported

**Comment by lfernandoavalos** [comment]
Is there any update on this? Or I might just be doing things wrong. I'm currently building a component ui library and generating build files with .js and .css. Is there a way I can load the css by only importing the component without requiring me to load both the component and css?

```
// What I'm currently doing - importing the generated css file from webpack
import 'path/to/dist/Bagels/index.css';
import Bagels from 'path/to/dist/Bagels';

// What I wish - Automagically import css by just importing component
import Bagels from 'path/to/dist/Bagels';
```
