### ISSUE TITLE
Is it possible to ignore urls (in CSS files only) ? (option url: false)

### ISSUE THREAD

**Issue by martinlemahieu** [webpack-contrib/mini-css-extract-plugin#320]
Hi ! I'm trying to migrate from `extract-text-webpack-plugin` and I can't figure out if there is an option similar to `url: false` in `mini-css-extract-plugin` ?

Or any other way to ignore image urls in CSS files. (But not in JS files).

Many thanks in advance for any help or answer you can provide. 😃

**Comment by evilebottnawi** [comment]
Don't use this plugin for `css`, it is abandoned and deprecated

**Comment by martinlemahieu** [comment]
Sorry for my english, I'm trying to migrate FROM `extract-text-webpack-plugin` TO `mini-css-extract-plugin`.

I'm looking for a way not to process image files, in `extract-text-webpack-plugin` I was using `{options: {url: false}}`, is there a similar option in `mini-css-extract-plugin` ? Or any other solution to achieve this ?

**Comment by evilebottnawi** [comment]
@martinlemahieu it is option for `css-loader`, not for this plugin

**Comment by martinlemahieu** [comment]
@evilebottnawi it is ! 🤣 Sorry it seems I'm too tired, thank you for pointing it out, I could have spend some time figuring it out myself !

**Comment by oshanz** [comment]
hi @martinlemahieu , I'm having the same issue. so can you please mention your solution?

**Comment by Abdull** [comment]
Another example:

```
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

// ...

module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.s[ac]ss$/i,
        use: [
          MiniCssExtractPlugin.loader,
          { 
            loader: 'css-loader',
            options: {
              url: false
            }
          },
          'resolve-url-loader',
          'sass-loader'
        ]
      },
      // ...
    ]
  }
};
```

**Comment by graham73may** [comment]
I was really struggling with where to put these settings...

Just to add to these examples, here's what I have with Webpack / Laravel Mix

```js
mix
    // SASS files.
    .sass('scss/style.scss', 'css/style.min.css')

    // Add sourcemaps.
    .sourceMaps()

    // Run clean-css on all stylesheets.
    .cleanCss({
        level: 2,
    })

    // Mix options.
    .options({
        processCssUrls: false, // Disable URL resolving
        terser        : {
            extractComments: false,
        },
    });
```
