### ISSUE TITLE
Correct syntax for publicPath in options

### ISSUE THREAD

**Issue by cutme** [webpack-contrib/mini-css-extract-plugin#324]
I'm trying add publicPath option to loader inline:

`
    use: [
        devMode ? 'style-loader' : MiniCssExtractPlugin.loader?options.publicPath='../'
    ]
`

What is the correct syntax?

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin#minimal-example

**Comment by cutme** [comment]
Thanks, but I need to add this option only in prod mode (condition).
