### ISSUE TITLE
cacheGroups depending on import file name

### ISSUE THREAD

**Issue by brettsmason** [webpack-contrib/mini-css-extract-plugin#325]
I'm looking for help with the `cacheGroups` feature as I think it will solve an issue I have.
I have a single JavaScript entry file `index.js` which imports 2 Sass files like so:
```
import './style.scss'
import './editor.scss'
```

What I'd like to end up with is two CSS files - `style.css` and `editor.css`.

Is this possible to achieve with the `cacheGroups` option mentioned [here](https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-css-based-on-entry)?
I haven't been able to work out to modify this example to do it.

Any help much appreciated!

**Comment by evilebottnawi** [comment]
@brettsmason for questions please use `gitter` or `stackoverflow`, thanks
