### ISSUE TITLE
How to avoid loading of extracted CSS?

### ISSUE THREAD

**Issue by jaylinski** [webpack-contrib/mini-css-extract-plugin#33]
I'm using this plugin to extract and inline my critical CSS.   
Since the extracted CSS gets inlined in my HTML, it does not have to be loaded anymore.

Can I tell this plugin to not load the CSS it extracted?

If this is not (yet) possible, can it be implemented easily? (I could try and submit a PR)

Otherwise I'll switch back to `extract-text-webpack-plugin`.

**Comment by michael-ciniawsky** [comment]
Wrapping this [block](https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L142-L216) should do the trick

```js
const load = options.load ||  true

if (load) {
  // ...code
}
```

**Comment by jaylinski** [comment]
@michael-ciniawsky Thanks for the response!

But it seems I stayed awake for too long and didn't realize that the `html-webpack-plugin` was auto-injecting the CSS (since it's a main chunk) into my HTML.

It seems this plugin isn't loading the extracted CSS automatically at all... :sweat_smile:
