### ISSUE TITLE
support webpack@5

### ISSUE THREAD

**Issue by victors1681** [webpack-contrib/mini-css-extract-plugin#330]
```
...... /node_modules/mini-css-extract-plugin/dist/index.js:217
      mainTemplate.hooks.requireEnsure.tap(pluginName, (source, chunk, hash) => {
                                       ^

TypeError: Cannot read property 'tap' of undefined
    at compiler.hooks.thisCompilation.tap.compilation (/Users/santosv/workspace/webpack-boilerplate/node_modules/mini-css-extract-plugin/dist/index.js:217:40)
    at SyncHook.eval [as call] (eval at create (/Users/santosv/workspace/webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/santosv/workspace/webpack-boilerplate/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/santosv/workspace/webpack-
```

**Comment by davetron5000** [comment]
Looks like “MainTemplate.hooks.requireEnsure removed”: https://github.com/webpack/changelog-v5/blob/master/README.md#other-minor-changes

**Comment by evilebottnawi** [comment]
Feel free to send a PR

**Comment by hulkish** [comment]
related https://github.com/webpack/webpack/issues/8537

**Comment by phaistonian** [comment]
Any ETA on this one?

**Comment by evilebottnawi** [comment]
No ETA, but when webpack@5 was released, plugin already support webpack@5

**Comment by phaistonian** [comment]
@evilebottnawi  as I noticed in the [feedback summary](https://github.com/webpack/webpack/issues/8537), it's stated that it's not compatible yet.

**Comment by Septdir** [comment]
I would really like to use `mini-css-extract-plugin` with webpack 5

However, it looks like it won't work before  webpack 5release.
So far I have found an alternative.

`extract-css-chunks-webpack-plugin`

**Comment by ylemkimon** [comment]
I can confirm no warnings or errors are produced with `webpack@>=5.0.0-beta.23` and `mini-css-extract-plugin@^0.11.0`. (#477, #571, #573)

**Comment by evilebottnawi** [comment]
Yes, fixing HMR is on our roadmap (current or next week), maybe we found time faster for this

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v0.11.3
