### ISSUE TITLE
Error while using with Angular 7

### ISSUE THREAD

**Issue by santoshyadav198613** [webpack-contrib/mini-css-extract-plugin#335]
Angular/cli : 7.14
webpack: 4.23.1
Node : 8.11.1 

C:\Users\yadasanb\COE-Framework\Angular 5 Repo\framework\node_modules\mini-css-e
xtract-plugin\dist\index.js:136
    compiler.hooks.thisCompilation.tap(pluginName, compilation => {
                   ^

TypeError: Cannot read property 'thisCompilation' of undefined
    at MiniCssExtractPlugin.apply (C:\Users\yadasanb\COE-Framework\Angular 5 Rep
o\framework\node_modules\mini-css-extract-plugin\dist\index.js:136:20)
    at Compiler.apply (C:\Users\yadasanb\COE-Framework\Angular 5 Repo\framework\
node_modules\webpack-stream\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (C:\Users\yadasanb\COE-Framework\Angular 5 Repo\framework\node_mo
dules\webpack-stream\node_modules\webpack\lib\webpack.js:33:19)
    at Stream.<anonymous> (C:\Users\yadasanb\COE-Framework\Angular 5 Repo\framew
ork\node_modules\webpack-stream\index.js:132:20)
    at _end (C:\Users\yadasanb\COE-Framework\Angular 5 Repo\framework\node_modul
es\through\index.js:65:9)
    at Stream.stream.end (C:\Users\yadasanb\COE-Framework\Angular 5 Repo\framewo
rk\node_modules\through\index.js:74:5)
    at DestroyableTransform.onend (C:\Users\yadasanb\COE-Framework\Angular 5 Rep
o\framework\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at endReadableNT (C:\Users\yadasanb\COE-Framework\Angular 5 Repo\framework\n
ode_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

CODE"

return gulp.src([`${config.srcFolder}/**.scss`])
        .pipe(named())
        .pipe(sourcemaps.init())
        .pipe(webpackStream({
            devtool: 'source-map',
            module: {
                rules: [
                    {
                        test: /\.scss$/,
                        use: [
                            MiniCssExtractPlugin.loader,
                            { loader: 'css-loader', options: { minimize: false } },
                            'sass-loader',
                            { loader: 'postcss-loader', options: { syntax: 'postcss-scss', plugins: [autoprefixer()] } },
                        ]
                    },
                    {
                        test: /\.(svg)$/,
                        use: [
                            {
                                loader: 'url-loader',
                                options: {
                                    limit: 8192
                                }
                            },
                            {
                                loader: 'svgo-loader',
                                options: {
                                    svgo: svgMinOptions
                                }
                            },
                            {
                                loader: 'svg-colorize-loader',
                                options: {
                                    color1: "#000000",
                                    color2: "#FFFFFF"
                                }
                            },
                            {
                                loader: require.resolve('./svg-loader.js')
                            }
                        ]
                    }
                ]
            },
            plugins: [
                new MiniCssExtractPlugin('[name].css')
            ]
        }))
        .pipe(sourcemaps.write('.'))
        .pipe(filter(["**/*.css*", "**/*.css.map"]));
}

**Comment by evilebottnawi** [comment]
Better create this problem in `angular` plugin repo

**Comment by evilebottnawi** [comment]
Also looks you use old webpack version

**Comment by benfjohnson** [comment]
If anyone else updates their webpack version and continues to run into this when running an application locally, make sure you've also bumped `webpack-dev-server` (assuming you're using it to develop locally). Earlier versions will throw the same error.
