### ISSUE TITLE
Possible regression in 0.4.4

### ISSUE THREAD

**Issue by dustinsoftware** [webpack-contrib/mini-css-extract-plugin#337]
I can't repro this issue outside of my work's source code (which I can't share), so I understand having this fixed is a bit of a longshot. That said, I'll share as much as I can about the problem we're running into:

In #284 , `this.id` was set to empty string in the constructor. *Somehow*, in one of our projects, this causes `React` to be imported as `undefined` in a lazy loaded component. 

After using `yarn link` locally with `mini-css-extract-plugin`, I can confirm that the issue did not happen before that change for us. Commenting out the initial assignment to `this.id` and rebuilding fixes the runtime issue.

Our project looks something like this:
- Main component
  - Lazy loaded component, whose source is minified and published to an internal npm registry
  - Lazy loaded component's exported stylesheet

```js
export class LazyLoaded extends React.Component {
	constructor() {
		super();
		this.state = { loaded: false };
	}
	componentDidMount() {
		import('lazy-loaded-example').then(component => { this.setState({ loadedComponent: component.default })})
	}
	render() {
		return this.state.loadedComponent
			? React.createElement(this.state.loadedComponent, {})
			: React.createElement('h1', {}, 'Loading');
	}
}
```

After change:
![image](https://user-images.githubusercontent.com/942358/51147655-f37ad400-180f-11e9-9848-aa1b97d647e1.png)

![image](https://user-images.githubusercontent.com/942358/51147668-0392b380-1810-11e9-8620-ca2dfd083608.png)

I can repro this pretty reliably locally, but I'm not sure what information I could share that would be helpful.

```
  "devDependencies": {
    "css-loader": "^1.0.0",
    "mini-css-extract-plugin": "^0.4.5",
    "postcss-loader": "^3.0.0",
    "url-loader": "^1.1.2",
    "webpack": "^4.16.0",
    "webpack-cli": "^3.0.8"
  },
  "scripts": {
    "build": "webpack"
  },
```

**Comment by dustinsoftware** [comment]
Ok, it looks like this issue is related `NamedModulesPlugin` using a strict equality check, comparing `id` to `null` [somewhere around here](https://github.com/MhMadHamster/webpack/blob/87dd7a2ed40f69f97e1402b5438a18da8400381c/lib/NamedModulesPlugin.js#L32).

https://github.com/webpack/webpack/issues/7088
https://github.com/webpack/webpack/pull/7152/files

Should `this.id` be initialized to null in `MiniCssExtractPlugin`, if at all? It's still unclear why that change was introduced.

cc @lfre @sokra do you have any ideas off the top of your head where to investigate next? For now we'll work around the problem by pinning to an older version of this plugin.

**Comment by evilebottnawi** [comment]
@dustinsoftware problem solved in `webpack@5`, doesn't think it is possible fix on plugin side

**Comment by dustinsoftware** [comment]
Sorry, I’ve since moved on to another co and don’t have a reliable repro for this anymore. I think we worked around the problem by pinning to an older package version.
