### ISSUE TITLE
Add Error code for chunk loading failure

### ISSUE THREAD

**Issue by SergeyPanchenkoWeWork** [webpack-contrib/mini-css-extract-plugin#346]
## Feature request
Added code property on Error object received when failed to load chunk, To help identify loading errors.
Related to https://github.com/webpack/webpack/issues/8695

**What is the expected behavior?**
add `CSS_CHUNK_LOAD_FAILED` in `error.code`

**How should this be implemented in your opinion?**
Add `error.code = 'CSS_CHUNK_LOAD_FAILED'` in https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L362

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by SergeyPanchenkoWeWork** [comment]
Sure  https://github.com/webpack-contrib/mini-css-extract-plugin/pull/347 😃
