### ISSUE TITLE
Extract all chunks to single css not working

### ISSUE THREAD

**Issue by sainathsr** [webpack-contrib/mini-css-extract-plugin#351]
I am using vue cli 3 with with mini-css-extract-plugin v .5.0

I tried the recommended config from the docs 

```
  optimization: {
    splitChunks: {
      cacheGroups: {
        styles: {
          name: 'styles',
          test: /\.css$/,
          chunks: 'all',
          enforce: true
        }
      }
    }
```

It does not seem to work , I still get multiple css when using dynamic entry points . Please help with this

**Comment by evilebottnawi** [comment]
Without minimum reproducible test repo we can't help, also we can't help without full config. 

vue cli can have own config for `splitChunks`.
