### ISSUE TITLE
[Optimization request] Remove empty "modules"

### ISSUE THREAD

**Issue by Andarist** [webpack-contrib/mini-css-extract-plugin#357]
When using this plugin we might end up with something like this:
<details>
<summary>Click</summary>
/***/ 54:
/***/ (function(module, exports, __webpack_require__) {

// extracted by mini-css-extract-plugin

/***/ }),

/***/ 92:
/***/ (function(module, exports, __webpack_require__) {

// extracted by mini-css-extract-plugin

/***/ }),

/***/ 93:
/***/ (function(module, exports, __webpack_require__) {

// extracted by mini-css-extract-plugin

/***/ }),

/***/ 94:
/***/ (function(module, exports, __webpack_require__) {

// extracted by mini-css-extract-plugin

/***/ }),

/***/ 95:
/***/ (function(module, exports, __webpack_require__) {

// extracted by mini-css-extract-plugin

/***/ }),

/***/ 96:
/***/ (function(module, exports, __webpack_require__) {

// extracted by mini-css-extract-plugin

/***/ }),

/***/ 97:
/***/ (function(module, exports, __webpack_require__) {

// extracted by mini-css-extract-plugin

/***/ }),

/***/ 98:
/***/ (function(module, exports, __webpack_require__) {

// extracted by mini-css-extract-plugin

/***/ }),
</details>

Seems like this could be optimized away - i know that probably minifier + gzip makes this kinda cheap, but parsing costs add up and it would be always good to strive for less code in such cases.

**Comment by evilebottnawi** [comment]
Please provide minimum reproducible test repo, it should be removed by webpack

**Comment by Andarist** [comment]
I've somehow missed your reply. Gonna try to prepare slimmed down repro for this.

**Comment by irudoy** [comment]
@evilebottnawi minimum reproducible test repo: https://github.com/irudoy/webpack-mceplugin-empty-repro

**Comment by irudoy** [comment]
@evilebottnawi any thoughts?

**Comment by evilebottnawi** [comment]
@irudoy sorry, some busy, but you can send a PR with implementation this feature :+1:

**Comment by irudoy** [comment]
@evilebottnawi I experimented a bit, but with no luck. Can you point out how to achieve this?

**Comment by evilebottnawi** [comment]
@irudoy we solve this problem for extract-text-webpack-plugin (https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/webpack-1/index.js#L273), i think solution is same

**Comment by irudoy** [comment]
Some results:

```
entry1: 269 empty modules
entry2: 186 empty modules

with empty modules:
entry1: 49.9 KiB / 14.3 KiB (gzip)
entry2: 15.8 KiB / 4.8 KiB (gzip)

without empty modules:
entry1: 40.4 KiB / 12.1 KiB (gzip)
entry2: 8.8 KiB / 3.3 KiB (gzip)
```

**Comment by evilebottnawi** [comment]
Great :+1:

**Comment by aleen42** [comment]
I found that the problem still existed when using `Webpack@5.71.0` + `mini-css-extract-plugin@2.6.0`.
