### ISSUE TITLE
mini-css-extract-plugin can't extracting all CSS in a single file

### ISSUE THREAD

**Issue by zjlhope** [webpack-contrib/mini-css-extract-plugin#359]
I do as the document says,but it create many css file，how can i do

**Comment by evilebottnawi** [comment]
Please see documentation, also for questions use gitter or stackoverflow. Anyway we can't help you without minimum reproducible test repo, feel free to feedback

**Comment by YueminHu** [comment]
> I do as the document says,but it create many css file，how can i do

https://github.com/webpack-contrib/mini-css-extract-plugin/issues/224
