### ISSUE TITLE
What's the difference between filename and chunkFilename options

### ISSUE THREAD

**Issue by ripperdoc** [webpack-contrib/mini-css-extract-plugin#36]
As the title, it seems sometimes one is used, sometimes the other. Could someone explain?

**Comment by michael-ciniawsky** [comment]
Async Chunk => `chunkFilename` e.g `import(/* webpackChunkName: "foo" */ './file.css')` => `foo.css`

Sync Chunk (e.g an Entrypoint) => `filename` => `import styles from 'file.css'` (in `entry.js`) => `entry.css`

[Code Splitting](https://webpack.js.org/guides/code-splitting/)
[import()](https://webpack.js.org/api/module-methods/#import-)

**Comment by mahmoudZakaria90** [comment]
It's the Amazing Lazyload, whenever you find `chunk` you automatically use it when you want to import it dynamically.

**Comment by littlepoolshark** [comment]
Finally, I had make a good understood of the difference between them with this awesome answer!!
