### ISSUE TITLE
Feature request: Further splitting for each extracted CSS file

### ISSUE THREAD

**Issue by kevinzang** [webpack-contrib/mini-css-extract-plugin#361]
See sample repo here: https://github.com/kevinzang/mini-css-extract-plugin-split-by-chunk.

I've included details in the README. Here's a summarized version:

- I want to further split each extracted CSS file into the part that's for above the fold content and the part that's not.
- I tried to do this with optimization.splitChunks.cacheGroups, but I couldn't get it to work because it doesn't allow the same module to be in multiple cacheGroups at the same time. If two independent apps, loaded on separate pages, require the same component's CSS, I want that component's CSS to be in both apps, but cacheGroups doesn't allow that.
- Is this use-case something that MiniCSSExtractPlugin can support? If not, do you have any suggestions how to achieve the goal?
- I came up with a solution by forking MiniCSSExtractPlugin and adding a `splitChunks` option to split the `renderedModules` into groups, but I'd still like to open this issue in hopes of having a more standardized approach.

Thanks!

**Comment by evilebottnawi** [comment]
@kevinzang thanks for issue, interesting idea, maybe we can solve this on `webpack` side (adding new option to `splitChunks`)?

**Comment by kevinzang** [comment]
Sure! I've opened corresponding Webpack feature request here to get their opinion: https://github.com/webpack/webpack/issues/8909.

**Comment by kevinzang** [comment]
I believe my problem is solved with

```
chunks: chunk => chunk.name === `${app}-app`
```

which limits each app's cacheGroup to only that app.
