### ISSUE TITLE
Same link added twice

### ISSUE THREAD

**Issue by tenjojeremy** [webpack-contrib/mini-css-extract-plugin#364]
`mini-css-extract-plugin` injects `<link href="/css/main.bundle.css" rel="stylesheet" />` to the html on buildtime.

When I load `preload-webpack-plugin` after `mini-css-extract-plugin`, `preload-webpack-plugin` injects `<link as="style" href="/css/main.bundle.css" rel="preload">` to the head as expected, but now I am left with 2 calls to the same file.

is there a way to remove  `<link href="/css/main.bundle.css" rel="stylesheet" />` injected by `mini-css-extract-plugin`?

**Comment by evilebottnawi** [comment]
Please open issue in `preload-webpack-plugin`
