### ISSUE TITLE
Question: Is there any way to only extract the css files from initial chunk?

### ISSUE THREAD

**Issue by lsycxyj** [webpack-contrib/mini-css-extract-plugin#369]
I don't think the browser needs to make extra an request to fetch the css file of its own async js chunk which it has been loaded. So I want to disable. 
It should be something like the "fallback" option of `extract-text-webpack-plugin` and its behavior. However, I'm not able to find an equivalent way with `mini-css-extract-plugin` and webpack 4.

For example, let's say we have several pages will be loaded on demand:
```javascript
// routes.js inside intial-chunk.js
import './initial-chunk.css';
const routes: [
  {
    module: () => import('pageA')
  }
];

// pageA.js
import './pageA.css';
export default {
  // something that pageA should do
};

// pageB.js
import './pageB.css';
export default {
  // something that pageB should do
};
```
And the output files should be like this:
```
vendor.js
initial-chunk.js
initial-chunk.css
pageA.js
pageB.js
// Note that there isn't a "pageA.css" or "pageB.css" file. These css files are inside their own chunks and loaded by some other loaders, `style-loader` for example
```
How can I achieve this? Thank you very much.

**Comment by evilebottnawi** [comment]
Please use gitter or stackoverflow for questions, it is bug tracker, thanks!

You `style-loader/url` or `style-loader/usage`.

**Comment by jcreamer898** [comment]
Was there a resolution on this? We have a bunch of dynamic imports, and they're each getting their own CSS files and I'd like to bubble them up to their closest entrypoint, but haven't been able to find the right config to achieve it.

**Comment by lsycxyj** [comment]
@jcreamer898  I've never found the right config to solve this problem with `style-loader`. So I tried to create a pull request #432 to solve it.

**Comment by yanguoyu** [comment]
`    splitChunks: {
      cacheGroups: {
        vendors: {
          test: /[\\/]node_modules[\\/](react|react-dom|antd|lodash|echarts)[\\/]/,
          name: 'vendors',
          chunks: 'all',
        },
        appStyles: {
          test: (m) => m.constructor.name === 'CssModule',
          name: 'appStyles',
          chunks: 'all',
        },
        default: {
          minChunks: 2,
          priority: -20,
          reuseExistingChunk: true,
        },
      },
    },`
maybe you can use this, it work for me. only create two css. not 1.css, 2.css, 3.css....

**Comment by lsycxyj** [comment]
In this way, you will have to load a lot of other css rules when you don't need.

> ![image](https://user-images.githubusercontent.com/12881040/63904886-0069d200-ca45-11e9-8baf-cee4d98a087a.png)
> 
> maybe you can use this, it work for me. only create two css. not 1.css, 2.css, 3.css....

**Comment by yanguoyu** [comment]
is this not your want?

**Comment by lsycxyj** [comment]
No, I want to load css modules only when you need
