### ISSUE TITLE
0.6.0 reloading stylesheets is not working anymore

### ISSUE THREAD

**Issue by birkir** [webpack-contrib/mini-css-extract-plugin#376]
Hey, took me a while to figure out what was causing this.

I have the following stack 
 - next@8.0.3
 - @zeit/next-sass@1.0.1

The following config:
```js
const sass = require('@zeit/next-sass');

[sass, {
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: '[local]___[hash:base64:5]',
  },
}]
```

**The Problem**
The project is reporting in the chrome console (and this is normal and hasn't caused any issues before)
> Conflicting order between:
> * css ./node_modules/css-loader??ref--10-3!./node_modules/postcss-loader/src??ref--10-4!./node_modules/sass-loader/lib/loader.js??ref--10-5!./src/components/container/Container.scss
> * css ./node_modules/css-loader??ref--10-3!./node_modules/postcss-loader/src??ref--10-4!./node_modules/sass-loader/lib/loader.js??ref--10-5!./src/components/card/Card.scss

BUT

1. When changing route
2. Most of the components on the new page will be **unstyled** unless I hard-reload the page.

Looks like the styles are not injected into the head

**Solution**

When I downgraded to 0.5.0 I get the same flash of some unstyled components on route change and the following message from webpack:
> [HMR] Reloading stylesheets...

Following by a correct CSS render.

---

I will attempt to make a repro with vanilla webpack setup, but until then, this issue can serve as a placeholder.

**Comment by evilebottnawi** [comment]
Are you sure you are in right repo? Since 0.6.0` hmr was implemented, looks you have invalid configuration

**Comment by evilebottnawi** [comment]
Please create **minimum** reproducible test repo

**Comment by birkir** [comment]
Yes, I think the problem is, by supporting HMR of styles, issues like the "conflict" will cause styles not to render

**Comment by ScriptedAlchemy** [comment]
Yeah please create a repo so we can debug this. 

It's very hard to debug issues without an example of the problem :)

**Comment by birkir** [comment]
Repro: https://github.com/birkir/mcep-next-repro

**Comment by ScriptedAlchemy** [comment]
Awesome, I’ve got an event this evening but will dig into the problem this weekend

**Comment by ScriptedAlchemy** [comment]
Okay on my phone I quickly had a look, did HMR work previously via next? If so then there might be some conflict between how they HMR and how we do.

**Comment by evilebottnawi** [comment]
@birkir can you test again with `0.7.0` version?

**Comment by ScriptedAlchemy** [comment]
Thanks, For the ping! Will set a reminder to check this

**Comment by birkir** [comment]
Still the same issue. I traced it to this issue as well: https://github.com/sheerun/extracted-loader/issues/11

I am not sure which one is at fault or if it is a cause of multiple packages not working together.

**Comment by evilebottnawi** [comment]
Unfortunately, we cannot solve this problem on our side, `zeit` should migrate on hmr code of this plugin (maybe they already done this), other loader should implement own `hot` interface
