### ISSUE TITLE
normalize-url not working in IE11

### ISSUE THREAD

**Issue by BetterCallSky** [webpack-contrib/mini-css-extract-plugin#385]
This module depends on `normalize-url`, but it doesn't work for IE11 because it's not transpiled to ES5.  
For example https://github.com/sindresorhus/normalize-url/blob/master/index.js#L5 this line contains an arrow function.
I can see that there is a similar package but for es5 https://www.npmjs.com/package/normalize-url-es5.

**Comment by evilebottnawi** [comment]
Please use issue template, also we use old version `normalize-url` that support ES5 (https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/package.json#L44)

**Comment by evilebottnawi** [comment]
Oh, you are right need decrease version to `1.9.1` (https://github.com/sindresorhus/normalize-url/blob/v1.9.1/index.js)

**Comment by DimitrK** [comment]
same here

**Comment by maystrenkoYurii** [comment]
@evilebottnawi Having the same issue. When will it be resolved?

**Comment by ScriptedAlchemy** [comment]
Will open PR tonight. Ive got users on both my plugins opening issues about it. Sorry for delay folks!

**Comment by evilebottnawi** [comment]
Also we need fix check place

**Comment by jcarty** [comment]
@ScriptedAlchemy @evilebottnawi when will this go live?
