### ISSUE TITLE
Error: Can't resolve 'normalize-url' with HMR enabled

### ISSUE THREAD

**Issue by glen-84** [webpack-contrib/mini-css-extract-plugin#387]
* Operating System: Windows 10 Home
* Node Version: v10.15.3
* NPM Version: 6.4.1
* webpack Version: 4.30.0
* mini-css-extract-plugin Version: 0.6.0

### Expected Behavior

No error with HMR enabled.

### Actual Behavior

This error with HMR enabled:

```
ERROR in ../node_modules/mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js
Module not found: Error: Can't resolve 'normalize-url' in 'C:\Users\Glen\Desktop\css-hmr-issue\node_modules\mini-css-extract-plugin\dist\hmr'
 @ ../node_modules/mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js 18:19-43
 @ ./app/styles/main.scss
 @ ./main.ts
 @ ../node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-bootstrapper
```

Change `hmr: isHot` to `hmr: false` (twice), and the error will go away.

Could this be an issue with [aurelia-webpack-plugin](https://github.com/aurelia/webpack-plugin)? All I know is that it works with MCEP 0.5.0 + css-hot-loader.

### Code

https://github.com/glen-84/css-hmr-issue/blob/master/webpack.config.js

### How Do We Reproduce?

https://github.com/glen-84/css-hmr-issue (`npm i`, `npm start`)

(this is a copy of our project that I reduced from ~571 files to 31)

**Comment by evilebottnawi** [comment]
Looks like issue in `aurelia-webpack-plugin` we don't do something strange here

**Comment by glen-84** [comment]
But it's weird that it was working fine with MCEP 0.5.0 + css-hot-loader.

**Comment by glen-84** [comment]
@jods4 👋 Should I transfer this issue to `aurelia-webpack-plugin`?

**Comment by evilebottnawi** [comment]
@glen-84 need debug why it is happens, but i think will be great create issue in aurelia-webpack-plugin too

**Comment by glen-84** [comment]
https://github.com/aurelia/webpack-plugin/issues/160.

**Comment by glen-84** [comment]
According to one of the `aurelia-webpack-plugin` developers, it is unlikely to be the cause of the error. That issue has been closed.

**Comment by evilebottnawi** [comment]
Yes, anyway feel free to feedback here for other developers

**Comment by glen-84** [comment]
@evilebottnawi This should not be closed yet – it's still not resolved, and it's not yet clear which package is the cause.

**Comment by glen-84** [comment]
This seems to have just stopped happening in the repro project. 😕

I'm going to try it again in our real project, and see what happens.

**Comment by glen-84** [comment]
Please ignore my last comment – I accidentally used `npm run build` instead of `npm start`, which is where the issue is (still) happening. 🤦‍♂

**Comment by glen-84** [comment]
I can swear that I deleted `node_modules` *and* `package-lock.json` yesterday, and it didn't work. I just did it again now (along with `npm cache clear --force`), and now it's working! 🎉

(sorry about the false alarm)
