### ISSUE TITLE
background-position not getting minified correctly

### ISSUE THREAD

**Issue by emilmuller** [webpack-contrib/mini-css-extract-plugin#388]
* Operating System: Linux mint 18
* Node Version: 11.4.0
* NPM Version: 6.4.1
* webpack Version: 4.30.0
* mini-css-extract-plugin Version: 0.6.0

Not using OptimizeCSSAssetsPlugin in dev mode, one background-position is this:

`    background-position: right calc(0.375em + 0.25rem) center;`

When using the following configuration in prod:

```
    optimization: {
        minimizer: [new TerserJSPlugin({}), new OptimizeCSSAssetsPlugin({})],
    }
```

background-position now becomes:

`    background-position: 100% calc(.375em + .25rem);`

Which is not correct. Mind you I am doing transpilation of sass to css. The background-position is the position of the validation icon in a text input in Bootstrap.

Kind regards, Emil

**Comment by evilebottnawi** [comment]
No related to this plugin, problem in cssnano

**Comment by emilmuller** [comment]
@evilebottnawi Thanks! Sorry, I didn't know it was related to a dependency! Seems the issue has already been reported: https://github.com/cssnano/cssnano/issues/712
