### ISSUE TITLE
Add the ability to specifiy minimum chunk size.

### ISSUE THREAD

**Issue by maclockard** [webpack-contrib/mini-css-extract-plugin#389]
* Operating System: MacOS
* Node Version: 8.11.1
* NPM Version: yarn 1.12.4
* webpack Version: 4.29.6
* mini-css-extract-plugin Version: 0.5.0

### Feature Proposal

Add an option to specify the minimum chunk size before mini-css-extract-plugin creates an additional CSS chunk. This would work very similarly to [`splitChunks.minSize`](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunksminsize) and could potentially use the value from that by default.

### Feature Use Case

Currently if an async chunk has CSS not in the parent chunk, mini-css-extract-plugin
 unconditionally makes a separate CSS chunk, regardless of how small that chunk is. For example right now I'm getting a separate CSS chunk with a single class selector with a total size of 400 bytes. A chunk size this small isn't worth the round trip due to network latency, putting just the CSS into the parent chunk's CSS would eliminate this cost.

**Comment by evilebottnawi** [comment]
You can solve this using `splitChunks` please provide minimum reproducible test repo and I will show how to do it

**Comment by maclockard** [comment]
shouldn't this just be a part of the documentation then?

**Comment by evilebottnawi** [comment]
Sorry for delay, yep, we should documented this

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/mini-css-extract-plugin/issues/234
