### ISSUE TITLE
moduleFilename option has no effect

### ISSUE THREAD

**Issue by MDSilviu** [webpack-contrib/mini-css-extract-plugin#398]
I'm trying to use the moduleFilename option to output the extracted css in a different directory but it has no effect.

* Operating System: Windows 10
* Node Version: 8.15.0
* NPM Version: 6.4.1
* webpack Version: 4.32.0
* mini-css-extract-plugin Version: 0.6.0

### Expected Behavior

Change the name of the outputted file

### Actual Behavior

Nothing changes, the default filename option is used

### Code

https://gist.github.com/MDSilviu/166a066360e9013b77226cae9f42babf

**Comment by evilebottnawi** [comment]
It is not published right now

**Comment by mauricesnip** [comment]
@evilebottnawi I'd love to see this feature being published. Any ETA on this?
