### ISSUE TITLE
 webpack4打包不能提取css为单独的文件（mini-css-extract-plugin）

### ISSUE THREAD

**Issue by gottayan** [webpack-contrib/mini-css-extract-plugin#405]
https://segmentfault.com/q/1010000015853260/a-1020000015853588

**Comment by gottayan** [comment]
结合style-loader可以 但是less-loader不可以

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
