### ISSUE TITLE
use splitChunks to extract global css

### ISSUE THREAD

**Issue by ckrad** [webpack-contrib/mini-css-extract-plugin#410]
i want get a style.css as global css by using splitChunks and mini-css-extract-plugin. but it wii also product a useless style.js. how can i remove the style.js
<img width="377" alt="屏幕快照 2019-06-15 上午6 54 24" src="https://user-images.githubusercontent.com/4309830/59542819-6f518780-8f3a-11e9-9e0c-6566e35fec30.png">

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
