### ISSUE TITLE
Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by elios264** [webpack-contrib/mini-css-extract-plugin#421]
* Operating System: Mac
* Node Version: 12.4
* NPM Version: 6.10
* webpack Version: 4.35.2
* mini-css-extract-plugin Version: 0.7.0

### Expected Behavior

Compile without problems
### Actual Behavior
Magic error that disappears when recompiling:

### Code

```

  Webpack compilation failed (client)

    ERROR in ./theme/theme.client.less
    Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ../node_modules/less-loader/dist/cjs.js):


    Cannot read property 'substring' of undefined
          in undefined (line undefined, column undefined)
        at /Users/elios264/Desktop/alto/promo-panel/node_modules/webpack/lib/NormalModule.js:302:20
        at /Users/elios264/Desktop/alto/promo-panel/node_modules/loader-runner/lib/LoaderRunner.js:367:11
        at /Users/elios264/Desktop/alto/promo-panel/node_modules/loader-runner/lib/LoaderRunner.js:233:18
        at context.callback (/Users/elios264/Desktop/alto/promo-panel/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
     @ ./client/appLoader.js 10:0-33
     @ multi webpack-hot-middleware/client?dynamicPublicPath=true react-hot-loader/patch ./client/appLoader
```

```
    ERROR in ./src/theme/theme.client.less (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--5-3!./src/theme/theme.client.less)
    Module build failed (from ../node_modules/less-loader/dist/cjs.js):
    
    
    Cannot read property 'substring' of undefined
          in undefined (line undefined, column undefined)
```

### How Do We Reproduce?

* Clone: https://github.com/elios264/minicss-bug
* npm install
* npm start

it happens half the times, probably a race condition because, if I save any file (so webpack recompiles), it will recompile fine, in a larger project I have happens everytime and I have to force webpack to recompile

**Comment by evilebottnawi** [comment]
Please update wepback and MCEP to latest version, looks you use old global webpack version

**Comment by evilebottnawi** [comment]
oh, looks it is less error

**Comment by elios264** [comment]
hey @evilebottnawi I'm not using a global webpack version, and MCEP is on it's latest version, also the error disappears when recompiling, could you help me isolate if the error is in mini-css or less-loader or less package?

**Comment by evilebottnawi** [comment]
need, investigate, try to use less-loader without mini-css-extract-plugin and if error disappears it is bug in less-loader

**Comment by elios264** [comment]
Hey @evilebottnawi effectively I removed mini-css and replaced it for style-loader and the error still happens (just less often), so I'm guessing is a bug in less-loader, thanks for the help, I'm going to open a bug in that project.

**Comment by jasonverber** [comment]
It appears to be a bug in less, not less-loader. See https://github.com/less/less.js/pull/3360
