### ISSUE TITLE
filename option not working

### ISSUE THREAD

**Issue by jairusd** [webpack-contrib/mini-css-extract-plugin#423]
* Operating System: windows 10
* Node Version: 12.2.0
* NPM Version: 6.9.0
* webpack Version: ^4.35.3
* mini-css-extract-plugin Version: ^0.7.0

### Expected Behavior

webpack should output the the entry point css:
dist/client/css/main.css

### Actual Behavior

on development mode, the output is:
dist/client/css/client.css

on production mode, the output is:
dist/client/css/0.css

### How Do We Reproduce?

Here's  my repo, it isn't much yet so I hope it isn't a pain to look at.
https://github.com/jairusd/ssr

**Comment by evilebottnawi** [comment]
Please use https://github.com/webpack-contrib/mini-css-extract-plugin#module-filename-option

**Comment by jairusd** [comment]
Thank you for your response. Do I use moduleFilename alone or should i use it to adjust filename option? I still couldn't achieve my goal. my goal is to get a static filename for entry point css so in my html, i know how to point to the external css src.

i dont understand what chunkFilename is for

```javascript
 new MiniCssExtractPlugin({
    filename: 'css/main.css',
    chunkFilename: '[id].css',
    moduleFilename: ({name}) => `css/${name}.css`
  }),
```

**Comment by evilebottnawi** [comment]
hm, `chunkFilename` for chunks, so you get `[0]` because you use `chunkFilename: [id].css`, just change `[id]` on `[name]`
