### ISSUE TITLE
Support multiple instances of MiniCssExtractPlugin

### ISSUE THREAD

**Issue by davidli16** [webpack-contrib/mini-css-extract-plugin#429]
- Operating System: All
- Node Version: All
- NPM Version: All
- webpack Version: 4
- mini-css-extract-plugin Version: 0.8.0

### Feature Proposal

ExtractTextWebpackPlugin supports multiple instances so that it can be included as part of the pipeline for multiple loaders. I believe that we have a scenario outlined below that is not handled by any of the core Webpack features or by MiniCssExtractPlugin.

We have a large codebase that includes hundreds of SCSS files written prior to our adoption of CSS modules. Thus, we have two distinct loaders, one for our legacy SCSS and basic CSS files with `modules` disabled and another without.

### Feature Use Case

This is a pared down version of our CSS loader configuration using ExtractTextPlugin
```
{
    // CSS modules
    test: /\.scss$/,
    exclude: [/_\w+\.scss/],
    use: ExtractTextPlugin.extract({
        use: [
            {
                loader: 'css-loader',
                options: {
                    // Enable CSS modules by default on all files
                    modules: true,
                    importLoaders: 1,
                    minimize: isProd,
                },
            },
            {
                loader: 'sass-loader',
                {
                    includePaths: [
                        path.join(options.root, 'src'),
                    ],
                },
            },
        ],
        fallback: 'style-loader',
    }),
},
{
    // Legacy CSS files (no CSS modules)
    test: /_\w+\.scss$|\w+\.css$/,
    use: ExtractTextPlugin.extract({
        use: [
            {
                loader: 'css-loader',
                options: {
                    // Note that `modules: false` is set here by default
                    importLoaders: 1,
                    minimize: isProd,
                },
            },
            {
                loader: 'sass-loader',
                options: {
                    includePaths: [
                        path.join(options.root, 'src'),
                    ],
                },
            },
        ],
        fallback: 'style-loader',
    }),
},
```

**Comment by evilebottnawi** [comment]
Use `splitChunk` in you case, each css modules file should have `test.modules.css` name so you can extract them easy

**Comment by davidli16** [comment]
Maybe I am misunderstanding how MiniCssExtractPlugin works. but it's not clear to me how `splitChunk` would work for this use case. I actually want to generate a single output file containing CSS processed by both loader configurations. Furthermore, I actually need to configure the loaders in different ways.

I sincerely want to apologize for rehashing what appears to be the same topic, but I legitimately believe this may be a different use case.

Here is an even more extreme pared down version example of something I tried to do:

```
{
    // CSS modules
    test: /\.css$/,
    exclude: [/_\w+\.css/],
    use: [
        MiniCssExtractPlugin.loader,
        {
            loader: 'css-loader',
            options: {
                // Enable CSS modules by default on all files
                modules: true,
            },
        },
    ],
},
{
    // Legacy CSS files (no CSS modules)
    test: /_\w+\.css$/,
    use: [
        MiniCssExtractPlugin.loader,
        {
            loader: 'css-loader',
            // Note that `options.modules: false` is set here by default
        },
    ],
},
```

**Comment by evilebottnawi** [comment]
As i said above use `splitChunk` with `test: /_\w+\.css/`

**Comment by evilebottnawi** [comment]
Please try to do this and if you still can't do this put here example (reproducible test repo with small readme) and i will correct configuration, no need put issue without trying to set it up

**Comment by davidli16** [comment]
Thanks for the prompt response. I will give it another try!

**Comment by davidli16** [comment]
Created an updated simplified repro, and it appears MiniCssExtractPlugin does properly extract from multiple rules if included as a loader in each of them (no splitChunk needed). It was definitely only working on the last ruleset last time I tried this out.

Thanks for the help! Seems to be working now!

**Comment by mmarekbb** [comment]
As mentioned above, using splitChunks is not the solution. ExtractTextPlugin supported multiple instances, which let us in combination with the multi-loader to pass _all_ styles that _all_ match the same test rule (basically just ending with .scss) to pass through two instances of it - say a light and dark theme. The dark theme then had some scss variables prepended before compilation.

1. I don't think this can be achieved with splitChunks. splitChunks decides which file goes to which bundle, but we need all files to go to two bundles instead.
2. Creating multiple entry points is not great, because we would need to import all individual scss files in light.scss and dark.scss before adding them to the entries, at which point we can just run the sass compiler manually without webpack.

The proposed solution would be for the MiniCssExtractPlugin to expose a loader that's specific to its instance. A sample config would be something like this -

```javascript
import multiLoader from 'multi-loader';
import combineLoaders from 'webpack-combine-loaders';

const extractLightTheme = new MiniCssExtractPlugin({ filename: 'light.css' });
const extractDarkTheme = new MiniCssExtractPlugin({ filename: 'dark.css' });

{
  test: /\.scss$/, // thanks to multiLoader this goes through both extract plugins
  use: multiLoader(
    combineLoaders([
      extractLightTheme.loader,
      'css-loader',
      { loader: 'sass-loader', options: { additionalData: '@import "light-theme-vars.scss"' } }
    ]),
    combineLoaders([
      extractDarkTheme.loader,
      'css-loader',
      { loader: 'sass-loader', options: { additionalData: '@import "dark-theme-vars.scss"' } }
    ]),
  )
}
```

@alexander-akait I don't think this is possible to achieve with the current version of MiniCssExtractPlugin, because it only exposes a single global loader. We consider opening a pull request for adding this functionality if it's wanted here.
