### ISSUE TITLE
Export locals as ES2015 Modules

### ISSUE THREAD

**Issue by calebeby** [webpack-contrib/mini-css-extract-plugin#43]
Hi,

Right now when I use this plugin my bundle ends up having a bunch of these:

```js
function(e, t, n) {
    e.exports = {
      home: "home_4zXj",
      headerContents: "headerContents_fgfT",
      info: "info_SpI-",
      dcmp: "dcmp_7LbX",
      cmp: "cmp_FYP2",
      pre: "pre_1JF_",
      off: "off_2kzf",
      adminPanel: "adminPanel_VjUM",
      navigationDrawerButtonContainer: "navigationDrawerButtonContainer_Gjyw",
      navigationDrawerButton: "navigationDrawerButton_11km"
    };
  }
```

Since this does not use es6 exports and instead uses `module.exports`, webpack is unable to inline these. If this plugin did use es6 exports, my bundle size would be much smaller because they could be inlined:

Code coming out of this plugin:
```js
export const home = "home_4zXj";
export const headerContents = "headerContents_fgfT";
export const info = "info_SpI-";
// etc.

export default {
  home: "home_4zXj",
  headerContents: "headerContents_fgfT",
  info: "info_SpI-",
  dcmp: "dcmp_7LbX",
  cmp: "cmp_FYP2",
  pre: "pre_1JF_",
  off: "off_2kzf",
  adminPanel: "adminPanel_VjUM",
  navigationDrawerButtonContainer: "navigationDrawerButtonContainer_Gjyw",
  navigationDrawerButton: "navigationDrawerButton_11km"
};
```

Then, after Webpack processes it, the css module would be inlined, and unused properties would be removed.

I made a fork of `extract-text-webpack-plugin` that does this: https://github.com/webpack-contrib/extract-text-webpack-plugin/compare/master...calebeby:master

Would you accept a similar PR to this repo?

Thanks!!!

**Comment by evilebottnawi** [comment]
@calebeby PR welcome

**Comment by Kovensky** [comment]
I believe @michael-ciniawsky was working on something like this for the new css-loader.

**Comment by evilebottnawi** [comment]
close in favor https://github.com/webpack-contrib/mini-css-extract-plugin/issues/424
