### ISSUE TITLE
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):

### ISSUE THREAD

**Issue by Bhushankumar-pawar** [webpack-contrib/mini-css-extract-plugin#436]
We are migrating CSS-loader from v0.28.11 to v3.1.0
We have 2 projects:

Project A- No component dependency on any other project - (containing some components)
Project B - We are importing Project A as node modules
We are able to run and build project A successfully. But when we try to run Project B we getting a dependency error for CSS files from Project A.(we exported Project A as node module)

**Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):**

Operating System: macOS Mojave
Node Version: v10.16.0
NPM Version: 6.9.0
webpack Version: 4.29.5
mini-css-extract-plugin Version: 0.8.0

### Expected Behavior

We should be able to run and create a build using CSS-loader with version v3.1.0 and mini-css-extract-plugin.

### Actual Behavior
```

ERROR in ./src/help/css/about.qcss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './Project/A/src/typography/css/qx-typography.css' in 'D:\Projects\B\src\help\css'
    at factory.create (D:\Projects\B\node_modules\webpack\lib\Compilation.js:823:10)
    at factory (D:\Projects\B\node_modules\webpack\lib\NormalModuleFactory.js:397:22)
    at resolver (D:\Projects\B\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (D:\Projects\B\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at D:\Projects\B\node_modules\neo-async\async.js:2830:7
    at D:\Projects\B\node_modules\neo-async\async.js:6877:13
    at normalResolver.resolve (D:\Projects\B\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (D:\Projects\B\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
    at hook.callAsync (D:\Projects\rx\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\Projects\B\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
```

### Code

```js
// webpack.config.js
module: {
    rules: [
     {
      test: /\.css$/,
      use: [{
        loader: miniCssExtractPlugin.loader,
        options: {
          sourceMap: true,
          publicPath: "../"
        }
      }, {
        loader: "css-loader"
      }, {
        loader: "postcss-loader"
      }],
      exclude: [/examples/, /docs/]
    }, {
      test: /\.qcss$/,
      use: [{
        loader: miniCssExtractPlugin.loader,
        options: {
          sourceMap: true,
          publicPath: "../"
        }
      }, {
        loader: "css-loader",
        options: {
          modules: {
            localIdentName: "[name]_[local]_[hash:base64:5]"
          },
          importLoaders: 1,
          
        }
      }, {
        loader: "postcss-loader"
      }]
    }
  ]
}
```

### How Do We Reproduce?

Project A- No component dependency on any other project - (containing some components with css files and css modules )

Project B - We are importing Project A as node modules and using css files of nodeModule of ProjectA.
Link Project A with Project B using npm-link. 

We are able to run and build project A successfully. But when we try to run Project B we getting a dependancy error for css files from Project A.

Same works fine with if we do css-loader of Project A to v3.1.0 and Project B to v1.0.0
But we get a compile-time error if we change both projects css-loader version to 3.1.0

**Comment by evilebottnawi** [comment]
Answered, please read error
```
ModuleNotFoundError: Module not found: Error: Can't resolve './Project/A/src/typography/css/qx-typography.css' in 'D:\Projects\B\src\help\css'
```

Webpack can't resolve file, please fix path to `qx-typography.css`, also without reproducible test repo we can't help

**Comment by bring2dip** [comment]
If your  import css files using postcss-import and use absolute import like 'help/about.css'. This plugin actually will search the relative path './help/about.css'. So adding ~ will help.  '~help/about.css'.
 
[Stackoverflow Answer](https://stackoverflow.com/questions/46523825/error-with-import-when-using-extract-text-webpack-plugin)
