### ISSUE TITLE
Loaders run twice with MiniCssExtractPlugin enabled

### ISSUE THREAD

**Issue by shahkashani** [webpack-contrib/mini-css-extract-plugin#439]
- Operating System: Mac OS 10.14.6
- Node Version: 10.16.0
- NPM Version: 6.9.0 (nice)
- webpack Version: 4.35.3
- mini-css-extract-plugin Version: 0.8.0

### Expected Behavior

Loaders should only run once?

### Actual Behavior

This might not be an actual issue, since it appears to use cached chunks, but if you enable the [speed-measure-webpack-plugin](https://github.com/stephencookdev/speed-measure-webpack-plugin) on a project that is using this plugin, you'll note that loaders run twice:

![Screen Shot 2019-08-13 at 3 54 25 PM](https://user-images.githubusercontent.com/1395893/62972937-222b4e00-bde3-11e9-82eb-fea328def9a8.png)

Is this expected? In order to speed up builds, is there any way around it? 

### Code

```js
const SpeedMeasurePlugin = require('speed-measure-webpack-plugin');
const smp = new SpeedMeasurePlugin();

module.exports = smp.wrap({
  module: {
    rules: [
      {
        test: /\.s?css$/,
        use: [MiniCssExtractPlugin.loader],
      },
    ],
  },

  plugins: [
    new MiniCssExtractPlugin({
      filename: `[name]-[contenthash:8].css`,
    }),
  ] 
});
```

### How Do We Reproduce?

Just apply the [speed-measure-webpack-plugin](https://github.com/stephencookdev/speed-measure-webpack-plugin) to any project using the MiniCssExtractPlugin.

**Comment by shahkashani** [comment]
Briefly mentioned here: https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/45

So perhaps this is just a reporting issue in the speed-measure plugin?

**Comment by evilebottnawi** [comment]
Yes, please open issue in speed-measure plugin
