### ISSUE TITLE
Error: Didn't get a result from child compiler

### ISSUE THREAD

**Issue by divyam5-30** [webpack-contrib/mini-css-extract-plugin#446]
const withSass = require("@zeit/next-sass");
const nextConfig = require("./config");

const withCSS = require('@zeit/next-css')

module.exports = withCSS(withSass(
    {
    cssModules: true,
    cssLoaderOptions: {
      importLoaders: 1,
      localIdentName: "[local]___[hash:base64:5]",
    },
    webpack (config, options) {
      config.module.rules.push({
            test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
            use: {
                loader: 'url-loader',
                options: {
                    limit: 100000
                }
            }
        });

    return {...nextConfig(config)};
  }
}));

this is my next.config.js file 
Im using Nextjs - 9.0.2
webpack 4.32.1

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
