### ISSUE TITLE
Webpack 5 Support Plan? 

### ISSUE THREAD

**Issue by septs** [webpack-contrib/mini-css-extract-plugin#447]
The webpack 5 changelog:

> The compat layer for webpack 3 plugins has been removed. It had already been deprecated for webpack 4.

see https://github.com/webpack/changelog-v5/blob/master/README.md#tapable-upgrade

> Modules now have to define which source types they support via Module.getSourceTypes(). Depending on that, different plugins call source() with these types. i. e. for source type javascript the JavascriptModulesPlugin embeds the source code into the bundle. Source type webassembly will make the WebAssemblyModulesPlugin emit a wasm file. Custom source types are also supported, i. e. the mini-css-extract-plugin will probably use the source type stylesheet to embed the source code into a css file.

see https://github.com/webpack/changelog-v5/blob/master/README.md#module-source-types

**Comment by evilebottnawi** [comment]
Yes, webpack only on alpha release, compatibility will be done for beta or rc

**Comment by septs** [comment]
@evilebottnawi webpack 5 release, first beta version.

**Comment by evilebottnawi** [comment]
We already support webpack@5, just deprecation warnings :smile:
