### ISSUE TITLE
moduleFilename option doesn't get called when processing over chunks

### ISSUE THREAD

**Issue by fabis94** [webpack-contrib/mini-css-extract-plugin#449]
- Operating System: doesn't matter
- Node Version: doesn't matter
- NPM Version: doesn't matter
- webpack Version: 4.28.1
- mini-css-extract-plugin Version: latest (0.8.0)

### Expected Behavior

moduleFilename option should apply to each module being processed

### Actual Behavior

moduleFilename option doesn't get called when processing over chunks

### Code

![image](https://user-images.githubusercontent.com/938316/65165799-241ea780-da48-11e9-8fd8-d0d44df8e228.png)

I've highlighted the problematic lines of code with red. Why doesn't the function get called always? If you want a separate function for handling chunk file names, that's fine, but at least provide some dynamic way of resolving them instead of just always falling back to the 'chunkFilename' string.

### How Do We Reproduce?

See above

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by fabis94** [comment]
Are you kidding? I literally posted a screenshot from the mini-css-extract-plugin codebase, you don't have to create any sort of special conditions to reproduce this. moduleFilename doesn't apply to chunks, create any setup with chunks and you'll see this.

**Comment by evilebottnawi** [comment]
No, you can send a PR with fix and tests or create minimum reproducible test repo for other developers who have time to fix it, sometimes developers cannot find the time to immediately fix the error, and after some time it becomes difficult to reproduce some errors, therefore we ask create reproducible test repo

**Comment by kylerberry** [comment]
@fabis94 I had this same issue and it was resolved by upgrading my mini-css-extract-plugin to `0.7.0`

**Comment by wangxianfa** [comment]
I had the same issue with mini-css-extract-plugin@0.9.0

**Comment by evilebottnawi** [comment]
`moduleFilename` was removed in favor `filename`/`chunkFilename`, if you will have problems with new version (1.0.0, release will be today), please open a new issue
