### ISSUE TITLE
MiniCssExtractPlugin.Loader doesn't parse IE 5-9 compatible css declaration

### ISSUE THREAD

**Issue by FurkanKozen** [webpack-contrib/mini-css-extract-plugin#450]
- Operating System: Windows 10 Pro v1803
- Node Version: 10.16.3
- NPM Version: 6.9.0 
- webpack Version: 4.41.0
- mini-css-extract-plugin Version: 0.8.0

### Expected Behavior

When I import a 3rd party library css into a js file, webpack compilation should be completed regardless of whether the file is valid or invalid. Even in jquery-ui (v1.12.1) some IE8-compatible css declarations causes build to be failed. I expect an option property for MiniCssExtractPlugin.loader to validate css or not (true/false). If this issue is related to less-loader or something else, please let me know.

### Actual Behavior
Webpack compilation fails.

### Code
```css
/* quotation from jquery-ui 1.12.1 */
filter: Alpha(Opacity=.3); /* support: IE8
```
```js
// webpack Error Output in PowerShell
ERROR in ./src/lib/Jquery/jquery-ui.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):


        opacity: .003;
        filter: Alpha(Opacity=.3); /* support: IE8 */
                     ^
Could not parse alpha
      in D:\...\Jquery\jquery-ui.css (line 1307, column 23)
    at runLoaders (D:\...\node_modules\webpack\lib\NormalModule.js:316:20)
    at D:\...\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\...\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\...\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
 @ ./MasterPages/Main.js 21:0-41
 @ ./Default.js

.
.
.

    ERROR in ./src/lib/Jquery/jquery-ui.css (./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/less-loader/dist/cjs.js!./src/lib/Jquery/jquery-ui.css)
    Module build failed (from ./node_modules/less-loader/dist/cjs.js):


        opacity: .003;
        filter: Alpha(Opacity=.3); /* support: IE8 */
                         ^
    Could not parse alpha
          in D:\...\Jquery\jquery-ui.css (line 1307, column 23)
```

### How Do We Reproduce?

Import jquery-ui css into a js file and add less-loader, css-loader and MiniCssExtractPlugin.loader

**Comment by evilebottnawi** [comment]
Problem in less-loader: `Could not parse alpha`, less doesn't support this notation
