### ISSUE TITLE
plugin still use `__webpack_public_path__` when options.publiPath is set

### ISSUE THREAD

**Issue by ItoshikiNozomu** [webpack-contrib/mini-css-extract-plugin#456]
* Operating System: Windows 10
* Node Version: 10.13.0
* Npm Version: 6.10.1
* webpack version: 0.8.0

## Expected Behavior
first i define a runtime variable `__webpack_public_path__`  using `webpack.DefinePlugin` .
```
      new webpack.DefinePlugin({
        __webpack_public_path__: `window.__publicPath`
        // __webpack_public_path__:`some_static_path`
      }),
```

then i set the `MiniCssExtractPlugin.loader` options 
```
              options: {
                publicPath: 'my_static_assets_path'
              }
```
 expect the plugin to take the `options.publicPath` peroperty

## Actual Behavior
run`npm run build` 

and got the following errors
```
./src/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ReferenceError: window is not defined
    at Object.<anonymous>
```
seems that the loader take the `__webpack_public_path__` variable

## How Do We Reproduce?
Minimal repro case: https://github.com/ItoshikiNozomu/mini-css-extract-plugin-testcase

**Comment by evilebottnawi** [comment]
Please use issue template and create minimum reproducible test repo

**Comment by ItoshikiNozomu** [comment]
@evilebottnawi issue description comment updated

**Comment by evilebottnawi** [comment]
@ItoshikiNozomu why you use `DefinePlugin`? You can't use `window.__publicPath` because all urls calculated (resolved) when you extract styles and can't be changed in runtime

**Comment by ItoshikiNozomu** [comment]
i have some code like 
```
const ImgBox=()=><img src={require('./assets/some_img.png')}/>
```
and i want the require base tobe determined at runtime. Accordingto the [doc](https://webpack.js.org/guides/public-path/#on-the-fly), i define the `__webpack_public_path__ ` variable. It works fine if i dont apply the css extract plugin.

i understand a extracted css file is something static,but i think the `url(some_url)` statement in css shoul take the `options.publicPath` but not `__webpack_public_path__ `  to caculate the final url string

**Comment by evilebottnawi** [comment]
> i understand a extracted css file is something static,but i think the url(some_url) statement in css shoul take the options.publicPath but not __webpack_public_path__ to caculate the final url string

Yes, you can't use `__webpack_public_path__` in `DefinePlugin` plugin as i written above. Use plugin option.
