### ISSUE TITLE
Webpack 4: mini-css-extract-plugin + file-loader not loading assets

### ISSUE THREAD

**Issue by quinn** [webpack-contrib/mini-css-extract-plugin#457]
- Operating System:
OS X
- Node Version:
12
- NPM Version:
Yarn
- webpack Version:
4
- mini-css-extract-plugin Version:
0.8.0
### Expected Behavior
fonts and images are extracted and included in the manifest. 

### Actual Behavior

random nonsense happens:

```
{
  "index.css": "http://localhost/73fb447517000dc3ba5d-index.css",
  "index.js": "http://localhost/index-47fc96d3da8b1d79dfaa.js",
  "fonts/main.scss": "http://localhost/fonts/ed58e0dd7a5aa4d020f58ebb2a008d80-Font.ttf",
  "images/main.scss": "http://localhost/images/516bc9ab49b39b551ca05a8c2f436529-Font.svg"
}
```

### Code

```js
 {
  test: /\.css$/,
  use: [
    MiniCssExtractPlugin.loader,
    {
      loader:  require.resolve('css-loader'),
      options: {
        sourceMap: true,
      },
    },
    {
      loader:  require.resolve('postcss-loader'),
      options: {
        ident:   'postcss',
        plugins: () => [
          postcssPresetEnv(),
        ],
      },
    },
  ],
},
{
  test: /\.(woff|eot|ttf)$/,
  use: [{
    loader: require.resolve('url-loader'),
    options: {
      limit: 25000,
      name: 'fonts/[hash]-[name].[ext]'
    }
  }]
}

```

plugin:
```
      new MiniCssExtractPlugin({
        filename:      '[hash]-[name].css',
        chunkFilename: '[hash]-[id].css',
      }),
```

### How Do We Reproduce?
 Should be possible with the above loaders. Same as this SO question: https://stackoverflow.com/questions/53918083/webpack-4-mini-css-extract-plugin-file-loader-not-loading-assets

**Comment by yoriiis** [comment]
Hello @evilebottnawi, I reproduce the same issue with the version `0.4.3`.

The problem appears to have been introduced with this commit: https://github.com/webpack-contrib/mini-css-extract-plugin/commit/18c066e.

**Comment by stulzer** [comment]
I can also confirm, when upgrading from `0.4.0` to `0.4.5`. A `manifest.json` file that usually have 100+ lines, now have ~17 lines.

**Comment by evilebottnawi** [comment]
It should be fixed on the plugin, don't know what we can do here, sorry
