### ISSUE TITLE
SourceMap could not be removed with `devtool: false` and `mode: production`

### ISSUE THREAD

**Issue by JounQin** [webpack-contrib/mini-css-extract-plugin#46]
https://github.com/JounQin/Rubick/blob/assets/static/app.029a1ec171ca216e26b5.css#L3

sourceMappingURL is not removed.

webpack Configuration: https://github.com/JounQin/Rubick/blob/master/build/base.ts

Reproduction Step: `yarn build` and view `app.*.css` file in `dist/static` folder.

**Comment by evilebottnawi** [comment]
@JounQin Thanks for issue :+1:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by JounQin** [comment]
@sokra It should be related to https://github.com/webpack/webpack/issues/6803 and after remove SourceMapDevtoolPlugin it works as expected now, so I'm going to close this issue here.
