### ISSUE TITLE
can i extract css based on  non-entry?

### ISSUE THREAD

**Issue by Lx15** [webpack-contrib/mini-css-extract-plugin#461]
i have many entries, and every entry has several chunks that are generated by  dynamic modules .
i use webpack's splitChunk, so the dynamic modules is splited into several  files. then if i use mini-css-extract-plugin now, it will extract css by every  splited file . i don't want that  and i dont want to extract css based on  entry too .  I want to extract css based on  non-entry ( dynamic module).  Is there a workable method?  thank U .

**Comment by evilebottnawi** [comment]
You can do it using `splitChunk`, please use stackoverflow or gitter for questions, it is bug tracker, thanks
