### ISSUE TITLE
Resource Files

### ISSUE THREAD

**Issue by th3fallen** [webpack-contrib/mini-css-extract-plugin#47]
with sass-loader i was able to do something like this to add a resource file to all my scss files

is that possible with this as well? and im just missing it?
```
{
            loader: 'sass-loader',
            options: {
              data: '@import "styles/resources";',
              includePaths: [path.join(cwd, 'app')],
            },
          },```

**Comment by evilebottnawi** [comment]
@th3fallen why? Can you describe use case?

**Comment by th3fallen** [comment]
Wow! super fast response!

Yes, we have a resources.scss sheet that contains an import to our variables file and mixins so they're available globally in scss sheet without having to import them manually all over the place.

**Comment by evilebottnawi** [comment]
@th3fallen why import `sass/scss` variables in `css` extracted file? It is does make sense

**Comment by th3fallen** [comment]
wait am i being totally stupid, do you use this in conjunction with sass-loader? (the goal is to have those variables available to them while they're scss sheets so when they're compiled they dont cry about not having mixins are variables

**Comment by evilebottnawi** [comment]
@th3fallen i think your question related to `sass-loader`, not `mini-css-extract-plugin`, because this plugin just extract `css` from you bundle (chunks).

**Comment by th3fallen** [comment]
looks that way, it sounds like i could just use this with sass-loader and all would be perfect since sass-loader compiles it and adds what i need and this would extract. thanks i'll give er a shot

**Comment by michael-ciniawsky** [comment]
For SASS it is better to `@import` them via `sass-loader` for each file since variables will be compiled 'away', while on the other hand for things like CSS Custom Properties, Autoprefixing and Minifaction `postcss` support could be added to handle these tasks on the 'asset level' (the 'whole'  extracted CSS file).
