### ISSUE TITLE
Unable to extract scss into separate style file

### ISSUE THREAD

**Issue by mmr0370** [webpack-contrib/mini-css-extract-plugin#470]
![截屏2019-12-0213 37 40](https://user-images.githubusercontent.com/22002244/69933243-002c1780-1509-11ea-8e21-1675797c3a83.png)

![截屏2019-12-0213 39 15](https://user-images.githubusercontent.com/22002244/69933291-2ce02f00-1509-11ea-99df-a1b3d5ebeb1b.png)

The css file can be packaged normally, the sass file build will not report an error, but it is not extracted

**Comment by mmr0370** [comment]
other people has  a similar problem.

**Comment by mmr0370** [comment]
链接地址： https://segmentfault.com/q/1010000019532945

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
