### ISSUE TITLE
CssModule context property is null in v0.8.1

### ISSUE THREAD

**Issue by i-like-robots** [webpack-contrib/mini-css-extract-plugin#473]
- Operating System: Mac OS 10.14
- Node Version: 10.14
- NPM Version: 6.4.1
- webpack Version: 4.41.2
- mini-css-extract-plugin Version: 0.8.1

### Expected Behavior

We have implemented [code splitting](https://webpack.js.org/plugins/split-chunks-plugin/) in our apps which uses each module's `context` property to decide whether they should be extracted into separate chunk. We have used this configuration for some time but has broken when using v0.8.1 of this package.

### Actual Behavior

The `context` property for instances of `CssModule` is `null` instead of a string as we expect so our Webpack compilation fails. e.g.:

```js
(module) => module.context.includes('foo') // TypeError: Cannot read property 'includes' of null
```

### Code

Here is an example configuration for enabling code splitting using `module.context`:

```js
// webpack.config.js
module.exports = {
  optimization: {
    splitChunks: {
      cacheGroups: {
        vendors: {
          test (module) {
            return module.context.includes('dom-loaded')
          }
        }
      }
    }
  }
}
```

### How Do We Reproduce?

Try adding the code splitting configuration shown above to a project using this plugin and a CSS entry point (or try any configuration which expects `module.context` to be a string).

EDIT: test repo here https://github.com/i-like-robots/broken-css-extract-plugin

**Comment by evilebottnawi** [comment]
We don't touch this code in `8.1.0`, please create reproducible test repo

**Comment by i-like-robots** [comment]
Here you go: https://github.com/i-like-robots/broken-css-extract-plugin

If you run `npx webpack` or `npm run build` it should fail.

Install v0.8.0 of this plugin and run the Webpack build again and it should pass.

Hope that helps!

**Comment by evilebottnawi** [comment]
@i-like-robots what about `return module.context && module.context.includes('dom-loaded')`?

**Comment by i-like-robots** [comment]
We can do that but I'm concerned that a public part of this module's interface has changed unexpectedly.

**Comment by i-like-robots** [comment]
Thank you @evilebottnawi - much appreciated 🙇
