### ISSUE TITLE
Conflicting order. Following module has been added

### ISSUE THREAD

**Issue by wjq1994** [webpack-contrib/mini-css-extract-plugin#479]
WARNING in chunk 14 [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--9-2!./node_modules/sass-loader/lib/loader.js??ref--9-3!./node_modules/vue-loader/lib??vue-loader-options!./src/views/purchasing_manage/components/purchaseServiceAuditDialog.vue?vue&type=style&index=0&lang=scss&
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--9-2!./node_modules/sass-loader/lib/loader.js??ref--9-3!./node_modules/vue-loader/lib??vue-loader-options!./src/components/ExportZip.vue?vue&type=style&index=0&lang=scss&
   - couldn't fulfill desired order of chunk group(s)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

It is expected, you can disable order the warning using the `ignoreOrder` option or you can fix order

**Comment by vocoWone** [comment]
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
  
  new MiniCssExtractPlugin({
      ignoreOrder: true
    }),
