### ISSUE TITLE
WARNING in asset size limit: The following asset(s) exceed the recommended size limit

### ISSUE THREAD

**Issue by wjq1994** [webpack-contrib/mini-css-extract-plugin#484]
how do i resolve it ???
question description:
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  static/css/app.ec1f6756c0b6d1e0cc96.css (262 KiB)
  static/js/app.3b3179fd8babfe587e50.js (1.37 MiB)
  static/kindeditor/kindeditor-all.js (314 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.63 MiB)
      static/css/app.ec1f6756c0b6d1e0cc96.css
      static/js/app.3b3179fd8babfe587e50.js

**Comment by evilebottnawi** [comment]
https://webpack.js.org/configuration/performance/

`performance: { hints: false }`
