### ISSUE TITLE
mini-css-extract-plugin + sass-loader + splitChunks

### ISSUE THREAD

**Issue by Loykos** [webpack-contrib/mini-css-extract-plugin#49]
I've the follow example configuration to use mini-css-extract-plugin with Webpack 4:

```
entry: {
   a: ['./js/a.js', './scss/a.scss'],
   b: ['./js/b.js', './scss/b.scss']
},
module: {
    rules: [
       [...],
       {
        test: /\.(css|sass|scss)$/,
        use: [
            MiniCssExtractPlugin.loader,
            {
                loader: 'css-loader',
                options: {
                    importLoaders: 2,
                    sourceMap: true
                }
            },
            {
                loader: 'postcss-loader',
                options: {
                    plugins: () => [
                        require('autoprefixer')
                    ],
                    sourceMap: true
                }
            },
            {
                loader: 'sass-loader',
                options: {
                    sourceMap: true
                }
            }
        ]
},
optimization: {
    splitChunks: {
        cacheGroups: {
            js: {
                test: /\.js$/,
                name: "commons",
                chunks: "all",
                minChunks: 7,
            },
            css: {
                test: /\.(css|sass|scss)$/,
                name: "commons",
                chunks: "all",
                minChunks: 2,
            }
        }
    }
},
plugins: [
    new MiniCssExtractPlugin({
        filename: "dist/[name].css",
    }),
]
```
And the following sass files:
```

// a.scss
@import 'global.scss';
@import 'vendor.css';
[...] 

// b.scss
@import 'global.scss';
@import 'vendor.css';
[...]
```

When I run webpack `vendor.css` is inserted in in `commons.css` bundle while `global.scss` not.

In general every import of `.css` file get processed by splitChunks option (only if extension `.css` is specified in the name) while `.scss` files not.

I have a project with multiple sass entry point and many @import of sass component and I'd like to create a common bundle with shared sass modules.

The chunk of js files works properly.

**Comment by okamiconcept** [comment]
I have the same problem, the scss imports are not chunked (or bad), it seems it's a missing feature from sass-loader which export all scss in one module.

See: https://github.com/webpack-contrib/sass-loader/issues/455

The only solution for the moment is to have only one entry for scss, it results on one big css.

**Comment by Loykos** [comment]
Just to clarify, with the above configuration i get:
`a.css`
`b.css`
`common.css` => common css only and not common scss import. 

@okamiconcept  do you mean I have to create manually a `common.scss` as entry file to import?

**Comment by okamiconcept** [comment]
@Loykos Yes If you want to create a common css, you have to build it yourself, i hope another person have a better solution to that! :)

**Comment by Kovensky** [comment]
This is a problem with, I believe, all compile-to-css languages unless you take particular care to not use `@import` or use it in a way that can will not be converted by the compiler itself.

Basically, they work like a C preprocessor `#include`, and will just inline the source code of the `@import`. To webpack, you're really only importing a _single_ `.css` file, and not a `.css` file that imports other `.css` files.

**Comment by ZSkycat** [comment]
I think of a solution.
Change the entry file scss to js file.
This can also allows implement wildcardsto to load the scss module.

**Comment by ZSkycat** [comment]
@KytoSai 
you need
```js
            {
                test: /\.scss$/,
                use: [
                    'style-loader', // or MiniCssExtractPlugin.loader
                    { loader: 'css-loader', options: { sourceMap: true, importLoaders: 1 } },
                    { loader: 'sass-loader', options: { sourceMap: true } },
                ],
            },
```

then you can use like
```js
// style/index.js
import '../base.scss';
import './layout.scss';
import './nav-component.scss';

import './component/v-base-nav.scss';
import './component/v-nav-dropdown.scss';
import './component/v-realtime-nav.scss';

```

**Comment by Loykos** [comment]
Yes, I moved style import inside js entry files and it's working

**Comment by michael-ciniawsky** [comment]
**`webpack.config.js`**
```js
entry: {
   a: ['./js/a.js',  => './scss/a.scss' <=],
   b: ['./js/b.js',  => './scss/b.scss' <=]
},
```

CSS Entrypoints are **not** officially supported (yet), it might look like it works but that's not the case and additionally one will get an useless JS File per CSS entrypoint containing only the `webpack` runtime. **Don't use CSS Files as entrypoints**, import into the JS entry intead
