### ISSUE TITLE
Modules when loaded from loaders do not emit properly despite compiling correctly 

### ISSUE THREAD

**Issue by alexa-griffin** [webpack-contrib/mini-css-extract-plugin#491]
- Operating System: windows
- Node Version: 12.6.0
- NPM Version: 6.12.1
- webpack Version: ^4.41.5
- mini-css-extract-plugin Version: ^0.9.0

### Expected Behavior
A module when loaded from a (custom) loader is emitted properly.

### Actual Behavior
A module when loaded from a (custom) loader is not extracted, despite it going through the compilation process and even appearing to have been processed `MiniCssExtractPlugin`. This can be shown by the fact that the compiled source (found in the callback of `this.loadModule`) is `// extracted by mini-css-extract-plugin`.

### Code
https://gist.github.com/alexa-griffin/fd78b66a195187a95c2e466da205941f

### How Do We Reproduce?
the above is a minimal reproducible example, some of the directories will need to be manually created because gists are weird.

**Comment by evilebottnawi** [comment]
`loadModule` just load module, it is not affected on extracting

**Comment by alexa-griffin** [comment]
Then why does it say it is extracted?

**Comment by evilebottnawi** [comment]
You can use `exclude` to avoid that behavior for files

**Comment by alexa-griffin** [comment]
Ok after a lot of testing I believe I have come to a result, I will post my findings here in case anyone else has to deal with this.

I believe this stemmed from my misunderstanding of the `loadModule` behavior. I thought it was a programmatic equivalent to adding an import statement, this is not the case as it is not actually emitted by webpack. I thought it was because I was using url-loader for another asset which does emit the asset even if it is loaded from loadModule.
