### ISSUE TITLE
Document relationship to css-loader

### ISSUE THREAD

**Issue by scottdotjs** [webpack-contrib/mini-css-extract-plugin#494]
Documentation Is:

- [X] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The documentation says "It's recommended to combine mini-css-extract-plugin with the css-loader" without any further explanation. Why is it recommended, what happens if you do, what happens if you don't?

### Your Proposal for Changes

Please add an explanation. Thank you!

Note: I opened an identical issue for [the same comment in the style-loader docs](https://github.com/webpack-contrib/style-loader/issues/477).

**Comment by evilebottnawi** [comment]
Do not duplicate issue

**Comment by scottdotjs** [comment]
> Do not duplicate issue (We will update this in both repositories when we understand that you do not understand.)

No need for the snarky comment. By the way, I filed this issue six months ago and it was ignored until I found and reported the same issue on the other plugin.

**Comment by evilebottnawi** [comment]
No snarky comment, I just don't understand what you don't understand, I can't improve docs while I don't understand what do you don't understand :smile:
