### ISSUE TITLE
Output logging is too verbose and can't be disabled or minimized

### ISSUE THREAD

**Issue by kaiyoma** [webpack-contrib/mini-css-extract-plugin#496]
After enabling this plugin on our project, our webpack build now spits out hundreds of pages of `mini-css-extract-plugin` output, none of which is particularly helpful or informative. I see thousands of lines like this:

```
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/postcss-loader/src/index.js??ref--11-2!node_modules/less-loader/dist/cjs.js??ref--11-3!webpack/color-sharing-loader.js!<redacted>:
    Entrypoint mini-css-extract-plugin = *
       2 modules
```

Is there a way to disable or minimize all these messages? Our CI logs are now full of them and all this extra noise makes legitimate errors harder to find.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

You can setup output using that option https://webpack.js.org/configuration/stats/

**Comment by kaiyoma** [comment]
> You can setup output using that option https://webpack.js.org/configuration/stats/

@evilebottnawi Which option specifically controls the output of this plugin? There are a dozens of options available under `stats`.

**Comment by lensbart** [comment]
@evilebottnawi I’ll gladly help solving this issue by referring to another identical issue.

The same topic has been discussed [here](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/168) with many 👍’s and +1’s, so there certainly is a strong demand for it to be fixed.

Using `stats` to enable/disable logs or to set the desirable log level prevents useful output from other plugins to be shown. It would be very handy for many people if the logs from this plugin (which seem to be less useful) would not be displayed under the default `info` level, but rather as `verbose`. After all, they seem to be quite verbose. 😉

**Comment by kaiyoma** [comment]
Ah, thanks for linking the other issue. Seems like lots of people agree that the output logging is too verbose and quite annoying. There should be a fix in this plugin that doesn't involve changing the `stats` configuration.

**Comment by evilebottnawi** [comment]
@lensbart stats output creates webpack + webpack-cli, we are not doing anything special, this is not even an error, you can setup the output using the `stats` option in your configuration. Tell me how you want to fix it? We display all the data necessary for analysis, you can set `stats: "errors-warnings"`

**Comment by kaiyoma** [comment]
> @lensbart stats output creates webpack + webpack-cli, we are not doing anything special, this is not even an error, you can setup the output using the `stats` option in your configuration. Tell me how you want to fix it? We display all the data necessary for analysis, you can set `stats: "errors-warnings"` to avoid extra output in develement env

This is not a good solution. I tried this out locally and I noticed that some very helpful webpack output is now being suppressed (specifically, the display of assets, file sizes, and chunks).

The correct solution, which someone else mentioned already (in the other issue), is that the messages from this plugin should be logged at the `verbose` level. That way, they're suppressed during normal operation, but users can view them if they really want to. I'm pretty sure that will solve the issue here and make everyone happy.

**Comment by evilebottnawi** [comment]
> The correct solution, which someone else mentioned already (in the other issue), is that the messages from this plugin should be logged at the verbose level.

What? We don't use logger, what should be suppressed? Please read the documentation about the `stats` option.

**Comment by kaiyoma** [comment]
Sorry, I think "debug" is the right word here. You can log all these messages at the "debug" level. If users want to see them, they can turn on debug logs:

https://webpack.js.org/configuration/stats/#statsloggingdebug

**Comment by evilebottnawi** [comment]
We can't disable that on plugin side, you can setup that in your configuration, for webpack@5 we simplify output, but it is really not related to that plugin
