### ISSUE TITLE
css-loader don't work.

### ISSUE THREAD

**Issue by wangyajundev** [webpack-contrib/mini-css-extract-plugin#497]
{
        test: /\.css$/,
        use: ['style-loader', {
                loader: MiniCssExtractPlugin.loader,
        },
        {
                loader: 'css-loader',
                options: {
                        esModule: true,
                        modules: {
                                localIdentName: '[name]__[local]__[hash:base64:5]',
                        },
                },
        },
        'postcss-loader']
},

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
