### ISSUE TITLE
mini-css-extract-plugin is used with react-loadable

### ISSUE THREAD

**Issue by purple-force** [webpack-contrib/mini-css-extract-plugin#503]
- Operating System: macOS Catalina 10.15.2
- Node Version: 10.16.0
- NPM Version: 6.9.0
- webpack Version: 4.17.2
- mini-css-extract-plugin Version: 0.9.0

### Expected Behavior

A simple spa demo, there are two pages, `page1.jsx` and `page2.jsx`, which individually import `page1.css` and `page2.css`.In `index.jsx`, I import them dynamically with `react-loadable`. when running `npm run build`, the expeced is `index.js`,`index.css`,`1.js`,`2.js` . I want all css in one file.

### Actual Behavior

The result is `index.js`,`1.js`,`2.js`,`1.css`,`2.css`.Where is `index.css`? 

### How Do We Reproduce?

https://github.com/purple-force/mini-css-issue
This is a mini demo.

run `npm run build` and outputs will be in `build`.

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file

**Comment by purple-force** [comment]
I did it that way, but got `index.js`,`styles.css`,`0.js`,`2.js`,`3.js`,and `0.js`seems unnecessary due to its content. When setting `cacheGroups.[name].name` to `index`,which is to get `index.css`，but what I get is `0.js`,`1.js`,`2.js` and `index.css` without `index.js`.
