### ISSUE TITLE
Can support specify the position when  insert CSS asynchronously?

### ISSUE THREAD

**Issue by kingller** [webpack-contrib/mini-css-extract-plugin#504]
- Operating System:
- Node Version: 12.13.1
- NPM Version: 6.12.1
- webpack Version: 4.41.2
- mini-css-extract-plugin Version: 0.8.0

### Feature Proposal

When  insert CSS asynchronously, insert it before a style link, because the position of the css file will affect its weight.

```
mainTemplate.hooks.requireEnsure.tap(
   ...
   'var head = document.getElementsByTagName("head")[0];',
   'head.appendChild(linkTag);',
   ...
)
```

Can I pass in a string to replace the words bellow?
```
'head.appendChild(linkTag);'
```

### Feature Use Case

I extracted a theme color file to switch theme colors. Then I want to insert CSS asynchronously before it (when dynamic import used) to keep the styles of theme color file override the inserted file.

**Comment by kingller** [comment]
Now I use [css-async-process-webpack-plugin](https://www.npmjs.com/package/css-async-process-webpack-plugin) to solve this issue.

**Comment by evilebottnawi** [comment]
It was solved in the near future, https://github.com/webpack-contrib/mini-css-extract-plugin/pull/495

**Comment by kingller** [comment]
OK. Thanks very much.
