### ISSUE TITLE
Cannot read property 'pop' of undefined

### ISSUE THREAD

**Issue by purple-force** [webpack-contrib/mini-css-extract-plugin#505]
- Operating System: macOS Catalina 10.15.2

- Node Version: 10.16.0

- NPM Version: 6.9.0

- webpack Version: 4.17.2

- mini-css-extract-plugin Version: 0.9.0

### Expected Behavior

A spa demo with two pages [https://github.com/purple-force/mini-css-issue](https://github.com/purple-force/mini-css-issue).

`page1.jsx` and `page2.jsx` is loaded by `react-loadable` in `index.jsx`, where `react-loadable`'s loading is set to `() => <Loading />`. `loading.jsx` import `loading.css`. It will not throw above error if `import './loading.css'` is removed. 

The error is from https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L498, where `bestMatch` is `undefined`.

what expected is `js`, `css` files   in build directory after run build with name set by `output.filename` and `new MiniCssExtractPlugin`'s option `filename`. and `css` contents are in one file.But if chunkFilename is set，filename will be invalid.

### Actual Behavior

`Cannot read property 'pop' of undefined`
![image](https://user-images.githubusercontent.com/16146970/75225277-4087f280-57e5-11ea-8519-fa246b0fa012.png)

**Comment by fivethreeo** [comment]
#487 Got the same problem, any idea to the cause?

**Comment by khades** [comment]
more likely this #341

**Comment by alexandrukis** [comment]
This happens because your entry point shares its name with the cache group

```js
entry: {
    index: './src/index.jsx',
},
...
cacheGroups: {
    index: {
        name: 'index',
        test: (m, c, entry = 'index') => {
            return m.constructor.name === 'CssModule' && recursiveIssuer(m) === entry;
         },
         chunks: 'all',
         enforce: true,
    }
}
```

Try changing your `cacheGroups` definition to this, see if it works:

```js
cacheGroups: {
    indexStyles: {
        name: 'index',
        test: (m, c, entry = 'index') => {
            return m.constructor.name === 'CssModule' && recursiveIssuer(m) === entry;
         },
         chunks: 'all',
         enforce: true,
    }
}
```

**Comment by evilebottnawi** [comment]
Answer above, it was error in webpack@5 by default, we can't fix it on our side, sorry
