### ISSUE TITLE
this._identifier.split error, can't read property

### ISSUE THREAD

**Issue by gartz** [webpack-contrib/mini-css-extract-plugin#506]
- Operating System: MacOS
- Node Version: v12.13.1
- NPM Version: 6.12.1
- webpack Version: 4.41.6
- mini-css-extract-plugin Version: 0.9.0

### Expected Behavior
To not throw errors when `this._identifier` is not a string (might be `null`)

### Actual Behavior

```js
    const resource = this._identifier.split('!').pop();
                                      ^

TypeError: Cannot read property 'split' of undefined
```

### Code

it's huge, but basically when enabled SSR rendering for the CSS loaders

### How Do We Reproduce?

Add loaders: 
* css-loader with option onlyLocals: true
* url-loader with option emitFile: false
* file-loader with option emitFile: false

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by gartz** [comment]
I'm using the react-create-app, if I enable the `onlyLocals` from `css-loader` it gives that error mentioned, when I disable it, seems to work, but I'm not sure yet if the builded file is valid.

**Comment by evilebottnawi** [comment]
@gartz Maybe you can provide steps to reproduce it using CRA?

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/mini-css-extract-plugin/issues/205
