### ISSUE TITLE
Readme: deps badge is broken

### ISSUE THREAD

**Issue by snitin315** [webpack-contrib/mini-css-extract-plugin#507]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- mini-css-extract-plugin Version:

### Expected Behavior / Situation

The badge should not be broken.

![Screenshot from 2020-03-08 08-44-01](https://user-images.githubusercontent.com/46647141/76155953-57014880-6119-11ea-8fe6-a66c426ab62c.png)

![Screenshot from 2020-03-08 08-47-07](https://user-images.githubusercontent.com/46647141/76155958-6c767280-6119-11ea-8ec4-64d347c3b75c.png)

### Actual Behavior / Situation

Broken Badge in README.

### Addition Information

I will work on this issue.

**Comment by evilebottnawi** [comment]
Make sure that the provider gives you access to the web resource, everything works well
