### ISSUE TITLE
{opacity: 50%}  is transpiled to {opacity: 1%} 

### ISSUE THREAD

**Issue by Cody2333** [webpack-contrib/mini-css-extract-plugin#513]
- Operating System: MacOS 10.15.2
- Node Version: v12.16.1
- NPM Version:v6.13.4
- webpack Version:v4.41.5
- mini-css-extract-plugin Version:v0.9.0

### Expected Behavior
correctly build css files.

### Actual Behavior
```
.App {
  opacity: 50%;
}
```
is transpiled into 
```
.App {
  opacity: 1%;
}
```

### How Do We Reproduce?

using `npx create-react-app` to init a project
edit App.css 
```
.App {
  opacity: 50%;
}
```
runing `yarn build`

build/static/css/xxx.css got `{opacity:1%}`

here is an example repo:
https://github.com/Cody2333/mini-css-extract-plugin-issues

**Comment by evilebottnawi** [comment]
We don't touch your CSS, it is bug css minimizer

**Comment by evilebottnawi** [comment]
Bug in `optimize-css-assets-webpack-plugin`, maybe in cssnano
