### ISSUE TITLE
Help with order of operations inside MiniCSSExtractPlugin.apply 

### ISSUE THREAD

**Issue by elchicofrommo** [webpack-contrib/mini-css-extract-plugin#517]
Hey team, I'm looking to hack up the apply function to allow me to output all the dependent CSS/SCSS into a single file for each OrginalSource for the entry point. I'm pretty close to my solution but I'm stuck with the naming of the file. The problem as I see it is that when the fileNameTemplate function is called I don't actually have the the sources ready because the render function hasn't been called. My question is this, is there any reason this.renderContentAsset couldn't be called outside the render and assigned to a local scope variable that can be returned when render is called? I'm so new to Webpack I'm sure I'm missing something. I actually did what I just suggested and it seems to work, but I don't know enough about the lifecycle to know what potential issues come by doing it this way. Please see below for my example

 ```
         if (renderedModules.length > 0) {
            let renderedSources = this.renderContentAsset(
              compilation,
              chunk,
              renderedModules,
              compilation.runtimeTemplate.requestShortener
            )
            result.push({
              render: () =>
                renderedSources,
              filenameTemplate: ({ chunk: chunkData }) =>
                this.options.moduleFilename(chunkData),
              pathOptions: {
                chunk,
                contentHashType: MODULE_TYPE,
              },
              identifier: `${pluginName}.${chunk.id}`,
              hash: chunk.contentHash[MODULE_TYPE],
            });
```

**Comment by evilebottnawi** [comment]
Sorry for delay, 

>  I'm looking to hack up the apply function to allow me to output all the dependent CSS/SCSS into a single file for each OrginalSource for the entry point. 

It is not good idea

I want to close issue because it is questions (you can use stackoverflow for this), anyway I want to help, please provide real example what do you want achieve, I don't think you need own plugin for this
