### ISSUE TITLE
Don't work with css-modules

### ISSUE THREAD

**Issue by TotooriaHyperion** [webpack-contrib/mini-css-extract-plugin#519]
- Operating System: macOS Mojave 10.14.6 
- Node Version: 12.13.1
- NPM Version: 6.14.2
- webpack Version: 4.42.0
- mini-css-extract-plugin Version: 0.9.0

### Expected Behavior

Should work with css-module

### Actual Behavior

If any css file includes a css-module export, then the HMR breaks.
a.css
```
:local(.aaa) {
  background-color: pink; // hmr warns: do not know how to reload themselves, and style won't update
}
.aa {
  background-color: khaki; // hmr warns: do not know how to reload themselves, and style won't update
}
```
b.css
```
.bbb {
  background-color: skyblue; // this works, no warning, style updated.
}
```
Those style without css-module will work. scss file is the same behaviour with css.

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
        {
          test: /\.s?css$/,
          exclude: /node_modules/,
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
              options: {
                hmr: !isProd,
              },
            },
            {
              loader: "css-loader",
              options: {
                importLoaders: 2,
                modules: {
                  mode: "global",
                  localIdentName: isProd
                    ? "_[hash:base64]"
                    : "[path][name]__[local]",
                },
              },
            },
            {
              loader: "postcss-loader",
              options: {
                plugins: [
                  require("autoprefixer")(),
                  require("postcss-flexbugs-fixes")(),
                ],
              },
            },
            { loader: "sass-loader" },
          ],
        },
```

### How Do We Reproduce?

just add css-modules into the advanced example shown in readme.md.
Then those css/scss file with a :local() in it will fail to hot reload.
Those css/scss file without any :local() works fine.

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by TotooriaHyperion** [comment]
> Please create reproducible test repo

reproduce: https://github.com/TotooriaHyperion/mini-css-extract-plugin-bug

**Comment by TotooriaHyperion** [comment]
If style inside :local() block is empty, there would not be a css module and then hmr works.
But if there is a css-module actually exist, the hmr breaks:
![image](https://user-images.githubusercontent.com/16434801/77494308-648c3180-6e80-11ea-994a-e18ee3d20776.png)

**Comment by TotooriaHyperion** [comment]
Looks like we need a similar behavior like https://github.com/webpack-contrib/style-loader/pull/298

**Comment by evilebottnawi** [comment]
It is bug, it is feature, css-modules doesn't support HMR

**Comment by sethomas** [comment]
replacing the loader of `mini-css-extract-plugin` with `style-loader`, I am able to HMR css-modules without a page reload.

**Comment by alexander-akait** [comment]
Fixed
