### ISSUE TITLE
moduleFilename doesn't work when i using runtimeChunk

### ISSUE THREAD

**Issue by frhandlee** [webpack-contrib/mini-css-extract-plugin#523]
- Operating System: macos
- Node Version: 10.15.3
- NPM Version: 6.10.0
- webpack Version:4.42.1
- mini-css-extract-plugin Version: 0.9.0

### Expected Behavior
moduleFilename can work

### Actual Behavior
moduleFilename can't work when i open runtimeChunk

### Code

```js
    runtimeChunk: {
      name: 'common/js/mainfest'
    }
```

### How Do We Reproduce?

it's  will certainly appear  when  open runtimeChunk，and it's ok in 'extract-text-webpack-plugin'

**Comment by evilebottnawi** [comment]
runtimeChunk and moduleFilename is difference, please create reproducible test repo

**Comment by Jessidhia** [comment]
By using debug `console.error`s, I can confirm that the `moduleFilename` function doesn't get invoked at all: the `chunkFilename` function is invoked instead. However, making `chunkFilename` a function causes the error in https://github.com/webpack-contrib/mini-css-extract-plugin/issues/417 instead:

```
ERROR in chunk runtime [entry]
Cannot read property 'replace' of undefined

ERROR in chunk runtime [entry]
[name].[contenthash].js
Path variable [contenthash] not implemented in this context: [name].[contenthash].js
```

**Comment by wangxianfa** [comment]
> runtimeChunk and moduleFilename is difference, please create reproducible test repo

i had the same issue. when add runtimeChunk in webpack.optimization，moduleFilename cant work. remove runtimeChunk, moduleFilename work again.

**Comment by evilebottnawi** [comment]
`moduleFilename` was removed in favor `filename`/`chunkFilename`, if you will have problems with new version (1.0.0, release will be today), please open a new issue
