### ISSUE TITLE
Is "enable HMR only in development" really necessary?

### ISSUE THREAD

**Issue by HerrZatacke** [webpack-contrib/mini-css-extract-plugin#525]
Version of Webpack used: `4.42.0`
Version of the plugin: `mini-css-extract-plugin: 0.9.0`
the use-case that fails: **Unclear Documentation**

As stated in the documentation:
the `hmr` option should only be `true` in development mode.
https://github.com/webpack-contrib/mini-css-extract-plugin/blob/1ffc393a2e377fe0cc341cfcbc5396e07a8e4077/README.md#L348

This comment recommends to 
> just change the hmr property to true
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/392#issuecomment-519026323

I've tried it like this and:
✔️in mode `development` hmr is working  
✔️in mode `production` the generated sources are the same regardless of the `hmr` option

So, as I prefer just using the `mode` parameter, I _think_ it's not necessary to explicitly set environment variables via
`hmr: process.env.NODE_ENV === 'development'`

But *could* there be any side effects I did not consider, or would it make sense to 
- [ ] update the documentation with either an explanation why it is necessary to disable hmr on production 
- [ ] or update the example?

And if there are no side effects, would it make sense to enable the option per default?

**Comment by evilebottnawi** [comment]
Because it ads a lot of runtime code which is not needed in production mode, feel free to send a PR to docs if you want to improve it

**Comment by evilebottnawi** [comment]
We remove that option in next release and enable HMR by default when you have HotModuleReplacmentPlugin
