### ISSUE TITLE
Does not create a CSS file per JS file which contains CSS

### ISSUE THREAD

**Issue by noslouch** [webpack-contrib/mini-css-extract-plugin#527]
- Operating System: macOS 10.14.6
- Node Version: 12.16.0
- NPM Version: 6.13.4
- webpack Version: 4.43.0
- mini-css-extract-plugin Version: 0.9.0

### Expected Behavior

> It creates a CSS file per JS file which contains CSS

This doesn't seem to be the case. I would expect one CSS file for each JS file that imports CSS. Instead I'm seeing a single combined CSS file.

### Actual Behavior

It creates a _single_ CSS file containing all the CSS it encounters

### Code

```js
// webpack.config.js
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  plugins: [new MiniCssExtractPlugin()],
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [MiniCssExtractPlugin.loader, 'css-loader'],
      },
    ],
  },
};
```

```js
// src/index.js
import './a';
import './b';
```

```js
// src/a.js
import './a.css';
```

```js
// src/b.js
import './b.css';
```

```css
/* a.css */
body {
  background: green;
}
```

```css
/* b.css */
h1 {
  font-size: 100px;
}
```

### How Do We Reproduce?

Clone this repo and run `npx webpack` and check out the `dist` folder. I'd expect to see a CSS file for each JS module, but instead there's a single concatenated `main.css` file.

**Comment by evilebottnawi** [comment]
Duplicate, known issue, we will fix it in webpack@5

**Comment by ashishmahi** [comment]
Hey @alexander-akait  i'm using 
    "mini-css-extract-plugin": "^2.1.0",
    "webpack": "^5.44.0",

but still having one single css file instead of separate css file. 

//
app.js
import './foo.csss'
renders <HelloWorld>
//
-------------
HelloWorld.js
import "./bar.css"
//


new MiniCssExtractPlugin()
----------------//plugins
{
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: "css-loader",
            options: { sourceMap: dev },
          },
        ],
      },
  ---------------//rules
