### ISSUE TITLE
Is it normal to see assets output twice with this plugin?

### ISSUE THREAD

**Issue by coreyworrell** [webpack-contrib/mini-css-extract-plugin#532]
- Operating System: Alpine Linux (Docker)
- Node Version: 14.2.0
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- mini-css-extract-plugin Version: 0.9.0

### Expected Behavior

Normal compilation output of assets listed once

### Actual Behavior

Seeing assets listed twice. Not sure why the svgs and woff files (and .gitkeep) are listed again.

### Code

https://gist.github.com/coreyworrell/5df6544b654741072db83f2c58658b77

Thank you.

**Comment by evilebottnawi** [comment]
Bug on `OptimizeCssAssetsPlugin`, we recommend to use https://github.com/webpack-contrib/css-minimizer-webpack-plugin, it is official with cache and parallel, if it is not help - feel free to feedback and please create minimum reproducible test repo thanks
