### ISSUE TITLE
can‘t split  css  by chunk

### ISSUE THREAD

**Issue by yiqianglin** [webpack-contrib/mini-css-extract-plugin#54]
I want to split css by chunk，but all build into Entrypoint app，generate only one css(app.css). This is my config:
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
![image](https://user-images.githubusercontent.com/15794229/37866138-5a7c3442-2fc1-11e8-8d72-ef58574660b2.png)
![image](https://user-images.githubusercontent.com/15794229/37866143-73b3dabe-2fc1-11e8-9854-06b631f24eac.png)
![image](https://user-images.githubusercontent.com/15794229/37866147-7923c716-2fc1-11e8-986f-f744e0998236.png)

page:
![image](https://user-images.githubusercontent.com/15794229/37866182-f8334c70-2fc1-11e8-9067-1b24163fdb4c.png)
and has differance css in differance chunk, but it generate only one  css:
![image](https://user-images.githubusercontent.com/15794229/37866196-28a8a1e8-2fc2-11e8-9acc-b27f01abb18b.png)

this is my code:
https://github.com/yiqianglin/webpack4Demo

**Comment by bebraw** [comment]
You could expand on my work at #57. Essentially you have to define a function to write the CSS file through webpack's API. The rest should be there.

**Comment by sokra** [comment]
Remove the `style-loader` and `vue-style-loader`

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/54#issuecomment-377189128
