### ISSUE TITLE
Bump `webpack-sources` to support `webpack@5`

### ISSUE THREAD

**Issue by vjpr** [webpack-contrib/mini-css-extract-plugin#542]
In a recent commit support for `webpack@5` was added.

https://github.com/webpack-contrib/mini-css-extract-plugin/commit/903a56ea3fa08e173cd548d23089d0cee25bafea

I think `webpack-sources` might need updating to from `1.4` to `2.0.0-beta.8`.

- Operating System: macOS
- Node Version: 14
- NPM Version: 6.14.4 (using pnpm@5)
- webpack Version: 5.0.0-beta.18
- mini-css-extract-plugin Version: 0.9.0

**Comment by evilebottnawi** [comment]
No, it can't be upgraded right now, also we have compatibility between `1` and `2` to support webpack@4 and webpack@5, it will be bumped after drop webpack@4, we can't do it right now, sorry

**Comment by michenly** [comment]
@alexander-akait Hi I would like to revisit this since it had been 1 year.
if not, would adding resolution for `webpack-sources@2.3.0` in a webpack-5 consuming project be a ok solution? Do you foresee any problem with that approach?

**Comment by alexander-akait** [comment]
@michenly we will do major release in near future and drop `webpack-sources`, now we use `compiler.webpack` there webpack keeps itself export

**Comment by alexander-akait** [comment]
We reduce a lot of our deps in many loaders and plugins and will do it in future more

**Comment by michenly** [comment]
Thank you for the reply. I'll keep an eye out on the release. Also happy to try out beta branch and help test it when there is one.

**Comment by alexander-akait** [comment]
There won't be much change, only drop webpack v4 and old Node.js version, so it will be stable :smile:
