### ISSUE TITLE
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):

### ISSUE THREAD

**Issue by iceycc** [webpack-contrib/mini-css-extract-plugin#543]
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: Package exports for 'xxxxxx/node_modules/kleur' do not define a valid './colors' target

**Comment by gengshaojing** [comment]
What is your Node.js version?

Anything between >= 13.0 and < 13.7 had an earlier version of exports map support that has since been removed and deprecated.

**Comment by jadamec** [comment]
How did you fix this issue @iceycc , please?
