### ISSUE TITLE
ERROR in Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by ShimshonMarketing66** [webpack-contrib/mini-css-extract-plugin#563]
since I updated to angular 10 

![Screenshot_1](https://user-images.githubusercontent.com/32569701/89733570-f7f48680-da5e-11ea-80b2-56ebc04a70e8.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
