### ISSUE TITLE
add url information in MiniCssExtractPlugin.loader  output

### ISSUE THREAD

**Issue by tarnishablec** [webpack-contrib/mini-css-extract-plugin#565]
- Operating System: windows 10
- Node Version: 12.14.1
- NPM Version: 6.13.4
- webpack Version: 4.44.1
- mini-css-extract-plugin Version: 0.9.0

### Feature Proposal
MiniCssExtractPlugin generate a `<link>`  element with `href` in html template

Can MiniCssExtractPlugin.loader output that href url just like `file-loader` did

so next loader can deal with that url

```ts
import info from "./index.css"
//  get some url info
```

### Feature Use Case

I need url to inject external stylesheet to `shadowdom` by adding `<link>` element inside `shadowroot`

**Comment by evilebottnawi** [comment]
Out of scope of mini-css-extract-plugin

**Comment by evilebottnawi** [comment]
You need to do it manually on application code side, we just extract CSS

**Comment by tarnishablec** [comment]
> You need to do it manually on application code side, we just extract CSS, also you can inject styles in shadow root without link

Technically it is right, but inject large size raw css content to `shadowroot` will cause performance problem when the component was used many times in document.

**Comment by evilebottnawi** [comment]
You can create own loader to do this, we just extract files, anyway can you provide simple example, I will think how it can be implemented from our side

**Comment by fregante** [comment]
For anyone who lands here, you don't need `mini-css-extract-plugin` for this if you just want to extract an existing file


```js
import url from "./index.css?loadAsUrl"
console.log(url)
```

in your config:

```js
  module: {
    rules: [
      // disable plugin on these URLs
      {
        test: /\.s?css$/,
        resourceQuery: { not: [/loadAsUrl/] },
        use: [MiniCssExtractPlugin.loader, "css-loader"],
      },

      // sass support if you need it
      {
        test: /\.scss$/,
        use: "sass-loader",
      },

      // generate a URL
      {
        test: /\.s?css$/,
        resourceQuery: /loadAsUrl/,
        type: "asset/resource",
        generator: {
          filename: "css/[name].css",
        },
      },
    ],
  },
```

I think if you want it to follow the dependencies you'll have to add `css-loader` to the last block as well.
