### ISSUE TITLE
mini-css-extract-plugin Callback was already called. 

### ISSUE THREAD

**Issue by LeachZhou** [webpack-contrib/mini-css-extract-plugin#577]
- Operating System: Mac Mojave 10.14.3
- Node Version: v10.13.0
- NPM Version: 6.4.1
- webpack Version: 4.8.3
- mini-css-extract-plugin Version: 0.10.0

### Expected Behavior

html-loader attrs: ['img:src', 'link:href'] can be used with MiniCssExtractPlugin.loader without error

### Actual Behavior

An error occurred when html-loader attrs: ['img:src', 'link:href']  and MiniCssExtractPlugin.loader were used together

### Code

```js
{
    test: /\.css$/i,
    exclude: /node_modules/,
    use: [
        MiniCssExtractPlugin.loader,
        'css-loader',
    ]
},
{
    test: /\.(htm|html)$/i,
    exclude: /node_modules/,
    use: [
        {
            loader: 'html-loader',
            options: {
                attrs: ['img:src', 'link:href']
            }
        },
    ]
},
```

```js
/Users/xxx/project/landing2/node_modules/webpack/node_modules/neo-async/async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/Users/xxx/project/landing2/node_modules/webpack/node_modules/neo-async/async.js:16:11)
    at /Users/xxx/project/landing2/node_modules/webpack/node_modules/neo-async/async.js:2818:7
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

### How Do We Reproduce?

```json
"css-loader": "^0.28.11",
"html-loader": "^0.5.5",
"mini-css-extract-plugin": "^0.10.0",
"style-loader": "^0.21.0",
"webpack": "^4.8.3",
```

According to the above configuration, an error will occur

**Comment by evilebottnawi** [comment]
@LeachZhou Update `webpack`, `css-loader` and `mini-css-extract-plugin` to latest version. If it is not help, please create reproducible test repo

**Comment by LeachZhou** [comment]
> @LeachZhou Update `webpack`, `css-loader` and `mini-css-extract-plugin` to latest version. If it is not help, please create reproducible test repo and I will reopen issue

@evilebottnawi I tried to update to the latest version, but I still got an error

```json
"css-loader": "^4.2.2",
"mini-css-extract-plugin": "^0.11.0",
"webpack": "^4.44.1",
```

```js
/Users/xxx/project/landing2/node_modules/_neo-async@2.6.2@neo-async/async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/Users/xxx/project/landing2/node_modules/_neo-async@2.6.2@neo-async/async.js:16:11)
    at /Users/xxx/project/landing2/node_modules/_neo-async@2.6.2@neo-async/async.js:2818:7
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by LeachZhou** [comment]
@evilebottnawi 
https://github.com/LeachZhou/loading2

### How to reproduce
1. command line 
```
npm i
``` 
```
npm run dev
```

**Comment by evilebottnawi** [comment]
Update dependencies please https://github.com/LeachZhou/loading2/blob/master/package.json

**Comment by LeachZhou** [comment]
> Update dependencies please https://github.com/LeachZhou/loading2/blob/master/package.json

already updated

**Comment by aexvir** [comment]
I'm having the same issue 🤔️

```json
"css-loader": "^4.2.2",
"mini-css-extract-plugin": "^0.11.0",
"style-loader": "^1.2.1",
"webpack": "^4.44.1",
```

**Comment by LeachZhou** [comment]
@evilebottnawi help us check this issue，please

**Comment by evilebottnawi** [comment]
@LeachZhou Please run `npm outdate` and update **all** deps, you provide broken example, a lot of dependencies are missed in `package.json`, same strange things in configuration like `UglifyJsPlugin` and `TerserPlugin`, you don't need two plugins for minify JS, `optimize-css-assets-webpack-plugin` replaced by https://github.com/webpack-contrib/css-minimizer-webpack-plugin, you don't need `webpack.HotModuleReplacementPlugin` because webpack-dev-server automatically inject this plugin.

Bug on `html-webpack-plugin` side

**SECURITY WARNING**: remove `accessKey` and `secretKey` from your repo, you leak access

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/mini-css-extract-plugin/issues/489
