### ISSUE TITLE
report error message

### ISSUE THREAD

**Issue by likezero** [webpack-contrib/mini-css-extract-plugin#589]
https://github.com/webpack-contrib/mini-css-extract-plugin/blob/bb09d757e5355b7015a3e463bc1030056c23e1c2/src/index.js#L360

when link load error, please record `event.message`

var err = new Error("Loading CSS chunk " + chunkId + " failed.\\n(" + request + "), msg:" + event.message);'

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment]
Why you need this
