### ISSUE TITLE
'[name].[hash].css' causes hash to be compiled as a variable

### ISSUE THREAD

**Issue by FabianHippmann** [webpack-contrib/mini-css-extract-plugin#596]
- Operating System:
Ubuntu 20.04
- Node Version:
v12.18.4
- NPM Version:
6.14.6
- webpack Version:
 5.0.0-rc.0

- mini-css-extract-plugin Version:
0.6.0

### Expected Behavior
Compiling a production build with webpack 5 should work as expected. This 

### Actual Behavior
When using webpack 5 to compile a bundle - the terser option in webpack 5 seems to mess up the `[name].[hash].css` option and creates produces a bundle like -> 

```js
/******/ 				var href = "" + ({}[chunkId]||chunkId) + "." + __webpack_require__.h ? __webpack_require__.h() : 33a77d7a305d7b86ce61 + ".css";
```
the "hash" gets bundled as a variable - instead of a string. 

### Code

```js
 new MiniCssExtractPlugin({
        filename: stable ? '[name].css' : '[name].[hash].css',
      }),
```

Output bundle.js
```js
/******/ 				var href = "" + ({}[chunkId]||chunkId) + "." + __webpack_require__.h ? __webpack_require__.h() : 33a77d7a305d7b86ce61 + ".css";
```

### How Do We Reproduce?

Webpack 5rc with a production build - be sure to disable the terser.

```js
 optimization: {
    minimize: false
  }
```

 - we tried it on 5 different machines - linux, mac, windows - mixed & it worked on some & on others failed. 

```js
 new MiniCssExtractPlugin({
        filename: stable ? '[name].css' : '[name].[hash].css',
      }),
```

**Comment by evilebottnawi** [comment]
Fixed in master, release will be today

**Comment by evilebottnawi** [comment]
Please try https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v0.11.3, feel free to feedback
