### ISSUE TITLE
[BUG] clientLogLevel "none" not working

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [webpack-contrib/mini-css-extract-plugin#598]
```
module.exports = {
    devServer: {
      clientLogLevel: 'silent', // this
      contentBase: path.resolve(__dirname, build),
      stats: 'errors-only',
      port: 3000,
      hot: true,
    },
}
```

![image](https://user-images.githubusercontent.com/69426460/95030899-6b132580-06bb-11eb-83e8-227df04d65be.png)

![image](https://user-images.githubusercontent.com/69426460/95030909-78c8ab00-06bb-11eb-9a06-ebe4a8f15347.png)

Solution:
-
you should use the special hmr logger and not use your own. hmr logger respects settings

**Comment by MaxmaxmaximusAWS** [comment]
temp solution for chrome:

![image](https://user-images.githubusercontent.com/69426460/95031453-c7c40f80-06be-11eb-86b0-07d1e5e4d2e2.png)

![image](https://user-images.githubusercontent.com/69426460/95031464-d3173b00-06be-11eb-952a-10194fb3dc62.png)

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
