### ISSUE TITLE
Consuming directly from GitHub isn't possible

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/mini-css-extract-plugin#61]
If you do `npm i webpack-contrib/mini-css-extract-plugin#2899ed376a290817b03f3280d4f552b9326224ba -D`, the package is missing source making it impossible to use the plugin.

One way to solve this would be to set up a [postinstall script](https://survivejs.com/maintenance/packaging/building/index.html#generating-a-build-on-postinstall).

**Comment by sokra** [comment]
This is related to `webpack-contrib/webpack-defaults`.

**Comment by bebraw** [comment]
Moved to https://github.com/webpack-contrib/webpack-defaults/issues/102 .
