### ISSUE TITLE
Any plan to upgrade @types

### ISSUE THREAD

**Issue by fwh1990** [webpack-contrib/mini-css-extract-plugin#611]
I'm migrating webpack from 4 to 5, and facing a problem that `@types/mini-css-extract-plugin` is reference type from `@types/webpack`, it's incompatible with latest webpack.

More incompatible packages I'm using are listed below:
* @types/mini-css-extract-plugin
* @types/compression-webpack-plugin
* @types/optimize-css-assets-webpack-plugin
* @types/terser-webpack-plugin

**Comment by evilebottnawi** [comment]
No, `@types/mini-css-extract-plugin` is not out repo, so we can't update it

**Comment by fwh1990** [comment]
> No, `@types/mini-css-extract-plugin` is not our repo, so we can't update it, built-in types will be in near future

Well, I will not complete migrating until you do that. Thank you for your help.
