### ISSUE TITLE
Cache group settings are sometimes ignored

### ISSUE THREAD

**Issue by shameleo** [webpack-contrib/mini-css-extract-plugin#615]
- Operating System: Win 10
- Node Version: 12.18.3
- NPM Version: 6.14.7
- webpack Version: 5.0.0
- mini-css-extract-plugin Version: 1.0.0

### Expected Behavior
Output files: `index.js`, `index.css`, `shared.js`, **`shared.css`**

### Actual Behavior
Output files: `index.js`, `index.css`, `shared.js`. 
Css from `src/shared/test.css` expected to be in `dist/shared.css`, but goes to `dist/index.css` instead.

### Code

```js
// webpack.config.js
// full config: https://github.com/shameleo/mini-css-extract-plugin-issue/blob/7c5487a89b0bdfb6b3177cf2ed8a672450bb9975/webpack.config.js
optimization: {
    splitChunks: {
        cacheGroups: {
            'shared': {
                chunks: 'all',
                enforce: true,
                test: ({resource}) => resource && resource.includes('shared'),
                //priority: 100,          // didn't help
                name: 'shared'
            }
        }
    },
},
plugins: [
    new MiniCssExtractPlugin({
        filename: `[name].css`
    }),
]
```

```js
// index.js
import { test } from './shared/test.js';
import './index.css';
console.log('ENTRY ', test);
```

```js
// shared/test.js
import './test.css';
export const test = 'TEST';
```

### How Do We Reproduce?
```
git clone https://github.com/shameleo/mini-css-extract-plugin-issue.git
npm install
npm run dev
```

**Comment by evilebottnawi** [comment]
No modules - no chunks

**Comment by shameleo** [comment]
> Can you try: `type: 'css/mini-extract'`?

You mean `cacheGroup` option? So if I use it instead of `test()` function I'm getting `index.js` and `shared.css`. If I combine it with `test()` function (which seems to be invalid) it outputs `index.js` and `index.css`

**Comment by evilebottnawi** [comment]
> You mean cacheGroup option? So if I use it instead of test() function I'm getting index.js and shared.css.

yes, now you have `shared.css`

**Comment by shameleo** [comment]
Yes, now I have `src/shared/test.css` + `src/index.css` => `dist/shared.css`.
But what I want is  `src/index.css` => `dist/index.css` and `src/shared/test.css` => `dist/shared.css`

**Comment by evilebottnawi** [comment]
You need to specify group for `src/index.css`, you don't have `enforce: true` for this, so nothing to create

**Comment by shameleo** [comment]
@evilebottnawi, no rush, file names could mislead you. `dist/index.css` must contain **all** css from `index.js` (except files from "shared" cache group), not only from 'src/index.css'. `index.js` is **entry**, so I expect css which did't match "shared" cache group end up there. And it is, unless I force extracting all css in "shared" according to your advice.

**Comment by evilebottnawi** [comment]
You `test` and `type` together, sorry splitting is a part of webpack, there is nothing to here with this, but you need two groups if you want to extract into 2 files

**Comment by shameleo** [comment]
So, real reason was that my `test` function is invalid. I should use `module.nameForCondition()` instead of `module.resource`, or just regex. `test` function is called twice, so the first time `module.resource` has expected value (and splitting for js files works), but the second time `module.resource` is `undefined`, and css goes to entry css bundle.
I don't know if undefined `resource` is valid case or not, as well as what is the difference from `nameForCondition()`, as Webpack docs doesn't even mention it. It seems nobody cares to read issues mindfully here.

**Comment by evilebottnawi** [comment]
> It seems nobody cares to read issues mindfully here.

Because you don't want to read the official documentation

> test function is called twice, so the first time module.resource has expected value (and splitting for js files works), but the second time module.resource is undefined, and css goes to entry css bundle.

No

**Comment by shameleo** [comment]
> Because you don't want to read the official documentation

I've read it reasonable amount of time. The only mentioning of `nameForCondition` is on [this](https://webpack.js.org/migrate/5/) page. But docs mention `resource` for testing. Actually, I needed to look through source code to find out what is going on. I don't know the difference, but Webpack uses `nameForCondition` when you specify regex instead of function. And yes, it is the only thing I needed to change in my code to get result which I've expected.

> No

Not too clear. I've rechecked, it actually called more then twice for css modules. **This is my `test` function**:
```
test(module) {
    const isMatched = module.resource && module.resource.includes('shared');
    
    console.log('res : ', module.resource);
    console.log('name: ', module.nameForCondition());

    return isMatched;
},
```
[Full example, test function is modified a little](https://github.com/shameleo/mini-css-extract-plugin-issue.git)

**And this is output**:
```
res :  /home/shameleo/Projects/mini-css-extract-plugin-issue/src/index.js
name:  /home/shameleo/Projects/mini-css-extract-plugin-issue/src/index.js
res :  /home/shameleo/Projects/mini-css-extract-plugin-issue/src/shared/test.js
name:  /home/shameleo/Projects/mini-css-extract-plugin-issue/src/shared/test.js
res :  /home/shameleo/Projects/mini-css-extract-plugin-issue/src/shared/test.css
name:  /home/shameleo/Projects/mini-css-extract-plugin-issue/src/shared/test.css
res :  /home/shameleo/Projects/mini-css-extract-plugin-issue/src/index.css
name:  /home/shameleo/Projects/mini-css-extract-plugin-issue/src/index.css
res :  undefined
name:  /home/shameleo/Projects/mini-css-extract-plugin-issue/src/shared/test.css
res :  undefined
name:  /home/shameleo/Projects/mini-css-extract-plugin-issue/src/index.css
```
It clearly shows that `module.resource` is `undefined` sometimes, while `module.nameForCondition()` is not. Is it issue? I don't know. You might know, but it's too hard to ask you.

**Comment by evilebottnawi** [comment]
Can you create simple example?

**Comment by shameleo** [comment]
I did my best, too make it a little clearer, it's already quite minimal.

**input (dependency tree):**
index.js (entry)
....index.css
....shared/test.js
........shared/test.css

**expected ouput:**
index.js
index.css
shared-bundle.js
shared-bundle.css

**webpack config part:**
```
optimization: {
    splitChunks: {
        cacheGroups: {
            'shared': {
                chunks: 'all',
                enforce: true,
                test(module) {
                    // This is NOT correct
                    const isMatched = module.resource && module.resource.includes('shared');

                    // This is correct
                    //const isMatched = module.nameForCondition().includes('shared');
                    
                    console.log('res : ', module.resource);
                    console.log('name: ', module.nameForCondition());
                
                    return isMatched;
                },
                name: 'shared-bundle'
            }
        }
    },
},
plugins: [
    new MiniCssExtractPlugin({
        filename: `[name].css`
    }),
]
```

**Full code: https://github.com/shameleo/mini-css-extract-plugin-issue/tree/d9a853cb3d12da988ef3c6b6887196693699a338**

**Comment by evilebottnawi** [comment]
You can use `nameForCondition`, it is safe https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/CssModule.js#L59
