### ISSUE TITLE
Negative lookups don't work for `assetNameRegExp`

### ISSUE THREAD

**Issue by zenopopovici** [webpack-contrib/mini-css-extract-plugin#617]
- Operating System: MacOs 10.15.7
- Node Version: 12.19.p
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- mini-css-extract-plugin Version: 1.0.0

### Expected Behavior

The plugin should ignore `style.css`, `global.css`, `post-33.css` files.

### Actual Behavior
It will process all of them. 

### Code

```js
      new OptimizeCSSAssetsPlugin({
        assetNameRegExp: /^(?!style|global|post-).*\.css$/g,
        cssProcessor: require('cssnano'),
        cssProcessorOptions: { map: { inline: false, annotations: true } },
        cssProcessorPluginOptions: {
          preset: ['default', { discardComments: { removeAll: true } }]
        },
        canPrint: true
      }),
```

### How Do We Reproduce?

Run the above config.

**Comment by evilebottnawi** [comment]
Not related to this plugin, please open an issue in `OptimizeCSSAssetsPlugin`, anyway I recommend to migrate on https://github.com/webpack-contrib/css-minimizer-webpack-plugin

**Comment by zenopopovici** [comment]
@evilebottnawi My mistake, that was the place where I wanted to report it in the first place. I guess I had multiple tabs open. Sorry for the trouble. 

🤩 Also thanks for the tip, I didn't know about it. I think I'll migrate right away as I see it has working sourcemaps support.
