### ISSUE TITLE
export 'default' (imported as 'aaa') was not found in './bbb.less'

### ISSUE THREAD

**Issue by Yijx** [webpack-contrib/mini-css-extract-plugin#619]
Operating System: windows
Node Version: v12.19.0
NPM Version: 6.14.8
webpack Version: 5.1.0
mini-css-extract-plugin Version: 1.0.0

I have same question as #618 and #613 . I am update webpack4 to 5
when I use react and write this code:
`
 import aaa from './bbb.less';
`
webpack5 warning me :  export 'default' (imported as 'aaa') was not found in './bbb.less'.
I 'm sorry but I don't quite understand 'You should not use import something from './style.css' if you don't use locals' in #618

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please read changelog, you don't need to use default import

**Comment by evilebottnawi** [comment]
Just use `import './style.css'`/`import './style.less'`/`import './style.sass'`
