### ISSUE TITLE
GitHub readme doesn't reflect actual functionality

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/mini-css-extract-plugin#62]
The stable and development version are two different things with different sets of features. I got burned by this as I tried to use a development feature and there's no easy way to do that due to #61. Maybe it would be better to push development bits to a branch of its own so people don't get confused.

**Comment by sokra** [comment]
This is true for most of the github repositories.

**Comment by evilebottnawi** [comment]
@bebraw can we close this issue here?
