### ISSUE TITLE
mini-css-extract-plugin don't wotr with webpack5

### ISSUE THREAD

**Issue by deicidemilan** [webpack-contrib/mini-css-extract-plugin#620]
Hello,

I have issue with "mini-css-extract-plugin": "^1.0.0" and "webpack": "^5.1.1".
When I run "npm run build"  I don't get .css files (.js are created) but with  "mini-css-extract-plugin": "^0.8.0" it's work perfect.
And with "npm run build  -- --mode development" I got .css in both situation.

So my code is:

package.json
`{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack",
    "prod": "npm run build",
    "dev": "npm run build  -- --mode development",
    "watch": "npm run build  -- --mode development --watch"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^5.0.0",
    "html-webpack-plugin": "^4.5.0",
    "mini-css-extract-plugin": "^1.0.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^10.0.3",
    "webpack": "^5.1.1",
    "webpack-cli": "^4.0.0"
  }
}`

webpack.config.js
`const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

module.exports = {
    entry: {
        index: path.resolve(__dirname, 'src/js/index.js')
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name].[contenthash].js'
    },
    module: {
        rules: [
            {
                test: /\.scss$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    'css-loader',
                    'sass-loader'
                ]
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin( {
            template: './src/index.html',
            filename: '../index.html',
            chunks: ['login'],
            minify: {
                collapseWhitespace: true,
                removeComments: true,
                removeRedundantAttributes: true,
                removeScriptTypeAttributes: true,
                removeStyleLinkTypeAttributes: true,
                useShortDoctype: true
            }
        }),
        new CleanWebpackPlugin(),
        new MiniCssExtractPlugin({
            filename: '[name].[contenthash].css'
        })
    ]
};`

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Update webpack to `5.1.2`

**Comment by deicidemilan** [comment]
> Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.
> 
> Please help us help you by recreating the issue using one of our templates.
> 
> Update webpack to `5.1.2`

With "webpack": "^5.1.2", "mini-css-extract-plugin": "^1.0.0" works now perfect.

Tnx for answer
