### ISSUE TITLE
Getting warnings for `export 'default' (imported as 'mod') was not found`

### ISSUE THREAD

**Issue by amir20** [webpack-contrib/mini-css-extract-plugin#625]
- Operating System: Mac Os 10.15.x
- Node Version: 14.13.1
- NPM Version: yarn 1.22.5
- webpack Version: weback 5.1.2
- mini-css-extract-plugin Version: 1.0.0

I am seeing multiple warnings that look like 

```
WARNING in ./assets/App.vue?vue&type=style&index=0&id=5bcdaf03&scoped=true&lang=scss& 1:472-475
export 'default' (imported as 'mod') was not found in '-!../node_modules/mini-css-extract-plugin/dist/loader.js??clonedRuleSet-1[0].rules[0].use[0]!../node_modules/css-loader/dist/cjs.js!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/postcss-loader/src/index.js??clonedRuleSet-1[0].rules[0].use[2]!../node_modules/sass-loader/dist/cjs.js!../node_modules/vue-loader/lib/index.js??vue-loader-options!./App.vue?vue&type=style&index=0&id=5bcdaf03&scoped=true&lang=scss&' (possible exports: )
 @ ./assets/App.vue 4:0-88
 @ ./assets/main.js 8:0-28 59:19-22
```

### Code

https://gist.github.com/amir20/753be944314fbe5a9f8d58bf0c326dc1

### How Do We Reproduce?

https://github.com/amir20/dozzle/tree/webpack5

`yarn && yarn build`

**Comment by evilebottnawi** [comment]
Please open an issue in `vue` plugin

**Comment by amir20** [comment]
I can do that. But the stacktrace suggests the problem is with this plugin. Did I miss something?

**Comment by evilebottnawi** [comment]
> WARNING in ./assets/App.vue?vue&type=style&index=0&id=5bcdaf03&scoped=true&lang=scss& 1:472-475

Here `?vue`, it is syntax for `vue` loader
