### ISSUE TITLE
"Extracting CSS based on entry" example doesn't work

### ISSUE THREAD

**Issue by pinkiebala** [webpack-contrib/mini-css-extract-plugin#628]
- Operating System: ubuntu20.04
- Node Version: 12.16.1
- NPM Version: 6.13.4
- webpack Version: 4.36.1
- mini-css-extract-plugin Version: 1.1.0

### Expected Behavior

[Extracting CSS based on entry example](https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-css-based-on-entry) should work.

In the reproduce repo,
CSS of `comp1.css` should merge into `app1.css`.
CSS of `comp2.css` should merge into `app2.css`.

### Actual Behavior

Each of `comp1` & `comp2` has its own CSS chunk.

And:

```js
function recursiveIssuer(m) {
  if (m.issuer) {
    return recursiveIssuer(m.issuer);
  } else if (m.name){ // <--- this is `undefined`
    return m.name;
  }
  return false;
}
```

### How Do We Reproduce?

Here is the reproduce repo
https://github.com/pinkiebala/extract-css-entry-failed-reproduce

**Comment by cap-Bernardito** [comment]
There is an error in the documentation, we will fix it.

You can achieve the desired effect using the example below:

```js
const webpackVersion = require("webpack").version;

function recursiveIssuer(m) {
  if (m.issuer) {
    return recursiveIssuer(m.issuer);
  }

  const chunks = webpackVersion === "4" ? m._chunks : m.getChunks();

  for (const chunk of chunks) {
    return chunk["name"];
  }

  return false;
}

module.exports = {
  entry: {
    app1: path.resolve(__dirname, "..", "src", "app1.js"),
    app2: path.resolve(__dirname, "..", "src", "app2.js"),
  },
  ...
  optimization: {
    splitChunks: {
      cacheGroups: {
        app1Styles: {
          // For webpack 4 name should not be equal entry. We recommend upgrading to webpack@5
          name: "style_app",
          test: (m, c, entry = "app1") =>
            m.constructor.name === "CssModule" && recursiveIssuer(m) === entry,
          chunks: "all",
          enforce: true,
        },
      },
    },
  },
};
```

**Comment by pinkiebala** [comment]
Thanks a lot!
