### ISSUE TITLE
Path variable [contenthash] not implemented in this context

### ISSUE THREAD

**Issue by Baune8D** [webpack-contrib/mini-css-extract-plugin#63]
**Code:**
```javascript
new MiniCssExtractPlugin(
{
    filename: "[contenthash].min.css",
    chunkFilename: "[contenthash].chunk.min.css"
}
```

**Output:**
```
Path variable [contenthash] not implemented in this context: [contenthash].min.css
```

[chunkhash] and [hash] works fine.

macOS: 10.13.3
Node.js: 9.9.0
Webpack: 4.3.0
mini-css-extract-plugin: 0.2.0

**Comment by evilebottnawi** [comment]
@Baune8D just wait release `mini-css-extract-plugin` today. Thanks!

**Comment by KyleAMathews** [comment]
@sokra hasn't made a new release yet with contenthash support https://github.com/webpack-contrib/mini-css-extract-plugin/releases
