### ISSUE TITLE
Css `preload` does not work in Firefox

### ISSUE THREAD

**Issue by k2snowman69** [webpack-contrib/mini-css-extract-plugin#632]
- Operating System: OSX
- Node Version: v12.18.4
- NPM Version: 6.14.6
- webpack Version: 5.0.0
- mini-css-extract-plugin Version:1.1.0

### Expected Behavior

When I modify a css file, that when the page reloads, styles are loaded by the browser

### Actual Behavior

Though I do see the following in the head tag:
```
<link rel="preload" type="text/css" href="/app.css" as="style">
<link rel="preload" type="text/css" href="http://localhost:9091/app.css?1603240249373" as="style">
```

My styles are broken in Firefox 81.0.2 (64-bit)
Everything works in Chrome 86.0.4240.111
Everything works in Safari 14.0 (14610.1.28.1.9)

### Code

```js
// webpack.config.js
// css loader info
        {
          test: /\.(sa|sc|c)ss$/,
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
              options: {},
            },
            'css-loader'
          ],
        },

// plugins
    plugins: [
      // @ts-ignore - JS-94 - Types for MiniCssExtraPlugin are incorrect
      // https://github.com/DefinitelyTyped/DefinitelyTyped/issues/32680
      new MiniCssExtractPlugin({
        chunkFilename: isProduction ? '[name].[contenthash].css' : '[name].css',
        filename: isProduction ? '[name].[contenthash].css' : '[name].css',
      }),
      new HtmlWebpackPlugin({
        chunks: ['app'],
        favicon: `./src/browser/favicon-196x196.png`,
        filename: 'index.html',
        template: 'src/browser/app.html',
        title: 'removed-for-security',
      }),
      ...(isProduction ? [] : [new webpack.HotModuleReplacementPlugin()]),
    ],
```

### How Do We Reproduce?

I'd assume if you have an example app:
1. Run it
2. Open it in Firefox
3. Modify a css file somewhere
4. Wait for reload
5. See broken styles

On this... it maybe super useful to have an `example-mini-css-extra-plugin` repository that we can clone to try and reproduce things that we think are bugs. I'm not sure if one exists nor did I find documentation to one but just a suggestion to ease the "minimal reproduction requirements" thing.

**Comment by evilebottnawi** [comment]
We don't support `preload`

**Comment by evilebottnawi** [comment]
If you need a help please create reproducible test repo
