### ISSUE TITLE
onerror memory leak

### ISSUE THREAD

**Issue by dgeibi** [webpack-contrib/mini-css-extract-plugin#639]
- Operating System: Mac
- Node Version: 12
- NPM Version: 12.18.2
- webpack Version: 4.44.2
- mini-css-extract-plugin Version: 1.2.0
- browser:  chrome 86.0.4240.111

### Expected Behavior

should unref onerror after onload

### Actual Behavior

onerror remains in the memory

![截屏2020-10-26 下午7 25 22](https://user-images.githubusercontent.com/2224764/97167022-18f88800-17c1-11eb-84f7-e146fd3ed428.png)

### Code

https://github.com/dgeibi/mini-css-extract-plugin-mem-leak-demo

### How Do We Reproduce?

```
git clone https://github.com/dgeibi/mini-css-extract-plugin-mem-leak-demo
cd mini-css-extract-plugin-mem-leak-demo
npm i
npm run build
# open dist/index.html with chrome
```

**Comment by evilebottnawi** [comment]
PR welcome, easy to fix

**Comment by evilebottnawi** [comment]
Big thanks!
