### ISSUE TITLE
Path variable [contenthash] not implemented in this context

### ISSUE THREAD

**Issue by DevSide** [webpack-contrib/mini-css-extract-plugin#64]
I've got this error:

```
ERROR in chunk account
[name]-[contenthash].bundle.css
Path variable [contenthash] not implemented in this context: [name]-[contenthash].bundle.css
```

After adding some debug into `TemplatedPathPlugin:replacePathVariables` function:
- my `account` chunk has `contentHash: { javascript: 'c3b502d300' }`
- data.contentHashType is `undefined`, should be javascript ?

**Comment by evilebottnawi** [comment]
Dup https://github.com/webpack-contrib/mini-css-extract-plugin/issues/63
