### ISSUE TITLE
when you set output.iife to false, plugin does not work properly

### ISSUE THREAD

**Issue by muzea** [webpack-contrib/mini-css-extract-plugin#644]
- Operating System: macOS
- Node Version: 12.18.2
- NPM Version: 6.14.5
- webpack Version: 5.3.2
- mini-css-extract-plugin Version: 1.2.1

### How Do We Reproduce?

[repo for reproducible issue](https://github.com/muzea-demo/webpack_style)

When `output.iife` is set to `true`, the output is as expected.

### Expected Behavior

output shoule be

```
build_test
├── app.acss
└── app.js
```

### Actual Behavior

```
build_test
└── app.js
```

**Comment by alexander-akait** [comment]
The next verison of webpack should fix this problem

**Comment by utlime** [comment]
Hi @alexander-akait ,
could you please say which exactly version it will be or issue to track?

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/releases/tag/v5.22.0

> refactor libraries to inline exporting code into runtime to allow using with output.iife: false

**Comment by alexander-akait** [comment]
Tests passed, now you can use `output.iife` and `output.module` with `mini-css-extract-plugin`, just update webpack to `5.22.0` version
