### ISSUE TITLE
CSS is not emitted for imports from `html-webpack-plugin`

### ISSUE THREAD

**Issue by ogonkov** [webpack-contrib/mini-css-extract-plugin#646]
- Operating System: macOS 10.15.7
- Node Version: v10.17.0
- NPM Version: 6.11.3
- webpack Version: 5.4.0
- mini-css-extract-plugin Version: 1.2.1

### Expected Behavior

CSS chunk emitted, and inserted to html with CSS-modules hash

### Actual Behavior

HTML emmited without css chunk and empty `class` attribute

### Code

https://gist.github.com/ogonkov/2e23941414d6f0b3d5328bd80cba5674

### How Do We Reproduce?

Instructions in gist above.

**Comment by ogonkov** [comment]
Same case previously produce an error #489

**Comment by evilebottnawi** [comment]
Sorry, not related to `mini-css-extract-plugin`, please open an issue in HTMLWebpackPlugin

**Comment by ogonkov** [comment]
I see that require in template is returns module, but it didn"t have any content. How it could be not related to loader?

**Comment by evilebottnawi** [comment]
No
