### ISSUE TITLE
Loader triggers ton of compilations out of nowhere

### ISSUE THREAD

**Issue by carljohnesan** [webpack-contrib/mini-css-extract-plugin#654]
- Operating System: osx 10.13.6 High Sierra
- Node Version: 14.8.0
- NPM Version: 6.14.7
- webpack Version: 4.44.2
- mini-css-extract-plugin Version: 1.3.0

Tons of webpack compilation events appear, means code compiles tons of times. Expected this not to happen.
Here's minimal reproduction repo - <https://github.com/carljohnesan/mini-css-extract-bug-reproduction>

**Comment by evilebottnawi** [comment]
Expected, because we use `child` compilations, don't do it

**Comment by carljohnesan** [comment]
Got it. But how do I avoid unneeded `console.log`s in webpack compilation hooks?

**Comment by evilebottnawi** [comment]
Yes, you can get top compilation using `compiler.hooks.thisCompilation`

**Comment by carljohnesan** [comment]
Thank you
