### ISSUE TITLE
When reading from webpack5 filesystem cache imported assets from css are not found

### ISSUE THREAD

**Issue by piecyk** [webpack-contrib/mini-css-extract-plugin#655]
- Operating System: macOS
- Node Version: 12.14.1
- NPM Version: 6.13.4
- webpack Version: 5.4.0
- mini-css-extract-plugin Version: 1.3.0

### Expected Behavior

When webpack is running from cache, output is the same as without. 

### Actual Behavior

When reading from cache assets imported from css are not found.

### Code

https://github.com/piecyk/mini-css-extract-plugin-asset-cache-bug

### How Do We Reproduce?

1. checkout mini-css-extract-plugin-asset-cache-bug
2. yarn webpack
3. checkout output from ./dist 

```
./dist/
├── index.html
├── main.css
├── main.js
└── static
    └── webpack-logo.svg
```
4. rm -rf ./dist/
5. yarn webpack
6. checkout output from ./dist 
```
./dist/
├── index.html
├── main.css
└── main.js
```

**Comment by evilebottnawi** [comment]
Yep, bug `mini-css-extract-plugin` doesn't work with `asset` modules, critical, need to fix

**Comment by piecyk** [comment]
Hmm hard to say where or how to start with this 🤔 Obvious workaround is to use file-loader/url-loader rather new assets. Also if someone want's to have a look added testes cases https://github.com/piecyk/mini-css-extract-plugin/tree/bugfix/655 can use this as base branch.

**Comment by evilebottnawi** [comment]
I will send a fix today

**Comment by evilebottnawi** [comment]
Hope, we don't break anything, anyway there is one way to check, release it :smile:

**Comment by evilebottnawi** [comment]
Please try https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v1.3.1

**Comment by piecyk** [comment]
@evilebottnawi works! Thanks 👏

**Comment by Varedis** [comment]
This seems to have broken Webpack 4 compatibility. 

v1.3.0 works with Webpack 4
v1.3.1 does not

**Comment by evilebottnawi** [comment]
@Varedis when you speak it is broken please provide reproducible test repo, hard to say what is not working

**Comment by evilebottnawi** [comment]
We have tests for v4 and all works fine, hard-source-webpack-plugin will be never compatibility with this

**Comment by Varedis** [comment]
Maybe this helps, I don't really have the time to make a test repo at the minute, sorry:

using `mini-css-extract-plugin@1.3.1` and `webpack@4.29.6`:

![image](https://user-images.githubusercontent.com/397126/99813107-2fcf9780-2b3f-11eb-8f7c-5fcad4d0756c.png)

Using `mini-css-extract-plugin@1.3.0` with the same webpack version and exactly same config works fine.

**Comment by evilebottnawi** [comment]
Please update webpack@4 to the latest stable version

**Comment by evilebottnawi** [comment]
i.e. `4.44.2`

**Comment by evilebottnawi** [comment]
We try to avoid supporting old version of webpack, there are a lot of other bugs
