### ISSUE TITLE
When I use the insert option with a function, i can't find any code about insert the linkTag in bundle.js

### ISSUE THREAD

**Issue by Awen-hub** [webpack-contrib/mini-css-extract-plugin#659]
webpack.config.js   can see in here  [https://paste.ubuntu.com/p/p6Hj33yxbd/]

The problem is I can't see any code to create a link to load css file in bundle.js, and css is loaded by a created linkTag in HTML file. I want to create a linkTag in a dom which id is "#app", so can you tell me how can i resolve this problem?

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Because linkTag only for async chunks
