### ISSUE TITLE
import styles only have comments will result in empty chunk

### ISSUE THREAD

**Issue by githoniel** [webpack-contrib/mini-css-extract-plugin#660]
- Operating System: win10
- Node Version: Node v14
- NPM Version: 6.14.8
- webpack Version: webpack 4/5
- mini-css-extract-plugin Version: master branch

### Expected Behavior

it will extract 0kb chunks when import a file only contains comments and with css minimizer

for example: 

```js
// entry app.js
import 'bootstrap.less'
```

```less
/* stylelint-disable at-rule-empty-line-before,at-rule-name-space-after,at-rule-no-unknown */
/* stylelint-disable no-duplicate-selectors */
/* stylelint-disable */
/* stylelint-disable declaration-bang-space-before,no-duplicate-selectors,string-no-newline */
@import '../../style/themes/index';  // only contain less vars
@import '../../style/mixins/index'; // only contain mixins
```
We will get `app.css` below without css minimizer

```css
/* stylelint-disable at-rule-empty-line-before,at-rule-name-space-after,at-rule-no-unknown */
/* stylelint-disable no-duplicate-selectors */
/* stylelint-disable */
/* stylelint-disable declaration-bang-space-before,no-duplicate-selectors,string-no-newline */
```

and with css minimizer we will get a empty file  `app.css` 

### Actual Behavior

do not get empty css file

I'm not sure which package should resolve this. I think maybe we can fix this by

1. remove comments by css-loader, but it do not provide this now
2. remove empty files by `css-minimizer-webpack-plugin`
3. `mini-css-extract-plugin` remove chunks only have comments

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Do not ignore section how we can reproduce, respect time of other developers

**Comment by evilebottnawi** [comment]
And yes, expected, empty chunks with code is still chunks, when can be dependency for other chunks, and we should load them, otherwise graph will be broken, like empty js file, you will still get empty js chunk
