### ISSUE TITLE
TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by mikeandersun** [webpack-contrib/mini-css-extract-plugin#661]
I use update` webpack` to 5.9.0  and get this error. Is there any samples with `webpack `5.9.0 ?
`TypeError: The 'compilation' argument must be an instance of Compilation`

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
