### ISSUE TITLE
Less verbose output

### ISSUE THREAD

**Issue by samgermain** [webpack-contrib/mini-css-extract-plugin#666]
- Operating System: Windows 10 Pro v. 1909
- Node Version: v12.18.4
- NPM Version: 6.14.6
- webpack Version: 4.44.2
- mini-css-extract-plugin Version: 1.3.1

### Feature Proposal
Make an option that allows for less verbose output. The output from this plugin floods the console. This makes more important output less noticeable, and I have never once found any use for the mini-css-extract-plugin output.

Right now it's this

```
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-1!node_modules/postcss-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!src/components/SignInForm/style.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/components/SignInForm/style.scss] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/components/SignInForm/style.scss 2.78 KiB {mini-css-extract-plugin} [built]
```

but for every scss file. I have something like 20 some scss files in my project, this is a huge amount of output to the console.

[This has been brought up before](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/496), and the solutions are work arounds and not perfect

**Comment by sokra** [comment]
That's fixed in webpack 5

**Comment by alexander-akait** [comment]
Answer above
