### ISSUE TITLE
Plugin is Sensitive to Case in Command Line

### ISSUE THREAD

**Issue by GreggThelen** [webpack-contrib/mini-css-extract-plugin#669]
In Visual Studio 2019 when running Webpack from the Developer PowerShell command line if the case of the folder names doesn't match the case as viewed in File Explorer the plugin will fail.  Other plugins are not impacted in this way (CopyPlugin & ProvidPlugin both work fine).

For example:
PS C:\Development\Foo\web> npm start     <----- mini-css-extract-plugin fails
PS C:\Development\Foo\Web> npm start     <----- mini-css-extract-plugin works.

Versions I'm using:
 "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^7.0.0",
    "css-loader": "^5.0.1",
    "css-minimizer-webpack-plugin": "^1.1.5",
    "file-loader": "^6.2.0",
    "mini-css-extract-plugin": "^1.3.3",
    "style-loader": "^2.0.0",
    "url-loader": "^4.1.1",
    "webpack": "^5.11.0", (also failed in 5.10.3)
    "webpack-cli": "^4.2.0",
    "webpack-merge": "^5.7.0"

When researching this issue there were other references to case being important - but I thought it would be about the case of the folder names in configuration files.  This is not that.  This is the case as expressed in the actual command line prompt.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
