### ISSUE TITLE
Can filename/chunkFilename support function type ?

### ISSUE THREAD

**Issue by Fuji-sunny** [webpack-contrib/mini-css-extract-plugin#67]
Much thanks for this project!

Here my project is a multi-page project, which means that I need my dist directory to be like this: 
dist/
   |---a/
   |     |---js/
   |     |      |---a.js
   |     |---css/
   |     |      |---a.css
   |     |---html/
   |     |      |---a.html
   |---b/
   |     |---js/
   |     |      |---b.js
   |     |---css/
   |     |      |---b.css
   |     |---html/
   |     |      |---b.html

The entry point is 'xxx/js/xxx.js' so the [filename] in mini-css-extract-plugin is 'xxx/js/xxx'.
After webpack build my css files are in the [xxx/js/] directory, not my expectation [xxx/css/] directory.

In extract-text-webpack-plugin [filename] can be a function type and provide a getPath function as its arguments. 
Can mini-css-extract-plugin's [filename] support function type like this ?
Or any other suggestion about the above implementation ?

**Comment by sokra** [comment]
Send a PR to allow `function` for `filename`

**Comment by lcxfs1991** [comment]
@evilebottnawi @sokra 

I look into the source code today and find that a bit difficult to just pass a `function` to `filename` option.

Any suggestions for what we can do?

**Comment by evilebottnawi** [comment]
@lcxfs1991 https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L103 just add before check on function and if function run it and save in filename

**Comment by lcxfs1991** [comment]
@evilebottnawi Are you at Gitter? Let me discuss with you there.

**Comment by evilebottnawi** [comment]
@lcxfs1991 give me link

**Comment by lcxfs1991** [comment]
@evilebottnawi https://gitter.im/webpack/webpack

**Comment by davityavryan** [comment]
Hi guys,
Any news regarding this change?

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by Fuji-sunny** [comment]
Is there any update with this issue?

**Comment by glen-84** [comment]
@Fuji-sunny See #145.

**Comment by domonique-ncino** [comment]
It will be great if this gets merged in

**Comment by rohmann** [comment]
It looks like you can set `filename` to a function if `chunkFilename` is also set. For example:

```
new MiniCssExtractPlugin({
      filename: ({ chunk }) => `dist/${entries[chunk.name].dest}`,
      chunkFilename: '[id]'
    })
```

Unless I'm missing something, maybe this just needs a bit of documentation and better error handling?

**Comment by truedue** [comment]
Try to use `moduleFilename`. You don't need to set `chunkFilename `.
```
new MiniCssExtractPlugin({
  moduleFilename: (chunk) => `dist/${chunk.name}.css`
}),
```
This works fine :)

**Comment by silkfire** [comment]
@evilebottnawi The `moduleFilename` option doesn't seem to work. Nothing changes when I use it.

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack-contrib/mini-css-extract-plugin/pull/602, `chunkFilename` as `Function` available on for webpack@5, webpack@5 release will be `2020-10-10`

**Comment by evilebottnawi** [comment]
`moduleFilename` was removed in favor `filename/chunkFilename`
