### ISSUE TITLE
Command Line Is Case Sensitive.

### ISSUE THREAD

**Issue by GreggThelen** [webpack-contrib/mini-css-extract-plugin#670]
- Operating System: Windows 10  (Visual Studio 2019)
- Node Version: 14.15.1
- NPM Version: 6.14.8
- webpack Version: 5.11.0
- mini-css-extract-plugin Version: 1.3.3

### Expected Behavior

I expect the mini-css-extract-plugin to work its mojo.

### Actual Behavior

Produces a compilation error on 'loader'.

### Code

                test: /\.css$/,
                use: [
                    { loader: MiniCssExtractPlugin.loader },
                   "css-loader"                       
                ]

### How Do We Reproduce?
The plugin works or does not work based on the command line:
PS C:\Development\Foo\web> npm start <----- mini-css-extract-plugin fails
PS C:\Development\Foo\Web> npm start <----- mini-css-extract-plugin works.

Note the difference in the case of the 'w' in the word web, above.

For some reason, the command line folder names must match the case of the folder names as viewed in File Explorer.  This isn't a problem in Webpack 4 and it only a problem in WebPack 5 for this particular plugin.  (I've not tried many other plugins, yet).

**Comment by alexander-akait** [comment]
Not related to this plugin, I don't know what mean `npm start` and what `npm start` do, if you were informed of a problem in this manner, how would you help? I think nothing, respect time of other developers

**Comment by alexander-akait** [comment]
Anyway feel free to feedback here

**Comment by alexander-akait** [comment]
If you provide more information I will help you

**Comment by GreggThelen** [comment]
'start' kicks off webpack:

 "scripts": {
    "start": "webpack --config webpack.dev.js",
    "build:dist": "webpack --config webpack.prod.js"
  },

I think the ticket is very clear that there is case sensitivity when running this plugin that was evident in Webpack 4 and does not appear to impact other plugins.

**Comment by GreggThelen** [comment]
^-- Sorry, I had to update that about 3 times.

**Comment by alexander-akait** [comment]
How it is related to webpack or the plugin? We don't touch your paths, no line of code what touch paths, please provide reproducible test repo

**Comment by GreggThelen** [comment]
A change of case on that line is the difference between the plugin failing or succeeding.
If it is true that the plugin or webpack don't interact with that line I'd certainly be interested to know why it impacts the results.

**Comment by alexander-akait** [comment]
If you provide example of the problem I will say why it happens

**Comment by DaanDL** [comment]
I have a similar issue, using Vue CLI 4, in combination with pnpm 6.0.2 and scaffolding a new project. 
Runing 'pnpm build' will work (in PowerShell) when my path starts with C:/, if it starts with c:/ I get the following error:
 Error: No module factory available for dependency type: CssDependency

I already disabled `case-sensitive-paths` plugin in Webpack but this doesn't resolve the issue.
