### ISSUE TITLE
surport multi files config.

### ISSUE THREAD

**Issue by Viyozc** [webpack-contrib/mini-css-extract-plugin#671]
### Feature Proposal
I wanna extract multiple files with different css filename pattern. 
for example:
there are .web.less & .h5.less files in project. and now i can only extract them in a single file. 
i guess if the plugin can surport name options to connect loader and plugin.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
