### ISSUE TITLE
Webpack 4 build TypeError: compilation.getAssets(...) is not iterable

### ISSUE THREAD

**Issue by igorokb** [webpack-contrib/mini-css-extract-plugin#679]
- Operating System: Ubuntu 14.04
- Node Version: 8.9.4
- NPM Version: 5.6.0
- webpack Version: 4.16.5
- mini-css-extract-plugin Version: 1.3.4, 1.3.2, 1.3.1

### Expected Behavior

Building process doesn't throw any error and corresponding bundle and assets files are generated

### Actual Behavior

The building process stops with the following error:
```js
/home/igorb/Projects/var/www/team-work/public/node_modules/mini-css-extract-plugin/dist/loader.js:122
    for (const asset of compilation.getAssets()) {

TypeError: compilation.getAssets(...) is not iterable
```
The same behavior is seen on all the 1.3.x versions. Meanwhile the 1.2.1 version was able to complete the task with no issues.

### Code

```js
// webpack.config.js
```
https://gist.github.com/igorokb/2ec60f78c805e8763073f93017dd31f0

**Comment by igorokb** [comment]
Thanks for the quick answer @alexander-akait ! But I would rather stay with the 1.2.1 version of your plugin. As you could notice the tech stack is pretty old. Updating of webpack may cause much more issues then it would solve :). As your description states, the plugin supports webpack 4, I thought it might be useful for you to be aware of this. It doesn't sound like the version number 4.16.5 is one of some earliest unstable versions.
Overall your plugin is very useful and the version 1.2.1 worked for me like a charm. Great job, guys!

**Comment by alexander-akait** [comment]
@igorokb in theory v4 should not break nothing, if you can to check it just create `dist` using old verison and new verison and run `diff` between them, and you will found all changes, I think no problem here will be

**Comment by alexander-akait** [comment]
Sometimes it's hard to maintain old version and new version from one semver major, for example `postcss@8.0.0` is broken, due some problems before release, but most of plugins have `8` as peerDeps

**Comment by alexander-akait** [comment]
Let's close, solution - is updating webpack@4 to the latest version

**Comment by yexiaodong** [comment]
npm install -D webpack  webpack-cli
