### ISSUE TITLE
 Cannot destructure property `createHash` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by taikongfeizhu** [webpack-contrib/mini-css-extract-plugin#69]
when build with mini-css-extract-plugin@0.3.0，the shell show that info：
```javascript
const { Template, util: { createHash } } = _webpack2.default;
                          ^
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
```

**Comment by taikongfeizhu** [comment]
it's need to update wepback from ^4.1.0 to ^4.3.0

**Comment by EddyVinck** [comment]
I updated to Webpack ^4.8.3 and my build compiled again.

**Comment by codejamninja** [comment]
I'm getting this error on webpack `4.16`

**Comment by vpalos** [comment]
This is happenning to me with webpack 4.16 and mini-css-extract-plugin 0.4.1.

Any solutions?

**Comment by kevnk** [comment]
`npm i mini-css-extract-plugin -D` fixed it for me

**Comment by kdevsoftware** [comment]
fixed by installing latest version of webpack.
`npm i webpack --save`

**Comment by aeksco** [comment]
Using `next` version `8.0.4` - adding `webpack` at `4.8.3` as a dev dependency solved the problem, but I couldn't for the life of me say what was broken or how the update fixed it. Blew at least 3 hours today battling my dependencies. Intensely frustrating - thanks a million @EddyVinck, you're a lifesaver!

**Comment by maxHoo** [comment]
same error in webpack@4.1.1 and  @4.34.0

**Comment by anirudhajith** [comment]
This is the only thing that worked for me:
```
npm install -g npm@latest
rm -rf node_modules
npm install
```

**Comment by lili21** [comment]
same error on webpack@4.41.5
