### ISSUE TITLE
mini-css-extract-plugin don't wotr with webpack5

### ISSUE THREAD

**Issue by humorHan** [webpack-contrib/mini-css-extract-plugin#693]
No CSS file generated。The configuration is as follows

webpack:5.20.0
mini-css-extract-plugin: 1.3.5

`
module: {
  rules: [
    {
    test: /.scss$/,
      use: [
        MiniCssExtractPlugin.loader,
        'css-loader',
        'sass-loader'
      ]
    }
  ]
},
`
....
`
plugins: [
  new MiniCssExtractPlugin({
     filename: '[name].[contenthash].css'
  })
]
`

**Comment by humorHan** [comment]
got it, webpack-merge retains the problems caused by the two versions of vue-loader！
intersting~

**Comment by PEZO19** [comment]
@humorHan Can you please specify what your solution was? How `webpack-merge` and `vue-loader` are related?
