### ISSUE TITLE
Question: Are the loaders still evaluated from right to left?

### ISSUE THREAD

**Issue by Legends** [webpack-contrib/mini-css-extract-plugin#70]
Are the loaders still evaluated from right to left?
Or did this change with wp v4?

**Comment by evilebottnawi** [comment]
@Legends can you describe more information? Loaders always works from bottom to top (or from right to left)

**Comment by bebraw** [comment]
The loader order didn't change in wp4.

**Comment by Legends** [comment]
Thanks!

**Comment by Legends** [comment]
Yeeeaaaaaaaaaaaah, just tossed Text-Extract-Plugin...now it works with webpack 4.
I was tweaking the new optimization section all the time...

Why didn't you say anything.. :D
