### ISSUE TITLE
The 'onload' attribute of <link> is not triggered.

### ISSUE THREAD

**Issue by lmrwork** [webpack-contrib/mini-css-extract-plugin#717]
I want to lazyload these extracted css, My configuration is as follows:
~~~~~
new MiniCssExtractPlugin({
  filename: '[name].[contenthash:8].css',
  chunkFilename: '[id].[contenthash:8].css',
  attributes: {
    media: 'print',
    onload: `this.media='all'`,
  },
}),
~~~~~
~~~~~
{
  test: /\.css$/i,
  use: [
    { loader: this.mode === 'development' ? 'style-loader' : MiniCssExtractPlugin.loader },
    { loader: 'css-loader' },
    { loader: 'postcss-loader' }
  ]
},
~~~~~
extract css:
~~~~~
<link media="print" onload="this.media='all'" rel="stylesheet" type="text/css" href="http://localhost/lib/844.dd40ffc9.css">
<link media="print" onload="this.media='all'" rel="stylesheet" type="text/css" href="http://localhost/lib/997.42c61dda.css">
~~~~~

Unfortunately, the 'onload' attribute of <link> is not triggered, :(

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please respect time other developers, please fix it and I will reopen, thanks

**Comment by jpnelson** [comment]
@alexander-akait Would you consider accepting a PR that adds an option to load CSS in this way? It's a recommended pattern, eg. https://www.filamentgroup.com/lab/load-css-simpler/

Thanks for your work on this plugin :)
