### ISSUE TITLE
[BUG?] The 'onload' attribute of <link> is not triggered. 

### ISSUE THREAD

**Issue by lmrwork** [webpack-contrib/mini-css-extract-plugin#721]
- Operating System: window 10
- Node Version: v14.15.1
- NPM Version: 6.14.10
- webpack Version: 5.24.2
- mini-css-extract-plugin Version: 1.3.9

### Expected Behavior

link tag will execute 'onload' attribute after inserted.

### Actual Behavior

'onload' did not execute after link tag is inserted to body.

### Code

```webpack.config.js
new MiniCssExtractPlugin({
  filename: '[name].[contenthash:8].css',
  chunkFilename: '[id].[contenthash:8].css',
  attributes: {
    media: 'print',
    onload: `this.media='all'`,
  },
}),
```
```
{
  test: /\.css$/i,
  use: [
    { loader: this.mode === 'development' ? 'style-loader' : MiniCssExtractPlugin.loader },
    { loader: 'css-loader' },
    { loader: 'postcss-loader' }
  ]
},
```
extract css:
```html
<link media="print" onload="this.media='all'" rel="stylesheet" type="text/css" href="http://localhost/lib/844.dd40ffc9.css">
<link media="print" onload="this.media='all'" rel="stylesheet" type="text/css" href="http://localhost/lib/997.42c61dda.css">
```
Unfortunately, the 'onload' attribute of is not triggered, :(

**Comment by alexander-akait** [comment]
It is limitation, you can't use `onload` event because it is used internally by this plugin (https://github.com/webpack-contrib/mini-css-extract-plugin/blob/6ae4c3ede6b4d02c2c80234a6dc22c355c2e3855/src/index.js#L762), otherwise plugin will not work, don't use it, sorry

**Comment by jpnelson** [comment]
@alexander-akait Would you consider accepting a PR that adds an option to load CSS in this way? It's a recommended pattern, eg. https://www.filamentgroup.com/lab/load-css-simpler/

Thanks for your work on this plugin :)
