### ISSUE TITLE
HMR with chunk splitting fails to reload the modified chunk if it’s not the last

### ISSUE THREAD

**Issue by andersk** [webpack-contrib/mini-css-extract-plugin#730]
- Operating System: Linux
- Node Version: 14.16.0
- NPM Version: 6.14.11
- webpack Version: 5.27.2
- mini-css-extract-plugin Version: 1.3.9

### Expected Behavior

Hot module reload should work with all CSS chunks.

### Actual Behavior

When there are multiple CSS chunks due to `optimization.splitChunks`, hot module reload only works with the last CSS chunk.

### Code

https://gist.github.com/andersk/2d45d4363478b22e998e177836ebce12

```js
// webpack.config.js
const HtmlWebpackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
  mode: "development",
  entry: {
    foo: ["./common.css", "./foo.css"],
    bar: ["./common.css", "./bar.css"],
  },
  module: {
    rules: [
      { test: /\.css$/, use: [MiniCssExtractPlugin.loader, "css-loader"] },
    ],
  },
  optimization: {
    splitChunks: { chunks: "all", minSize: 1 },
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: "foo.html",
      template: "foo.html",
      chunks: ["foo"],
    }),
    new HtmlWebpackPlugin({
      filename: "bar.html",
      template: "bar.html",
      chunks: ["bar"],
    }),
    new MiniCssExtractPlugin(),
  ],
};
```

### How Do We Reproduce?

1. ```sh
   git clone https://gist.github.com/andersk/2d45d4363478b22e998e177836ebce12 css-hmr-test
   cd css-hmr-test
   npm install
   npx webpack serve --hot
   ```
2. Open http://localhost:8080/foo.html.
3. Edit `foo.css`, e.g. by changing `green` to `blue`, and see that the change is applied in the browser immediately.
4. Edit `common.css`, e.g. by changing `green` to `blue`, and see that the change is not applied.

In the browser console, you can see that the wrong chunk has been reloaded:

```
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - ./common.css
[HMR] App is up to date.
[HMR] css reload http://localhost:8080/foo.css
```

This may be the same as one of the issues reported in #444. If so, consider this to be a minimal reproducible test case as requested there.

**Comment by alexander-akait** [comment]
Works fine, can't reproduce, update webpack to the latest version

**Comment by alexander-akait** [comment]
Feel free to feedback

**Comment by alexander-akait** [comment]
![Screenshot from 2021-03-26 20-38-05](https://user-images.githubusercontent.com/4567934/112671440-36667680-8e73-11eb-90da-7037bfc645d6.png)

**Comment by andersk** [comment]
Interesting. I didn’t think to try multiple browsers before, but I tried it in Chrome and both chunks can be updated as expected. In Firefox, only the last chunk can be updated.

Same result after updating css-loader 5.1.3 → 5.2.0, mini-css-extract-plugin 1.3.9 → 1.4.0, webpack 5.27.2 → 5.28.0. (Just pushed these updates to the Gist.)

I reproduced in a freshly created Firefox profile to rule out problems with Firefox configuration or extensions, and in both Firefox 87 and yesterday’s nightly to rule out problems with a specific Firefox version.

Can you try reproducing in Firefox?

**Comment by alexander-akait** [comment]
hm, Firefox has aggressive cache, so using `http://localhost:8080/foo.css?ver=1616860138471` is not invalidate cache, very weird

**Comment by joemaller** [comment]
Still seeing this in 2025 with v2.9.4 and webpack v5.102.1. 

I've got a webpack config with multiple entry targets, each outputting a JS and CSS file. Link tags are added to the page on the server (WordPress enqueue). CSS is extracted using `MiniCssExtractPlugin.loader`.

Regardless of which file is modified, the runtime always reloads the CSS file corresponding to the last item from the `entry` array. `[HMR] css reload...`

A workaround appears to be enabling `liveReload` and watching the CSS files in the output directory. This won't be HMR, but it's better than manually reloading. For true HMR, re-order the `entry` array with the active file last. 

Optimizations has the following set:
```js
  runtimeChunk: "single",
  splitChunks: { chunks: "all" }
```
