### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by chenjian0915** [webpack-contrib/mini-css-extract-plugin#731]
The reason for the error is that when the version of mini-css-extract-plugin is greater than 1.3.5, when speed-measure-webpack-plugin is used, the title error will be reported

webpack version: 5.27.2
webpack-cli version: 4.5.0
speed-measure-webpack-plugin version: 1.3.1
mini-css-extract-plugin version:  >1.3.5

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please respect time of other developers. Thanks.
