### ISSUE TITLE
[Feature Request] Option to prevent the actual file from being emitted

### ISSUE THREAD

**Issue by ferdinando-ferreira** [webpack-contrib/mini-css-extract-plugin#74]
Thanks for the excellent module.

Is it possible to have an option similar to file-loader [emitFile](https://webpack.js.org/loaders/file-loader/#emitfile)? The use case is the generation of the server side versions of packages, same use case as the one in the file-loader and the effect is to prevent the actual generation of the file (as it won't actually be used).

Best regards

**Comment by ferdinando-ferreira** [comment]
For the moment I ended up using the plugin located at [Ignore Emit Webpack plugin
](/mrbar42/ignore-emit-webpack-plugin), sinking all the css emitted after the build phase.
Would be nice to have it as a configuration in this plugin but that solves the problem fine so I'm closing the issue

**Comment by pravdomil** [comment]
@ferdinando-ferreira can you please reopen the issue? because I missing `emitFile` option in this package
