### ISSUE TITLE
less file can not be compress

### ISSUE THREAD

**Issue by zxpsuper** [webpack-contrib/mini-css-extract-plugin#747]
### recently, I start to use webpack and mini-css-extract-plugin, the version I use is that:
> "webpack": "^5.33.2"  "mini-css-extract-plugin": "^1.4.1"

And when I try to build the file, I found that **the less file can not be compress but sass file can**.

![image](https://user-images.githubusercontent.com/28730619/115854409-cab8fe80-a45c-11eb-95de-f241dfb9278d.png)
![image](https://user-images.githubusercontent.com/28730619/115854437-d278a300-a45c-11eb-8580-4bd7501886ed.png)

after webpack building, the final css is:

![image](https://user-images.githubusercontent.com/28730619/115854646-094eb900-a45d-11eb-9eb8-385e80273679.png)

webpack.config.js
```js
module: {
  rules: [
    {
      test: /\.(sa|sc|c)ss$/,
        use: [
          {
             loader: MiniCssExtractPlugin.loader,
                options: {
                    publicPath: '../',
                },
          },'css-loader','postcss-loader','sass-loader',
        ],
      },
      {
          test: /\.less$/,
             use: [
                {
                   loader: MiniCssExtractPlugin.loader,
                      options: {
                          publicPath: '../',
                        },
                    },
                    'css-loader',
                    'postcss-loader',
                    'less-loader',
                ],
            }
        ],
    },
plugins: [
  new MiniCssExtractPlugin({
    filename: 'css/[name].[contenthash].css',
    chunkFilename: 'css/[name].[contenthash].css',
  })
]
```
Do i need to change the options in MiniCssExtractPlugin loader? I hope I can get your help. Thanks

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates. 

For minification you CSS files, please use https://github.com/webpack-contrib/css-minimizer-webpack-plugin. 

If you need help more please update your issue using the issue template. Thanks
