### ISSUE TITLE
Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered

### ISSUE THREAD

**Issue by perteraul** [webpack-contrib/mini-css-extract-plugin#748]

**Comment by Florkin** [comment]
Hi,
I got this error with webpack encore. Did you found a solution @perteraul ?

**Comment by alexander-akait** [comment]
Run `npm ls webpack`/`yarn why webpack` and `npm ls mini-css-extract-plugin`/`yarn why mini-css-extract-plugin`

**Comment by willianantunes** [comment]
Same error here. Output of `npm ls webpack`:

```
willianantunes.com@0.1.0 /home/antunes/Development/git-personal/willianantunes.com
├─┬ gatsby@3.4.0
│ └── UNMET PEER DEPENDENCY webpack@5.36.1 
└─┬ gatsby-plugin-netlify-cms@5.4.0
  └── UNMET PEER DEPENDENCY webpack@5.36.1  deduped

npm ERR! peer dep missing: webpack@^2.0.0 || ^3.0.0 || ^4.0.0, required by @pieh/friendly-errors-webpack-plugin@1.7.0-chalk-2
npm ERR! peer dep missing: webpack@^2.0.0 || ^3.0.0 || ^4.0.0, required by @pieh/friendly-errors-webpack-plugin@1.7.0-chalk-2
```

`npm ls mini-css-extract-plugin`:

```
willianantunes.com@0.1.0 /home/antunes/Development/git-personal/willianantunes.com
├─┬ gatsby@3.4.0
│ └── mini-css-extract-plugin@1.3.9 
└─┬ gatsby-plugin-netlify-cms@5.4.0
  └── mini-css-extract-plugin@1.5.0
```

**Comment by alexander-akait** [comment]
@willianantunes What is npm verison? You have two problems here:
- You don't have `webpack` in `package.json` (just add this in package.json) and run `npm i`
- @pieh/friendly-errors-webpack-plugin doesn't support webpack v5, need open an issue in `friendly-errors-webpack-plugin`, but I think you don't need this plugin...

Other note:

- `mini-css-extract-plugin` have multiple versions, but should be not a problem here for you

**Comment by ddcech** [comment]
@willianantunes I upgraded gatsby to a prerelease `"gatsby": "^3.5.0-next.2"`. I also have `"gatsby-plugin-netlify-cms": "5.5.0-next.1"` It fixed the issue for me.

**Comment by willianantunes** [comment]
Sorry for the delay in answering it, everyone. I could solve with the same approach @ddcech posted above.

My NPM version is 7.11.1, @alexander-akait. Thank you for the help!

**Comment by ddcech** [comment]
Let me know if you need any help
