### ISSUE TITLE
loader rule issuer tests always fail when experimentalUseImportModule is enabled.

### ISSUE THREAD

**Issue by WearyMonkey** [webpack-contrib/mini-css-extract-plugin#755]
It is likely this is an underlying webpack `importModule` issue, but as I can easily reproduce with `mini-css-extract-plugin` I thought I would report here first.

- Operating System:

OSX 10.15.7

- Node Version:

v12.22.1

- NPM Version:

yarn 1.22.10

- webpack Version:

webpack 5.36.2
webpack-cli 4.6.0

- mini-css-extract-plugin Version:

1.6.0

### Expected Behavior

When `experimentalUseImportModule` is true, issuer condition on rules are respected. e.g.

```
// CSS:
.test {
    background-image: url('./test.svg');
}

// webpack config:

const miniCssExtractPlugin = new MiniCssExtractPlugin({experimentalUseImportModule: true});

module.exports = {
    ...
    plugins: [miniCssExtractPlugin],
    module: {
        rules: [
            {
                test: /\.css$/,
                use: [MiniCssExtractPlugin.loader, 'css-loader'],
            },
            {
                test: /\.svg$/,
                issuer: /\.css$/,
                use: ['svg-url-loader']
            }
        ]
    }
}
```

### Actual Behavior

The `issuer` test fails and no loader is applied to the svg file causing the build to file. 
Disable `experimentalUseImportModule` and the build passes.

### Code

https://github.com/WearyMonkey/mini-css-extract-issue

### How Do We Reproduce?

```
git clone https://github.com/WearyMonkey/mini-css-extract-issue
cd mini-css-extract-issue
yarn
yarn webpack
```

**Comment by WearyMonkey** [comment]
Switching the issuer to `issuer: /\.css/,` (no `$`) works as expected.

So I switched my issuer to `issuer: x => { console.log('FOO', x); return x.includes('css') },` and saw that webpack is calling the `issuer` test with:  `/Users/toby/dev/issue/src/test.css.webpack[javascript/auto]`.

This is enough to unblock me, but might be worth documenting and/or fixing in webpack.

**Comment by alexander-akait** [comment]
@WearyMonkey yes, you are right, `issuer` in this case is other

@cc @sokra what do you think?
