### ISSUE TITLE
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by bspatil0001** [webpack-contrib/mini-css-extract-plugin#76]
Even though I disabled the cache(cache: false), it is giving the same error. Has anyone have a solution for that??

**Comment by evilebottnawi** [comment]
@bspatil0001 please upgrade your `webpack` to latest version. `npm/yarn cache clear && npm/yarn install`

**Comment by bspatil0001** [comment]
I am using web pack 4.1.1, after clearing nom cache still it is giving same
error.

Thank You,

With Regards,
Basavanagouda.S.Patil

**Comment by bspatil0001** [comment]
Here is the test repo ere is my repo https://github.com/bspatil0001/webpack-test.git

it is giving undefined function error.
