### ISSUE TITLE
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by bspatil0001** [webpack-contrib/mini-css-extract-plugin#77]
I am using webpack 4.1.1, i made cache false, still i am getting the error. Is there a solution for this issue?

**Comment by pshurygin** [comment]
You should use webpack 4.4.1

**Comment by evilebottnawi** [comment]
@bspatil0001 Yes please upgrade your webpack to latest version.

**Comment by bspatil0001** [comment]
I tried 'npm install webpack@4.4.1' but still I am getting

npm WARN buble-loader@0.5.0 requires a peer of buble@* but none is
installed. You must install peer dependencies yourself.
npm WARN sass-loader@6.0.7 requires a peer of node-sass@^4.0.0 but none is
installed. You must install peer dependencies yourself.

+ webpack@4.4.1
updated 1 package in 14.327s


I tried nom cache clear --force. Then tried install web pack 4.4.1.

Nothing is working. Do you know how to upgrade my webpack.

Thank You,

With Regards,
Basavanagouda.S.Patil

**Comment by bspatil0001** [comment]
Here is the test repo ere is my repo https://github.com/bspatil0001/webpack-test.git

it is giving undefined function error.

**Comment by nagipogu** [comment]
I tried this command 
npm install webpack@3.11.0
it's not working
