### ISSUE TITLE
When I use the vant library, I introduce the component CSS and package it as a JS file

### ISSUE THREAD

**Issue by KO-Good-code** [webpack-contrib/mini-css-extract-plugin#770]
- Operating System:
- Node Version: 13.7.0
- NPM Version: 6.7
- webpack Version: 4.5.0
- mini-css-extract-plugin Version: ^1.6.0

### Expected Behavior

Detach the vant component CSS as a separate CSS file

### Actual Behavior

When I use the vant library, I introduce the component CSS and package it as a JS file

### Code

```js
{
        test: /\.css$/i,
        use: [
            MiniCssExtractPlugin.loader,
            {
                loader: 'css-loader',
                options: {
                    importLoaders: 1,
                }
            },
            'postcss-loader'
        ]
    },
```

```js
import Button from 'vant/lib/button';
import 'vant/es/icon/index.css';
import './index.css';
```

**Comment by alexander-akait** [comment]
Please use https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file, you can set `test` and specify module
