### ISSUE TITLE
Insert function is not ran when rendering a React app within a Web Component

### ISSUE THREAD

**Issue by poisonWinslow** [webpack-contrib/mini-css-extract-plugin#785]
- **Operating System**: MacOs 10.14.6
- **Node Version**: 12.18.3
- **Yarn Version**: 2.4.2
- **webpack Version**: 5.36.0
- **mini-css-extract-plugin Version**: 2.1.0

### Expected Behavior

Overriding the `insert` function within the webpack.config.js executes the function when rendering the application within a Web Component.

Expected DOM structure:
```
...
  <body>
    <div>
      <custom-web-component>
      #shadow-root (open)

          <--- the link element below does not get injected when the insert function is not ran --->
          <link rel="stylesheet" type="text/css" href="App.[contenthash].css">

          <div id="react-root" style="height: 100%; width: 100%;">
              <div id="App">
                  <h1 class="someStyle_2EDy6dB5bnNpxmLVHIGUpk">This should be red</h1>
                  <p>This should be green</p>
              </div>
          </div>
      </custom-web-component>
    </div>
  </body>
...
```

### Actual Behavior

The `insert` function is never ran causing the styles to not be included within the Web Component

Actual DOM structure is missing the `<link>` element that the `insert` function should be inserting.

### Code

https://github.com/poisonWinslow/minicssextractplugin-react-web-component-repo

**Comment by alexander-akait** [comment]
In this case you need to load styles dynamically, because when you use `import` at the top, it is initial chunk and `html-webpack-plugin` creates `link` in `index.html` (also make sense to improve our docs about it, here the issue https://github.com/webpack-contrib/mini-css-extract-plugin/issues/760), and it is impossible to add this in shadow dom, alternative `html-webpack-plugin` can support custom inject function

**Comment by poisonWinslow** [comment]
> you need to load styles dynamically
Could you elaborate on this a little further? I believe this was occuring when I was using code splitting, but want to make sure I am understanding you correctly. 

> it is impossible to add this in shadow dom
This is not the case. In a previous iteration of this solution, I was code splitting all portions of the application that required CSS and the `insert` function was successfully injecting the `link tag` inside of the `shadow dom`

> alternative html-webpack-plugin can support custom inject function
The HTML page you are viewing that is generated by the `html-webpack-plugin` is just for demonstration purposes. I do not use that HTML page in production as this product is a `micro-front-end` application that is rendered by other consuming web pages

**Comment by alexander-akait** [comment]
> Could you elaborate on this a little further? I believe this was occuring when I was using code splitting, but want to make sure I am understanding you correctly.

`insert` function works only for dynamic loading styles, in your case you just use `import * as styles from './style.css'`

> This is not the case. In a previous iteration of this solution, I was code splitting all portions of the application that required CSS and the insert function was successfully injecting the link tag inside of the shadow dom

> The HTML page you are viewing that is generated by the html-webpack-plugin is just for demonstration purposes. I do not use that HTML page in production as this product is a micro-front-end application that is rendered by other consuming web pages

Please provide full reproducible example

**Comment by poisonWinslow** [comment]
I've created a branch on the repo linked in the OP. As you can see, when the portion of the application that contains the CSS is code-split, the insert function does run and does insert the link tag into the shadow dom. 


https://github.com/poisonWinslow/minicssextractplugin-react-web-component-repo/tree/code-split-example
