### ISSUE TITLE
Class names being garbled 

### ISSUE THREAD

**Issue by abhsrivastava** [webpack-contrib/mini-css-extract-plugin#79]
I have this scss file in my project

```
h1 {
   border-bottom: 3px solid #880055;
   display: inline;
}
.container {
   font-size: 1.3rem;
}
.is-completed {
   text-decoration: line-through;
   color: #00ff00;
}
```

I run this scss through the mini-css-extract-plugin. My webpack.config.js is 

```
         {
            test: /\.scss$/,
            include: [path.resolve(__dirname, "src/styles")],
            use: [
               MiniCssExtractPlugin.loader,
               {
                 loader: "css-loader",
                 options: {
                   modules: true,
                   sourceMap: true,
                   importLoader: 2
                 }
               },
               "sass-loader"
            ]
         }
```

and plugins like

```
      new MiniCssExtractPlugin({
         filename: "foo.css",
         chunkFilename: "[id].css"
      })
```
when my page loads, I start the chrome developer tools and go into network -> CSS and I see a foo.css

when I open this file I see

```
h1 {
  border-bottom: 3px solid #880055;
  display: inline; }
.pxcHIyOVHeytUeG27u4TO {
  font-size: 1.3rem; }
._1Z5_KVJNKd1X2P3HKM63j {
  text-decoration: line-through;
  color: #00ff00; }
```

so h1 is good, but all other class names are somehow garbled.

I don't know why this is happening.

My sample project is loaded [here](https://github.com/abhsrivastava/react-ts-todo)

**Comment by KyleAMathews** [comment]
Because modules: true enables CSS Modules 

https://github.com/css-modules/css-modules/blob/master/README.md

**Comment by evilebottnawi** [comment]
Yes, don't related to MCEP, please use `modules: false` for `css-loader`
