### ISSUE TITLE
ignore or exclude something extract into css file

### ISSUE THREAD

**Issue by lerit** [webpack-contrib/mini-css-extract-plugin#792]
Operating System: Ubuntu 20
Node Version: v14
NPM Version: v6
webpack Version: v5
mini-css-extract-plugin Version: v2.1.0

### Feature Proposal
Support  ignore or exclude something into css file.

### Feature Use Case
i  use variable __webpack_public_path__ [On The Fly](https://webpack.js.org/guides/public-path/#on-the-fly),and css in js work fine.

when apply this plugin to extract css into static css file,such as url cannot use __webpack_public_path__ at runtime.

is there any way to keep some css(url,image-set and so on) in js,and extract other content into css file?

**Comment by alexander-akait** [comment]
Expected, you can use `url.filter` in `css-loader` to ignore some urls
