### ISSUE TITLE
options insert not work.

### ISSUE THREAD

**Issue by obf1313** [webpack-contrib/mini-css-extract-plugin#796]
- Operating System: win10
- Node Version:  v12.16.2
- NPM Version: 6.14.4
- webpack Version: 5.3.2
- mini-css-extract-plugin Version: 2.1.0

### Expected Behavior
my css link label will be insert after app label;

### Actual Behavior
it also insert in head.so sad, I do look all issues but not has solution.

### Code
https://github.com/MeehooCN/company_share
webpack config in build directory.
```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?
https://github.com/MeehooCN/company_share

**Comment by alexander-akait** [comment]
It works only for asynchronous chunks, we should describe it in readme, we already have an issue for this, you can help and send a PR to docs, feel free to feedback
