### ISSUE TITLE
 [webpack-contrib/mini-css-extract-plugin] TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by bspatil0001** [webpack-contrib/mini-css-extract-plugin#80]
I am using webpack 4.1.1.

I tried 'npm install webpack@4.4.1' but still I am getting

npm WARN buble-loader@0.5.0 requires a peer of buble@* but none is
installed. You must install peer dependencies yourself.
npm WARN sass-loader@6.0.7 requires a peer of node-sass@^4.0.0 but none is
installed. You must install peer dependencies yourself.

+ webpack@4.4.1
updated 1 package in 14.327s

I tried nom cache clear --force. Then tried install web pack 4.4.1.

Nothing is working. Do anyone know how to upgrade my webpack?

**Comment by evilebottnawi** [comment]
@bspatil0001 can you create minimum reproducible test repo? Looks you don't have `webpack@4.4.1`

**Comment by bspatil0001** [comment]
I tried 'npm install webpack@4.4.1' but still I am getting

npm WARN buble-loader@0.5.0 requires a peer of buble@* but none is
installed. You must install peer dependencies yourself.
npm WARN sass-loader@6.0.7 requires a peer of node-sass@^4.0.0 but none is
installed. You must install peer dependencies yourself.

+ webpack@4.4.1
updated 1 package in 14.327s


I tried nom cache clear --force. Then tried install web pack 4.4.1.

Nothing is working. Do you know how to upgrade my webpack.

Thank You,

With Regards,
Basavanagouda.S.Patil

**Comment by bspatil0001** [comment]
Here is my repo https://github.com/bspatil0001/webpack-test.git

**Comment by bspatil0001** [comment]
I tried to upgrade my webpack, but it it not getting updated my webpack. I
have my test repo, friend npm install webpack@4.4.1, but in vain. I have
given msgs I am getting when I tried to upgrade webpack.

**Comment by felipero** [comment]
Have you tried remove . your node_modules directory and run npm again?

**Comment by lexsemenenko** [comment]
I have the same issue using Webpack 4.6.0

**Comment by evilebottnawi** [comment]
Just ensure you update `webpack` to latest version. `npm/yarn cache clear -- forece && npm/yarn install`, also check you can install webpack globally. Thanks!

**Comment by krso92** [comment]
Hey guys, I got same error here. I am on latest `webpack` and `mini-css-extract-plugin`. used @gwenf code to config and I still have same err:

```
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> (/.../mini-css-extract-plugin/dist/index.js:26:44)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/.../mini-css-extract-plugin/dist/cjs.js:3:18)
    at Module._compile (module.js:649:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by maciej-gurban** [comment]
0. Make sure your configuration matches the one in README
1. Remove your `node_modules`
2. Update webpack version in `package.json`
3. Run npm install

Updating from `webpack@4.2.0` to `webpack@4.11.1` fixed it for me
