### ISSUE TITLE
Looks like plugin overwrites some files without errors/warnings

### ISSUE THREAD

**Issue by krutoo** [webpack-contrib/mini-css-extract-plugin#804]
- Operating System: Ubuntu
- Node Version: 14.16.0
- NPM Version: 7.20.0
- webpack Version: 5.48.0
- mini-css-extract-plugin Version: 2.2.0

### Expected Behavior

Accorging to docs:
https://webpack.js.org/plugins/mini-css-extract-plugin/#extracting-css-based-on-entry

I have two entry points in webpack config (desktop and mobile) with optimization like in article.

In each JS entry i have css imports (css-modules)

I expect to get something in `dist` folder similar to:
```
dist
├── mobile
│   ├── index.js
│   └── index.css
└── desktop
    ├── index.js  
    └── index.css
```

### Actual Behavior

In my `dist` folder after build i have:
```
dist
├── mobile
│   └── index.js
├── desktop
│   └── index.js  
└── mobile_styles
    └── index.css
```

There is also no "styles_desktop" folder or something similar with desktop styles.

### How Do We Reproduce?

Repo with example project here: 
https://github.com/krutoo/mini-css-extract-plugin-tests

**Comment by alexander-akait** [comment]
1. Change `import styles from './module.module.css';` on `import styles from './desktop.module.css';` in `src/desktop.jsx`, because you just don't have module, so no CSS chunks in output
2. Also you don't need `recursive` searcher for webpack v5, just use:
```
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const path = require('path');

module.exports = {
  mode: 'development',
  entry: {
    mobile: './src/mobile.jsx',
    desktop: './src/desktop.jsx',
  },
  output: {
    clean: true,
    filename: '[name]/index.js',
    path: path.resolve(__dirname, 'dist'),
  },
  resolve: {
    extensions: ['.js', '.jsx'],
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: '[name]/index.css',
    }),
  ],
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: 'babel-loader',
      },
      {
        test: /\.module\.css/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {
              modules: {
                localIdentName: '[path][name]__[local]--[hash:base64:3]',
              },
            },
          },
        ],
      },
    ],
  },
  optimization: {
    splitChunks: {
      cacheGroups: {
        desktopStyles: {
          type: "css/mini-extract",
          name: 'desktop',
          chunks: (chunk) => {
            return chunk.name === "desktop"
          },
          enforce: true,
        },
        mobileStyles: {
          type: "css/mini-extract",
          name: 'mobile',
          chunks: (chunk) => {
            return chunk.name === "mobile"
          },
          enforce: true,
        },
      },
    },
  },
};
```

Also you can found `src_common_jsx` with commons modules due `import()`

**Comment by krutoo** [comment]
@alexander-akait How can i create only two css files for top entries? Even its uses common module 
(i want to copy styles of common module to both of result css files)

**Comment by alexander-akait** [comment]
using `reuseExistingChunk`

**Comment by krutoo** [comment]
> using `reuseExistingChunk`

I trying to add it like this:
```js
module.exports = {
optimization: {
    splitChunks: {
      cacheGroups: {
        desktopStyles: {
          type: 'css/mini-extract',
          name: 'desktop',
          chunks: chunk => chunk.name === 'desktop',
          enforce: true,
          reuseExistingChunk: true,
        },
        mobileStyles: {
          type: 'css/mini-extract',
          name: 'mobile',
          chunks: chunk => chunk.name === 'mobile',
          enforce: true,
          reuseExistingChunk: true,
        },
      },
    },
  },
};
```

But i still have dist folder with three css files:
```
dist
├── mobile
│   └── index.css
├── desktop
│   └── index.css  
└── src_common_jsx
    └── index.css
```

What am i doing wrong?

**Comment by alexander-akait** [comment]
You need duplicate module in both places?

**Comment by alexander-akait** [comment]
I recommend avoid it, bad for performance

**Comment by krutoo** [comment]
I need it to create critical css for each entry (mobile, desktop) with Module Federation bootstrap.

In my project i have index file (entry) that dynamically imports "bootstrap" file like here:
https://webpack.js.org/concepts/module-federation/#uncaught-error-shared-module-is-not-available-for-eager-consumption

**Comment by alexander-akait** [comment]
For critical CSS you need another tool than splitting by entries... anyway you use `dependeOn` and move common code to own entry and use `chunks: chunk => chunk.name === 'mobile' || chunk.name === 'common'` to keep code for each or improve logic `test`, there are many techniques to achieve this

**Comment by alexander-akait** [comment]
Or you can `import './common'` instead `import('./common')`, because common in this case is initial chunks (you need to load this before `mobile` and `desktop`, otherwise you will have invalid order), or you can do all async chunks and load `common` then `mobile`/`desktop`

**Comment by alexander-akait** [comment]
Here example where common inside each chunk https://github.com/webpack-contrib/mini-css-extract-plugin/pull/822

**Comment by krutoo** [comment]
> Or you can `import './common'` instead `import('./common')`, because common in this case is initial chunks (you need to load this before `mobile` and `desktop`, otherwise you will have invalid order), or you can do all async chunks and load `common` then `mobile`/`desktop`

Thank you for your answer.

As far as I understood, the presence of a dynamic import of bootstrap file  is required in the case of using module federation.

**Comment by alexander-akait** [comment]
In this case you can load your CSS dynamically using `import()`

**Comment by krutoo** [comment]
> In this case you can load your CSS dynamically using `import()`

with css modules it is does not seem possible

**Comment by alexander-akait** [comment]
There are a lot of cases of how you can solve this, without a real example and description I can not help, sorry, I provide example for original problem

**Comment by krutoo** [comment]
> There are a lot of cases of how you can solve this, without a real example and description I can not help, sorry, I provide example for original problem

Original exmple also uses css-modules

In real world app we have many js-files that imports css files as modules

Because of this we can not import all css modules in entry like this:
```js
import a from '../../components/a/a.module.css';
import a from '../../../common/components/b/b.module.css';
/* ...many other css modules */
import('./boostrap');
```

**Comment by alexander-akait** [comment]
What do you want from this? I provide small example, you can modify it as you want to achieve the desired result, are you waiting for me to write it to you?

**Comment by krutoo** [comment]
@alexander-akait I'm sorry for disturbing, but your answer about lot of cases does not help to understand exactly how solve the problem

I will try to look for a solution elsewhere as this is a different issue
