### ISSUE TITLE
mini-css-extract-plugin + postcss-loader

### ISSUE THREAD

**Issue by hellosmithy** [webpack-contrib/mini-css-extract-plugin#81]
Running node 8.10.0 on macOS

```
"mini-css-extract-plugin": "0.4.0",
"postcss-loader": "2.1.3",
"webpack": "4.4.1"
```
With the following config

```
rules: [
{
  test: /\.css$/,
  use: [
    MiniCssExtractPlugin.loader,
    {
      loader: 'css-loader',
      options: {
        modules: true,
        importLoaders: 1,
        localIdentName: '[hash:base64:6]',
        minimize: { safe: true }
      }
    },
    {
      loader: 'postcss-loader',
      options: {
        plugins: () => [
          require('stylelint')({ configFile: '.stylelintrc' }),
          require('postcss-reporter')({ throwError: failOnError })
        ]
      }
    }
  ],
  include: values(paths.modules),
  exclude: /node_modules/
}
```

I'm finding that only a subset of my css is loaded and postcss-loader seems to not correctly pre-process the css (e.g. css variables are no longer converted, imports don't seem to be followed). If I replace mini-css-extract-plugin with style-loader then everything works correctly (albeit with an inline style tag instead of a css file).

**Comment by evilebottnawi** [comment]
@hellosmithy can you disable `minimize: false` or/and add `ident: "postcss-loader"` for `postcss-loader`?

**Comment by hellosmithy** [comment]
@evilebottnawi just tried both settings and neither seem to make a difference

**Comment by evilebottnawi** [comment]
@hellosmithy remove `importLoaders` ?

**Comment by hellosmithy** [comment]
@evilebottnawi again no change - I've simplified my css imports to a couple of files for testing purposes and seeing the same issue. It looks like postcss.config is no longer being followed possibly. I've tried with and without specifying the path to postcss.config in postcss-loader

**Comment by evilebottnawi** [comment]
@hellosmithy very strange, can you create minimum reproducible test repo?

**Comment by paul-ivannikov** [comment]
@hellosmithy you lose plugin in your configuration file
```javascript
{
  ...
  rules: [
   {
    test: /\.pcss$/,
    use: [
      MiniCssExtractPlugin.loader,
      {
        loader: 'css-loader',
        options: {
          importLoaders: 1,
          sourceMap: true,
          url: false
        }
      },
      {
        loader: 'postcss-loader',
        options: {
          plugins: () => plugins,
          sourceMap: true
        }
      }
    ]
  }
  ],
  plugins: [
    new MiniCssExtractPlugin({
      filename: './static/css/styles.css'
    })
  ]
}
 ```

**Comment by hellosmithy** [comment]
@paul-ivannikov sorry I just missed that off my issue description, but I do have the plugin.
I'll get a repo set up to try and re-create the problem

**Comment by hellosmithy** [comment]
@evilebottnawi @paul-ivannikov sorry in setting up the example repo I've discovered the problem - I was inadvertently overwriting my postcss.config settings in the webpack config. Apologies for the false alarm!

**Comment by Bulala-liu** [comment]
Hi, my config of css rules is the same to yours, but the result showed only part of css files have been extracted.
