### ISSUE TITLE
Prevent the extraction of css from dynamic chunks.

### ISSUE THREAD

**Issue by DanMat** [webpack-contrib/mini-css-extract-plugin#812]
### Feature Proposal
An option to not to include the dynamic chunk files while extracting the css.

### Feature Use Case
In a collection of projects that my company maintains we have a scenario where the css included in the dynamic chunk files are so minuscule that splitting them up in a separate file and making a request for this small file looked detrimental to our site performance. 
So, just looking to see if creating an option to filter out chunk files is a good opt

**Comment by alexander-akait** [comment]
Sorry, it is wrong use case

**Comment by DanMat** [comment]
Sorry, I don't follow. 
Is there something wrong with this request?
Thanks

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack-contrib/mini-css-extract-plugin/issues/234
