### ISSUE TITLE
outputOptions.pathInfo = true breaks sourcemaps

### ISSUE THREAD

**Issue by randypuro** [webpack-contrib/mini-css-extract-plugin#814]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version: 5.51.1
- mini-css-extract-plugin Version: 2.2.0

### Expected Behavior

Source map line numbers are correct, even with `outputOptions.pathinfo` is true

### Actual Behavior

https://github.com/webpack-contrib/mini-css-extract-plugin/pull/783 adds a 3 line comment block to the top of the output; so source map line numbers are all off by 3

### How Do We Reproduce?

With a sourcemapped setup, click on a css class link in browser dev tools, and notice that the link shows the wrong line in the source.

**Comment by alexander-akait** [comment]
> How Do We Reproduce?

Can't reproduce

![Screenshot from 2021-08-31 14-53-03](https://user-images.githubusercontent.com/4567934/131497888-177f563d-c713-4479-9dcc-5edd6da536c9.png)
4 and 10 lines
![Screenshot from 2021-08-31 14-53-08](https://user-images.githubusercontent.com/4567934/131497930-bbf5a5ff-20bb-4a80-998e-68d5da72a2bb.png)
in file 4 and 10 lines

In future, please provide steps, without steps I can't find the problem

**Comment by alexander-akait** [comment]
oh, reproduced

**Comment by randypuro** [comment]
Thank you!
