### ISSUE TITLE
webpack /webpack-test/node_modules/mini-css-extract-plugin/dist/index.js:198       compilation.hooks.contentHash.tap(pluginName, chunk => {  ^  TypeError: Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by bspatil0001** [webpack-contrib/mini-css-extract-plugin#83]
earlier I was getting 
`[webpack-contrib/mini-css-extract-plugin] TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'`

Now
When I do 
webpack --version
I am getting 4.1.1

I tried 'npm install webpack@4.4.1' but still I am getting

`
➜  webpack-test git:(master) ✗ npm install webpack@4.4.1
npm WARN test-webpack@1.0.0 No description
npm WARN test-webpack@1.0.0 No repository field.

+ webpack@4.4.1
updated 1 package in 17.347s
`

I tried nom cache clear --force. Then tried install web pack 4.4.1.

Nothing is working. Do anyone know how to upgrade my webpack?

Here is my repo https://github.com/bspatil0001/webpack-test.git

Thank you

**Comment by claviska** [comment]
I had this error and updated webpack globally:

```
sudo npm -g update webpack
```

Solved it for me.

**Comment by evilebottnawi** [comment]
@bspatil0001 yes, look you have old version of `webpack`. Thanks!

**Comment by aendrew** [comment]
Anyone arriving here from Google, I had a similar error message when I somehow managed to put the plugin into `resolve.plugins` instead of the top-level `plugins` array — worth checking that you've instantiated it in the correct place!
