### ISSUE TITLE
Would you mind exposing resolve() to the function used in "insert" option?

### ISSUE THREAD

**Issue by henning-meinhardt** [webpack-contrib/mini-css-extract-plugin#834]
When using the "insert" option with a function to override the default insertion behaviour, webpack's loading mechanism is blocked until the inserted <link> tag is actually fetched by the browser. You are using a Promise in the createStylesheet() function of the generated runtime code and attach an onload() handler to the link element that is passed to the custom function as single argument. So loading the stylesheet resolved the Promise and loading other things goes on.

This does not suit my special use case. I have a webcomponent that is inserted into an external portal (not within my control). The webcomponent needs the stylesheet in its shadow dom, not in the browser's main document. So I used a function to locate the shadow root and insert the <link> tag there instead of the default place. That works fine unless the portal decides to remove the webcomponent from the DOM (user navigates to an other portal page) and later reinsert it (user coming back to original page having the webcomponent). The portal is an SPA so we have no full page request but rather the webcomponent is just reinitialzed using a new shadow root element. Now the <link> tag I inserted before is missing.

One option would be to keep a copy of the inserted link tag before the webcomponent is removed from the page and reinsert it when it reappears. But that makes rthe code hard to understand.

imho, a better solution would be to use your "insert" option with a function that does not actually insert the <link> tag to the page but only stores it (or the href it refers to) at some place, letting the webcomponent take it up and actually insert it when needed. Unfortunately that does not work because webpack's loading mechanismus is blocked and the webcomponent does not get initialized/mounted until i really insert the <link> tag so that the browser has a chance to fetch it, resolving the promise...

My suggestion is to pass the resolve (and maybe also the reject) functions as additional arguments to the "insert" function, so my implementation of that function could just call resolve() to indicate that loading should processed.

Looking at your runtime code in createStylesheet() and the embedded onLinkComplete() I realize I could already trigger the resolve() function by calling link.onload({ type: "load" }), faking the "onload" event. But I'd like to have an official API here.

Kind regards
Henning

**Comment by alexander-akait** [comment]
Sorry, out of scope, web components supports will be in near future, we already works on this and please use the issue template

**Comment by alexander-akait** [comment]
If you need better answer, please provide small example if usage
