### ISSUE TITLE
(0 , _identifier.getUndoPath) is not a function

### ISSUE THREAD

**Issue by popuguytheparrot** [webpack-contrib/mini-css-extract-plugin#836]
Webpack 5.53.0 
mini-css-extract-plugin 2.3.0

### Bug report

ERROR in 4565.css
(0 , _identifier.getUndoPath) is not a function
TypeError: (0 , _identifier.getUndoPath) is not a function
    at MiniCssExtractPlugin.renderContentAsset (/builds/6Sc9YDTE/0/corpcrm/corpcrm-ui/node_modules/mini-css-extract-plugin/dist/index.js:725:54)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
