### ISSUE TITLE
"mini-css-extract-plugin" every time injects a new number in main.js file on each build which is changing contenthash number of main.js unnecessarily

### ISSUE THREAD

**Issue by sudarshantanwer** [webpack-contrib/mini-css-extract-plugin#838]
### Bug report
"mini-css-extract-plugin" every time injects a new number in main.js file on each build which changing contenthash number of main.js unnecessarily

### Actual Behavior
 I am using webpack 5, and using contenthash for the main.js file. But my main.js file gets a new hash number on every build even if there is nothing changed in my application. When I compared two main.js files from two different builds, then I found that the "mini-css-extract-plugin" injects a new number in main.js file everytime on each build. That causing to change the hash number of my main.js. I don't know why mini-css-extract-plugin is updating these numbers in my main.js file and how to stop this so that my main.js hash number doesn't get changed unnecessarily. I am attaching a comparison of two main.js files.

### Expected Behavior
this plugin should not inject any new number on every build in main.js unnecessarily

### How Do We Reproduce?
Use mini-css-extract-plugin with webpack 5. Use "contenthash" or "chunkhash" in main.js file naming. Make multiple builds and check the hash number of main.js file changing on every build.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
 System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 461.45 MB / 16.00 GB
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Firefox: 83.0
    Safari: 13.1.2
  Packages:
    copy-webpack-plugin: ^9.0.1 => 9.0.1 
    eslint-webpack-plugin: ^3.0.1 => 3.0.1 
    html-webpack-plugin: ^5.3.2 => 5.3.2 
    uglifyjs-webpack-plugin: ^2.2.0 => 2.2.0 
    webpack: ^5.52.0 => 5.53.0 
    webpack-cli: ^4.8.0 => 4.8.0 
    webpack-dev-server: ^4.1.0 => 4.2.1 
    webpack-hot-middleware: ^2.25.0 => 2.25.1

**Comment by sudarshantanwer** [comment]
This same issue is 
<img width="1467" alt="Screenshot 2021-09-23 at 11 39 39 PM" src="https://user-images.githubusercontent.com/4198058/135348114-e2b3067b-9580-4c0a-8f92-a242e44e0aeb.png">

**Comment by alexander-akait** [comment]
Yes, because you use hot, you should not use `hot` in production, remove `HotModuleReplacement` plugin for production build, or you need to use `chunkhash`, but I do not recommended it, feel free to feedbakc, if you provide example of the problem I will show you how to fix it

**Comment by sudarshantanwer** [comment]
> Yes, because you use hot, you should not use `hot` in production, remove `HotModuleReplacement` plugin for production build, or you need to use `chunkhash`, but I do not recommended it, feel free to feedbakc, if you provide example of the problem I will show you how to fix it

@alexander-akait , As you suggested, I commented "hot" in webpack config file. But, still this same issue is there

Below, I am pasting my webpack.config.js file. Any help would be appriciated.

`const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const webpack = require('webpack')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const ESLintPlugin = require('eslint-webpack-plugin')
const CopyPlugin = require('copy-webpack-plugin')

module.exports = (env, argv) => {
  return {
    mode: argv.mode === 'production' ? 'production' : 'development',
    entry:
            {
              config: './public/config.js',
              version:
                    './public/version.js',
              bundle:
                    './src/index.js'

            },
    devtool: 'source-map',
    devServer:
            {
              static: path.resolve(__dirname, 'dist'),
              historyApiFallback:
                    {
                      index: 'index.html'
                    },
              // hot: true,
              port:
                    4567
            },
    optimization: {
      // minimize: true,
      moduleIds: 'deterministic',
      // runtimeChunk: 'single',
      splitChunks: {
        cacheGroups: {
          name: false,
          vendor: {
            test: /[\\/]node_modules[\\/]/,
            filename: 'vendors.[contenthash:8].js',
            chunks: 'all'
          }
        }
      }
    },
    plugins: [
      new MiniCssExtractPlugin({
        // Options similar to the same options in webpackOptions.output
        // both options are optional
        filename: '[name].[contenthash:8].css'
        // chunkFilename: "[id].css",
      }),
      new CopyPlugin({
        patterns: [
          {from: './public/assets', to: 'assets'}
        ]
      }),
      new webpack.ProvidePlugin({
        Buffer: ['buffer', 'Buffer']
      }),
      new webpack.HotModuleReplacementPlugin(),
      new HtmlWebpackPlugin({
        title: 'Control Center',
        filename: 'index.html',
        template: 'src/index.html'
      }),
      new ESLintPlugin({
        // fix: true,
        failOnError: false,
        emitWarning: true,
        files: ['src/**/*.{js,jsx}', '!**/tests/**']
      })
    ],
    output:
            {
              filename: (chunkData) => {
                return chunkData.chunk.name === 'bundle'
                  ? '[name].[chunkhash:8].js'
                  : '[name].js'
              },
              path:
                    path.resolve(__dirname, 'dist'),
              publicPath:
                    '/',
              clean:
                    true,
              pathinfo:
                    false
            },
    // context: path.resolve(__dirname, 'src'),
    resolve: {
      extensions: ['*', '.js', '.jsx', '.css'],
      alias:
                {
                  src: path.resolve(__dirname, 'src/'),
                  apis:
                        path.resolve(__dirname, 'src/apis/'),
                  components:
                        path.resolve(__dirname, 'src/components/')
                },
      fallback: {
        'fs':
                    false,
        'tls':
                    false,
        'net':
                    false,
        'path':
                    false,
        'zlib':
                    false,
        'http':
                    false,
        'https':
                    false,
        // "stream": false,
        'crypto':
                    false,
        // "timers": false
        'timers':
                    require.resolve('timers-browserify'),
        // "buffer": require.resolve("buffer/")
        'stream':
                    require.resolve('stream-browserify'),
        'buffer':
                    require.resolve('buffer')
      }
    },
    module: {
      rules: [
        {
          test: /\.js[x]?$/,
          // exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              // presets: ['es2015'],
              sourceMap: true,
              presets: ['@babel/preset-env']
              // "presets": ["env", "es2015", "react"],
              // "plugins": ["react-hot-loader/babel"]
            }
          }
        },
        {
          test: /\.css$/,
          // exclude: /node_modules/,
          include: [/node_modules\/react-datetime-picker/, /node_modules\/react-clock/, /node_modules\/react-tabs/, /node_modules\/react-calendar/],
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
              options: {
                // publicPath: "/public/path/to/",
              }
            },
            {
              loader: 'css-loader',
              options: {
                sourceMap: true,
                importLoaders: 2
              }
            },
            {
              loader: 'resolve-url-loader'
            }
          ]
        },
        {
          test: /\.(png|svg|jpg|gif)$/,
          use: [
            'file-loader'
          ]
        },
        {
          test: /\.(csv|tsv)$/,
          use: [
            'csv-loader'
          ]
        },
        {
          test: /\.xml$/,
          use: [
            'xml-loader'
          ]
        },
        {
          test: /\.scss$/,
          exclude: /node_modules/,
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
              options: {
                // publicPath: "/public/path/to/",
              }
            },
            {
              loader: 'css-loader',
              options: {
                sourceMap: true,
                importLoaders: 3
              }
            },
            {
              loader: 'resolve-url-loader'
            },
            {
              loader: 'sass-loader',
              options: {
                sourceMap: true
              }
            }
          ]
        }
      ]
    }
  }
}
`
