### ISSUE TITLE
MiniCssExtractPlugin impact of AureliaPlugin

### ISSUE THREAD

**Issue by deleonio** [webpack-contrib/mini-css-extract-plugin#863]
This Option (`experimentalUseImportModule: true`) break the Aurelia build.

I don't know why?!

https://webpack.js.org/plugins/mini-css-extract-plugin/#experimentaluseimportmodule

**Comment by 3cp** [comment]
It's indeed an issue in aurelia-webpack-plugin's webpack5 support.
This one can be closed. Thx!
