### ISSUE TITLE
Set existing plugin options per loader

### ISSUE THREAD

**Issue by jdanil** [webpack-contrib/mini-css-extract-plugin#870]
### Feature Proposal

I would like to propose exposing some existing plugin options as loader options instead.

### Feature Use Case

I have a use case where I would like to use different `mini-css-extract-plugin` options for different file paths. For instance...

```
{
  module: {
    rules: [
      {
        test: /\.css$/u,
        use: [MiniCssExtractPlugin.loader, "css-loader"],
      },
      {
        test: /\.scss$/u,
        use: [MiniCssExtractPlugin.loader, "css-loader", "sass-loader"],
      },
    ],
  },
  plugins: [
    new MiniCssExtractPlugin({
      insert: ?,
    }),
  ],
}
```

Given these two file paths, I would like to set different "insert" locations for each. At the moment I have to revert to `style-loader` for one of these paths. The specific use case I have is that when developing an application that uses shadow roots, I need to make sure the styles are inserted at the correct location for them to be in scope.

The proposed state would be something like this...

```
{
  module: {
    rules: [
      {
        test: /\.css$/u,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              insert: "#id-a",
            },
          },
          "css-loader",
        ],
      },
      {
        test: /\.scss$/u,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              insert: "#id-b",
            },
          },
          "css-loader",
          "sass-loader",
        ],
      },
    ],
  },
  plugins: [
    new MiniCssExtractPlugin(),
  ],
}
```

I suspect this is a similar request to #671.

**Comment by alexander-akait** [comment]
Sorry, it is not possible, because generation runtime code happens inside plugin

**Comment by jdanil** [comment]
OK no worries. Not very familiar with webpack plugin/loader internals, but I suspected it was set up this way for a reason.
I can continue to use `style-loader` for one of the paths. Thanks @alexander-akait.
