### ISSUE TITLE
One CSS per entry point

### ISSUE THREAD

**Issue by skosch** [webpack-contrib/mini-css-extract-plugin#89]
extract-text-webpack-plugin used to give me one CSS per entry point. Now if I understand correctly my only options are maximum splitting, or everything lumped together into one file as per the Readme example (which curiously gets named `0.css` despite the `name` field).

There seems to be no documentation yet on how `splitChunks: { cacheGroups ... }` works, just a few scattered examples. Can I use mini-css-extract-plugin to generate exactly one css file for each entry point, named identical to the respective entry point? Or do I need to use a different plugin for that? Thank you!

**Comment by skosch** [comment]
Ah, never mind -- seems to be related to https://github.com/webpack-contrib/mini-css-extract-plugin/issues/23

**Comment by kevindurb** [comment]
#23 doesnt seem to address your question of one css per entry. I also want to do this, did you find a way to do this?

**Comment by skosch** [comment]
@kevindurb sorry about the late reply – did you get it to work? What issue are you having exactly?

**Comment by GiancarlosIO** [comment]
@skosch did you find a solution for this? :cry:
