### ISSUE TITLE
MiniCssExtractPlugin is incopatible with cross-package configurations

### ISSUE THREAD

**Issue by Zackere** [webpack-contrib/mini-css-extract-plugin#892]
### Bug report

MiniCssExtractPlugin does not work in cross-package compilation setting
Context:
When configuring a monorepo for parallel compilation (https://webpack.js.org/configuration/configuration-types/#parallelism) I noticed that `MiniCssExtractPlugin` does not work when more than 1 configuration has `MiniCssExtractPlugin` as a plugin.

I suggest, that `src/index.js:206` which now looks like this:
` webpack.util.serialization.register(CssModule, "mini-css-extract-plugin/dist/CssModule", null...`

to be changed to something like this:
` webpack.util.serialization.register(CssModule, "mini-css-extract-plugin/dist/CssModule", __dirname`
or
` webpack.util.serialization.register(CssModule, "mini-css-extract-plugin/dist/CssModule", Math.random()`

1st one would prevent using the loader from the same `node_modules` twice and would enable using multiple `MiniCssExtractPlugin` accross multiple configurations (which is what I want)

2nd one would allow using `MiniCssExtractPlugin` multiple times without any restrictions

### Actual Behavior

Webpack throws an error:
`Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered`

### Expected Behavior

Webpack should be able to compile multiple configurations with `MiniCssExtractPlugin` as a plugin

### How Do We Reproduce?

Set up two packages, which use `MiniCssExtractPlugin`. It is important, that webpack configurations have proper loader resolution:
`    resolveLoader: {
      modules: [path.resolve(__dirname, 'node_modules'), 'node_modules'],
    }
`
Set up a third package, which as a webpack.config.js exports configurations of previous 2 packages.
Run webpack in the third package. It throws the error I described.
If we agree on a solution I'd more than happy to submit a PR

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack-contrib/mini-css-extract-plugin/issues/886, bug in webpack, already reported

**Comment by Zackere** [comment]
Shoot, sorry for bothering you then :) Wasnt aware of that issue, thanks

**Comment by Zackere** [comment]
@alexander-akait is it a duplicate, though?

**Comment by alexander-akait** [comment]
hm, I think I was wrong, `parallelism` on multi compiler level is another thing

**Comment by alexander-akait** [comment]
So you have multiple `mini-css-extract-plugin` in multiple packages? Will be great to look at example of structure

**Comment by Zackere** [comment]
subpackage sources: https://gist.github.com/Zackere/60549f09db9fd2bd36b4a150ee576dc7
compiler sources: https://gist.github.com/Zackere/08997a266a25b3bdb20bd846bb57385a

the folder structure should look as follows:

- `package1` folder with `subpackage` sources
- `package2` folder with `subpackage` sources
- `compiler` folder with `compiler` sources

**Comment by Zackere** [comment]
Oh, and I discovered they clash even without parallelism enabled

**Comment by alexander-akait** [comment]
Yep, I see, you have multiple copied of `mini-css-extract-plugin`, ideally we should include version of package too, because you can multiple different versions (or we should provide absolute path)... in theory we can try `__dirname + "../../mini-css-extract-plugin/dist/CssModule"`, so path will be different for different packages, I don't test it locally, please try

**Comment by Zackere** [comment]
Ill try it tomorrow, but it should suffice

**Comment by Zackere** [comment]
Ok, passing absolute path worked. I submitted a PR

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/mini-css-extract-plugin/pull/894
