### ISSUE TITLE
Error: webpack.config.js:664  new MiniCssExtractPlugin({ ^  TypeError: MiniCssExtractPlugin is not a constructor

### ISSUE THREAD

**Issue by icurto2020** [webpack-contrib/mini-css-extract-plugin#898]
How to reproduce (Node)
npx create-react-app test
cd test
npm run build

webpack.config.js:664
        new MiniCssExtractPlugin({^
TypeError: MiniCssExtractPlugin is not a constructor

**Comment by snitin315** [comment]
Duplicate of #896

**Comment by jathanasiou** [comment]
For reference, this seems to be the root cause of https://github.com/facebook/create-react-app/issues/11930
