### ISSUE TITLE
Do not implicitly minify CSS

### ISSUE THREAD

**Issue by dilyanpalauzov** [webpack-contrib/mini-css-extract-plugin#904]
### Actual Behavior

CSS output is implicitly minified for `mode: “production”`.

### Expected Behavior

CSS output shall not be implicitly minified.

### How Do We Reproduce?

I use webpack with
```
export default {
    optimization: {
        minimize: false,
        concatenateModules: true
    },
    mode: 'production',
    experiments: {
        outputModule: true
    },
    module: {
        rules: [{
            test: /\.styl$/,
            use: [
                MiniCssExtractPlugin.loader,
                preprocessLoader,
                {
                    loader: 'css-loader'
                },
                {
                    loader: 'stylus-loader'
                }
            ]
        ]}
     }
  }
```

The [documentation of mini-css-extrac-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin#minimizing-for-production) says:
```
### Minimizing For Production

To minify the output, use a plugin like [css-minimizer-webpack-plugin](https://github.com/webpack-contrib/css-minimizer-webpack-plugin.
```

As I do not used this plugin, I expect that the output will not be minified.

When I run webpack in delevopment mode, the CSS output is not minified, but the javascript contains extra code:
```diff
@@ -25,28 +25,12 @@                                                 
 /******/       __webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
 /******/ })();
 /******/                                                                                                                               
+/******/ /* webpack/runtime/make namespace object */   
+/******/ (() => {                                                  
+/******/       // define __esModule on exports                     
+/******/       __webpack_require__.r = (exports) => {
+/******/               if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
+/******/                       Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
+/******/               }
+/******/               Object.defineProperty(exports, '__esModule', { value: true });
+/******/       };
+/******/ })();
+/******/ 
 /************************************************************************/
 var __webpack_exports__ = {};
+/*!***********************************!*\
+  !*** ./src/index.js + 40 modules ***!
+  \***********************************/
+// ESM COMPAT FLAG
+__webpack_require__.r(__webpack_exports__);
  
 // EXPORTS
 __webpack_require__.d(__webpack_exports__, {
+  "default": () => (/* binding */ src)
-  "Z": () => (/* binding */ src)
 });
  
 ;// CONCATENATED MODULE: ./src/js/common/code-snippet.js
@@ -8069,5 +8055,5 @@
 
 /* harmony default export */ const src = (calendar);
 
+var __webpack_exports__default = __webpack_exports__["default"];
-var __webpack_exports__default = __webpack_exports__.Z;
 export { __webpack_exports__default as default };

```
When I switch to production mode, the above extra output from Javascript disappears, but the CSS output is not minified anymore.

Rationale: I use webpack to create an intermediary library.  The final product does the minification for production.  It however does not strip the code for `/* webpack/runtime/make namespace object */`. 

I want my output to not have the extra javascript code above (dead code) and that CSS is not minified.

I would prefer that Webpack in first place  does not generate the dead code, but this is not handed there — https://github.com/webpack/webpack/issues/13856 .

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

  System:
    OS: Linux 5.15 Fedora Linux 35 (Workstation Edition)
    CPU: (4) x64 AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx
    Memory: 350.05 MB / 5.72 GB
  Binaries:
    Node: 16.13.1 - /tmp/yarn--1643097911860-0.38631170254074876/node
    Yarn: 1.22.17 - /tmp/yarn--1643097911860-0.38631170254074876/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Firefox: 96.0
  Packages:
    css-loader: ^6.0.0 => 6.5.1 
    eslint-webpack-plugin: ^3.0.1 => 3.1.1 
    istanbul-instrumenter-loader: ^3.0.1 => 3.0.1 
    karma-sourcemap-loader: ^0.3.7 => 0.3.8 
    karma-webpack: ^4.0.2 => 4.0.2 
    preprocess-loader: ^0.3.0 => 0.3.0 
    stylus-loader: ^6.0.0 => 6.2.0 
    url-loader: ^4.1.0 => 4.1.1 
    webpack: ^5.28.0 => 5.67.0 
    webpack-cli: ^4.6.0 => 4.9.2

**Comment by alexander-akait** [comment]
Sorry, it is impossible right now, we have an issue in webpack to avoid runtime code, we can't fix it here, anyway we have `runtime` option, you can set it and plugin will not generate runtime, other runtime generates by webpack and necessary for working

**Comment by IAluI** [comment]
What about CSS output implicitly minification? Can it be managed?

**Comment by alexander-akait** [comment]
What do you mean?

**Comment by IAluI** [comment]
Like the author of the issue, it seemed to me that the plugin is responsible for CSS minification. But after your question, I researched this better and it seems that the minification is due to the webpack settings (mode: 'production' ).

**Comment by alexander-akait** [comment]
It means you have CSS minimizer plugin for production
