### ISSUE TITLE
Error in types

### ISSUE THREAD

**Issue by huineng** [webpack-contrib/mini-css-extract-plugin#905]
issue with types

might relate to https://github.com/webpack-contrib/mini-css-extract-plugin/pull/903/files

I'm getting this error with the latest release 2.5.3
typescript 4.5.5
webpack 5.67.0
 "@types/mini-css-extract-plugin": "^2.5.1",  (maybe your types are not updated)

```
node_modules/mini-css-extract-plugin/types/index.d.ts:110:32 - error TS2304: Cannot find name 'HTMLLinkElement'.

110   insert?: string | ((linkTag: HTMLLinkElement) => void) | undefined;
                                   ~~~~~~~~~~~~~~~

node_modules/mini-css-extract-plugin/types/index.d.ts:193:32 - error TS2304: Cannot find name 'HTMLLinkElement'.

193   insert?: string | ((linkTag: HTMLLinkElement) => void) | undefined;
                                   ~~~~~~~~~~~~~~~

node_modules/mini-css-extract-plugin/types/index.d.ts:200:31 - error TS2304: Cannot find name 'HTMLLinkElement'.

200   insert: string | ((linkTag: HTMLLinkElement) => void) | undefined;
                                  ~~~~~~~~~~~~~~~
```

**Comment by alexander-akait** [comment]
Can you provide `tsconfig.json` or configuration for `mini-css-extract-plugin`? This options used to runtime, so browsers globals types should be avalaible

**Comment by huineng** [comment]
Ok, i will close it, 

I just had to add "dom" to my tsconfig lib array

many thanks for your fast response

**Comment by elf-mouse** [comment]
@alexander-akait, @huineng 

- `webpack@5.72.0`
- `workbox-build@6.5.2`
- `typescript@4.6.3`
- `mini-css-extract-plugin` > 2.5.2

If `["ESNext", "Dom", "WebWorker"]` are added to tsconfig lib, more errors will occur!!!
but `["ESNext", "WebWorker"]` config is ok for `mini-css-extract-plugin` <= 2.5.2

Is there a solution?

**Comment by huineng** [comment]
i don't think dom and webworker work well together, see my conversation here after i closed the ticket above
https://github.com/GoogleChrome/workbox/issues/3035#issuecomment-1055505706

**Comment by elf-mouse** [comment]
Helpful to me. Thanks a lot :)
