### ISSUE TITLE
Build error with vue loader relating to typescript definitions

### ISSUE THREAD

**Issue by woahitsjc** [webpack-contrib/mini-css-extract-plugin#906]
### Bug report

I'm not able to upgrade from versions `v2.50` and up. Currently using `webpack v5.66.0` but also tried the latest `v5.67.0` and also did not work.

`vue-loader` version is v15.9.8

### Actual Behavior

Getting this error:
```
error TS2322: Type 'VueLoaderPlugin' is not assignable to type '((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance'.
  Property 'apply' is missing in type 'VueLoaderPlugin' but required in type 'WebpackPluginInstance'.

36         new VueLoaderPlugin(),
           ~~~~~~~~~~~~~~~~~~~~~

  node_modules/webpack/types.d.ts:12344:2
    12344  apply: (compiler: Compiler) => void;
           ~~~~~
    'apply' is declared here.
```

### Expected Behavior

The build should be running with no errors.

### How Do We Reproduce?

Build with these dependency versions:
- `mini-css-extract-plugin: ^2.5.0`
- `webpack: ^5.66.0`
- `vue-loader`: ^2.5.0`

**Comment by alexander-akait** [comment]
Please open an issue in `VueLoaderPlugin`, I think they use old types i.e. `@types/webpack`
