### ISSUE TITLE
mini-css-extract-plugin is not found

### ISSUE THREAD

**Issue by diy4869** [webpack-contrib/mini-css-extract-plugin#912]
### Bug report

After I added SWC loader, the mini CSS extract plugin could not be found. However, I added it. When I checked the relevant source code, I found that I judged whether there was a plug-in from this, not from this_ compiler. options. Do plugins perform judgment processing

Switching from SWC loader to TS loader is normal
![image](https://user-images.githubusercontent.com/29079700/152935304-973c8680-3364-42fd-bc94-358e8165165a.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/29079700/152934915-a1ebaebe-09c4-44b2-bad7-49f64222d6b5.png)
![image](https://user-images.githubusercontent.com/29079700/152935047-3367f6f8-b0f8-4d51-902e-e9507a97edcb.png)

![image](https://user-images.githubusercontent.com/29079700/152934801-2d7d52d5-891e-492d-9f76-ebf0c1d9964e.png)

### Expected Behavior
normal operation

**Comment by alexander-akait** [comment]
Please fill out all fields and I will reopen and help, thanks
