### ISSUE TITLE
Type <plugin> is not assignable to type 'MiniCssExtractPlugin[]'

### ISSUE THREAD

**Issue by eatondustin1** [webpack-contrib/mini-css-extract-plugin#916]
### Actual Behavior

The following error occurs when adding conditional plugins to the webpack config inline via `concat`.

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/11006966/155198012-290b7c1b-9198-4b02-bf40-ec3b16639314.png">

### Expected Behavior

Adding conditional plugins to the webpack config inline via `concat` should not produce TypeScript errors. This was working prior to v2.5.0.

### How Do We Reproduce?

Here is a minimal reproduction config. The same error occurs with other plugins, `ProgressPlugin` is just used as an example here. I got the same errors when testing with: `IgnorePlugin`, `HtmlWebpackPlugin`, `ForkTsCheckerWebpackPlugin`, and `EnvironmentPlugin`.

```typescript
const config: Configuration = {
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'css/[name].[fullhash].css',
      chunkFilename: 'css/[id].[fullhash].css',
    }),
  ].concat(QUIET ? [] : [new webpack.ProgressPlugin()]),
}
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 1.65 GB / 32.00 GB
  Binaries:
    Node: 16.13.1 - ~/.asdf/installs/nodejs/16.13.1/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.1.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 97.1.34.81
    Chrome: 98.0.4758.102
    Safari: 15.2
```

Packages:
mini-css-extract-plugin: 2.5.0
webpack: 5.69.1
webpack-cli: 4.9.2
webpack-dev-server: 4.7.4
webpack-merge: 5.7.3

**Comment by eatondustin1** [comment]
One workaround is to add the conditional plugin after defining the config that includes `MiniCssExtractPlugin`.

```typescript
const config: Configuration = {
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'css/[name].[fullhash].css',
      chunkFilename: 'css/[id].[fullhash].css',
    }),
  ],
}

config.plugins = config.plugins.concat(
  QUIET ? [] : [new webpack.ProgressPlugin()]
)
```

Another is to add the conditional plugin inline prior to adding `MiniCssExtractPlugin`.

```typescript
const config: Configuration = {
  plugins: (QUIET ? [] : [new webpack.ProgressPlugin()]).concat([
    new MiniCssExtractPlugin({
      filename: 'css/[name].[fullhash].css',
      chunkFilename: 'css/[id].[fullhash].css',
    }),
  ]),
}
```

**Comment by alexander-akait** [comment]
Sorry, we can't fix it here, you should improve types of concat

**Comment by eatondustin1** [comment]
Looking into it more, it looks like the only reason it worked before was because `MiniCssExtractPlugin` was untyped (inferred as `any`), which meant we were trying to `concat` a type of `ProgressPlugin[]` to a type of `any[]`, which it was fine with. When types were added to `MiniCssExtractPlugin` in 2.5.0, we were then trying to `concat` a type of `ProgressPlugin[]` to a type of `MiniCssExtractPlugin[]`, which won't work. If we cast the array to the type of `Configuration.plugins` before calling `concat`, it works just fine.

```typescript
const config: Configuration = {
  plugins: ([
    new MiniCssExtractPlugin({
      filename: 'css/[name].[fullhash].css',
      chunkFilename: 'css/[id].[fullhash].css',
    }),
  ] as (((this: webpack.Compiler, compiler: webpack.Compiler) => void) | webpack.WebpackPluginInstance)[]).concat(QUIET ? [] : [new webpack.ProgressPlugin()]),
}
```

Thanks @alexander-akait!

**Comment by alexander-akait** [comment]
You can move `plugins` to own variable too and add types to array or you can avoid using `concat` in favor `push`
