### ISSUE TITLE
Miss allChunks option in Release Notes and Migration instruction

### ISSUE THREAD

**Issue by SanSan-** [webpack-contrib/mini-css-extract-plugin#925]
Documentation Is:

Release Notes has no words about `allChunks` remove from  options and what to do

- [ V] Missing
- [ V] Needed
- [ V] Confusing
- [ X] Not Sure?

### Detail

I have no answer about migration from 0.12.0 to 2.x.x, cause latest version don't support `allChunks` options. SO didn't help too.

### Your Proposal for Changes

Add to Release Notes or Documentation what to do with `allChunks` option in new versions.

**Comment by alexander-akait** [comment]
We don't have the `allChunks` option in our options for v0.12.0, we have many examples here in docs https://github.com/webpack-contrib/mini-css-extract-plugin, please clarify what you can't achieve

**Comment by SanSan-** [comment]
so, yes, i see. i think it is uncompatible with `thread-loader` in new versions,  cause when they together 
```
  module: {
    rules: [
       ...,
      {
        test: /\.scss$/,
        use: [          
          loaders.getCacheLoader(path.resolve(settings.cacheDir, 'css')),
          loaders.getThreadLoader('css'),
          MiniCssExtractPlugin.loader,
          'css-loader',
          'sass-loader'
        ]
      },
      ...
   },
   plugins: [
    ...,
    new MiniCssExtractPlugin({
      filename: `./css/[name].bundle${settings.resourcePrefix}.css`
    }),
```
following error is thrown

```
Module build failed (from ./node_modules/thread-loader/dist/cjs.js): Thread Loader (Worker 0) You forgot to add 'mini-css-extract-plugin' plugin (i.e. plugins new minicssextractplugin() )
```
it wasn't like this before, in 0.12.0
