### ISSUE TITLE
adapt old browser event base tag v1.6.2

### ISSUE THREAD

**Issue by YanxinTang** [webpack-contrib/mini-css-extract-plugin#937]
### Modification Proposal

make v1.6.2 adapt old browser event 

### Expected Behavior / Situation

the event is defined

### Actual Behavior / Situation

the event is undefined

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 84.77 MB / 16.00 GB
  Binaries:
    Node: 17.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.4
  Packages:
    webpack: ^5.40.0 => 5.40.0 
    webpack-cli: ^4.7.2 => 4.7.2 
    webpack-dev-server: ^3.11.2 => 3.11.2 
    webpack-sources: ^1.1.0 => 1.4.3

### Additional

I have fixed it and all tests pass. But there is no branch as base to merge the pull request. Hope you can update and release a new version.

https://github.com/YanxinTang/mini-css-extract-plugin/tree/fix/ie8-event

**Comment by alexander-akait** [comment]
Sorru, we dont't support IE8, you can fork and change code
