### ISSUE TITLE
"no window.document found, will not HMR CSS" when emit=false

### ISSUE THREAD

**Issue by ntucker** [webpack-contrib/mini-css-extract-plugin#943]
### Bug report

When using webpack devserver with a server and client bundle where the server bundle

### Actual Behavior

"no window.document found, will not HMR CSS" is output to the console

### Expected Behavior

Since emit = false, there is no need to attempt HMR anyway so simply ignore this

### How Do We Reproduce?

1. checkout https://github.com/ntucker/anansi/tree/25803a5b49316c7e73846efbe774d5cbe3eb28a3
2. yarn install
3. yarn build:pkg
4. cd examples/concurrent
5. yarn start
6. observe logging statement

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 26.13 GB / 31.30 GB
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 3.2.1 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
```

**Comment by alexander-akait** [comment]
You need to use different setup for server and client, but you miss `How Do We Reproduce?`, so I can't help

**Comment by ntucker** [comment]
I do use different setup for server - I set emit = false as described here: https://github.com/webpack-contrib/mini-css-extract-plugin#emit. I still need the css stuff to run so the classnames are set properly to enable hydration

**Comment by alexander-akait** [comment]
Why you run server chunk on client? Please fill out all fields in an issue template to avoid unnecessary questions

**Comment by alexander-akait** [comment]
Just intresting do you expected to reload CSS or just avoid message?

**Comment by ntucker** [comment]
Just to avoid the message... I believe the only reason it thinks HMR is running on server is because I'm using webpack-dev-server with hot = true and it's injecting the HMR stuff into entrypoint for both client and server bundle. However, that client code doesn't cause any problems itself; just that it seems to be triggering this console message

**Comment by ntucker** [comment]
FYI: landed the branch to master so it's deleted now: https://github.com/ntucker/anansi/commits/master

**Comment by alexander-akait** [comment]
I think we can improve check here, do you want to send a PR?

**Comment by ntucker** [comment]
@alexander-akait done: https://github.com/webpack-contrib/mini-css-extract-plugin/pull/953
