### ISSUE TITLE
Auto-load entry css chunk

### ISSUE THREAD

**Issue by dougalg** [webpack-contrib/mini-css-extract-plugin#96]
It seems that right now, any CSS that is imported in the entry chunk gets split out (as expected) but does not get automatically loaded in the same way that chunk CSS does. It seems useful to have the option of either automatically loading that CSS chunk asynchronously, or just keeping it in bundle and loading it via style-loader or similar.

**Comment by sokra** [comment]
It should be loaded by the HTML, via `<style>` tag

**Comment by dougalg** [comment]
Hi @sokra, thanks for replying. I just want to say that I appreciate all your (and everyone else's) hard work on Webpack, and I think it's an amazing build tool.

So, if we are building a component/plugin/etc then users must load the css themselves? That would work in many cases (although not my use case, unfortunately). Is the problem with having this as an option that it would overly complicate the plugin, or is it a more ideological problem, along the lines of "css should be loaded in the 'natural', 'correct' way, via HTML"?

I understand that that is the ideal, but it's not necessarily true for all use cases, eg if a user is loading a 3rd party script asynchronously, and just wants it "to work", having that entry point be able to bundle/load it's own CSS is useful.

I'm also willing to do some work, and put in a PR for this, but the documentation on writing plugins seems a little spare. If this is something that you would consider adding if I wrote a PR, then I will take a look at it in my free time, would be that acceptable?

**Comment by evilebottnawi** [comment]
@dougalg Look on https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L74. IIt is good practice extract css to separate file and add field (`css`, `scss`) in `paclage.json`. If you want save style in js, just don't use this plugin. When you extract css you **should** manually loader extracted file (html plugin do this automatically). Thanks!

**Comment by dougalg** [comment]
@evilebottnawi thanks for the feedback. I do appreciate that it is best practice to load primary CSS in the HTML, but as this plugin already does asynchronous injection of CSS it doesn't seem like much of a stretch to me. I will take another look at my application's structure and see what alternatives there are on my side

**Comment by rockwalrus** [comment]
You can work around this by dynamically importing the css module you want to dynamically load.
