### ISSUE TITLE
SyntaxError when building in GitHub Actions

### ISSUE THREAD

**Issue by scriptify** [webpack-contrib/mini-css-extract-plugin#960]
### Bug report

When building inside GitHub Actions (ubuntu-latest, Node.js 16), a very strange behavior can be observed: Some hex numbers are transpiled into invalid JavaScript, which causes a SyntaxError during runtime.
![image](https://user-images.githubusercontent.com/20152692/179740368-e0fe589c-2144-43f8-8c8d-80a806fc838c.png)

I was first able to observe this behavior in the production build of an app which uses the jsQR library. That library makes use of the following object containing a lot of hex numbers: [Link to file](https://github.com/cozmo/jsQR/blob/master/src/decoder/decodeData/shiftJISTable.ts).

By trial and error, I was able to narrow it down to the `mini-css-extract-plugin`.

### Actual Behavior

The following code produces invalid JS:
```typescript
console.log("Table: ", {
    0xe69d: 0x8b5a,
});
```

Resulting code with SyntaxError:
```typescript
console.log("Table: ", {
    59c73: 35674
});
```

### Expected Behavior

The hex number should be transpiled without SyntaxErrors.

### How Do We Reproduce?

[I've created the most minimal, reproducible example I was able to come up with.
](https://github.com/scriptify/mini-css-extract-plugin-hex-bug)

[You can see a deployed version of the app here.](https://cheap-ear.surge.sh/)

If the `mini-css-extract-plugin` is replaced with `style-loader`, [everything seems to work fine](https://github.com/scriptify/mini-css-extract-plugin-hex-bug/commit/d9f0db5863513ee2cb5b7909906d1b929e4b8567).

One thing I was also observing: [If I disable Terser by setting `minimize` to `false` in the webpack config, the behavior seems to disappear too.](https://github.com/scriptify/mini-css-extract-plugin-hex-bug/commit/1f7449cf0e7833c89021eed72d420366dcbcda9a)

As already said, I was only able to reproduce this bug by building inside GH Actions. Building locally with Windows or WSL (Ubuntu) didn't yield the same results. I also tried to run the  GH Action locally using [act](https://github.com/nektos/act) and Docker, without luck (no SyntaxError).

Do you have any clue where this could come from and how it could be fixed?

I already spent hours and hours narrowing it down and finding a solution for it, as it really became a problem for our dev team.
TBH, this is one of the most awkward things which ever happened in my career, so I'm really asking myself if I'm missing something very obvious here.

### Results of `npx webpack-cli info`
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 6.34 GB / 15.96 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.19041.1566
  Packages:
    babel-loader: ^8.2.5 => 8.2.5
    css-loader: ^6.7.1 => 6.7.1
    html-webpack-plugin: ^5.5.0 => 5.5.0
    source-map-loader: 4.0.0 => 4.0.0
    style-loader: ^3.3.1 => 3.3.1
    webpack: ^5.73.0 => 5.73.0
    webpack-cli: ^4.10.0 => 4.10.0
    webpack-dev-server: ^4.9.3 => 4.9.3
    webpack-merge: ^5.8.0 => 5.8.0

**Comment by alexander-akait** [comment]
Can you try to disable https://webpack.js.org/configuration/optimization/#optimizationrealcontenthash and check it?

**Comment by scriptify** [comment]
> Can you try to disable https://webpack.js.org/configuration/optimization/#optimizationrealcontenthash and check it?

It really seems to fix the issue. How is that possible? How does the content hash correlate with the actual transpilation/bundling/minification process?

Setting this to false could be bad for long term caching, right?

Thank you so much for your help, I'm quite astonished that you saw a connection so fast and came up with a possible solution!

**Comment by alexander-akait** [comment]
> It really seems to fix the issue. How is that possible? How does the content hash correlate with the actual transpilation/bundling/minification process?

You can change `[contenthash:4]` to `[contenthash:8]` (or to `6`), `4` is too short.

Why does it happen?

Content hash plugin in webpack just replaced original filesnames/hashes/etc in assets, using regexp, we have protections to avoid such cases, but when hash is too short we can't fix it, for exampe you can try to set `[contenthash:1]` and see how many characters will be replaces, my strong recommendation is using `8`.
