### ISSUE TITLE
Duplication styles of same component in different chunks, when using CSS modules and React.lazy

### ISSUE THREAD

**Issue by tippillow** [webpack-contrib/mini-css-extract-plugin#964]
### Bug report
css styles of "shared" component duplicated when using css modules and react-lazy. It can broke styles in some scenarios

### Actual Behavior
<img width="380" alt="1" src="https://user-images.githubusercontent.com/55249470/181737728-37c18fca-b09d-4e08-86b6-05e7b842a272.png">
 duplicated

### Expected Behavior
<img width="380" alt="2" src="https://user-images.githubusercontent.com/55249470/181737780-3830250d-3c82-4f0f-9580-f0e06bb5a82c.png">
 not duplicated

### How Do We Reproduce?

1. check https://github.com/tippillow/cra-css-modules-different-chunks-duplication
2. npm i
3. npm run build
4. serve -s build
5. navigate to page1 -> check list styles -> navigate to page2 -> check styles
6. check styles duplication

![4](https://user-images.githubusercontent.com/55249470/181740064-bfb8d85d-f85c-4ac0-b6f9-7c0ab8e0b04d.gif)

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

 System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.17.3 
    npm: 6.14.13 
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 13.1.3

**Comment by alexander-akait** [comment]
It means they have common modules in different chunks and webpack decide to duplicate it

**Comment by tippillow** [comment]
@alexander-akait is it possible to make css shared chunk?

**Comment by alexander-akait** [comment]
Yes, using `splitChunks` or just put it in common file

**Comment by tippillow** [comment]
@alexander-akait okay, thank you, will check https://webpack.js.org/plugins/split-chunks-plugin/

**Comment by tippillow** [comment]
@alexander-akait thx, made shared chunk, duplication has gone, you are the best

**Comment by aliakseikulba** [comment]
hi! i'm using CRA, react lazy, react-router and routes code splitting, have the same issue. could you help? what is your solution to make shared chunk?

**Comment by tippillow** [comment]
@aliakseikulba hi! My CRA project was ejected, so i easily access webpack.config.file and add splitChunk option. Please read link above. If you don't want to eject your project, you can use https://github.com/timarney/react-app-rewired or it's alternatives.

I made branch [add-shared-chunk](https://github.com/tippillow/cra-css-modules-different-chunks-duplication/tree/add-shared-chunk) in my project, where i created shared chunk, so you can look and try it. I hope I helped, let me know. Good luck!
