### ISSUE TITLE
Insert Closing slash

### ISSUE THREAD

**Issue by Vanillma** [webpack-contrib/mini-css-extract-plugin#965]
### Bug report
hi bro
I noticed that this plugin does not put the final slash when linking the css file to the head!!
![IMG_20220808_194044_891](https://user-images.githubusercontent.com/95992420/183452473-8284bc9b-3e04-4bd3-95d3-ecc625582f50.jpg)

**Comment by alexander-akait** [comment]
Because you don't need `/` in HTML5

**Comment by Vanillma** [comment]
> Because you don't need `/` in HTML5

But it is required in xhtml!
I think it's better to put an option to configure this apparently unimportant slash... because we run into problems with xhtml... also there may be other things that conflict with xhtml!!!

**Comment by alexander-akait** [comment]
Your doctype is not xhtml, your doctype is HTML5, look at your source code

**Comment by Vanillma** [comment]
> Your doctype is not xhtml, your doctype is HTML5, look at your source code

But I have heard in training courses that using xhtml rules (not doctype) in creating html improves performance in old browsers and their interpretation!!
Something like the use of hard JavaScript that is written more accurately and logically!
what is your comment?

**Comment by alexander-akait** [comment]
XHTML is deprecated and is not reccomend (w3 and whatwg) to use (except when you are implementing something for really legacy systems). Most of browsers use html5 spec parser, so my opinion is not to use XHTML. Even more your code is not XHTML valid so you still will have validations problems (and even problems with parser and probably your content will not render as you expceted).
