### ISSUE TITLE
Chunk loading order changed between 1.4 and latest version?

### ISSUE THREAD

**Issue by lwansbrough** [webpack-contrib/mini-css-extract-plugin#972]
I'm seeking some guidance on how to approach a problem with a large codebase migration. Our code base has nearly 1000 components/views. In migrating to webpack 5 from v4 and v1.4 or something of this plugin to the latest version, we've noticed 2 problems: our chunks are split differently, and the order of the CSS links appears to be different, which is causing issues with CSS cascades.

Previously, what we'd expect to see is if A.vue imports B.vue, B's CSS chunk would be loaded _after_ A's CSS chunk. This allowed B to override its parents styles. It also meant if A.vue asynchronously loaded B.vue, the loading of B would be consistently ordered (A then B in all cases.) I recognize this ordering is arbitrary in nature and may be considered an implementation detail, but we've coded 1000 components with this expectation.

Is it possible to recover this behaviour from before the webpack/plugin upgrade? Either webpack or this plugin are responsible for the ordering of how these styles are loaded. In particular, I'd like to know if this was a change that was made consciously (that way I'd know it's probably the culprit.)

It's worth noting that our development build (uses `style-loader`) works fine. So I suspect it was indeed a change to this plugin.

### Modification Proposal

Possibly provide a way to customize the order of component tree CSS?

### Expected Behavior / Situation
Outlined above.

### Actual Behavior / Situation
Outlined above.

**Comment by alexander-akait** [comment]
Please provide small example, without configuration and code I can say what is wrong

**Comment by lwansbrough** [comment]
@alexander-akait hey sorry this took a bit to get right. here's the repro: https://github.com/lwansbrough/mini-css-extract-plugin-demo

You can see the behaviour if you load the page with JS enabled vs. JS disabled.

**Comment by alexander-akait** [comment]
Hm, the order is expected, App -> A -> B, so you have APP the first and the B is last.

So you have:

> Previously, what we'd expect to see is if A.vue imports B.vue, B's CSS chunk would be loaded after A's CSS chunk.

```html
<style data-vue-ssr-id="a761e4f2:0">html, body {
   margin: 0;
   padding: 0;
   height: 100vh;
   }
   div {
   height: 100%;
   width: 100%;
   }</style><style data-vue-ssr-id="6d421302:0">.a[data-v-4403bb38] {
   background: blue;
   height: 100%;
   width: 100%;
   }
   [data-v-4403bb38] .b {
   background: red;
   }</style><style data-vue-ssr-id="194fba47:0">.b[data-v-4411d2b9] {
   background: green;
   height: 100%;
   width: 100%;
   }</style>
```

Bur if you look at devtools, you will find that you load CSS chunks twice - inlined in HTML, look at HTML code, and loaded in JS file, look at `/dist/app.js`, and that is the problem, also some of them with source maps some note...

**Comment by alexander-akait** [comment]
Also I noted if I disabled `mini-css-extract-plugin` and keep only `vue-style-loader`, we have the same problem, but if I remove `vue-style-loader` from client everything works fine, so I think the problem somewhere in `vue-style-loader`...

**Comment by alexander-akait** [comment]
Yeah, I jsut moved:
```
{
        test: /\.(scss|css)$/,
        exclude: /node_modules/,
        use: [
          'vue-style-loader',
          { loader: 'css-loader', options: { sourceMap: true } },
          { loader: 'sass-loader', options: { sourceMap: true } },
        ]
      }
```

to base to solve duplicate problem, but I still have the problem (without `mini-css-extract-plugin`)

**Comment by lwansbrough** [comment]
@alexander-akait Thanks for your help. Safe to say at this moment that this isn't an issue with this plugin.

**Comment by alexander-akait** [comment]
Feel free to ask/ping if you need a help

**Comment by lwansbrough** [comment]
@alexander-akait I'd like to take you up on that. :) I've improved the above example repro to more closely align the behaviour with our real setup. I've dropped vue-style-loader entirely.

There are two behaviours exhibited:

1.) SSR load: the page is loaded and after a short delay, the async component is loaded, causing the background to turn **red**. This behaviour is **unwanted**.
2.) Dynamic load: the A component is forced to reload after the B component has already been loaded, causing the background to turn **green.** This behaviour is **desired.**

Steps to repro for red:

1. Load the page, wait 3 seconds. _Red_

Steps to repro for green:

1. Load the page, wait 3 seconds. _Red_
2. Make a minor change to A.vue and save it, which causes webpack to reload A.vue. _Green_

The issue being demonstrated is that the stylesheets are not cascaded in a consistent order. Regardless of whether a component is loaded by SSR (and thus its CSS is linked on page load) or dynamically (by navigating between pages using an SPA router), the order of the CSS should remain consistent.

In our case, our components were written such that A is able to overwrite B at any time. This is the desired behaviour for our application, though we recognize that might not be true for everyone. Either way, consistent ordering of CSS is vital to prevent cascade bugs.

**Comment by lwansbrough** [comment]
Hmm, I downgraded to 1.3.7 (the first version supporting webpack v5) and still have the same problem, so unless something changed between 1.3.1 and 1.3.7, I'd say this is a webpack issue.

**Comment by alexander-akait** [comment]
But if we disable loader and plugin we still have this problem, I think the bug is not in webpack (it looks like), but I think something in vue loader/plugin and ssr logic, just for testing (I have a lot of issues and don't have time to check it right now, sorry) can you try `1.3.2`/`1.3.3`/etc so we can found which version create a problem, it will be easy to find workaround or potential places how we can fix/improve it

**Comment by lwansbrough** [comment]
@alexander-akait The issue continues to appear in 1.3.1 with webpack v5. So the behaviour is likely unique to webpack. What I suspect the issue is, is because of the way our CSS was written, it was more or less by chance that styles were being applied in the correct order due to there being fewer CSS chunks. More CSS was in the same file so the cascading was working by chance. We're electing to solve the problem by eliminating the category of CSS that can lead to these types of bugs.

**Comment by alexander-akait** [comment]
Hm, I looked at this deeply, so:

I modify `vue-loader` code:

**vue-loader/loaders/pitcher.js**
```js
// More code ...

 if (query.type === `style`) {
    const stringifyRequest = (r) => loaderUtils.stringifyRequest(this, r)
    
    const cssLoaderIndex = loaders.findIndex(isCSSLoader)
    if (cssLoaderIndex > -1) {
      const afterLoaders = loaders.slice(0, cssLoaderIndex + 1)
      const beforeLoaders = loaders.slice(cssLoaderIndex + 1)
      const request = genRequest([
        ...afterLoaders,
        stylePostLoaderPath,
        ...beforeLoaders
      ])
      // console.log(request)
      return query.module
        ? `export { default } from  ${request}; export * from ${request}`
        : `console.log("DEBUG " + ${stringifyRequest(`!${this.resourcePath}`)});export * from ${request}`
    }
  }
  
// More code ...  
```

And now we have some strange things, when we run SSR (i.e. just run server), our output is:

```
Rendering: /
DEBUG !./App.vue
DEBUG !./A.vue
DEBUG !./B.vue
```

But in browser we have

```
app.js:627 DEBUG !./B.vue
app.js:593 DEBUG !./A.vue
app.js:610 DEBUG !./App.vue
```

And you can see that the order is reversed.

To be honest, the logic in the browser seems to me more correct, because we `import B from './B.vue'` inside `A.vue` and so `B.vue` component should be ready to use (and so fully loaded) before `A.vue` code (same logic for `A.vue` and `App.vue`).

Even more when you have:
```
::v-deep .b {
  background: red;
}
```

You want to override style for the nested component, if we had a different order of styles, then this entry would have no meaning and all styles would be overrided by nested compoments (yes you can increase specificity using CSS, but this is out of this discussion).

Also I found this https://github.com/vuejs/vue-loader/issues/808

And we can find here two opposite points of view

**Comment by lwansbrough** [comment]
@alexander-akait I greatly appreciate the deep dive. It seems though we agree on the order, it is somewhat arbitrary. I think this issue can be closed. We're going to go ahead with updating our code.
