### ISSUE TITLE
Handling exported functions

### ISSUE THREAD

**Issue by yungvldai** [webpack-contrib/mini-css-extract-plugin#984]
Hi! First of all thank you for your work!

### Modification Proposal

I came across an interesting case in which a custom (modified) css-loader exports functions (as named exports). 
The [current implementation](https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/loader.js#L231) uses `JSON.stringify`, which causes export values of type `function` ​​to become `undefined`. It seems that we can fix this behavior quite easily without breaking anything by adding a check for `typeof === 'function'` and calling `(locals)[key].toString()` instead of `JSON.stringify((locals)[key])`.

What do you think?

### Expected Behavior / Situation

Function code is inserted instead of `undefined`

### Actual Behavior / Situation

Function code turns into `undefined`

**Comment by alexander-akait** [comment]
PR welcome :+1:

**Comment by yungvldai** [comment]
Thank you for answer! PR #985

**Comment by alexander-akait** [comment]
Fixed
