### ISSUE TITLE
What is `new Self`?

### ISSUE THREAD

**Issue by assembled-wei-wei** [webpack-contrib/mini-css-extract-plugin#989]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

https://github.com/webpack-contrib/mini-css-extract-plugin#multiple-themes

In the example there is a section

```
 plugins: [
    new Self({
      filename: "[name].css",
      attributes: {
        id: "theme",
      },
    }),
  ],
```

And I couldn't find any documentation about it. Can anyone shine some light on this?

### Your Proposal for Changes

Add some documentation about this usage

**Comment by alexander-akait** [comment]
Bug in docs it should be `MiniCssExtractPlugin`, feel free to send a PR

**Comment by assembled-wei-wei** [comment]
ah i see! thanks!
