### ISSUE TITLE
Plugin doesn't close the link tag

### ISSUE THREAD

**Issue by paulrockfordstudios** [webpack-contrib/mini-css-extract-plugin#994]
### Actual Behavior

When building in production, the plugin is not closing out the link tag.
### Expected Behavior

When building in production, the plugin should close out the link tag.

### How Do We Reproduce?

run build and you will see it is not closing out the link tag. easy to repoduce.
### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
my production is very large and is a private comapany website.

**Comment by paulrockfordstudios** [comment]
when building for production, the plugin is not closing out the link tag.

**Comment by alexander-akait** [comment]
Please fill out all feilds, otherwise I can't help

**Comment by paulrockfordstudios** [comment]
I update and filled out all fields.

**Comment by paulrockfordstudios** [comment]
ok. sorry, this may be a webpack issue. nevermind

**Comment by alexander-akait** [comment]
Sorry, I don't undestand you

**Comment by paulrockfordstudios** [comment]
The issue I am having is when I run build.  The link tag for the style.css file is not closing out in the index.html file and it is causing a syntax error unexpected token < .  but I removed the minicssextractplugin and the build had the same issue except on the favicon link tag.   so I'm not sure anymore if the issue is ith the plugin.

**Comment by alexander-akait** [comment]
I think you need investigate this locally and maybe bug in favicon plugin or you inject favicons in wrong way, I don't know

**Comment by paulrockfordstudios** [comment]
Actually, it was a webpack config issue. as I stated earlier and Its been fixed. thank you for the quick response.
